- src/modules/powerrename/ui/PowerRenameUI.cpp
Take an AddRef on the CPowerRenameProcessUI before passing it to the worker thread which runs the progress dialog.  We were seeing crashes due to a narrow timing window in the progress UI startup and teardown.  This should ensure that no longer happens.
Applies to https://github.com/microsoft/PowerToys/issues/11068
> Ensure the lifetime of CPowerRenameProcessUI on the worker thread

- installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp
- src/common/updating/installer.cpp
- src/common/updating/installer.h
In 0.35 we dropped support for 1809 and older. We also stopped supporting the msi extraction on 1809 and older.
Allow to extract the msi on any version of Windows.
Run `PowerToysSetup-0.0.1-x64.exe --extract_msi` on an older version of Windows and verify it extracts the msi.
> [bootstrapper] Allow msi extraction on 1809 and older

- .github/actions/spell-check/expect.txt
- src/modules/videoconference/VideoConferenceModule/VideoConferenceModule.cpp
Reiniting `_controlledMicrophones` from `updateControlledMicrophones` unmutes them, which is an intended behavior. However, we shouldn't update microphone when in fact it wasn't changed.
> [VCM] do not reinit microphone if it wasn't changed

- doc/devdocs/modules/launcher/new-plugin-checklist.md
PT Run new plugins needs extra steps for localization that can only be done after the first localization phase is done.
Update the new plugin checklist to add the extra localization steps.
> [devdocs] new plugin localization steps

- installer/PowerToysSetup/Product.wxs
The installer is not installing the localized resources for the  `System` plugin .
Update the installer to add the localized resources.
We tested this in the internal pipeline that creates the localized installer.
> [msi] add localized resources for "System" plugin

- src/modules/keyboardmanager/KeyboardManagerEngineLibrary/KeyboardManager.cpp
- src/modules/keyboardmanager/KeyboardManagerEngineLibrary/KeyboardManager.h
After moving the KBM engine our of the runner process, the mechanism to detect when the KBM editor is running, was leaking a handle.
Move the handle creation to the constructor instead of creating the event handle every time the kb hook is invoked.
Verify the handle is not leaked:
- open the task manager, go to the `Details` tab and add the `Handle` column to the list view.
- open notepad and type any letter, check if the engine's handle count increases.
Verify that the engine is correctly suspended when the editor is open:
- create a key mapping
- verify the key mapping is working
- open the editor and verify the key mapping is suspended
- close the editor and verify the key mapping is resumed …
> [KBM] Fix for handle leak

- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/VideoConference.xaml
Make the image clickable in Video Conference settings page.
Build and click on "Learn more" and the image itself.
> Add image hyperlink for Video Conference settings page 

- src/common/interop/interop.cpp
- src/common/interop/shared_constants.h
- src/modules/ShortcutGuide/ShortcutGuide/Resources.resx
- src/modules/ShortcutGuide/ShortcutGuide/main.cpp
- src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.cpp
- src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.h
- src/modules/ShortcutGuide/ShortcutGuide/target_state.cpp
- src/modules/ShortcutGuide/ShortcutGuide/target_state.h
- src/modules/ShortcutGuide/ShortcutGuide/trace.cpp
- src/modules/ShortcutGuide/ShortcutGuide/trace.h
- src/modules/ShortcutGuide/ShortcutGuideModuleInterface/shortcut_guide.cpp
- src/modules/ShortcutGuide/ShortcutGuideModuleInterface/shortcut_guide.h
- src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml.cs
- src/settings-ui/PowerToys.Settings/OobeWindow.xaml.cs
Every time `Shift+Win+?` is pressed we start `PowerToys.ShortcutGuide.exe` process. And if `ESC` or  `Shift+Win+?` is pressed the second time we terminate the process. For now, we use a centralized keyboard hook in the runner.
- Added SG shortcut to centralized keyboard hook
- Start SG process on SG hotkey
- Show SG window on start
- Terminate SG process on ESC
- Updated OOBE to use a new approach
- Remove remainings of press delay time for win key
- Test for race conditions
- Try to start from OOBE
Known issues:
- The focused window is not shown in the ShortcutGuide
- `Disable for apps` does not work …
> [Shortcut Guide] Start on demand

- src/modules/ShortcutGuide/ShortcutGuide/ShortcutGuide.exe.manifest
- src/modules/ShortcutGuide/ShortcutGuide/ShortcutGuide.vcxproj
- src/modules/ShortcutGuide/ShortcutGuide/ShortcutGuide.vcxproj.filters
- src/modules/ShortcutGuide/ShortcutGuide/main.cpp
- src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.cpp
- src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.h
- Show focused app in the SG popup
- Make SG process dpi aware so taskbar numbers are shown correctly
- Don't show SG popup if on the foreground is one of the disabled apps
> [Shortcut Guide] Regressions

- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
Fixes incorrect default Keyboard Shortcut showing up in Welcome to PowerToys window for Color Picker upon fresh install, as mentioned in #11199
Just a change from {Ctrl} to Expected value of {Shift}, as of the default HotKey assigned to Color Picker in Resources.resw and the corresponding .lcl files
Build the solution, install and open the Color Picker panel in the Welcome to PowerToys window. Ensure the keyboard combination to open Color Picker is shown as Win+Shift+C in every locale
Signed.
> Fix Incorrect HotKey for Color Picker in Welcome to PowerToys OOBE window

- src/modules/fancyzones/editor/FancyZonesEditor/CanvasZone.xaml
- src/modules/fancyzones/editor/FancyZonesEditor/CanvasZone.xaml.cs
- src/modules/fancyzones/editor/FancyZonesEditor/Themes/Dark.xaml
- src/modules/fancyzones/editor/FancyZonesEditor/Themes/HighContrast1.xaml
- src/modules/fancyzones/editor/FancyZonesEditor/Themes/HighContrast2.xaml
- src/modules/fancyzones/editor/FancyZonesEditor/Themes/HighContrastBlack.xaml
- src/modules/fancyzones/editor/FancyZonesEditor/Themes/HighContrastWhite.xaml
- src/modules/fancyzones/editor/FancyZonesEditor/Themes/Light.xaml
This PR enables keyboard navigation and manipulation of the canvas editor. The following things were changed/updated:
- Added keyboard logic.
**Tab**: move between zones
**Arrow keys**: change the position
**Shift + arrows keys**: make the canvas zone smaller or larger (following PowerPoint shape logic).
**Del**: delete the zone
- Updated canvas-selection styles.
**Things still need to fixed before merging in** (@enricogior can you team look at these items?):
- Due to the automatic snapping, canvas zones can get stuck when snapped together.
- It now requires to click on a canvas zone first to get the focus on the canvas zones window and vice-versa. Ideally, users can use tab to navigate through the zones and back to the little dialog window. …
> [FZ Editor] Keyboard support for canvas editor

- src/modules/ShortcutGuide/ShortcutGuide/main.cpp
If SG process is started from the runner, the current path is set to the runner executable path. Current code assumes that the current path is the executable path.
- Make a clean build of PowerToys
- Start PowerToys
- Press `Shift+Win+/`
- Verify that SG window is brought to the front
> [Shortcut Guide] Set current path to the executable's directory

- src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Main.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Properties/Resources.resx
Added quick default browser launch function in Uri plugin
source code 
Type only direct activation phrase (by default "//") in PT run and check if the item that open default browser is displayed.
***Quick browser***
***Original plugin***
review plz!
> [PT Run] Implement quick browser open in PT-run

- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/GeneralViewModel.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml
* Added `Downloading...` text.
* Mute the` Download and install` button after downloading started.
* Removed `Read more` for the error state.
* Changed button text to `Try to download and install` in the error state.
> [Auto-update][PT Settings] Updated UI

- .github/workflows/spelling.yml
This feature isn't ready yet and wasn't meant to be included
Remove comment handler (unintentionally included in #11114)
(It's fairly harmless as configured, but the noise is worth removing, the event handler should come back w/ the next release when the code is ready...)
Remove an event handler for a future feature
Be a non-member of the repository and comment on a PR (or check the [repository actions list](https://github.com/microsoft/PowerToys/actions/workflows/spelling.yml?query=event%3Aissue_comment+is%3Afailure))
I think. (Oddly this event is failing way less than expected.)
A CLA must be signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/PowerToys) and sign the …
> check-spelling: Remove stray field

- src/modules/ShortcutGuide/ShortcutGuide/d2d_window.cpp
- src/modules/ShortcutGuide/ShortcutGuide/main.cpp
- src/modules/ShortcutGuide/ShortcutGuide/overlay_window.cpp
- src/modules/ShortcutGuide/ShortcutGuide/overlay_window.h
- src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.cpp
- src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.h
- src/modules/ShortcutGuide/ShortcutGuide/trace.cpp
- src/modules/ShortcutGuide/ShortcutGuide/trace.h
1. Close SG window if
- Win key was pressed and released
- Win+key is pressed(e.g Win+A, Win+Shift)
- ESC was pressed. Moved it from the window procedure
- The shortcut is pressed again
2. Update ShortcutSession telemetry event with close type
3. Fix crash  when `thumb_window` is not initialized. To reproduce it start PT in debug mode, press `Win+D` and try to open SG window.
Try to close SG window with `ESC` key, pressing the shortcut again, pressing `Win+key` shortcut, pressing and releasing just win key
> [Shortcut Guide] Close SG window when win shortcut was pressed

- src/settings-ui/Microsoft.PowerToys.Settings.UI/Styles/TextBlock.xaml
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml
> [Auto-update][Settings] Bolden update ready/available info line

- src/common/updating/dotnet_installation.cpp
Update .NET Core 3.1 minimum version requirement to 3.1.15
> [Updating] Set dotnet version to 3.1.15

- src/modules/colorPicker/ColorPickerUI/Controls/ColorFormatControl.xaml
- src/modules/colorPicker/ColorPickerUI/Controls/ColorPickerControl.xaml
- src/modules/colorPicker/ColorPickerUI/Controls/ColorPickerControl.xaml.cs
- src/modules/colorPicker/ColorPickerUI/Properties/Resources.Designer.cs
- src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx
- src/modules/colorPicker/ColorPickerUI/Resources/Styles.xaml
- src/modules/colorPicker/ColorPickerUI/Views/ColorEditorView.xaml
This PR improves keyboard navigation for the ColorPicker Editor:
- Replaces the custom sliders with styled WPF sliders, making them keyboard-controllable.
- The colorpicker-mixer is now within a flyout, more suitable for keyboard navigation.
- Correct tab behavior (tab to switch between controls, arrow keys to navigate within the control)
- Overall visual / layout improvements
- Improvements to the focus visual of all controls
- Solving keyboard issue: #10987
> [ColorPicker] Improving keyboard navigation

- .github/actions/spell-check/expect.txt
- src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Programs/Win32Tests.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
This PR tries to fix #9776
On environments with Turkish locale selected, you can't run programs with capitalized `I` because `I` becomes `ı` thus fails to open the specified program.
**What is include in the PR:**
I suppressed [CA1308](https://docs.microsoft.com/visualstudio/code-quality/ca1308) for user facing text and used InvariantCulture for the launch issue.
**How does someone test / validate:**
Here's the end result:
One needs an environment with locale set to Turkish and try to run a program or a shortcut that has capitalized `I` in it.
Thankfully Windows has one in: `C:\Program Files\Windows Photo Viewer\ImagingDevices.exe`
I just needed to create a shortcut (LNK) for that and tested with it and it worked.
I signed the CLA.
> [PT Run] Fix Program Plugin launching issue in Turkish locale

- src/common/interop/interop.cpp
- src/common/interop/shared_constants.h
- src/modules/launcher/Microsoft.Launcher/dllmain.cpp
- src/modules/launcher/PowerLauncher/App.xaml.cs
- src/modules/launcher/PowerLauncher/Helper/SingleInstance`1.cs
Sometimes a user manually starts PowerToys Run or for some reason, there is a leaked process. Take into account, that even if we leak PT Run process it is a rare bug. Before starting PT Run we signal the exit event to close an existing process. Also, it fixes random poping up of PT Run.
- Close PT Run process before starting new by signaling the exit event
- Move `WaitForPowerToysRunner` to the main from Startup
First scenario:
- Start standalone PT Run
- Start PT
- Verify that the standalone PT Run was terminated. Check logs for errors.
Second scenario:
- Start PT 
- Restart PT
- Verify that new PT Run was started …
> [PowerToys Run] Single instance

- src/modules/fancyzones/editor/FancyZonesEditor/CanvasZone.xaml.cs
Fixed an issue with a stucked zone caused by the default magnetic snapper when the zone is moved with a keyboard. 
* Open the canvas layout editor and select any zone
* Move the zone with arrows
* Resize the zone with `Shift + Arrow`
* Drag the zone with a mouse to verify that magnetic snapping is working.
> [FZ Editor] Turn off magnetic snapping when moving/resizing a zone with the keyboard

- src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditor.xaml.cs
- src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditorWindow.xaml.cs
- src/modules/fancyzones/editor/FancyZonesEditor/CanvasZone.xaml.cs
- src/modules/fancyzones/editor/FancyZonesEditor/Overlay.cs
Added support to switch focus between the zones and the dialog using `Ctrl + Tab`.
> [FZ Editor] Switch between zone and dialog with Ctrl + Tab

- .github/actions/spell-check/expect.txt
- tools/BugReportTool/BugReportTool/BugReportTool.vcxproj
- tools/BugReportTool/BugReportTool/BugReportTool.vcxproj.filters
- tools/BugReportTool/BugReportTool/EventViewer.cpp
- tools/BugReportTool/BugReportTool/EventViewer.h
- tools/BugReportTool/BugReportTool/Main.cpp
- tools/BugReportTool/BugReportTool/XmlDocumentEx.cpp
- tools/BugReportTool/BugReportTool/XmlDocumentEx.h
We query for event viewer logs specific to PowerToys and report them. It is useful to correlate bug reports with Watson. Usually, Watson has memory dumps of crashes that are useful. Also, some crashes are not logged so it is useful to have at least some information about crashes. 
We report XAML view from the event viewer.
Based on https://docs.microsoft.com/en-us/windows/win32/wes/querying-for-events
Take into account, that xaml isn't very readable especially `EventData` section. For example, to get a Hashed bucket(correlation id for watson) we need to go to `Windows Error Reporting` xaml and take second to the end `Data` in `EventData` section. …
> [Bug Report Tool] Report event viewer logs

- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/PackageRepository.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/Win32ProgramRepository.cs
Some users report that the program plugin takes a lot of time to query. We want to know what is the number of indexed applications. Also, it is good to know how many application was indexed in case startup is slow.
> [Run Plugin] Logs

- src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs
- src/modules/launcher/PowerLauncher/App.xaml.cs
- src/modules/launcher/Wox.Plugin/PluginPair.cs
When PT Run exits we get null reference exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
Source: Microsoft.Plugin.Indexer
TargetAssembly: Microsoft.Plugin.Indexer, Version=0.37.2.0, Culture=neutral, PublicKeyToken=null
TargetModule: Microsoft.Plugin.Indexer.dll
TargetSite: Void Save()
at Microsoft.Plugin.Indexer.Main.Save()
at PowerLauncher.Plugin.PluginManager.Save()
at Wox.PublicAPIInstance.SaveAppAllSettings()
at PowerLauncher.App.<>c__DisplayClass20_0.<Dispose>b__0()
at Wox.Infrastructure.Stopwatch.Normal(String message, Action action)
at PowerLauncher.App.Dispose(Boolean disposing)
at PowerLauncher.App.Dispose()
at PowerLauncher.App.<RegisterExitEvents>b__15_2(Object s, SessionEndingCancelEventArgs e)
at …
```
> [PowerToys Run] Crash on exit, logs

- src/modules/launcher/PowerLauncher/SettingsReader.cs
- src/modules/launcher/Wox.Plugin/PluginMetadata.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerLauncherPluginViewModel.cs
Before we stored absolute paths for icons to the settings file. It usually causes problems for a developer. 
Steps to reproduce:
- Delete `PowerToys Run\settings.json`
- Start PT from visual studio(PT saves absolute paths)
- Clean solution 
- Start installed PT
- Check that plugin icons are not shown in the settings
We store relative paths to resolve this issue.
- Test with old settings
- Test with a clean settings
> [Run-Plugin Manager] Save relative path to settings

- src/common/interop/shared_constants.h
- src/modules/keyboardmanager/KeyboardManagerEditorLibrary/BufferValidationHelpers.cpp
- src/modules/keyboardmanager/KeyboardManagerEditorLibrary/KeyDropDownControl.cpp
- src/modules/keyboardmanager/KeyboardManagerEditorLibrary/ShortcutControl.cpp
- src/modules/keyboardmanager/KeyboardManagerEditorLibrary/SingleKeyRemapControl.cpp
- src/modules/keyboardmanager/KeyboardManagerEditorLibrary/SingleKeyRemapControl.h
- src/modules/keyboardmanager/KeyboardManagerEditorTest/BufferValidationTests.cpp
- src/modules/keyboardmanager/KeyboardManagerEditorTest/LoadingAndSavingRemappingTests.cpp
- src/modules/keyboardmanager/KeyboardManagerEngineTest/AppSpecificShortcutRemappingTests.cpp
- src/modules/keyboardmanager/KeyboardManagerEngineTest/OSLevelShortcutRemappingTests.cpp
- src/modules/keyboardmanager/KeyboardManagerEngineTest/SingleKeyRemappingTests.cpp
After updating to VS 16.10 KBM module fails to build. 
There are two issues:
- `int` can't be implicitly converted to `DWORD`. I'm not sure what is the reason behind it as both are 32-bit integers
- There are issues with initializing `RemapBufferItem({ 0x41, 0x42 }`. It produces an empty vector. I guess it's going to be fixed soon but we need to fix it to unblock master.
> [Area-Build] Fix build for VS 16.10

- src/modules/fancyzones/FancyZones/main.cpp
* Build the `fancyzones/FancyZones`
* Try to run several instances of `x64\Debug\modules\FancyZones\PowerToys.FancyZones.exe`
* Verify there is only one `PowerToys.FancyZones.exe` instance running 
* Verify in the log file `\AppData\Local\Microsoft\PowerToys\FancyZones\Logs\v0.0.1\log_2021-06-01.txt` warning `[warning] FancyZones instance is already running`
> [FancyZones] Allow single instance of "PowerToys.FancyZones.exe"

- tools/BugReportTool/BugReportTool/EventViewer.cpp
- tools/BugReportTool/BugReportTool/RegistryUtils.cpp
* Added `PowerToys.FancyZones.exe` to the event viewer.
* Added `PowerToys.FancyZones.exe` to the compatibility report.
* Fixed `PowerToys.KeyboardManagerEditor.exe` duplication in the compatibility report.
> [FancyZones] Updated bug reports

- src/settings-ui/PowerToys.Settings/App.xaml.cs
Small fix for minimized settings window not brought to front when opened from OOBE.
- Open Settings window from tray icon
- Open OOBE window from "Welcome to PowerToys" link
- Minimize Settings window
- Open Settings from the OOBE window > Welcome > Settings button
- Settings window should be brought to front and displayed
> [OOBE] Open minimized settings

- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter.UnitTest/UnitHandlerTests.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/UnitHandler.cs
Convert string unit representation to enum and then use single `UnitsNet.UnitConverter.Convert`
- Removed `ParsesInputForAbbreviations` and its tests as it's not needed for the new implementation
- Run tests
- Test manually for regressions 
> [Run Plugin] Rewrite ConvertInput

- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter.UnitTest/InputInterpreterTests.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter.UnitTest/UnitHandlerTests.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/ConvertModel.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/InputInterpreter.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/Main.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/UnitHandler.cs
Parse and convert logic was not divided well enough. Also, there was access to elements of an array(e.g. `split[3]`). Obviously, it is not a robust solution and will be probably hard to maintain. 
- Divide convert and parse logic. Added `ConvertModel` as an intermediate structure between parse and convert
- Updated tests. Added negative cases
- Test allowed conversions 
> [Run-Plugin] Divide into parse and convert

- src/common/utils/appMutex.h
- src/runner/main.cpp
Clean up runner's outdated code.
Remove outdated code that was detecting the MSIX version
Test the core main functionality at startup:
- check if when a second instance is started, the Settings app is opened
- check that a toast notification is correctly handled
- check that a first time run opens OOBE
> [runner] removed outdated MSIX code

- .github/actions/spell-check/expect.txt
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWPApplication.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Main.cs
- src/modules/launcher/PowerLauncher/Converters/HighlightTextConverter.cs
- src/modules/launcher/PowerLauncher/ResultList.xaml
- src/modules/launcher/Wox.Plugin/Result.cs
This PR introduces some existing Wox code to highlight the query in the search results text.
> [Run] Highlight search text

- PowerToys.sln
SLN was missing a close for endproject.  VS proper didn't fail but the build farm did.
> fixing merge oops that doesn't seem to trigger on VS

- src/common/utils/elevation.h
- src/modules/launcher/Microsoft.Launcher/dllmain.cpp
We disable the PT Run module if the PT Run process fails to start. In this PR we make it more robust. For some users, the process can not be started because the shell window is not available yet, and `GetShellWindow()` returns null. We've seen it happen on windows starup. So we should recover if `GetShellWindow()` fails. Take into account that we only use the shell window to start unelevated PT Run from elevated PT.
- Don't disable the module If the process can not be started
- Log a warning if `GetShellWindow()` returns null
- Log a warning if the process can not be started and PT is elevated. It is expected behavior
Can be tested artificially. Try to fail `GetShellWindow()`
A CLA must be …
> [PowerToys Run] Disable module on startup

- src/modules/fancyzones/lib/Settings.h
- src/modules/fancyzones/lib/ZoneSet.cpp
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
I have implemented a new algorithm for dealing with snapping overlapping tiles. What I'm proposing snaps to the tile with the closest center, unless the centers of the tiles are too close in which case it falls back to taking the smallest tile. I still need to add  a setting to adjust the level at which the algorithm falls back to taking the smallest tile.
**What is include in the PR:**
A new setting algorithm to select a zone when they overlap.
Temporarily disabled buffering of windows when selecting.
Change the "When multiple zones overlap:" setting to "Activate the zone whose center is closest to the cursor" in the Fancy zones settings. Here are some before and after gifs:
Before, split the overlapped area into multiple activation targets:
Now, …
> [FanzyZones] Zone activation based on zone center

- src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/SearchHelper/WindowsSearchAPI.cs
If URI parsing fails we fail to get any results from the Windows search plugin. 
If parsing of the URI fails log warning and skip the item.
> [Run-Plugin][Windows Search] Don't crash if URI can't be parsed

- src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
Don't crash if `UserSelectedRecord.json` or `QueryHistory.json` failed to update as it's not essential functionality. 
> [PowerToys Run] Don't crash if `UserSelectedRecord.json` can not be updated

- src/modules/fancyzones/lib/Zone.cpp
- src/modules/fancyzones/lib/Zone.h
- src/modules/fancyzones/lib/ZoneSet.cpp
Moved calculations that are pointless when the other than "ClosestCenter" algorithm is selected.
> [FancyZones] Avoid unnecessary calculations when selecting a zone

- .github/actions/spell-check/expect.txt
- src/common/utils/elevation.h
- src/modules/launcher/Microsoft.Launcher/dllmain.cpp
- src/modules/launcher/PowerLauncher/App.xaml.cs
- src/modules/launcher/PowerLauncher/Helper/SingleInstance`1.cs
- src/modules/previewpane/powerpreview/powerpreview.vcxproj
We have issues with starting PT Run where PT is elevated through the compatibility tab of the properties of the PowerToys.exe(#10400). PT Run can not be started because the system requires the `explorer.exe` to be elevated to start it. And if the `explorer.exe` is elevated PT Run starts elevated as well. So I think in this case PT Run inherits elevation from PT and there's nothing we can do because those structures are opaque. 
Also, PT Run cannot be started when PT is run elevated from a user account (#11038). PT runs on behalf of an admin account and can not access `explorer.exe` process of a user account.
We fixed it by choosing different approach to start a process unelevated from the elevated one(https://devblogs.microsoft.com/oldnewthing/20131118-00/?p=2643). …
> [PowerToys Run] Issues with elevation

- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesData.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesData.h
- src/modules/fancyzones/FancyZonesLib/JsonHelpers.cpp
- src/modules/fancyzones/FancyZonesLib/JsonHelpers.h
- src/modules/fancyzones/editor/FancyZonesEditor/Models/Device.cs
- src/modules/fancyzones/editor/FancyZonesEditor/Models/MainWindowSettingsModel.cs
- src/modules/fancyzones/editor/FancyZonesEditor/Models/Monitor.cs
- src/modules/fancyzones/editor/FancyZonesEditor/Overlay.cs
- src/modules/fancyzones/editor/FancyZonesEditor/Utils/FancyZonesEditorIO.cs
Changed work area initialization in the Editor. Passing all the necessary data from the C++ side.
Open FancyZones Editor with different monitor scaling, verify that layouts are placed correctly. To be sure, set any template grid layout, remove spacing and observe that layout borders match screen borders.
The bug is reproducible with scaling different from 100%, so at least one of the monitors should be scaled (Settings -> System -> Display -> Scale and layout).
> [FancyZones] "Match not found" error fix

- installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp
- tools/BugReportTool/BugReportTool/Main.cpp
Bootstrapper logs are not always picked up by the bootstrapper. So we log directly into the AppData folder.
- Change log directory to the appdata folder
- Remove copy of the bootstrapper logs from the temp folder into the bug report
Build the bootstrapper and verify that logs are present in the AppData folder
> Log to appdata folder from the bootstrapper and the msi

- src/modules/fancyzones/editor/FancyZonesEditor/Overlay.cs
- src/modules/fancyzones/editor/FancyZonesEditor/Utils/FancyZonesEditorIO.cs
Prevent wrong work area size with the `Allow zones to span across monitors` flag on.
* Turn on `Allow zones to span across monitors`, open Editor, verify the layout placed correctly.
* Turn the flag off, open Editor again, verify that all layouts are placed correctly.
> [FancyZones] "Match not found" fix update for the single layout for all monitors.

- src/modules/launcher/PowerLauncher/App.xaml.cs
- src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
If a user invokes PT Run while it's initializing the behaviour is undefined. 
Move hotkey registration to the end of the startup method.
- Run as a user, set run on startup
- Restart window
- Right after Windows started start pressing `Alt+space`
- Verify that PT Run doesn't crash and the search window is visible after pressing `Alt+Space`
> [PT Run] Register the hotkey after PT Run is initialized

- src/modules/awake/Awake/Program.cs
Fix the string in the system tray to show "PowerToys Awake" instead of "Awake" on more code paths.
> [Hotfix] PowerToys Awake - Show full name on tray

- src/modules/imageresizer/ui/Models/ResizeSize.cs
new numberbox control will NaN if left blank versus resetting to a zero.  This fix will check that.  If NaN, it makes the image a 1px sizing for pretty much all permutations
verifying if NaN and treating it like we do with a 0
> Image resizer checking for NaN, not just zero

- src/modules/fancyzones/FancyZonesModuleInterface/dllmain.cpp
An exception was thrown on closing the `m_toggleEditorEvent`.
Added checks and logs in case if there was an error on creation.
Enable/disable module multiple times. 
For me, it crashed on master after 3-10 reenablings. 
> [Hotfix][FancyZones] Unable to start correctly

- src/common/utils/elevation.h
- src/modules/launcher/Microsoft.Launcher/dllmain.cpp
We have the fallback implementation for starting PT Run process if we can not delegate it to the `explorer.exe`. 
We decided to remove ActionRunner as a middle process for starting PT Run and because it was made in the fallback this scenario hasn't been tested. Here we kind of revert it.
It can be tested artificially by returning false from `RunNonElevatedEx`.
> [PowerToys Run] Start PowerToys Run through the ActionRunner 

- tools/BugReportTool/BugReportTool/EventViewer.cpp
Clicking "Report Bug" creates a "EventViewer-PowerToys.Awake.exeFancyZonesEditor.exe.xml" file inside the zip, instead of two separate files for PowerToys Awake and FancyZonesEditor.
This PR fixes it.
> Fix merged process names in bug report tool

- src/modules/colorPicker/ColorPicker/dllmain.cpp
- src/modules/colorPicker/ColorPickerUI/App.xaml.cs
- src/modules/colorPicker/ColorPickerUI/Program.cs
In #11942 it is hard to understand if the ColorPicker process started and doesn't work or it hasn't started on the startup. Here, we update logging to correlate between the runner logs and the ColorPicker process logs. 
- Initialize logger on the module interface initialization. It was not initialized and we didn't get any logs before
- Add logs to understand how the ColorPicker process is created and destroyed 
- Run Color Picker
- Verify `ColorPicker` for logs
> [Color Picker] Logs

- .github/actions/spell-check/expect.txt
- src/modules/fancyzones/FancyZones/FancyZonesApp.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZones.h
- src/modules/fancyzones/FancyZonesLib/FancyZonesData.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesData.h
- src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj
- src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj.filters
- src/modules/fancyzones/FancyZonesLib/MonitorWorkAreaHandler.cpp
- src/modules/fancyzones/FancyZonesLib/MonitorWorkAreaHandler.h
- src/modules/fancyzones/FancyZonesLib/VirtualDesktop.cpp
- src/modules/fancyzones/FancyZonesLib/VirtualDesktop.h
- src/modules/fancyzones/FancyZonesLib/WindowMoveHandler.cpp
- src/modules/fancyzones/FancyZonesLib/WindowMoveHandler.h
- src/modules/fancyzones/FancyZonesLib/WorkArea.cpp
- src/modules/fancyzones/FancyZonesLib/WorkArea.h
- src/modules/fancyzones/FancyZonesLib/Zone.h
- src/modules/fancyzones/FancyZonesLib/ZoneSet.h
- src/modules/fancyzones/FancyZonesLib/trace.cpp
- src/modules/fancyzones/FancyZonesLib/trace.h
- src/modules/fancyzones/FancyZonesTests/UnitTests/UnitTests.vcxproj
- src/modules/fancyzones/FancyZonesTests/UnitTests/UnitTests.vcxproj.filters
- src/modules/fancyzones/FancyZonesTests/UnitTests/WorkArea.Spec.cpp
* Changed `ZoneWindow` to a more clear and suitable `WorkArea`.
* Moved method related to WorkArea.
> [FancyZones] Rename ZoneWindow -> WorkArea

- src/modules/launcher/Plugins/Microsoft.Plugin.Uri.UnitTests/UriHelper/ExtendedUriParserTests.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Uri/UriHelper/ExtendedUriParser.cs
Handle numeric input for URI plugin.
Numeric input was converted into an IP address. This is the behaviour of `System.Uri`.
- Search in PT Run for:
- `12345` should display no results.
- `12345.com` should display `http://12345.com/` as result.
> [PowerToys Run] URI Plugin: handle numeric input

- src/common/utils/process_path.h
- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
* Added retry loop in the `process_path`. The reason is that for UWP apps `EnumChildWindows` may not find the `ApplicationFrameHost` child immediately.
* Added logs
On my machine the bug is nearly always reproducible with this scenario:
* Set 4-zones grid layout
* Assign Settings window to several zones (I selected 1,3).
* Close Settings
* Reopen Settings
Settings may be opened fullscreen at first, but resized within a second.
Verify that Settings was resized every reopening. 
> [FancyZones] Window opening on the last zone

- Cpp.Build.props
> [Build] Disable compilation warnings for external projects

- .github/actions/spell-check/expect.txt
After updating and turning on the spell checker action, some PRs are giving an error because of the "IObservable" term.
Adds "IObservable" to the spell checker list of expected words.
Let's wait for the action to be successful.
> [spell checker] add IObservable term

- src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
- src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
> since during startup the visibility of the MainViewModel is set to Visibility.Collapsed the OnLoaded for the MainWindow is called only when the PT Run shortcut is pressed for the first time.
Moved the set of the visibility of the MainWindow to Collapsed after OnLoaded has been called.
This should improve performance when user press PT Run shortcut for the first time: https://github.com/microsoft/PowerToys/issues/8873#issuecomment-874226749 https://github.com/microsoft/PowerToys/issues/8873#issuecomment-856371692
Slightly noticeable on my computer.
> [PT Run] Improve First Call Performance

- src/modules/videoconference/VideoConferenceModule/Toolbar.cpp
enable VCM (uncommenting module loading in src/runner/main.cpp should be enough) and mute mic. Observe the toolbar doesn't hide 'X' window button.
> [VCM] Tweak toolbar top right vertical offset to allow closing apps

- .github/actions/spell-check/expect.txt
- tools/BugReportTool/BugReportTool/BugReportTool.vcxproj
- tools/BugReportTool/BugReportTool/BugReportTool.vcxproj.filters
- tools/BugReportTool/BugReportTool/InstallationFolder.cpp
- tools/BugReportTool/BugReportTool/InstallationFolder.h
- tools/BugReportTool/BugReportTool/Main.cpp
- Traverse PowerToys installation folder and write tree-like structure of it to the `installationFolderStructure.txt`
- Include a file version or None if the file doesn't have a version
- Calculate a file hash and specify it after the version. If the hash can not be retrieved include error message instead. `GetVersion` was adopted from https://docs.microsoft.com/en-us/windows/win32/seccrypto/example-c-program--creating-an-md-5-hash-from-file-content
- Install 0.44.4
- Build Bug Report Tool 
- Copy `BugReportTool.exe` to `C:\Program Files\PowerToys\Tools`
- Run bug report tool
- Find difference between your  `installationFolderStructure.txt` and the one posted here …
> [Bug Report Tool] Report installation folder structure

- tools/BugReportTool/BugReportTool/EventViewer.cpp
Adds the event viewer events of PowerToys.Settings.exe to bug reports.
Adds the event viewer events of PowerToys.Settings.exe to bug reports.
Run the bug report tool, an entry for PowerToys.Settings.exe should be created in the report.
This allows catching errors such as https://github.com/microsoft/PowerToys/issues/12520
> [Bug Report Tool] Get Settings event viewer data

- .github/actions/spell-check/expect.txt
- src/runner/tray_icon.cpp
Click on PowerToys icon should open settings if PowerToys is already running in the system tray.
This is not working if PowerToys is running elevated.
This is returning ERROR_ACCESS_DENIED.
https://github.com/microsoft/PowerToys/blob/c8f04923539f6136a37c9bd6e5e784636ea642a2/src/runner/main.cpp#L77
This fix allow a process running with lower privileges to send WM_COMMAND to PowerToys.
- Open PowerToys
- Ensure PowerToys is running in the system tray
- Open PowerToys a second time
- Settings should be opened
Test as normal user and elevated.
> [Runner] Open Settings Running Elevated

- src/ActionRunner/actionRunner.cpp
This PR includes a removal of an unused namespace alias in `actionRunner.cpp`.
A simple change removing the unused alias
Compile the modified file
> remove unused namespace alias

- src/common/utils/process_path.h
Remove retries from `get_process_path` as this function is used in different places and should be generic. For example, when used in low-level keyboard hook it is unacceptable to block execution for 1 second(it happens for full screen UWP applications).
When `alt+tab` is pressed in full-screen UWP application we receive `WM_PRIV_WINDOWCREATED` message and `FancyZones::WndProc` is blocked for one second. Take into account, that `Move newly created windows to their last known zone` should be checked. So basically we have cases when `EnumChildWindows` doesn't find a different pid and retry doesn't make sense in this case.
Test for KBM
- Add remapping `Ctrl(Left) + Q -> Play/Pause Media` for …
> Fix lags for UWP application in full screen mode

- src/modules/imageresizer/ui/Properties/Settings.cs
Make ImageResizer starting with malformed settings JSON.
If `%LOCALAPPDATA%\Microsoft\PowerToys\ImageResizer\settings.json` is not properly formatted, ImageResizer UI will be started with default settings instead of crashing.
- Add a mistake to `%LOCALAPPDATA%\Microsoft\PowerToys\ImageResizer\settings.json`
- ImageResizer UI will be started with default settings
> [ImageResizer] Handling malformed JSON

- tools/BugReportTool/BugReportTool/Main.cpp
- tools/BugReportTool/BugReportTool/ZipTools/zipfolder.cpp
For some users desktop path can not be represented as `char*`. On the other hand, https://github.com/kuba--/zip requires `char*` as a path for zip folder. 
To solve the issue we zip a folder into the temp folder and then copy it to the desktop.
Don't call `InstallationFolder::ReportStructure(reportDir);` in the debug mode because it takes a lot of time and makes testing in debug mode impossible. Also, updated the cziplib submodule.
> [Bug Report Tool] Zip folder can not be created

- .github/actions/spell-check/expect.txt
- README.md
Readme updates for improvements added in v0.45.
> v0.45 Updates

- .github/actions/spell-check/expect.txt
- src/modules/previewpane/powerpreview/settings.cpp
Invoking [SHChangeNotify SHCNE_ASSOCCHANGED](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shchangenotify#remarks) when thumbnail providers are turned on/off.
Reload thumbnail handlers providers are turned on/off.
Reboot should't be required anymore.
_Note: calling SHChangeNotify don't clear generated thumbnails. I have looked into this and I haven't found an offical way to clear thumbnails cache for a specific extension._
- Build and install PT
- Create a new svg file (copy/paste an existing file)
- Thumbnail should be generated
- Disable svg thumbnails
- Create a new svg file (copy/paste an existing file)
- Thumbnail should not be generated
- Enable svg …
> [File Explorer] Thumbnail handlers reload

- src/modules/keyboardmanager/KeyboardManagerEngineLibrary/KeyboardEventHandlers.cpp
- src/modules/keyboardmanager/common/RemapShortcut.h
When mapping a shortcut to `Alt+Tab` navigation with arrow keys is broken. It happens because there are intermediate keys sent even if they are not needed. So in this pr we don't sent those intermediate keys
Add the following remapping
Try to switch tabs with `Ctrl+D` and `Ctrl+Arrows`
> [Keyboard Manager]  `Alt+Tab` navigation with arrow keys i

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Helper/TranslationHelper.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/LocProject.json
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/WindowsSettings.json
- Improvements in `TranslationHelper` to prevent translation errors on incorrect strings (null, empty, whitespace).
- Update resource string for `ControlPanel`to match the string naming of `SettingsApp`.
- Enabling localisation pipeline for this project.
- Updating/adding if conditions in TranslationHelper to `string.IsNullOrWhiteSpace()`.
- Updates on resource string for "Control panel" name: `ControlPanel` => `AppControlPanel`
- Creating/adding `LocProject.json`.
Build code on my local machine and verify that everything works as expected.
> [PT Run] [WindowsSettings plugin] Translation improvements and LocProject.json

- .pipelines/pipeline.user.windows.yml
- .pipelines/restore-bootstrapper.cmd
Pipelines are failing to build current master after https://github.com/microsoft/PowerToys/commit/1f2f247c1d1155a4574a21cf86ff71c01e7cb798 with this error:
```
error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Windows.ImplementationLibrary.1.0.210204.1\build\native\Microsoft.Windows.ImplementationLibrary.targets.
```
Instructions to restore bootstrapper package before building.
Get it merged into master and see if it builds properly afterwards.
> [ci] restore bootstrapper nuget packages

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Helper/ResultHelper.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Main.cs
This PR implements filtering/searching by settings path. This works a bit like navigating through the settings: `app > area1 > area2`
Additional this PR fixes a "System.ArgumentNullException" in `ResultHelper.SetScores` and improves query duration on empty queries.
- Adding a new method to filter by settings path.
- Adding an if statement to prevent "System.ArgumentNullException" in `ResultHelper.SetScores` if the setting has no defined areas.
- Improve query time on empty queries like `$` ($ = activation command) by skipping filtering and setting score on every setting to the same value without checking setting`s properties.
Building locally for testing functionality and checking log file for …
> [PT Run] Settings plugin: Settings path filter and bug fixes

- .pipelines/ci/templates/build-powertoys-ci.yml
There is an internal requirement that we move to build agents that we
don't run ourselves. This discharges us of that requirement!
We're switching between the WinDevPool pool and the WinDevPoolOSS pool
based on whether this code is being built in the open-source tenant or
the internal/private one.
> Move away from the legacy windevbuildagents pool

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry/Main.cs
Handle invalid base keys for PT Run Registry plugin.
No `System.InvalidOperationException` in log file with invalid base keys as input.
- Test the following queries:
- `:qwerty`
- `:hkcuuuu`
- `:hkcu>`
- `System.InvalidOperationException` not logged in log file.
> [PT Run: Registry] Handle Invalid Base Keys

- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/ImageResizerViewModel.cs
Improvements on `.NullOrEmpty` check and the comment before to make the use case more clear.
See also this discussion: https://github.com/microsoft/PowerToys/pull/13285#discussion_r713135369
> [Code refactoring] Make code comment and NullOrEmpty check more clear

- src/modules/colorPicker/ColorPickerUI/ColorEditorWindow.xaml.cs
- src/modules/colorPicker/ColorPickerUI/NativeMethods.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Helpers/NativeMethods.cs
- src/settings-ui/PowerToys.Settings/OobeWindow.xaml.cs
ColorPicker Editor and OOBE window can be snapped intoFanzyZones.
Once snapped both can't be resized.
Setting WS_POPUP style to prevent snap into zones.
This is the same solution adopted for PT Run (actually hardcoded) https://github.com/microsoft/PowerToys/pull/9071
- Build PT
- Open Open ColorPicker Editor
- Validate that the window can't be snapped into zones (drag and win+arrows)
- Open Welcome to PT
- Validate that the window can't be snapped into zones (drag and win+arrows)
> [ColorPicker][OOBE] Fix FancyZones snap

- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
> Updated FZ color UX

- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/Resources.resx
- src/modules/fancyzones/FancyZonesLib/Settings.cpp
- src/modules/fancyzones/FancyZonesLib/Settings.h
- src/modules/fancyzones/FancyZonesLib/ZoneColors.h
- src/modules/fancyzones/FancyZonesLib/ZoneWindowDrawing.cpp
- src/modules/fancyzones/FancyZonesLib/ZoneWindowDrawing.h
- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/FZConfigProperties.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/FancyZonesViewModel.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml.cs
Use accent color and theme for zones
More screenshots including light theme here: https://github.com/microsoft/PowerToys/issues/4098#issuecomment-955576892
- Activate FZ
- Play with the settings toggle "Use custom colors"
- When enabled FZ should use colors configured in the settings (old behaviour)
- When disabled FZ should use Windows accent color and theme
- Change theme and accent color from Windows settings: FZ should use current Windows settings
> [FancyZones] Use accent color and theme

- src/runner/settings_window.cpp
Bring up opened settings window from the tray icon resize the window if is maximized
Handle maximized window
1. Open settings
2. Maximize window
3. Click on tray icon with left mouse cursor
4. Settings should be brought up maximized
> [Runner] Bring up maximized settings

- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/FindMyMouseSettings.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/MouseUtilsPage.xaml.cs
Find My Mouse is saving settings to two different directories. Fix the issue by saving in only one directory and deleting the wrong one.
Fix the error which caused the settings to be saved in two different directories.
Delete the wrong folder.
Run it, enter the settings page for Mouse Utils, and see the wrong directory disappear, while still having your settings load correctly. The wrong settings folder shouldn't be created again after changing settings.
> [FindMyMouse]Fix duplicated settings path

- .github/actions/spell-check/expect.txt
- src/modules/imageresizer/ui/Extensions/BitmapMetadataExtension.cs
- src/modules/imageresizer/ui/Models/ResizeOperation.cs
Improves resilience of the image resize implementation.
This PR fixes different categories of bugs in described in #9885 and #14266.
Bug category 1:
- Image contains partially invalid metadata which throws an exception on:
- reading a given metadata field
- writing metadata to a given field or persisting the image containing the metadata to disk. 
Bug category 2:
- Some metadata depends on the availability of a thumbnail image. The encoder crashes if the thumbnail image is not found.
- Loop over all metadata and try to read the actual value. Remove metadata item if exception is thrown while reading the value. Build up the metadata object from the scratch by adding all valid values. This resolves Bug category 1
- copy thumbnail image …
> [Image Resizer] Fix image resizer unexpected property type or value (#9885, #14266)

- PowerToys.sln
- src/common/utils/color.h
- src/modules/MouseUtils/FindMyMouse/FindMyMouse.cpp
- src/modules/MouseUtils/FindMyMouse/FindMyMouse.h
- src/modules/MouseUtils/FindMyMouse/dllmain.cpp
- src/modules/MouseUtils/MouseHighlighter/dllmain.cpp
- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/FindMyMouseProperties.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/MouseUtilsViewModel.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/MouseUtilsPage.xaml
Add more settings to Find My Mouse.
Settings for:
- Background color
- Spotlight color
- Overlay opacity
- Spotlight radius
- How bigger the spotlight is when the animation starts
- Animation duration (0 is instant)
Change some settings and see them applied to Find My Mouse.
> [FindMyMouse]Add additional settings

- src/modules/colorPicker/ColorPickerUI/Helpers/ColorHelper.cs
- src/modules/colorPicker/ColorPickerUI/Helpers/ColorRepresentationHelper.cs
- src/modules/colorPicker/ColorPickerUI/ViewModels/ColorEditorViewModel.cs
- src/modules/colorPicker/UnitTest-ColorPickerUI/Helpers/ColorRepresentationHelperTest.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/Enumerations/ColorRepresentationType.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/ColorPickerViewModel.cs
#14020 and #12630 - Show color as a float and as a decimal value
> Show color as a float and as a decimal value

- src/common/utils/registry.h
CI is currently failing on `undefined class 'std::basic_ostringstream<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>'` when building the `powerpreview.vcxproj` project.
Include `sstream` to resolve this name in CI.
> [ci][powerpreview]Add include to fix build error

- .pipelines/pipeline.user.windows.yml
CI is currently failing on postbuild static analysis of winrtcpp.exe inside Microsoft.Windows.CppWinRT packages. This makes little sense, since it's an official Microsoft release.
Skip the binary check for those files.
> [ci][binskim]skip cppwinrt.exe binary checks

- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml
Adding text to the File Explorer settings menu explaining how to enable preview pane.
New information block in File Explorer settings menu
Ensure localized translation is correct. Currently broken as we transition our build pipeline.
> Preview pane toggle instructions

- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/Win32ProgramFileSystemWatchers.cs
Program plugin fail to load if a FileSystemWatcher is initialized for a directory that does not exist or isn't accessible.
- Initialize FileSystemWatcher only for valid directories.
- Log as warning invalid directories.
- I have been able to repro this only in debug adding an invalid directory to the paths array.
- Validate that the directory is logged and skipped.
> [PT Run] [Program] FileSystemWatcher Crash

- src/runner/general_settings.cpp
- src/runner/main.cpp
On PT startup compare run on startup value from settings file with current state of task scheduler - if startup is true and there is no task, task was deleted manually, so startup should become false.
1) set run at startup to 'on'
2) exit powertoys
3) open task scheduler and remove powertoys startup
> Sync run on startup with actual task scheduler

- src/modules/fancyzones/FancyZonesLib/VirtualDesktop.cpp
- src/modules/fancyzones/FancyZonesLib/VirtualDesktop.h
* Changed `IVirtualDesktopManager` initialization
* Added missed nullptr check 
* Launch PT, verify that FZ works.
* Verify that no `[error] Failed to create VirtualDesktopManager instance`  in the logs.
> [FancyZones][Hotfix] Fix VirtualDesktopManager init 

- .pipelines/pipeline.user.windows.yml
- installer/PowerToysSetup/Product.wxs
- src/common/notifications/BackgroundActivatorDLL/BackgroundActivatorDLL.vcxproj
- src/common/notifications/BackgroundActivatorDLL/resource.h
- src/common/notifications/notifications.cpp
Rename `BackgroundActivatorDLL.dll` to `PowerToys.BackgroundActivatorDLL.dll`
- run PT non-elevated
- FancyZones enabled
- open some app as administrator
- try to zone that app
- confirm that "can't drag elevated app" toast notification is shown 
> [BackgroundActivatorDLL] Unify dll/exe naming 

- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/OpenWindows.cs
Removing PowerLauncher.exe from WindowWalker results.
- Open Launcher
- Type `<pow`
- PowerLauncher.exe shouldn't be displayed
> [WindowWalker] PowerLauncher removed from results

- src/modules/launcher/PowerLauncher/SettingsReader.cs
Update plugins icons and author on PT Run startup.
- Edit `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\settings.json` changing icons and author for some plugins.
- Verify that with 0.51.1 in Plugin Manager icons and author are broken
- Verify that with this build after PT Run start icons and author are properly updated
> Update PT Run plugins icons and author

- src/modules/interface/powertoy_module_interface.h
- src/modules/videoconference/VideoConferenceModule/VideoConferenceModule.cpp
- src/modules/videoconference/VideoConferenceModule/VideoConferenceModule.h
- src/runner/general_settings.cpp
- src/runner/general_settings.h
- src/runner/main.cpp
- src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/EnabledModules.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Microsoft.PowerToys.Settings.UI/ViewModels/ShellViewModel.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/VideoConference.xaml
VCM needs UAC access to turn itself off and since during install you need UAC, it is on by default magically.  We shouldn't enable this style of behavior since we're shifting toward a UAC free install.
1. Shift VCM to off by default
2. adding info bar for telling you must be admin to enable
> VCM as admin fixes

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation-issue.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/translation_issue.yml
There's an update for our labels changing `Triage-Needed` to `Needs-Triage`. 
Updating issue templates for this. 
Changes `Triage-Needed` to `Needs-Triage` for issue templates.
> Update Traige-Needed to Needs-Triage

- src/modules/MouseUtils/FindMyMouse/FindMyMouse.cpp
- src/modules/MouseUtils/MouseHighlighter/MouseHighlighter.cpp
In an effort to standardize user facing strings, adding proper "PowerToys" prefix to the titles of the windows created by mouse utils.
Changes to the Windows names.
Not sure how to make this strings user facing, but I assume they'll appear on some window inspector software.
> [MouseUtils]Add PowerToys to window names

- .github/ISSUE_TEMPLATE/config.yml
> "PowerToys user documentation" still points to the wiki in new issues fix

- src/modules/imageresizer/tests/Models/ResizeOperationTests.cs
- src/modules/imageresizer/ui/Extensions/BitmapMetadataExtension.cs
- src/modules/imageresizer/ui/Models/ResizeOperation.cs
see #14913
a fix for #14913
1. download image in found in issue https://github.com/microsoft/PowerToys/issues/2447#issuecomment-628058477
2. Resize the image
3. Check if all the metadata is there
*Before this fix:*
*After this fix:*
> [Image Resizer] Try to recover metadata even when the metadata data structure is invalid (#14913)

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/CalculateHelper.cs
This is a minor change that allows hexadecimal and binary numbers to be interpreted by the calculator plugin. The underlying Mages library supports parsing these numbers, so the validation regex here is the only barrier to them being used.
A modification to the expression validation regex that allows hex/binary numbers to be passed in calculations.
Type a calculation expression with a hex number (e.g. 0x12AB) or binary number (e.g. 0b1010) and the calculator will show the calculated result.
CLA has been signed.
> Add support for hex/binary numbers to calculator

- src/modules/launcher/PowerLauncher/PowerLauncher.csproj
Unused Package Referenced in a Project
Remove NuGet.CommandLine from PowerLauncher
Open the file PowerLauncher.csproj and See the Unused Reference.
> Remove Unused Package in PT Run

- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.WebSearch/Main.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.WebSearch/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.WebSearch/Properties/Resources.resx
Align subtitles for web search plugin
Change subtitle. 
Launch PT run and input the active command only to see if the result aligned with the result after keywords were entered. 
> [PT Run]Align subtitles for web search plugin

- src/modules/imageresizer/ui/Extensions/BitmapMetadataExtension.cs
- src/modules/imageresizer/ui/Models/ResizeOperation.cs
fixes regression #14715 
Resizing the [image](https://github.com/microsoft/PowerToys/issues/14715#issuecomment-989331525) was possible with version 0.49.1 and earlier. This fixes a regression introduced by me with PR #14914.
resizing image https://github.com/microsoft/PowerToys/issues/14715#issuecomment-989331525 works after this PR
> fix regression #14715 by adding an additional check for the newly build metadata object

- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/NativeMethods.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/Window.cs
Fix path not displayed for elevated process and task manager
Call `OpenProcess` with `PROCESS_QUERY_LIMITED_INFORMATION` instead of `PROCESS_ALL_ACCESS`.
- Open task manager and some apps as administrator
- Search opened window in PT Run
- Task manager and opened apps should display path as expected
- New changes: PT Run should be able to restore minimized task manager and elevated windows
> [Window Walker] Path for elevated process

- src/modules/launcher/PowerLauncher/Helper/EnvironmentHelper.cs
If the machine variables list doesn't contain a path variable, but user variable list does we get a crash while merging both lists:
```
Version: 0.53.3.0
OS Version: Microsoft Windows NT 10.0.19044.0
IntPtr Length: 8
x64: True
Date: 13-Jan-22 12:16:15 PM
Exception:
System.Collections.Generic.KeyNotFoundException: The given key 'Path' was not present in the dictionary.
at System.Collections.Generic.Dictionary2.get_Item(TKey key)
at PowerLauncher.Helper.EnvironmentHelper.GetMergedMachineAndUserVariables(Dictionary2 environment)
at PowerLauncher.Helper.EnvironmentHelper.<>c__DisplayClass2_0.b__0()
at Wox.Infrastructure.Stopwatch.Normal(String message, Action action)
at PowerLauncher.Helper.EnvironmentHelper.GetProtectedEnvironmentVariables()
at …
```
> [PT Run] Fix crash in EnvHelper if no machine path var exists

- src/modules/videoconference/VideoConferenceProxyFilter/VideoCaptureDevice.cpp
- src/modules/videoconference/VideoConferenceProxyFilter/VideoCaptureProxyFilter.cpp
For some reason, it doesn't crash on my machine (probably due to heap allocation APIs providing non-reused memory chunks on my system with 64GB RAM and an empty VM), but I was able to reproduce and debug it on a remote host. The issue was that `VideoCaptureProxyFilter::EnumPins` should initialize its `ppEnum` out parameter to `nullptr` in all cases, which we didn't do. I've also inspected all other methods accepting `**`-typed values and improved error reporting.
> [VCM] Initialize out method arguments in all erroneous cases

- src/modules/videoconference/VideoConferenceModule/VideoConferenceModule.cpp
Do not unmute devices on exit due to privacy issues.
Possible concerns: need to start PT again or change camera device in the app if you want to unmute it again.
> [VCM] Restore microphone muted states to their original state on exit

- src/modules/previewpane/GcodePreviewHandler/GcodePreviewHandlerControl.cs
- src/modules/previewpane/GcodeThumbnailProvider/GcodeThumbnailProvider.cs
- src/modules/previewpane/UnitTests-GcodeThumbnailProvider/GcodeThumbnailProviderTests.cs
Makes the G-code thumbnails transparent.
Dark mode:
Just a change to the output bitmap to include the unaltered alpha channel.
> Keep Gcode thumbnails transparency as is

- doc/devdocs/modules/powerpreview/monaco/readme.md
- doc/devdocs/modules/powerpreview/monaco/update-monaco-editor.md
Adds a doc for monaco maintaining
> monaco devdocs

- .gitignore
After https://github.com/microsoft/PowerToys/pull/15138 , building the installer creates `installer/PowerToysSetup/MonacoSRC.wxs`, which gets recognized as a new file by git.
Add the generated file to `.gitignore` so it doesn't get included in any future PRs by mistake.
Build the installer, verify `installer/PowerToysSetup/MonacoSRC.wxs` isn't listed with `git status` as an untracked file to add.
> [meta]git ignore monaco generated installer file

- .github/actions/spell-check/expect.txt
- src/modules/alwaysontop/AlwaysOnTop/AlwaysOnTop.cpp
- src/modules/alwaysontop/AlwaysOnTop/AlwaysOnTop.h
- src/modules/alwaysontop/AlwaysOnTop/WindowBorder.cpp
- src/modules/alwaysontop/AlwaysOnTop/WindowBorder.h
Completely release window border resources to reduce CPU/GPU consumption instead of hiding the border. 
It's expected now that the border will be shown with some delay when switching the virtual desktop.
> [AlwaysOnTop] Release/recreate borders instead of hiding/showing

- src/runner/main.cpp
Instead of loading settings from file when saving on closing , take runtime settings.
- Restart PT as admin
- Turn on Always run as administrator
- Turn off any module
- Exit PT
- Start PT
Confirm that disabled module is still disabled
> Fix disabling module as admin

- src/settings-ui/Settings.UI/Views/AlwaysOnTopPage.xaml
- src/settings-ui/Settings.UI/Views/VideoConference.xaml
- Always On Top placeholder text now uses the correct x:Uid, resolving: #15348
- Put the admin warning under the enable setting, resolving: #15488
> [Settings] UX bugfixes

- src/runner/main.cpp
i.e. Don't save if PT was only scheduling a restart
- Run PT 0.55
- If not, enable 'always run as admin' option
- If needed restart PT so it's running as admin
- Disable any module
- Close PT
- Open PT
- Observe that disabled modules are ENABLED
Using this version of PT, repeat the steps and confirm that disabled modules are still disabled after restart.
> [runner] Save settings on closing only when PT was actually running

- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/OpenWindows.cs
With #15441 I have implemented a check for the DWM property `IsCloaked` to hide invisible uwp app windows (#13637). After the change, all windows assigned to a virtual desktop that is not the current visible one aren't listed in the results anymore.
This PR removes the check for `IsCloaked` property temporary until I have implement an improved version of the check.
Tested the behavior.
> [PT Run] WindowWalker: Temporary remove IsCloaked check

- src/runner/general_settings.cpp
- src/runner/powertoy_module.cpp
PowerToys that use the `HotkeyEx` interface for activation register a global hotkey that overrides that same hotkey on other Applications even if the PowerToy is disabled.
When updating HotKeyEx, only register it for enabled modules and deregister it for disabled modules.
Update HotKeyEx when disabling or enabling modules.
Add a log message for using HotKeyEx similar to when using the centralized keyboard hook.
1. Verify Visual Studio shows the "Attach to Process" window when you press Ctrl+Alt+P.
2. Start PowerToys and enable the Mouse Pointer Crosshairs PowerToy with the Ctrl+Alt+P shortcut. Verify it works.
3. Disable Mouse Pointer Crosshairs, focus Visual Studio and press Ctrl+Alt+P. Verify …
> [Runner]remove hotkeyEx when disabling a module

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsTerminal/Helpers/TerminalQuery.cs
Before this change we query the AppUserModellID (AUMID) for every installed terminal app on every query. Because the method we used is async we sleeped 100 ms in a loop while waiting for the result. This leads to high query times: On each query up to 250 ms when wt and wt prev are installed.
I have changed the code and now we have query times up to 15 ms on fast machines and up to 35 ms on slow machines.
Now that we [know](https://github.com/microsoft/PowerToys/pull/15836#issuecomment-1025204301) that the AUMID didn't change in the future we can write it fixed in the code. Then we don't have to query it and the plugin queries become faster.
I have changed the package list into a dictionary and it now contains the packages names and …
> [PowerToys Run] Windows Terminal plugin: Improve query speed

- src/runner/main.cpp
- src/runner/restart_elevated.cpp
- src/runner/restart_elevated.h
> Fallback to run as admin after install, if running PT as user not possible

- src/modules/videoconference/VideoConferenceProxyFilter/VideoCaptureProxyFilter.cpp
Turns out NVIDIA broadcaster always expects `IPin` enumerator to be not null. We provide it with zero pins when no cameras are present.
> [VCM] Fix crash with NVIDIA broadcaster

- src/modules/videoconference/VideoConferenceModule/VideoConferenceModule.cpp
only unmute the virtual webcam when the module is disabled, since we're doing that only for our pass-through proxy cam
- disable the module
- make sure the mic is still muted
> [VCM] Do not unmute mics on disabling the module

- .pipelines/release.yml
- tools/BugReportTool/BugReportTool.sln
removal of this warning:
look at CI system
> Remove build server warning

- .github/actions/spell-check/expect.txt
- .vsconfig
- PowerToys.sln
- src/modules/ShortcutGuide/ShortcutGuide/ShortcutGuide.vcxproj
- src/modules/ShortcutGuide/ShortcutGuideModuleInterface/ShortcutGuideModuleInterface.vcxproj
- src/modules/alwaysontop/AlwaysOnTop/AlwaysOnTop.vcxproj
- src/modules/awake/AwakeModuleInterface/AwakeModuleInterface.vcxproj
- src/modules/fancyzones/FancyZones/FancyZones.vcxproj
- src/modules/fancyzones/FancyZonesTests/UnitTests/UnitTests.vcxproj
- tools/project_template/ModuleTemplate/ModuleTemplateCompileTest.vcxproj
removed SDK "Microsoft.VisualStudio.Component.Windows10SDK.17134" because is not required anymore.
VS should not ask to install the Windows 10 SDK v17134 anymore.
> Update vsconfig file

- src/README.md
I updated the settings-ui link, and removed the settings-web one
I tried the links and they worked in my repo
I've signed this.
> Fix broken link

- src/runner/main.cpp
After https://github.com/microsoft/PowerToys/pull/15920, PowerToys is not showing OOBE Welcome page after install. The reason for this is that it saves that it called OOBE before actually restarting as not elevated.
Only save that oobe was called if the call to open oobe is called inside runner.
Uninstall Powertoys, delete %localappdata%\Microsoft\PowerToys, install PowerToys built from this branch and verify the OOBE opens in the Welcome page.
> [OOBE]Not showing Welcome page after install

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/Microsoft.PowerToys.Run.Plugin.Calculator.csproj
- src/modules/launcher/PowerLauncher/PowerLauncher.csproj
> removing nowarn's

- src/modules/MouseUtils/FindMyMouse/FindMyMouse.cpp
- src/modules/MouseUtils/FindMyMouse/FindMyMouse.h
- src/modules/MouseUtils/FindMyMouse/dllmain.cpp
- src/settings-ui/Settings.UI.Library/FindMyMouseProperties.cs
- src/settings-ui/Settings.UI.Library/ViewModels/MouseUtilsViewModel.cs
- src/settings-ui/Settings.UI/Converters/FindMyMouseActivationShakeMouseIntToVisibilityConverter.cs
- src/settings-ui/Settings.UI/Settings.UI.csproj
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/MouseUtilsPage.xaml
Some users report find my mouse shaking activation being too sensitive.
This adds a setting so that there's a configurable minimum distance travelled for activation.
Logic for only activating Find My Mouse if the distance considering for detecting the shake is greater than a configurable distance.
Setting that only appears in settings if the activation method is "Shake mouse".
Play with the setting and see if it's applying. Higher values should make it harder to activate Find My Mouse.
> [FindMyMouse]setting for minimum shake distance

- src/codeAnalysis/GlobalSuppressions.cs
- src/modules/colorPicker/ColorPickerUI/ColorPickerUI.csproj
- src/modules/colorPicker/ColorPickerUI/Program.cs
- src/modules/colorPicker/UnitTest-ColorPickerUI/Helpers/ColorConverterTest.cs
- src/modules/colorPicker/UnitTest-ColorPickerUI/UnitTest-ColorPickerUI.csproj
> [ColorPicker] Enable analyzer and fix warnings

- .github/actions/spell-check/excludes.txt
Fixes #15753
* Adds excludes entry for `.pipelines/ESRPSigning_core.json`
* Look for a ✅ . 
* The log should show check-spelling is checking one fewer file than it was previously checked:
```diff
-Checking 2143 files
+Checking 2142 files
```
> spelling: Ignore .pipelines/ESRPSigning_core.json

- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/OpenWindows.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/ResultHelper.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/Window.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Main.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Properties/Resources.resx
- src/modules/launcher/Wox.Plugin/Common/VirtualDesktop/VDesktop.cs
- src/modules/launcher/Wox.Plugin/Common/VirtualDesktop/VirtualDesktopHelper.cs
The Window Walker plugin is crashing on startup when no Virtual Desktops exist.
Window Walker changes:
- With less than two desktop or if we can't read the desktop list the setting "Only windows from visible desktop" is not functional.
- Fixed typos in settings names.
VirtualDesktopHelper changes:
- The crash is fixed. 
- If the registry values are lost at runtime we keep the already known values. If they are missed on startup we set `DesktopList` and `CurrentDesktop` it to be empty.
- Several changes to improve behavior on missing registry keys.
- Adding code to handle the new position of the `CurrentDesktop` registry value on Windows 11.
- Several improvements for logging behavior.
- Speed up code.
Note:
- As it was before we …
> [Wox.Plugin: VirtualDesktopHelper] [WindowWalker] Fixes and small improvements

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Main.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Properties/Resources.resx
This is a follow up on the PRs #17023, #17108
This PR moves the description of the new scoring setting into the secondary text element (settings description property).
Local build.
> [PT Run] [Settings] System plugin: Move settings description

- src/common/utils/modulesRegistry.h
- src/common/utils/registry.h
Since we're treating svg files as an image when we add the "picture" kind so that the files can be found when searching / filtering for pictures. This needs to be done at the HKEY_LOCAL_MACHINE level.
- Add file kind argument to the powerpreview handlers changeset.
- Add a required field to the changes, so that some changes may not be considered vital.
- Add the Picture kind to the .svg file type.
Disable and re-enable SVG thumbnail while running PowerToys as admin. In file explorer search in the PowerToys repo root for "kind:picture" and verify svg files appear. (Explorer restart might be needed)
> [SvgThumbnail]Register as a picture kind

- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Main.cs
- src/settings-ui/Settings.UI.Library/ViewModels/PowerLauncherViewModel.cs
- src/settings-ui/Settings.UI/Views/PowerLauncherPage.xaml.cs
Each change in PowerToys Run settings triggers a plugin reload for plugins with the IReload interface. Program plugin has this interface and takes a long time to load, despite having no setting that would necessitate a reload.
- Don't reload the Program plugin on every setting change.
- Don't save the settings 3 times for each change. Only once is needed.
- To fix a UI glitch while reloading settings due to frequent saves, only reload the PTRun Settings if we didn't trigger a save in the last 500 milliseconds.
- After searching for a Plugin in Settings, a bug causes it to not trigger saves anymore, fix this.
Try to trigger the 100% CPU and UI glitch described in the issue and verify it no …
> [PTRun][Settings][Program] Fix 100% CPU load issue

- src/modules/fancyzones/FancyZonesLib/FancyZonesWindowProperties.h
- src/modules/fancyzones/FancyZonesLib/Settings.cpp
- src/modules/fancyzones/FancyZonesLib/Settings.h
- src/modules/fancyzones/FancyZonesLib/SettingsConstants.h
- src/modules/fancyzones/FancyZonesLib/WindowMoveHandler.cpp
- src/modules/fancyzones/FancyZonesLib/WindowUtils.cpp
- src/modules/fancyzones/FancyZonesLib/WindowUtils.h
- src/modules/fancyzones/FancyZonesLib/ZoneSet.cpp
- src/modules/fancyzones/FancyZonesLib/trace.cpp
- src/settings-ui/Settings.UI.Library/FZConfigProperties.cs
- src/settings-ui/Settings.UI.Library/ViewModels/FancyZonesViewModel.cs
- src/settings-ui/Settings.UI.UnitTests/ViewModelTests/FancyZones.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/FancyZonesPage.xaml
Restore original corners on the window unsnapping from the zone.
> [FancyZones] Restore original corners

- src/runner/UpdateUtils.cpp
In https://github.com/microsoft/PowerToys/issues/17057#issuecomment-1075082130, the user logs were polluted with messages of trying to check for updates in a loop.
Use a sensible default for minutes before re-checking for an update to try to avoid infinite loops.
Code quality check is what I'm looking for here, since it's not clear how the user got this to happen, but this should help prevent it.
> [Updater]Use sensible default time between checks

- src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/ContextMenuLoader.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Programs/Win32Tests.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWPApplication.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Main.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/WindowProcess.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry/Helper/RegistryHelper.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Components/Commands.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsTerminal/Main.cs
- src/modules/launcher/Wox.Infrastructure/Helper.cs
- src/modules/launcher/Wox.Test/Plugins/WindowsIndexerTest.cs
Before this PR users can start app in PT Run as admin but not as other user.
This PR extends the class `Wox.Infrastructure.Helper`:
- Add "run as user" feature to `OpenInShell`.
- New `RunAsUser` method.
And this PR adds a `Run as different user (Ctrl+Shift+U)` context menu to the following plugins on result that shows a "run as admin" context menu:
- Program plugin (except uwp apps *)
- Shell plugin
- Search plugin
_*) UWP apps normally installed per user. There this menu makes no sense._
Build locally and test if user input mask is shown and build succeeds.
> [PT Run] Run as user feature

- src/modules/launcher/Wox.Plugin/Common/VirtualDesktop/VirtualDesktopHelper.cs
`VirtualDesktopHelper` crashes in `UpdateDesktopList()` if the registry paths not available.
This PR changes code to proper handle this case in all registry queries.
Break registry paths in the code and validate that the code behaves as it should and she variables contains the expected values.
> [Hotfix ?] [PT Run] Fix crash in VirtualDesktopHelper

- doc/devdocs/modules/launcher/plugins/system.md
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System.UnitTests/ImageTests.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System.UnitTests/QueryTests.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Components/Commands.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Components/NetworkConnectionProperties.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Main.cs
Users reported that PT Run becomes slow/or not usable if they have many network adapters.
1. Improve the code to reduce number of loops and switch to for loops.
2. We now only read the network Information if we need them for and ip/mac result query.
3. We only read the network Information again if the last query ip/mac query is at least 5 seconds old.
4. We return the results in two steps:
1. The fast results like shutdown.
2. The slow results like mac or ip.
KNOWN BEHAVIOR/BUG: Delayed results aren't selected after shown to the user.
Created about 40 network adapters (Hyper-V switches) and tested if the results created faster and search behavior is more user friendly after the code changes.
A …
> [Hotfix ?] [PT Run] System plugin: Speed improvements and fixes

- .pipelines/ci/templates/build-powertoys-steps.yml
- .pipelines/release.yml
- installer/PowerToysSetup.sln
The Release build pipeline was (1) cleaning the PowerToysSetup solution,
which deleted the recently-signed PowerToys MSI and (2) rebuilding the
PowerToys MSI regardless of cleaning (thanks to WiX.)
This resulted in the final bundle _still_ containing an unsigned MSI
despite all our attempts to sign it.
I've turned off build cleaning and broken the dependency between
PowerToysBootstrapper and PowerToysSetup. This results in msbuild not
running the PowerToysSetup project's build steps at all, and therefore
not overwriting the signed msi with a newly-linked unsigned one.
> **NOTE**: This will impact your ability to <kbd>F5</kbd>-run the
bootstrapper from within Visual Studio. Going forward, you'll need to
build the MSI separately …
> Make sure the final WiX bundle contains a *signed* MSI

- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
https://github.com/microsoft/PowerToys/pull/17184 made it so we didn't list invalid shortcuts.
Some empty shortcuts are still valid, however, such as the classic shortcuts to File Explorer or Control Panel.
Still list shortcuts with empty targets.
Verify File Explorer appears again in PowerToys Run.
> [PTRun][Program]List special empty shortcuts

- src/modules/fancyzones/FancyZonesLib/WindowUtils.cpp
Fixed window size with non-100% monitor scaling.
Thanks @Jay-o-Way for the investigation :)
* Set scaling different from 100%
* Turn the `Restore the original size of the window when unsnapping` option on
* Snap window
* Unsnap window
* Verify the size is the same as before snapping
> [FancyZones] Restore window size fix

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsTerminal/Helpers/TerminalQuery.cs
Several users are reporting windows terminal plugin doesn't show results.
Added logging that could help to understand the issue.
> [PT Run][Windows Terminal] Logging missing profiles

- doc/devdocs/readme.md
- doc/specs/SCOOBE.md
- src/runner/Resources.resx
change `Github` to `GitHub` in docs and localization file
update some docs and localization file
> Fix 'GitHub' text case

- README.md
- doc/devdocs/readme.md
- installer/PowerToysSetup/PowerToys.wxs
- installer/PowerToysSetup/Product.wxs
- src/settings-ui/Settings.UI/PowerToys.Settings.csproj
- src/settings-ui/Settings.UI/Properties/PublishProfiles/InstallationPublishProfile.pubxml
After https://github.com/microsoft/PowerToys/pull/17797 , settings won't open when ran from the installer.
The main reason for it is that after running publish for building the installer, it's not properly configured to use the proper "win10-x64" runtime identifier.
- Use the "win10-x64" runtime identifier for building.
- Use the "win10-(target)" for publishing.
- With proper publishing, native runtimes for winappsdk are now copied to their proper places alongside the settings executable, so update installer.
- WinAppSDK 1.0.2 mentions some fixes for building with .net 6 https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-102 , so upgrade WinAppSDK to latest (1.0.3).
**How does someone test / …
> [Settings]Fix WinUI3 publish issues

- src/runner/main.cpp
- src/runner/restart_elevated.cpp
When trying to run PowerToys non-elevated, we're passing the `--dont-elevate` argument again, meaning the new process will just fail and try it again in a loop of creating new processes.
- Don't call new processes with `--dont-elevate` in a loop. If runner receives this argument, it should try to start non-elevated but shouldn't request the new process to try it as well.
- If the runner can't restart non-elevated, just fail, don't try to keep running elevated. There's likely a good reason for not being able to run non-elevated like using another admin user to install PowerToys. The process shouldn't try running as other user elevated when it fails to run non-elevated, as that new process would use another user's settings.
**How does …
> [runner]Fix non-elevated restart loop

- .github/workflows/spelling2.yml
GitHub apparently changed the behavior of raw.githubusercontent.com.
Previously, https://raw.githubusercontent.com/:org/:repo/HEAD/:path worked.
It no longer works.
Instead, we will use the master branch.
https://github.com/microsoft/PowerToys/pull/17936#issuecomment-1111119529
This overrides the `cspell` mapping to use a path that currently works.
Here's a current run showing it works: https://github.com/jsoref/PowerToys/actions/runs/2233958230
If you want to test, you can pull the branch into your own repository.
Unfortunately, changes to the workflow file aren't tested as part of a PR.
I'll eventually move this config into the action metadata folder (but not for the coming release).
A CLA …
> Fix check-spelling

- src/Update/PowerToys.Update.cpp
The update file downloaded in `%LOCALAPPDATA%\Microsoft\PowerToys\Updates` is deleted only if the update succed.
If the user decide to manually update from GitHub the downloaded updated is not deleted.
Lastly several users reported that  `%LOCALAPPDATA%\Microsoft\PowerToys\Updates` isn't cleanup: maybe file in use after the update?
**What is included in the PR:**
Perform a cleanup of obsolete msi/exe if PowerToys is up-to-date during update installation.
I have tested in debug enabling the check update button and changing PT version in `updating::get_github_version_info_async`.
- Copy some fies in  `%LOCALAPPDATA%\Microsoft\PowerToys\Updates`: exe, msi and txt
- Simulate an update from 0.56.0: every msi/exe should be deleted. …
> [Runner] Updates dir cleanup

- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/VSCodeHelper/VSCodeInstances.cs
This patch will improve discovery of non-standard (e.g. portable) installations of VS Code.
Minor change to how VS Code binaries are found (added case insensitive flag to string comparison)
I don't know ¯\\_(ツ)_/¯
> add case insensitivity to VS Code binary detection

- src/settings-ui/Settings.UI/Controls/CheckBoxWithDescriptionControl.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/MouseUtilsPage.xaml
- src/settings-ui/Settings.UI/Views/PowerLauncherPage.xaml
- src/settings-ui/Settings.UI/Views/ShortcutGuidePage.xaml
This PR solves a couple of minor Settings UX issues: 
#17943 - WordWrapping is now on for the Header text
#16884 - The TextBox in the Expander will now be disabled
#17110 - Fixed margins
> [Settings] Minor UI fixes

- src/modules/powerrename/PowerRenameUILib/MainWindow.xaml.cpp
- src/modules/powerrename/PowerRenameUILib/PowerRenameUI.vcxproj
- src/modules/powerrename/PowerRenameUILib/PowerRenameUI.vcxproj.filters
Fix regression - Open PowerRename on current monitor
Add missing reference to Version proj
Minor cleanup
- build and install PowerToys
- test if PowerRename is opened on correct monitor where it was spawned
> [PowerRename] Open PowerRename on current monitor

- src/settings-ui/Settings.UI.Library/Utilities/Helper.cs
- src/settings-ui/Settings.UI.Library/ViewModels/FancyZonesViewModel.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/FancyZonesPage.xaml
Show FZ settings for disable rounded corners only on Windows 11
@SeraphimaZykova does it make sense to skip ` FancyZonesWindowUtils::DisableRoundCorners(window)` if settings is enabled but OS is not Windows 11?
Another idea could be force disable of the setting if OS is not Windows 11.
- Disable rounded corners setting for FZ should be visible only on Windows 11
> [Settings][FancyZones] Rounded corners settings only on Windows 11

- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj
- src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj.filters
- src/modules/fancyzones/FancyZonesLib/FancyZonesWindowProcessing.h
- src/modules/fancyzones/FancyZonesLib/VirtualDesktop.cpp
- src/modules/fancyzones/FancyZonesLib/WindowMoveHandler.cpp
`Allow popup windows snapping` allows FancyZones to snap all popup windows including menus. 
Here is a fix for filtering those windows.
* Snap Visual Studio Code to a zone, and open any menu. Verify that the menu is where it's supposed to be and not on the top left corner of the zone.
* Same with MS Edge, you can check this by opening https://www.parkrun.ca/richmondolympic/results/latestresults/ and opening a menu.
Expected:
Wrong behavior:
> [FancyZones] Popup behavior fix

- .github/workflows/msstore-submissions.yml
Adds Microsoft Store Submission automation.
A YAML file that sends a new version of PowerToys to the Microsoft Store.
Manually running the yaml file. This will actually publish to the store, so be careful.
> Added automatic Microsoft Store integration

- src/modules/keyboardmanager/KeyboardManagerEngineLibrary/KeyboardEventHandlers.cpp
When triggering two shortcut remappings at the same time, the original remap was not being correctly released.
For example, when mapping "Shift(Left)+A" to "Shift(Left)+Q" and "Shift(Left)+S" to "Shift(Left)+W":
Then when you do the following sequence:
1. Press Shift
2. Press A
3. Press S
4. Unpress A
5. Unpress S
6. Press A
The output will be "QWA" instead of "QWQ" and further tries to use the remapping will fail until you press and unpress Q. The reason for this is that Q was not released at step 3 when the code is considering the new mapping.
When a new mapping is detected as the current one and the previous one is still active, release the action key triggered by the previous remapping as well.
**How does someone test / …
> [KBM]Fix concurrent shortcut remap locking key

- src/Update/PowerToys.Update.cpp
- src/common/updating/updateState.cpp
PowerToys.Update.exe now can recover from json containing current version and UpdateState::errorDownloading state + current time.
1. compile PT with Version.props = 0.59.0
2. Launch Settings, press "Check for Updates" to get an actual `githubUpdateLastCheckedDate` value copy it somewhere
3. Quit PT, set UpdateState.json to
```json
{"githubUpdateLastCheckedDate":"1654686636","releasePageUrl":"","state":1,"downloadedInstallerFilename":"","updateStateFileVersion":"v0.59.0"}
```
4. Substitute `githubUpdateLastCheckedDate` value with the value from step 2.
5. Launch Settings and press "Check for Updates" again, make sure that it changes to "Up to date" and not stays stuck with an error like it'd before.
A CLA must be signed. If …
> [Updating] Handle up-to-date from PowerToys.Update.exe

- src/modules/previewpane/UnitTests-MarkdownPreviewHandler/HelperFiles/MarkdownWithExternalImage.txt
This might be the problem why from time to time `MarkdownPreviewHandlerControlAddsBrowserToFormWhenDoPreviewIsCalled ` test fails - timeouts after 10s
> [Tests][MD preview] Don't target image on the internet in helper file

- .github/workflows/msstore-submissions.yml
`msstore-submissions.yml` was not sending the new Arm64 binaries to the Microsoft Store.
It now sends the new Arm64 URL to the Microsoft Store.
Run the task.
> Added Arm64 support on the store submission task.

- src/settings-ui/Settings.UI/OOBE/Views/OobeWhatsNew.xaml.cs
We added ARM64 architecture to our installer build. GitHub now provides two installer hashes for both architectures. 
Changed regular expression to eat new installer hash lines.
1. Start PowerToys
2. Open Welcome to PowerToys window
3. Hit What's New button.
4. Check there are no lines with installer hashes
> [OOBE] [What's New] Modified regular expression to hide "x64 ARM64 Installer Hash" lines.

- .github/actions/spell-check/expect.txt
- .pipelines/ci/templates/build-powertoys-ci.yml
I believe that there is a hidden "default branch" setting in Azure
DevOps, and ours is set to "master". CG only attempts to automatically
inject to builds off the default branch... and because we're a GitHub
repo running builds in AzDO we _can't change what the default branch
is_. Oops.
Copied from microsoft/terminal@e0bd76b30
> Make sure we run CG component detection on main

- .pipelines/ci/templates/build-powertoys-steps.yml
CI tests are timing out in CI. Prime suspect is that something changed with the WebView2 runtimes in the test machines. Let's try it out with this PR.
Disable tests that depend on WebView2.
CI is able to pass again.
> [ci][test]Disable tests that depend on WebView2

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/WindowsSettings.json
This PR updates the sharing settings results in Windows setting plugin.
_Note: After creating the screenshot I fixed name of nearby result._
Two new settings results are added and ones is updated with additional alt names.
Test results on local build.
> [PT Run] Settings plugin: Update sharing settings

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsTerminal/Helpers/TerminalQuery.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsTerminal/Main.cs
For speed up reasons we removed the call to GetAppListEntiresAsync in #15836.
Now that we have bumped min required os verison to 19041 we can go back to use api. But now we can use a non-async method. 
This PR implements the call to the method GetAppListEntries() and reverts some of the changes in #15836.
This PR adds scoring too for a better result order.
Local build and searching for terminal profiles.
> [PT Run] [Terminal Plugin] Use GetAppListEntires and add scoring

- src/modules/imageresizer/dll/ContextMenuHandler.cpp
- src/modules/powerrename/dll/PowerRenameExt.cpp
Some users can use software that makes the windows 11 tier 1 menu entries not show.
Still show old context menus, even if it means showing duplicate entries.
Some users can use software that makes the windows 11 tier 1 menu entries not show.
Still show old context menus, even if it means showing duplicate entries.
Right-clicking on Windows 11 still shows the old context menus, even if these will show duplicate entries in some configurations.
> [Win11]Also show old context menus

- doc/devdocs/modules/launcher/plugins/onenote.md
The img src in the onenote.md doc had incorrect capitalization which resulted in the img showing as broken, this fixes that
> Fixing img src for onenote.md doc

- src/common/SettingsAPI/settings_objects.h
- src/common/interop/keyboard_layout.cpp
Fixes random backticks being sent on some keyboard layouts when Fancy Zones is enabled
The use of `ToUnicodeEx` means that the keyboard state may change.
Ref https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-tounicodeex#remarks
> As ToUnicodeEx translates the virtual-key code, it also changes the state of the kernel-mode keyboard buffer. This state-change affects dead keys, ligatures, alt+numpad key entry, and so on. It might also cause undesired side-effects if used in conjunction with [TranslateMessage](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-translatemessage) (which also changes the state of the kernel-mode keyboard buffer).
Recently, it's been made possible to not change the keyboard state when calling this function, so I added code …
> [General]Fix dead keys being pressed by PowerToys

- .github/actions/spell-check/expect.txt
- src/modules/launcher/Plugins/Microsoft.Plugin.Folder.UnitTests/Sources/Path/FolderHelperTests.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Sources/Path/FolderHelper.cs
This allows %HOMEPATH% to be expanded to \Users\myuser before adding the system drive.
> PowerToys Run - FolderHelper.Expand

- src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml
right now if you click the settings button from the editor, settings app will launch under the overlay.  This is to remove the setting button.
@marypcbuk was the person that found the issue.
**Why approach taken:**
we'd have to make the Settings window AoT to solve the edge cases.  If we didn't do this solution, a user could click the editor overlay and then still lose settings.
> commenting out settings button in FZ Editor

- src/modules/previewpane/StlThumbnailProvider/StlThumbnailProvider.cs
- src/modules/previewpane/StlThumbnailProvider/StlThumbnailProvider.csproj
- src/settings-ui/Settings.UI.Library/PowerPreviewProperties.cs
- src/settings-ui/Settings.UI.Library/ViewModels/PowerPreviewViewModel.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/PowerPreviewPage.xaml
Adds the ability to customize the color of the rendered STL models.
There is no easy way to change the color of the G-Code thumbnails as these are not generated, but extracted from the file metadata (those thumbnails images are generated by the slicer software and included as part of the g-code metadata)
> [FileExplorer] StlThumbnailProvider customization

- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter.UnitTest/InputInterpreterTests.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter.UnitTest/UnitHandlerTests.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/Community.PowerToys.Run.Plugin.UnitConverter.csproj
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/InputInterpreter.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/Main.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/UnitConversionResult.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/UnitHandler.cs
- src/modules/launcher/PowerLauncher/PowerLauncher.csproj
Upgrades UnitsNet package to newest version to have support for plural units, did some refactoring due to deprecations in the package, and extended support for the 'metre'->'meter' conversion to also work for 'metres' or 'centimetre'.
Added some unit tests for the new functionality
> [PTRun] Support for plural units and improve alternative spellings

- src/runner/main.cpp
When there is no Updates dir, PowerToys breaks.
> [runner] Fix issue on files cleanup when directory doesn't exist

- src/modules/colorPicker/ColorPickerUI/Helpers/ZoomWindowHelper.cs
This fixes an issue where the zoom level did not appear to be reset after closing and re-opening the zoom window of the Color Picker.
When showing the zoom window, the zoom factor (that determines the scale of the zoom) was only set when zooming beyond the first "step". When exiting the zoom menu by pressing <kbd>Esc</kbd> instead of zooming out, this zoom factor was not reset, so when the user would zoom in somewhere else again, the zoom would seem to be stuck at the previous value until the user would zoom a second step.
The fix is to always set this zoom factor, also on the first zoom step.
Manual testing
> [ColorPicker] Always set the zoom factor

- src/modules/alwaysontop/AlwaysOnTop/AlwaysOnTop.cpp
- src/modules/alwaysontop/AlwaysOnTop/AlwaysOnTop.h
* Pin window on top
* Open TaskView
* Move pinned window to another virtual desktop
* Return to the initial virtual desktop
* Verify border doesn't stay on the initial virtual desktop
> [AlwaysOnTop] Fix: Border stays after moving window to another desktop

- installer/PowerToysSetupCustomActions/CustomAction.cpp
- src/common/utils/package.h
- src/modules/MeasureTool/MeasureToolModuleInterface/dllmain.cpp
- src/modules/PowerOCR/PowerOCRModuleInterface/dllmain.cpp
- src/modules/ShortcutGuide/ShortcutGuideModuleInterface/dllmain.cpp
- src/modules/alwaysontop/AlwaysOnTopModuleInterface/dllmain.cpp
- src/modules/colorPicker/ColorPicker/dllmain.cpp
- src/modules/launcher/Microsoft.Launcher/dllmain.cpp
- src/modules/powerrename/PowerRenameUILib/MainWindow.xaml.cpp
- src/modules/powerrename/dll/dllmain.cpp
- src/runner/centralized_hotkeys.cpp
- tools/project_template/ModuleTemplate/dllmain.cpp
- tools/project_template/README.md
C++ exceptions should be caught by reference to prevent unnecessary object copy and type slicing.
> Catch std::exception by reference

- src/modules/poweraccent/PowerAccent.Core/PowerAccent.cs
Adds support for an uppercase ß: ß
Apparently toUpper doesn't recognize this letter.
> [QuickAccent] Fixed ß uppercase bug

- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Utils/ReparsePoint.cs
Modify the icoPath for App Execution Aliases (i.e. Run Commands) to reflect the underlying package.
In the `GetRunCommandProgramFromPath` method, set the `IcoPath` property of the `Win32Program` instance.
To locate the icon path, the redirection path is acquired from the registry, using the `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths` registry key. Reuse the existing `GetPathFromRegistrySubkey` method to acquire the redirection path (following the logic outlined in https://docs.microsoft.com/en-gb/windows/win32/shell/app-registration). Expand environment variables on this path.
The IcoPath is only set if a valid redirection path is found.
Manual testing. Justification: Code path depends on the Windows registry, and the existing code base does not allow for mocking this …
> Improve the icon shown for app execution aliases.

- src/modules/launcher/Wox.Plugin/Common/DefaultBrowserInfo.cs
Workaround to fix command path for Firefox installed through Microsoft Store
When Firefox is installed through Microsoft Store its registry command path is not between quotes.
as discussed https://github.com/microsoft/PowerToys/issues/19260.
The change looks for the registry key that does not contain quotes and contains firefox.exe
Adds the quotes for the command and lets the rest of the code deals with it.
Tested it manually testing that power run web search works with Firefox installed through Microsoft Store.
And tested it works ok for other browsers and Firefox installed from the .exe
> Power Launcher fix Firefox command path

- .pipelines/ci/templates/build-powertoys-steps.yml
Enabling the WebView2 tests again, to check if CI has been updated with the latest WebView2 fixes.
> [ci]Enable tests that depend on WebView2

- doc/devdocs/modules/keyboardmanager/keyboardmanager.md
Fix typo.
```
atleast -> at least
```
> Fix typo in keyboardmanager.md

- src/modules/colorPicker/ColorPickerUI/Behaviors/AppearAnimationBehavior.cs
- src/modules/colorPicker/ColorPickerUI/Mouse/IMouseInfoProvider.cs
- src/modules/colorPicker/ColorPickerUI/Mouse/MouseInfoProvider.cs
- src/modules/colorPicker/ColorPickerUI/ViewModels/MainViewModel.cs
The PR fixes issue described in https://github.com/microsoft/PowerToys/issues/17636#issuecomment-1095166440
**Root cause analysis**
According to conditions, the warning is printed if position cannot be found in any of available monitors.
However, the position in the warning is always `[-1,1]` and obviously it's invalid. 
It's taken directly from `MouseInfoProvider` right after `MouseInfoProvider` object creation. 
In `MouseInfoProvider` constructor, `_previousMousePosition`  is not getting initialized, therefore `-1,1` can be returned.
**Fix description**
Update mouse information in `MouseInfoProvider `constructor, therefore information provided by the object is valid right after it's creation.
Check Color Picker logs for warnings
> ColorPicker-17636: Fix warning "Failed to get ... mouse position-1,1"

- src/common/utils/registry.h
Added registry key has precedence over software/classes/.reg for previewing .reg files. In order to preview it, we need to add this key as well.
> [FileExplorer Add-ons][Dev files] Add regfile registry key for previewing .reg files

- src/modules/MouseUtils/MouseHighlighter/MouseHighlighter.h
- src/modules/MouseUtils/MouseHighlighter/dllmain.cpp
- src/settings-ui/Settings.UI.Library/MouseHighlighterProperties.cs
- src/settings-ui/Settings.UI.Library/MouseHighlighterSettings.cs
- src/settings-ui/Settings.UI/Views/MouseUtilsPage.xaml
Consistent opacity setting across mouse mouse utils.
- Changed Mouse Highlighter opacity from 0-255 to 1-100
- Added code for migrate current value
Need to handle check settings version on ViewModel and utility since the JSON won't be updated until the settings page is opened.
- Open stable PT build
- Enable Mouse Highlighter
- Set opacity approx 130
- Open this PT build
- Start Mouse Highlighter
- Validate that opacity is approx 50%
- Open Mouse Highlighter settings
- Check that `%LOCALAPPDATA%\Microsoft\PowerToys\MouseHighlighter\settings.json` is migrated to version 1.1 and opacity is converted to %.
- Delete `%LOCALAPPDATA%\Microsoft\PowerToys\MouseHighlighter\settings.json`
- Open PT
- Check default opacity and version in the newly created …
> [Mouse Highlighter] Opacity 1-100

- src/modules/PowerOCR/PowerOCR/Helpers/OSInterop.cs
- src/modules/PowerOCR/PowerOCR/Helpers/WindowUtilities.cs
Fix focus on overlay on the first TextExtractor activation in most of the test cases.
<kbd>Esc</kbd> is not handled because, `overlay.Activate()` doesn't focus on the overlay window after the first run of TextExtractor.
In scope of this PR:
- added `WindowUtilities::ActivateWindow`
- removed unused code
1. Close PowerToys
2. Open PowerToys
3. Press TextExtractor hotkey (<kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> by default)
4. Press <kbd>Esc</kbd>
5. Overlay should be closed
> TextExtractor-20950: fix focus on overlay on the first TextExtractor activation

- .github/ISSUE_TEMPLATE/bug_report.yml
Asks the user to include the install method in their Bug Report.
Some bugs seem to appear only when installing through certain methods, so this would make it easier to reproduce. This issue comes to mind, as an example: https://github.com/microsoft/PowerToys/issues/21108
> [GitHub]Add install method to issue template

- src/modules/PowerOCR/PowerOCR/Helpers/ImageMethods.cs
related PR: https://github.com/microsoft/PowerToys/pull/20415
CJK OCR can detect non-CJK character like English. So, we need to add space between
- non-CJK word and non-CJK word
- non-CJK word and CJK word
> [TextExtractor] Add space between CJK words and non-CJK

- src/modules/poweraccent/PowerAccent.Core/PowerAccent.Core.csproj
- src/modules/poweraccent/PowerAccent.Core/PowerAccent.cs
Fixed position calculation for scaled desktops - where the scale is not the default 100%.
Modified the calculation for positioning on scaled desktops. Removed DPI adjustment as the system delivers adjusted values for the desktop size and position.
Tested all combinations: main and secondary monitor default and modified scale, different positionings. Tested on Windows 11
> Fix positioning on scaled desktop for issue microsoft#21059

- src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
- src/modules/launcher/Wox.Plugin/Result.cs
Hide PowerToys Run if the result action returns `true`, otherwise keep it open.
The solution is similar from the original:
https://github.com/Wox-launcher/Wox/blob/master/Wox/ViewModel/MainViewModel.cs#L211-L219
I have only made sure that the code compiles.
> PowerToys Run: Fix always hide after executing result

- doc/gpo/assets/PowerToys.admx
- doc/gpo/assets/VERSION.txt
There was an obsolete using that prevented users from import into Intune management.
In addition to the fix this PR adds a version information file. This file helps users to identify the downloaded admx later.
_nothing_
> [GPO] Fix the admx file by removing obsolete using

- .pipelines/ci/templates/build-powertoys-ci.yml
- .pipelines/ci/templates/build-powertoys-steps.yml
Just trying to see if building without multiprocessor fixes the current build issues on arm64.
Please ignore this PR
> [TEMP][ci]Remove multiprocessor build

- Cpp.Build.props
- src/common/updating/updating.cpp
- src/runner/unhandled_exception_handler.cpp
Turn on warning 4127 and changing 1 if expression to if constexpr
Unit Tests and CI
> Analyzers cpp turn on 4127

- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.cpp
An issue as been up about QuickAccent is been open after locking and unlocking the session on Windows 11 https://github.com/microsoft/PowerToys/issues/21036
A check has been added if the key still stroke when trigger is called (like space bar for example).
> disable trigger if letter is not longer pushed

- src/modules/poweraccent/PowerAccent.Core/PowerAccent.cs
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.cpp
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.h
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.idl
Detect shift key to navigate characters backwards with activation key set to space.
- Set activation key to space (also test with left/right/space)
- Activate quick accent
- Validate that shift + space is navigating characters backwards (left/right shift)
> [QuickAccent] Shift + Space to navigate backwards

- src/runner/settings_window.cpp
When closing the settings window, we're deleting the IPC, but some other thread might still try to access it.
Add some synchronization to avoid it.
Add a mutex and some locks to make sure we're checking for the ipc existence, using it, or deleting it only in one thread at the same time.
Tried reproing the issue #22137, without success.
> [Runner]Fix concurrency crashes when accessing ipc

- .config/dotnet-tools.json
- .pipelines/ci/templates/build-powertoys-steps.yml
- .pipelines/verifyNugetPackages.ps1
- src/modules/FileLocksmith/FileLocksmithUI/FileLocksmithUI.csproj
Validate consolidated Nuget packages in the build pipeline.
```
...
2022-11-23T19:28:44.2080069Z --------------------------------------------------------------------------------------
2022-11-23T19:29:00.9448407Z Tool 'dotnet-consolidate' (version '2.0.0') was restored. Available commands: dotnet-consolidate
2022-11-23T19:29:00.9449197Z 
2022-11-23T19:29:00.9449600Z Restore was successful.
2022-11-23T19:29:06.1290678Z Analyzing packages in C:\a\_work\1\s\PowerToys.sln
2022-11-23T19:29:06.1348482Z Found 1 non-consolidated packages
2022-11-23T19:29:06.1348905Z 
2022-11-23T19:29:06.1349276Z ----------------------------
2022-11-23T19:29:06.1349763Z Microsoft.Windows.SDK.BuildTools
2022-11-23T19:29:06.1350186Z ----------------------------
2022-11-23T19:29:06.1356405Z FileLocksmithUI - …
```
> Fail build when nugets aren't consolidated

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.TimeZone/Helper/ResultHelper.cs
Fixed a coding error that prevents searching on standard time zone names in PTRun.
> Fix PTRun Time Zone plugin bug

- Cpp.Build.props
6031 - Return value ignored: 'called-function' could return unexpected value
26451 - Arithmetic overflow: Using operator 'operator' on a size-a byte value and then casting the result to a size-b byte value. Cast the value to the wider type before calling operator 'operator' to avoid overflow (io.2)
28182 - Dereferencing NULL pointer.
The warnings 6031, 26451, 28182 were added to the *DisableSpecificWarnings* list when enabling warnings level 4.
But they were already solved by other PRs so removing then from the exclude list.
CI
> [Analyzers][CPP] Turn on warnings 6031, 26451, 28182

- src/modules/poweraccent/PowerAccent.Core/Tools/Calculation.cs
- src/modules/poweraccent/PowerAccent.UI/Selector.xaml
- src/modules/poweraccent/PowerAccent.UI/Selector.xaml.cs
Fix the displaying selector window after the user login.
1. Log-in using userA
2. Run QuickAccent and insert some letter
3. Log-in using userB
4. Log-in using userA
5. Run QuickAccent and insert some letter
1. Log-in via RDP
2. Run QuickAccent and insert some letter
3. Close RDP connection, keep session alive
4. Connect again
5. Run QuickAccent and insert some letter
In both these scenarios 0.64 version shows a blank rectangle.
The latest version from the main (with improved UI) is not showing a window at all.
> [Quick Accent] fix showing selector window

- src/modules/peek/Peek.UI/Extensions/WindowExtensions.cs
- src/modules/peek/Peek.UI/MainWindow.xaml.cs
- src/modules/peek/Peek.UI/NativeMethods.txt
- Make window centering perfectly edge-to-edge by accounting for hidden window padding/margin
- Make window centering scale aware
> [Peek] Add scale awareness to window centering

- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml.cs
- src/modules/peek/Peek.FilePreviewer/Models/PreviewSizeChangedArgs.cs
- src/modules/peek/Peek.FilePreviewer/Peek.FilePreviewer.csproj
- src/modules/peek/Peek.FilePreviewer/Previewers/UnsupportedFilePreviewer/UnsupportedFilePreviewer.cs
- src/modules/peek/Peek.UI/MainWindow.xaml.cs
- src/settings-ui/Settings.UI.Library/PeekProperties.cs
- src/settings-ui/Settings.UI.Library/ViewModels/PeekViewModel.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/PeekPage.xaml
- Defaulting unsupported file previewer window to 40%
- Added settings for unsupported file previewer window width and height (Percentage of monitor)
- Falls back to 680x500 if the custom percentage is too small.
> [Peek] Unsupported File Previewer - Setting Window Size

- .github/actions/spell-check/expect.txt
- src/modules/PowerOCR/PowerOCR/Helpers/ImageMethods.cs
> The following submissions are relevant.
#20415 #20926
Like Kanji ,Hiragana, Katakana, Hankaku-Katakana, they all do not need blanks. Korean OCR engine behavior and rules are different from ZH and JP. So I just add JP and ZH. (combie pr #20926 and #20415)
Japanese
> origin pic
> original error result
```
そ の 後 、 2 人 の 住 む 関東 は 本格的 に 梅雨入 り し 、 雨 の 日 の 午前 た け の さ さ や か
な 交流 が は し ま る 。 タ カ オ は 心 に 秘 め て い た 靴職人 に な る 夢 を 語 り 、 あ る 理由
か ら 味覚障害 を 患 う ユ キ ノ は タ カ オ の 作 る 弁当 の 料理 に 味 を 感 し る よ う に な
る 。 ユ キ ノ は 弁当 の お 礼 に と タ カ オ に 「 靴作 り の 本 」 を プ レ セ ン ト し 、 タ カ オ
は ユ キ ノ の た め に 靴 を 作 る こ と に 決 め 、 お そ る お そ る 彼女 の 足 を 採寸 す る 。
```
> results now (fixed)
```
その後 、 2 人の住む関東は本格的に梅雨入りし 、 雨の日の午前たけのささやか
な交流がはじまる 。 タカオは心に秘めていた靴職人になる夢を語り 、 ある理由
から味覚障害を患うユキノはタカオの作る弁当の料理に味を感しるようにな
る 。 ユキノは弁当のお礼にとタカオに …
```
> [TextExtractor] fix error blanks in japanese OCR

- src/modules/peek/Peek.FilePreviewer/Previewers/UnsupportedFilePreviewer/UnsupportedFilePreviewer.cs
Preserves transparency from file icons.
> [Peek] Unsupported File Previewer - Preserve Transparency For File Icons

- src/common/logger/logger.cpp
Our use of spdlog is creating a thread for logging for each utility. This is spending 100K-200K CPU cycles each 3s for each PowerToys that uses logging, according to https://github.com/microsoft/PowerToys/issues/22286
Logging is sparse enough that we can just flush after each message instead of having so many threads spinning.
Built and verified with sysinternals Process Explorer that threads for each disabled modules are no longer being created for logging. Logging still occurs.
I see there are still some threads that can be started for FancyZones and VCM. Those will be investigated and fixed on another PR.
> [Logs]Don't create a thread for each logger

- src/modules/videoconference/VideoConferenceModule/VideoConferenceModule.cpp
- src/modules/videoconference/VideoConferenceModule/VideoConferenceModule.h
VCM currently uses File watchers for the settings, whether the module is enabled or disabled. That results in a lot of wasted cycles, as seen in https://github.com/microsoft/PowerToys/issues/22286
Verified with sysinternal's Process Explorer that the threads for the File Watcher are only running when VCM is enabled.
> [VCM]Only use File Watchers if modules is enabled

- .github/actions/spell-check/expect.txt
- Cpp.Build.props
Conditionally sets `PreferredToolArchitecture` to `arm64` while running Arm64 Visual Studio / MSBuild. 
Without Condition applied and running on Arm64 device:
With Condition applied and running on Arm64 device:
> [ARM64][Build] Prefer Arm64 Build Tools when building from Arm64 devices

- src/runner/settings_window.cpp
Running settings non-elevated and modules elevated when PowerToys is running elevated results
in settings making changes in one file (non-elevated user dir) and modules are reading settings
from different (elevated user) dir
I'd rather leave this commented out than removed, as we might want to bring this back if we encounter different issues caused by this change.
> Run settings elevated when PT is running elevated

- src/common/utils/elevation.h
We're getting some hits in watson crashing in the FindDesktopFolderView function.
I've been unable to replicate it, so added some null checks to see if hits improve.
> [common]Add null checks to FindDesktopFolderView

- doc/devdocs/readme.md
- The location of the ReadMe changed is `doc/devdocs/readme.md`
- There were errors in numbering at 2 places in the ReadMe. (Two points displayed in the same line, repeated same number for 2 consecutive points)
- Previously there was a mixture of `1.` `1.` `1.` ... and `1.` `2.` `3.` ... indexing in the readme doc with some errors in the latter which is changed to a uniform use of  `1.` `1.` `1.` ....
Choose the `1.` `1.` `1.` ... scheme of indexing because it is less error prone (since both the errors were in `1.` `2.` `3.` ... scheme only).
--
> Fixed DevDocs ReadMe Lists Numbering

- src/modules/launcher/PowerLauncher/SettingsReader.cs
- src/modules/launcher/PowerLauncher/ViewModel/ResultsViewModel.cs
- src/modules/launcher/Wox.Infrastructure/UserSettings/PowerToysRunSettings.cs
- src/settings-ui/Settings.UI.Library/PowerLauncherProperties.cs
- src/settings-ui/Settings.UI.UnitTests/ViewModelTests/PowerLauncherViewModelTest.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerLauncherViewModel.cs
- src/settings-ui/Settings.UI/Views/PowerLauncherPage.xaml
With reference to #22964
I wanted to add an option to tab through available results similar to tab completion in a shell, rather than having to tab through each context item, or having to move my left hand to the arrow keys.
For the added setting, added the corrosponding test for settings.json backward compatibility, and the app directly, seems to function correctly.
> Added option to tab through results directly instead of context buttons

- src/modules/peek/Peek.UI/Helpers/FileExplorerHelper.cs
> [Peek] Fix opening Peek when FE window is set to full name path

- .pipelines/installWiX.ps1
- doc/devdocs/readme.md
WiX 3 development version binaries seem to have been removed from the internet. All deadlinks here: https://wixtoolset.org/docs/v3/releases/v3-14-0-6526/
CI depended on those, since we had to use the development version for the arm64 installer.
We've created a fork for those in https://github.com/JaneaSystems/wix3/releases/tag/wix3-3.14.0.6526
The SHA256 are verified by the script, so we can be sure we're using the same installers.
CI passes again, able to build the installer
> [ci]Fix dead links for WiX 3 binaries

- .pipelines/installWiX.ps1
- doc/devdocs/readme.md
The WiX3 binaries were reinstated in the WiX website, so we can use official links again on our CI.
This reverts commit 07f3507f11abb2eb7aa5e1d80a6a6d0413dce655.
Currently checking if CIs still pass.
> Revert "[ci]Fix dead links for WiX 3 binaries"

- src/modules/fancyzones/FancyZonesLib/WindowDrag.cpp
- src/modules/fancyzones/FancyZonesLib/WindowDrag.h
* Turn on `Make dragged window transparent` option
* Open the Magic: The Gathering Online or Unity window
* Drag it without snapping 
* Make sure the opacity hasn't changed and window looks and works as before
> [FancyZones] Opacity reset fix

- src/runner/settings_window.cpp
- src/runner/settings_window.h
- src/runner/tray_icon.cpp
- src/runner/tray_icon.h
- src/settings-ui/Settings.UI/App.xaml.cs
- src/settings-ui/Settings.UI/FlyoutWindow.xaml.cs
- src/settings-ui/Settings.UI/MainWindow.xaml.cs
- src/settings-ui/Settings.UI/Views/ShellPage.xaml.cs
The system tray quick launcher flyout assumes that the taskbar is always on the bottom of the primary screen.
This PR makes it so that the flyout tries to appear closer to the place where the tray icon was clicked.
- Send the coordinates of the click to settings to make the flyout appear on those coordinates.
- Adapt according to the screen dpis.
- Refactor argument passing to the settings app so that optional arguments are taken into account.
Tried opening settings normally and from a module like PowerRename to verify it still opened correctly (arguments refactoring)
Verified many taskbar positions / dpis on Windows 10.
Tried showing the flyout both as the first thing after we start PowerToys and also after opening Settings.
> [Flyout]Appear next to the tray icon position

- README.md
This PR fixes a broken link in the recent readme update
The link to the `disk-usage-footprint.md` document was relative and didn't point to the right location. This PR fixes that by referencing it as an absolute path.
> Fix link to disk usage footprint document

- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/LayoutAssignedWindows.cpp
- src/modules/fancyzones/FancyZonesLib/LayoutAssignedWindows.h
- src/modules/fancyzones/FancyZonesLib/WorkArea.cpp
- src/modules/fancyzones/FancyZonesLib/WorkArea.h
* Enable `During zone layout changes, windows assigned to a zone will match new size/position`
* Set shortcuts to 2 custom layouts with different amount of zones
* Snap window to a zone whose number is present in both layouts
* Change the layout using a shortcut
* Verify window fits the zone 
* Snap window to a zone whose number is present in only one layout
* Change the layout using a shortcut
* Verify window didn't change its position
> [FancyZones] Fix window resize on layout change

- src/runner/UpdateUtils.cpp
Improve how runner is detecting wheter network is metered during in order to downlod the update.
The code is used by the settings callback and the backgound worker.
Preserved the old logic that consider metered a WWAN connection.
References:
- https://devblogs.microsoft.com/oldnewthing/20221013-00/?p=107285
- https://learn.microsoft.com/en-us/previous-versions/windows/apps/hh750310(v=win.10)
- Build PT with a version different than 0.0.1
- Set network as not metered from Windows settings
- Open PT settings
- Check for updates
- Update should be downloaded and PT should ask for install
- Set network as metered from Windows settings
- Open PT settings
- Check for updates
- Update should't be downloaded and PT should ask for download and install
> [Runner] Improve metered network detection

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Components/Commands.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Components/ResultHelper.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Main.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Properties/Resources.resx
This PR adds a default off setting to show two separate results for recycle bin instead of one with a context menu.
**Setting off (default):**
- One result: Open Recycle Bin
- Context menu: Empty Recycle Bin (Shift+Del)
**Setting on:**
- First result: Open Recycle Bin
- Second result: Empty Recycle Bin
Local build and test of behavior.
> [PT Run] System plugin: Setting for separate "Empty Recycle Bin" result

- src/settings-ui/Settings.UI/Helpers/ShellGetFolder.cs
- src/settings-ui/Settings.UI/Views/GeneralPage.xaml.cs
Used shell32 select folder dialog, as the WinUI3 version is not working while elevated.
Manual test
> [Settings] bkp and restore - select folder crash when elevated

- src/modules/interface/powertoy_module_interface.h
- src/modules/pasteplain/PastePlainModuleInterface/dllmain.cpp
- src/runner/centralized_kb_hook.cpp
When trying to use Ctrl+V as the activation shortcut for Paste as Plain Text, it wasn't working.
This PR adds a flag we can pass when a module's action simulates input so we can ignore it.
Set Ctrl+V as the activation shortcut of Paste as Plain Text and verify it still works.
> [PastePlain]Support Ctrl+V as activation shortcut

- .github/actions/spell-check/excludes.txt
Spell checker is adding this to every PR:
This PR excludes that file from spell checking.
> [ci][spellchecker]Ignore resx noisy file

- src/modules/powerrename/PowerRenameUILib/MainWindow.xaml.cpp
Fix the crash that happens on PowerRename when clicking select all while filter is active (only show files that will be renamed)
Manual Testing
> [Power Rename] Select all while filter is active

- src/modules/Hosts/Hosts/Hosts.csproj
- src/modules/PowerOCR/PowerOCR/PowerOCR.csproj
- src/modules/awake/Awake/Awake.csproj
- src/modules/colorPicker/ColorPickerUI/ColorPickerUI.csproj
- src/modules/poweraccent/PowerAccent.Core/PowerAccent.Core.csproj
- src/modules/poweraccent/PowerAccent.UI/PowerAccent.UI.csproj
- src/modules/previewpane/MonacoPreviewHandler/MonacoPreviewHandler.csproj
- src/settings-ui/Settings.UI/PowerToys.Settings.csproj
It seems that a few C# projects are using the namespace 'interop' from a C++/CLI project without adding project references in their own project files.
Build the project locally
> Add missing project references

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/AwakePage.xaml
This addresses an addition to #24183 based on feedback from @Jay-O-Way to make the Awake settings (expiration date/time) responsive.
> [PR Fix] Update the Awake settings to be responsive

- src/settings-ui/Settings.UI.Library/HotkeySettingsControlHook.cs
- src/settings-ui/Settings.UI/Controls/ShortcutControl/ShortcutControl.xaml.cs
- src/settings-ui/Settings.UI/Controls/ShortcutControl/ShortcutDialogContentControl.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
This PR fixes some bugs in our custom shortcut edit dialog:
- Missing error badge in "invalid key" warning.
- The dialog is not PT Settings theme aware.
- Fixed a bug that when it is open but the window has no focus the key inputs are still catched.
Before:
After:
- Added a resw comment for the shortcut instruction text. Currently the format markers gets lost on translation.
Local build and tested functionality.
> [Settings] Shortcut edit dialog: Fix bugs 

- doc/devdocs/readme.md
Fixes dead link to settings spec. `/doc/devdocs/settings.md` does no longer exist. I guess it was replaced with `settingsv2/`.
> Devdocs: Fix dead link to settings spec

- src/settings-ui/Settings.UI.Library/AwakeProperties.cs
- src/settings-ui/Settings.UI.Library/AwakeSettings.cs
Current behavior of PowerToys Awake for the "Keep Away Until Expiration" option is to set the default value to the minimum time offset ( `0001-01-01T00:00:00+00:00` ).
This seems to crash the DatePicker control on negative timezone offsets. because it will essentially try to show the day before the minimum.
This PR changes the default offset to current date when initializing the properties. It also checks when loading data to show in settings if the year is < 2 and sets it to current date instead.
- Set the computer's timezone to Pacific time (-8 hours offset).
- Replace "%localappdata\Microsoft\PowerToys\Awake\settings.json" with the one from the original issue.
[settings.zip](https://github.com/microsoft/PowerToys/files/11199628/settings.zip)
- Start PowerToys, go to Awake Settings page …
> [Awake]Fix crash on negative timezone offsets

- src/modules/registrypreview/RegistryPreviewUI/MainWindow.xaml
XAML fixes for the transparency on the command bar and unified radial corners.
Changes shortcuts for Save and Save As buttons.
Moved to FontIcon for icon which should work on systems that don't have the specific Symbol font.  Also picks up support for the original icon that was required for Edit 😄 
Changed the background property for the command bar from transparent to one of the theme brushes, so that the overflow from the ... button had an opaque background.
Also added radial corner settings to the TextBox and the DataGrid, to match the rest of the UX, changed the keyboard accelerators for Save and Save As to be more "normal" and updated the method used to show an icon.
Ran the window several times in different sizes as well as in light and dark theme modes.
> [Registry Preview] Fixes in for the command bar in XAML

- src/modules/registrypreview/RegistryPreviewUI/FileName.cs
- src/modules/registrypreview/RegistryPreviewUI/MainWindow.Events.cs
- src/modules/registrypreview/RegistryPreviewUI/OpenFileName.cs
- src/modules/registrypreview/RegistryPreviewUI/RegistryPreviewUI.csproj
- src/modules/registrypreview/RegistryPreviewUI/SaveFileName.cs
- src/modules/registrypreview/RegistryPreviewUI/Strings/en-US/Resources.resw
Calls a different API for the FilePicker UI, since the built in version fails, when called by an app with Admin rights.
Calling FileOpenPicker and FileSavePicker from within the app would cause a crash, if the app was launched as an Administrator. 
It appears that this is a known issue for these APIs, so the code now calls the Win32/PInvoke versions, which does not have an issue with Admin rights.  All other changes support this shift to the "new" API.
Tested the Open file... button and Save as.... with different elevated and non-elevated states.
> [Registry Preview] Moving to a different API to call the File Picker

- installer/PowerToysSetup/FileLocksmith.wxs
- installer/PowerToysSetup/Product.wxs
- installer/PowerToysSetup/RegistryPreview.wxs
Installer is missing the "Microsoft.UI.Xaml\Assets\NoiseAsset_256x256_PNG.png" asset file for Registry Preview and File Locksmith, causing some UI elements, like tooltips, to appear with a transparent background when the Transparency effects option is turned on in Windows Colors settings.
This PR adds those files and fixes the issue.
Build installer and verified installed File Locksmith and Registry Preview have opaque backgrounds.
> [Installer]Add missing xaml noise png assets

- src/runner/settings_window.cpp
This is my best guess of what is happening, so please question everything I wrote bellow. :)
Couldn't reproduce the issue on update, but managed to reproduce it in a different way (details bellow) and it looks like the same issue. Fixes modules being disabled after PowerToys update. More details bellow. I haven't seen any downside to removing this code, let me know if you can think of any.
There is a race condition while PowerToys is being started after the update because of the following logic https://github.com/microsoft/PowerToys/blob/main/src/Update/PowerToys.Update.cpp#L184 which ends up starting PowerToys right after the install (update) second time as installer is running it as well in the end: https://github.com/microsoft/PowerToys/blob/main/installer/PowerToysSetup/Product.wxs#L20 …
> [runner] Don't save settings on Settings app start

- src/Update/PowerToys.Update.cpp
- src/Version.props
PowerToys is already being started from the installer which is run by the updater
Couldn't reproduce the issue. More details here https://github.com/microsoft/PowerToys/pull/25647.
Build the installer with 2 new versions e.g. 70 and 71.
Install v70 - observe that PT is running after installation
Update to v71 - observe that OOBE is shown after update
> [updater] Do not start PowerToys from PowerToys.Update.exe

- Cpp.Build.props
- src/modules/MouseUtils/FindMyMouse/FindMyMouse.cpp
Resolves issues building with Visual Studio 17.6 by disabling the building of C++/23 Standard Library Modules. Fixes struct member object initialization issue that triggers C26495 with FindMyMouse. 
Built with both VS 17.5 and VS 17.6 Preview 5 to verify that both builds continue functioning properly.
> [CI] Fix for building with Visual Studio 17.6

- src/modules/registrypreview/RegistryPreviewUI/MainWindow.Utilities.cs
- src/modules/registrypreview/RegistryPreviewUI/Strings/en-US/Resources.resw
Adds special handling for DWORD and QWORD Value types with empty values.
Additional handling for these two specific Value types.
Additional handling for these two specific Value types.
> Updates to parsing for certain Value types and empty values

- nuget.config
- src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Main.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Shell/ShellPluginSettings.cs
This pull request is based on [issue 4283](https://github.com/microsoft/PowerToys/issues/4283), along with other related issues. It adds a WindowsTerminal configuration option for the ExecutionShell.
Currently we do not have any UI for configuring which shell runner to use, but we do have a config option that we can change to switch between different ExecutionShell "modes". Then ones currently available are Cmd, PowerShell and RunCommand.
Even though in Windows 11, PowerToys opens WindowsTerminal by default when running terminal commands (by ">") as Non-Administrator, when running the command as an Administrator (Ctrl+Shift+Enter by default), it opens the old Powershell GUI as Administrator. In Windows 10, it is worse, since there is no way to open WindowsTerminal by using ">" commands. …
> Added an option in ExecutionShell enum for WindowsTerminal

- src/runner/settings_window.cpp
This PR reverts https://github.com/microsoft/PowerToys/pull/25647 , as it caused some issues regarding information passing to the Settings app.
For example, after a clean install without any local files saved:
- Awake gets turned off when Settings is opened.
- All mouse utilities are turned on (some are supposed to be off by default).
- When you restart as admin through Settings the new Settings window won't allow you to enable VCM. You need to close settings window and start it again to be able to do it.
- Reverts https://github.com/microsoft/PowerToys/commit/4b1aadafc2a8db6ffeb954d57d7d12b4289d7e24
- Minimizes the number of calls to get_general_settings.
- Delete "%localappdata%\Microsoft\PowerToys".
- Start PowerToys.
- Open Settings app.
- Verify Awake is still enabled.
- Verify Mouse …
> Runner save before opening settings

- tools/CleanUp_tool_powershell_script/CleanUp_tool.ps1
Fixed typo in `CleanUp_tool.ps1`
Powershell script has `–` instead of `-` in some places. I changed it and tested in my system.
First time doing PR. Sorry if I missed some steps for PR.
> [tools]Fix typo for CleanUp tool powershell script

- .github/workflows/package-submissions.yml
winget automated submission has been broken for a bit because the `wingetcreate` tool was unable to differentiate between user and machine scope on its installers. 
With its latest 1.2.6.0 release, we're able to override scope for each URL: https://github.com/microsoft/winget-create/releases/tag/v1.2.6.0
Add the scope override to the installer links to automate it.
Tried locally in Powershell by running similar commands and verifying the manifests are created correctly in ./out :
```powershell
$wingetPackage = "Microsoft.PowerToys"
$github = Invoke-RestMethod -uri "https://api.github.com/repos/Microsoft/PowerToys/releases"
$targetRelease = $github | Where-Object -Property name -match 'Release'| Select -First 1
$installerUserX64Url = $targetRelease | Select -ExpandProperty assets -First 1 …
```
> [ci]Fix winget automation by overriding scope

- installer/PowerToysSetupCustomActions/CustomAction.cpp
- tools/BugReportTool/BugReportTool/ProcessesList.cpp
Bug report and install list of processes entries for Mouse Without Borders and Peek are not OK, due to not being comma separated.
This PR fixes that so we can get proper bug reports in case there are crashes in the Event Viewer.
> [BugReport][Install]Fix process lists for Peek and MWB

- .github/actions/spell-check/expect.txt
- src/modules/peek/Peek.UI/Extensions/HWNDExtensions.cs
- src/modules/peek/peek/dllmain.cpp
Ctrl+Space is a shortcut that's used in many different applications.
This PR makes it so we only consume the shortcut in the low level keyboard handler if it's actually the Desktop or a Shell window that's on the foreground.
Uses some of the same logic that is used in Peek UI to detect if it's a Desktop or Shell window but translated to C++
Verified Ctrl+Space still brings up Peek in the Desktop and File Explorer.
Verified that Ctrl+Space still triggers Intellisense/auto-complete on Visual Studio and VS Code.
> [Hotfix][Peek]Consume shortcut only on Desktop and Shell

- src/common/utils/elevation.h
- src/modules/peek/peek/dllmain.cpp
- src/modules/peek/peek/peek.vcxproj
- src/settings-ui/Settings.UI.Library/PeekProperties.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PeekViewModel.cs
- src/settings-ui/Settings.UI/Views/PeekPage.xaml
Add a Setting to always run Peek not elevated, which is on by default.
If running Peek un-elevated brings other issues, the users can still manipulate the Setting to troubleshoot.
Uses the same process to create Peek that PowerToys Run uses when trying to run non-elevated.
Changes the process handle we get for starting non-elevated to also get a PROCESS_TERMINATE permission.
Created a network share through `net use t: \\localhost\c$\tempshare` and verified that Peek didn't work on 0.70.0 when running elevated but it works with this change and the Setting turned on.
> [Peek]Create Setting to run not elevated

- src/settings-ui/Settings.UI/ViewModels/MouseWithoutBordersViewModel.cs
- src/settings-ui/Settings.UI/Views/MouseWithoutBordersPage.xaml
Fix issues introduced by 667aad247ada979423ff41cc4c5dd5583eef85f8
- reintroduced border thickness
- made default status transparent in accordance w/ the improved design
- connect 2 machines
- status is highlighted
> [MWB] fix machine connection status highlighting

- src/modules/MouseWithoutBorders/App/Class/Setting.cs
- src/settings-ui/Settings.UI.Library/MouseWithoutBordersProperties.cs
Currently, when "Hide mouse at the screen edge" is turned on, it keeps showing the mouse cursor at the top of the screen and things that are beneath still get activated, like showing tooltips under the mouse.
This PR fixes this.
This error comes from misevaluating the value of a non-editable Setting when porting the code originally. We set it to false when the correct default should be true.
Also removes the Setting that we misread from the Settings file.
Testing Mouse Without Borders with the Hide mouse at the screen edge option turned on hides the cursor. (It does create some weird pixels at the screen top, like original MWB did)
> [MWB]Hide cursor when setting to the top of screen

- src/modules/peek/Peek.UI/Extensions/WindowExtensions.cs
- src/modules/peek/Peek.UI/NativeMethods.txt
After #26364, the way to bring the Peek window to the foreground doesn't seem to be working correctly. It sometimes seems to bring keyboard input in but not mouse input, making the way that we try to detect loss of focus not work when the option to "Automatically close the Peek window after it loses focus" not work.
Changed the way we bring the Peek Window to the foreground mimic what we do on other PowerToys, which is to first send some mouse simulated mouse input and then bring the window to the foreground. This seems to be more stable.
Tested switching files multiple times with both the "Automatically close the Peek window after it loses focus" on and off, both on the Desktop and on an Explorer window.
> [Peek]Fix foreground window setting

- src/modules/peek/Peek.FilePreviewer/Previewers/MediaPreviewer/ImagePreviewer.cs
All 3 tasks awaited in `LoadPreviewAsync` are setting `Preview`. Therefore, there was a race condition causing low (or high) quality thumbnail was shown even when full image was available.
> [Peek] Fix race condition when setting preview

- installer/PowerToysSetup/Product.wxs
Change the installer so it doesn't remove the Mouse Without Borders Service on upgrading.
This helps fix the issue that on upgrading and not running as admin, the Mouse Without Borders service gets uninstalled as part of the upgrade process and then it doesn't get installed again because PowerToys is not running as admin automatically.
Unfortunately this won't help when upgrading from 0.70.0 to a newer version, but should help after that.
- Built 2 installers with different versions.
- Installed the earlier version.
- Set Mouse Without Borders to use service and verified it's installed in services.msc . PowerToys should be set to not start automatically as admin
- Upgrade to the newer version.
- Verify the PowerToys.MWB.Service is still installed in services.msc
> [Installer]Keep MWB service on upgrade

- src/modules/MouseWithoutBorders/App/Class/Program.cs
- src/modules/MouseWithoutBorders/App/Class/Setting.cs
Currently, Mouse Without Borders won't work correctly if the service is deleted but the user has the Use Service option turned on.
This PR adds some code to make MouseWithoutBorders start without the service and disable the Setting if it can't start the service.
It also disables the Use Service option if that's the case.
Set PowerToys Mouse Without Borders to use the service.
Exit PowerToys.
delete the service.
Start PowerToys without admin permissions.
Mouse Without Borders will still start correctly and disable the service mode.
> [MWB]Work without service if service doesn't start

- src/modules/MouseWithoutBorders/App/Helper/FormHelper.cs
- src/modules/MouseWithoutBorders/App/Helper/NativeMethods.cs
- src/settings-ui/Settings.UI/Views/MouseWithoutBordersPage.xaml
Sometimes it seems that the "Hide mouse at the screen edge" option doesn't work alright, because the helper form used to steal focus is not able to get focus correctly.
Harden it by simulating some mouse input first, similar to what we do on other utilities.
Built PowerToys and started it outside Visual Studio. (Debugger attached makes gaining focus easier according to Windows rules)
After that, tried going to another computer and verified the focus is indeed stolen and that the Window at the top of the screen doesn't get focused instead.
Disable/Enable Mouse Without Borders in the Settings.
Again, tried going to another computer and verified the focus is indeed stolen and that the Window at the top of the screen doesn't get focused instead.
> [MWB]Simulate input to gain focus when hiding mouse

- src/modules/poweraccent/PowerAccent.Core/Languages.cs
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.h
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.idl
Adds multiplication (U+00D7, U+22C5) and division (U+00F7) signs to Languages.cs
The pull request addresses the lack of common mathematical signs in Quick Accent
- [x ] **Closes:** #24768
Manually validated
> Add multiplication and division signs to Languages.cs

- src/modules/Hosts/Hosts/MainWindow.xaml.cs
- src/modules/Hosts/Hosts/Strings/en-us/Resources.resw
- src/modules/Hosts/Hosts/Views/MainPage.xaml
- src/modules/Hosts/Hosts/Views/MainPage.xaml.cs
- Improved Hosts File Editor UX with keyboard shortcuts
- Fixed an issue where the right click flyout menu didn't get focus
- Added edit option to context menu
- CTRL+N: add new entry
- CTRL+E: edit selected entry
- CTRL+P: ping selected entry
- Delete: delete selected entry
- The right click context menu get focus when is opened
- Test CTRL+E, CTRL+P and Delete with the context menu opened
- Test CTRL+E, CTRL+P and Delete with the context menu closed and the entry focused with keyboard
- Test CTRL+N
> [Hosts] Add Keyboard Shortcuts

- src/runner/main.cpp
Fixes #8277 by adding an additional check to the singleton used in launching PT from another process.
Manual testing that crash no longer occurs when relaunching the PowerToys executable with an instance already running.
> Fixed singleton crash when launching a second PT runner process

- src/modules/colorPicker/ColorPickerUI/Settings/UserSettings.cs
- src/settings-ui/Settings.UI.Library/ColorPickerProperties.cs
- src/settings-ui/Settings.UI.Library/ColorPickerSettings.cs
Store color history in a separate file.
Not storing the color history in the settings file, as it is not a setting and it gets overwritten by the settings page (and occassionly history gets lost). The color history is stored in the colorHistory.json file instead
tested locally
> [ColorPicker] Store color history in a separated file

- .vsconfig
The current .vsconfig file works when we go through Visual Studio and click the warning to install missing requirements. However, it doesn't seem to work when you install Visual Studio from scratch by selecting "Import configuration" from the Visual Studio Installer app.
For some reason, the warning on Visual Studio will install the "Microsoft.VisualStudio.Component.VC.ATL" component, while Visual Studio Installer Import Configuration won't, unless it's specifically in the .vsconfig file.
Installed Visual Studio from Scratch through the import configuration method.
> [Dev]Add missing ATL lib to .vsconfig

- src/modules/registrypreview/RegistryPreviewUI/MainWindow.Utilities.cs
A line of code got removed at some point, causing DWORD Values to not show its value in the previewers.
Add back a line that should have been there on the last check-in for this file.
Tested with my usual collection of REG files and actually looked for the value on in the grid.
> [Registry Preview] Fix for bug 27234 that doesn't display DWORD values.

- src/runner/Resources.resx
- src/runner/main.cpp
When moving across versions, modules like the file preview/thumbnail handlers or the context menu extensions might keep their old versions loaded in explorer.exe or a preview handler process.
Before, the installer just restarted after an update when needed, but now we've turned that off.
This PR adds a toast notification to show a message so that users know they should restart their computer when possible.
Deleted or changed version in "%localappdata%\Microsoft\PowerToys\last_version_run.json" to simulate a new version and start PowerToys. The toast notification should be shown.
**Attention:** To test this running from Visual Studio, you need to have a PowerToys version installed so that the toast notification registry entries for PowerToys are in place, otherwise no notification will be …
> [Runner]ask to restart the computer after update

- src/runner/tray_icon.cpp
- src/runner/tray_icon.h
This reverts commit 4bf031d28f5c66c188ca7de244921f3ee1cb14a2.
Let's revisit this for the next release. It causes the tray icon to disappear from time to time
> Revert "Use guid to identify icon (#27570)"

- src/runner/tray_icon.cpp
`RegisterWindowMessage` is a shared global resource that cannot be released back to the system until the session is logged off. A session unique message is not required for tray icons, Explorer does not care what its value is, it just needs to be unique in the WNDPROC of the HWND that registered the icon. The tray icon id is also internal to the HWND and can be any value when the HWND just registers a single tray icon.
> [Runner] Unnecessary RegisterWindowMessage

- src/settings-ui/Settings.UI/SettingsXAML/Views/GeneralPage.xaml.cs
A user reported Settings crashes when trying to press the "Windows color settings" link.
This PR catches exceptions and logs them instead.
Couldn't repro the original issue, so verified:
- Clicking still opens the settings in the page where you can switch theme.
- Replaced inner code of "StartProcessHelper.Start" with an exception and verified clicking the link creates a log entry instead of crashing.
> [Settings]Fix crash opening system color settings

- src/modules/registrypreview/RegistryPreviewUI/RegistryPreviewXAML/MainWindow.xaml
A recent update of awesomeness came through this app, cleaning up the UI in various ways, which is amazing.  However, a bug may have snuck back into the code around the icons used in the commandbar in various languages; this brings the fix back into the code.
In the XAML file, I've removed all references to Icon="Name" and replaced it with a corresponding FontIcon; I also added an explicit FontFamily to the FontIcon to avoid issues across Windows versions and languages, per the "best practices" called out in the WinUI 3 documentation.
Visually verified the UI:
> [Registry Preview] Update all AppBarButtons to use an explicit AppBarButton.Icon (Fix for 27766)

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/WindowsSettings.json
This PR updates the results for device pages and bluetooth pages in Win10 and Win11. It fixes the outdated command for "Control panel > Devices and printers" in Win11.
> [PT Run > Settings plugin] Update device and bluetooth results

- src/Update/PowerToys.Update.cpp
- src/common/updating/updating.cpp
- src/common/updating/updating.h
- src/runner/UpdateUtils.cpp
- src/runner/main.cpp
Installers and logs are currently cleaned on PT startup only if it's up to date.
If the users skips some updates, the installers are accumulated wasting disk space.
- Moved the method that cleanup installers and logs in the common updating library
- Cleanup before downloading a new version
- Build PT with an old version
- Put some logs in `%LOCALAPPDATA%\Microsoft\PowerToys` and some installers in `%LOCALAPPDATA%\Microsoft\PowerToys\Updates`
- Verified that when the new version is downloaded installers and logs are cleaned up (tested from runner and from updater)
- Verified that when PT is started up to date installers and logs are cleaned up
> [Runner] Don't accumulate installers

- .pipelines/ci/templates/build-powertoys-ci.yml
- .pipelines/ci/templates/build-powertoys-installer.yml
- .pipelines/release.yml
Using our own pools like this gives us a lot of freedom in the tooling that's installed, the OS versions it targets, and when we take on Visual Studio updates.
As part of this effort, I've also stood up a "small" agent pool. At the time of this PR, that pool is using D2ads-v5 SKU VMs (2 vcore 8 GiB) versus the "large" agent pool's D8as-v5 (8 vcore 32 GiB). Smaller build tasks can in the future be moved over to the small pool. Compilation's the hard part, so it gets to stay on the large pool.
> Switch away from the WinDev agent pools

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest/NumberTranslatorTests.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/CalculateEngine.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/NumberTranslator.cs
On locales where the dot (.) is not used as a separator for numbers, our number translation was removing leading zeros from what it thinks are simple number tokens.
For example for a user with the number cultures of French(France):
123.01+52.30 gets tokenized as `123` `.` `01` `+` `52` `.` `30`. Then the `01` gets transformed into `1`, meaning we're calculating 123.1+52.30
This PR introduces changes and tests to correct this behavior, by trying to keep leading zeroes when we're parsing numbers.
@Jay-o-Way, Thanks for pushing this forward 😉  Any more tests from issues you think are worth adding?
- Keep leading zeroes when parsing numbers.
- Add tests for these edge cases.
- Adapt the division by zero detection, since now numbers with leading zeroes will reach that step.
The tests that were …
> [PTRun][Calc]Keep leading zeroes on languages where . is not a separator

- src/modules/registrypreview/RegistryPreviewUI/MainWindow.Utilities.cs
- src/modules/registrypreview/RegistryPreviewUI/RegistryValue.xaml.cs
- src/modules/registrypreview/RegistryPreviewUI/Strings/en-US/Resources.resw
This PR updates the data grid in Registry Preview to properly show the data values shown in Registry Editor.
> [Registry Preview] Better preview in data grid like in Regedit

- src/modules/registrypreview/RegistryPreviewUI/MainWindow.Utilities.cs
After https://github.com/microsoft/PowerToys/pull/28488, Registry preview does some escape character checks. On this code there's an iterator increment that doesn't recheck for bounds, so this was causing a out of bonds exception for some files, like the one presented in the issue.
Opened the file indicated as crashing in the issue and verified it no longer crashes Registry Preview.
> [HotFix][RegistryPreview]Fix out of bonds array access error

- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesWindowProcessing.cpp
- src/modules/fancyzones/FancyZonesLib/WindowUtils.cpp
- src/modules/fancyzones/FancyZonesLib/WindowUtils.h
Check the popup windows style in `WindowCreated`.
0.74:
Fixed:
Snap the Godot window, open any menu, and verify it's opened as expected.
> [FancyZones] Filter for non-processable windows

- .github/workflows/spelling2.yml
This reverts commit d3edd6acc2ac6cef8630d089980b493713bd47ff.
Spell check is failing on main. Let's revert this recent upgrade from the bot.
> Revert "[Deps]Bump check-spelling/check-spelling from 0.0.21 to 0.0.22 (#28953)"

- src/modules/registrypreview/RegistryPreviewUI/MainWindow.Events.cs
- src/modules/registrypreview/RegistryPreviewUI/MainWindow.Utilities.cs
- src/modules/registrypreview/RegistryPreviewUI/RegistryPreviewXAML/App.xaml.cs
Was reviewing someone else's PR and decided to take look at two issues and ended up fixing a third and fourth.
- #26029
- #28147 
- No number: exception being thrown on first run, when size/position JSON file is missing.
- Found an exception that was being thrown on first run, when the app tries to load a json file that hasn't been created yet.  The code always caught the exception, but if a simple if statement can prevent it, yay.
- Adds support for files that may have whitespace around the = of a value line; a past fix enabled whitespace elsewhere.
- Fixes issue for non-ASCII filenames, when app is registered as the default handler. (This was neat: if the filename is only ASCII then the app gets activated as "File" activation but if there are non-ASCII characters, then it activates as …
> [Registry Preview] Ended up with four unrelated fixes in one PR - not a role model, sorry

- .github/actions/spell-check/expect.txt
- src/modules/peek/Peek.Common/NativeMethods.txt
- src/modules/peek/Peek.FilePreviewer/Controls/ShellPreviewHandlerControl.xaml
- src/modules/peek/Peek.FilePreviewer/Controls/ShellPreviewHandlerControl.xaml.cs
- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml
- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml.cs
- src/modules/peek/Peek.FilePreviewer/NativeMethods.json
- src/modules/peek/Peek.FilePreviewer/NativeMethods.txt
- src/modules/peek/Peek.FilePreviewer/Peek.FilePreviewer.csproj
- src/modules/peek/Peek.FilePreviewer/Previewers/Interfaces/IShellPreviewHandlerPreviewer.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/PreviewerFactory.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/ShellPreviewHandlerPreviewer/Helpers/IStreamWrapper.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/ShellPreviewHandlerPreviewer/ShellPreviewHandlerPreviewer.cs
This PR adds support for [preview handlers](https://learn.microsoft.com/en-us/windows/win32/shell/preview-handlers) that displays previews from supported applications like Microsoft Office (assuming the user has it installed).
This should also help with:
- #26422 as these previewers uses a standard API ([`IPreviewHandler`](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ipreviewhandler)) that's built into Windows and gets hosted by file managers like File Explorer and [Everything](https://www.voidtools.com/support/everything/).
- #26726 as File Explorer plans to move away from its preview pane.
> [Peek] Add support for preview handlers

- src/modules/videoconference/VideoConferenceModule/VideoConferenceModule.cpp
- src/modules/videoconference/VideoConferenceModule/VideoConferenceModule.h
After https://github.com/microsoft/PowerToys/pull/28658, I've started experiencing issues when using "Startup action: Mute". Specifically, I have 2 physical mic devices and NVIDIA Broadcast device, and NVIDIA device wasn't unmuting in 90% cases after initial mute.
After debugging, it turns out that the callbacks for `VolumeNotifier::OnNotify` are in a race with `setMuteChangedCallback` to make the NVIDIA device muted, since `getMicrophoneMuteState` was returing false for it, because we haven't unumted the tracked physical device.
This PR removes the new callback logic.
- use "Mute" startup action and toggle mute all mics back and forth, verify that all mics stay in the same state.
- use "Unmute" startup action and verify it works as wellA
> [VCM] do not trigger cascade of un/mute changes

- src/modules/peek/Peek.UI/MainWindowViewModel.cs
- src/modules/peek/Peek.UI/PeekXAML/MainWindow.xaml.cs
- src/modules/peek/Peek.UI/Services/NeighboringItemsQuery.cs
https://github.com/microsoft/PowerToys/pull/27444 introduced a bug that randomly occur and unfortunately I hadn't hit during the PR testing 😞
I started experiencing this on latest PT version (may be related to WinAppSDK upgrade?)...
- The `Activate` method bring window to foreground and sometimes make Peek steal the focus to Desktop/Explorer.
- Due to the focus stealing selected files aren't properly read from Desktop/Explorer and Peek stuck on loading.
The adopted solution is to read the foreground window handle only once and before activating the Peek window (this will also help a lot with debugging).
Tested the first Peek window activation multiple times with multiples previewers: preview is always loaded without stucking.
> [Peek] Fix first preview stuck loading

- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml.cs
- Preview a video using Peek
- Hide Peek
- Preview a file (not necessary another video)
- The previous video flashes before update the preview
This PR fixes the issue removing the source from the underlying `MediaPlayer` of the `MediaPlayerElement` control.
> [Peek] Fix previous video flashing when peek is invoked

- src/runner/UpdateUtils.cpp
When there is a new update for PowerToys a notification occurs. Within the body of the notification there is a "->" which is used to indicate version going to and from. This PR replaces that arrow with an actual arrow character: '⇨'
> Update Toast Notification Arrow "⇨" was "->"

- src/modules/registrypreview/RegistryPreviewUI/MainWindow.Utilities.cs
Updated the string functions called when processing Key values to be better about repeating key names.
Replaced String.Replace with String.Substring to avoid the removal of multiple instances of a string, rather than just the last one.
If a Key had multiple instances of the exact same string, when the Key was parsed when populating the UI, all instances of the string were replaced instead of the just the last one.  If a Key had the text "\Control1234\Control" when the right most leaf was processed, the Key became "1234" because all instances of "\Control" were removed.
Tested with the sample included in #29152 as well as my usual collection of files.  Also confirmed that "deleted Keys" would still work as there was some concern from the OP of the bug.
> Fix for bug 29152, where Key names were being mishandled and returned as "invalid" in the UX

- src/modules/launcher/PowerLauncher/SettingsReader.cs
Bug fix for PT Run.
PR https://github.com/microsoft/PowerToys/pull/28601 introduced the TextBox and NumberBox types for additional options.
Their default values are not initiated with `settings.json` like the `Value` property (for CheckBox) is.
This PR fixes it.
Manually tested and everything works fine.
> [PT Run] Fix PluginAdditionalOptions value properties defaults.

- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesWindowProcessing.cpp
This reverts commit 1b333dfee001b2654a16cc8774f8864e895db067.
The generalizing fix for not automatically snapping popups https://github.com/microsoft/PowerToys/commit/1b333dfee001b2654a16cc8774f8864e895db067 broke the snapping for some applications. We can't release a proper fix during the hotfix since that might break other applications, so we're reverting the change for now.
Calculator snaps again
Godot right menus still don't snap automatically
> [HotFix]Revert "[FancyZones]Filtering popup windows for all operations (#28975)"

- src/common/interop/interop-tests/InteropTests.cs
Sometimes the Interop Tests hung in CI. This seems to be caused by the sending of a message before the OS has set up the pipes correctly. We add a little wait to the test to reduce flakiness.
Ran the "TestSend" with "Run Until Failure" and it ran 1000 times without hanging.
> [Tests]Fix flaky interop tests

- .pipelines/ci/templates/build-powertoys-precheck.yml
Resolve issue caused by no pull request number being logged to a system variable when CI runs after PR is merged
> [CI] Fix prebuild check to use commit when no pull request number exists

- .pipelines/ci/templates/build-powertoys-precheck.yml
CI is currently failing the precheck on main:
This is because on push, there's no `system.pullRequest`.
Use Build.SourceVersion from https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services , since there's no PR.
> [ci]Fix precheck getting commit id in the fallback

- .github/policies/resourceManagement.yml
- CONTRIBUTING.md
Added bot trigger command and adjusted contributing.md
> Add bot trigger for contribution thread

- Directory.Build.props
Visual Studio 17.8 is automatically adding the source control hash to the Product versions of C# binaries. Example:
This PR opts out of that new feature to avoid side effects.
One side effects discovered by @davidegiacometti is that this is added to the log folder as well. Example : `%LOCALAPPDATA%\Microsoft\PowerToys\Peek\Logs\0.0.1.0+7d9681ecd2533e63a13ac3a88257e698b9c7b5a9`
> [Build]Don't add source hash to product version of binaries

- .pipelines/release.yml
With the release of the latest 1ES Enterprise template on CI, our builds started failing the Guardian Post-Analysis checks.
Reverting to the release of the 1ES Enterprise template prior to the latest one fixes this to enable release until we figure out a better long term solution.
Dart CI successfully builds again.
> [ci]Fix 1ES Pipeline to stable release

- src/modules/fancyzones/FancyZonesLib/MonitorUtils.cpp
- src/modules/fancyzones/FancyZonesLib/WindowUtils.cpp
- src/modules/fancyzones/FancyZonesLib/WindowUtils.h
- Fix moved to the current active monitor when maximized not keep maximized
- Enable `Move newly created windows to the current active monitor` > Maximized window > Create new window on other monitor > New window should maximized
> [FancyZones] Fix moved to the current active monitor when maximized

- src/settings-ui/Settings.UI/SettingsXAML/App.xaml.cs
via system tray, PowerToys Settings is open but not in focus, double clicking / right click ->Settings will not force the focus back in.
1. Launch powertoys
2. Double click in systray to force settings app to launch
3. Launch Edge
4. Place edge on top of powertoys settings
5. Expected result is Settings goes into focus and visually on top of Edge.
> Forcing window back on double click / right click

- src/common/utils/gpo.h
- src/gpo/assets/PowerToys.admx
- src/gpo/assets/en-US/PowerToys.adml
- src/runner/UpdateUtils.cpp
- tools/BugReportTool/BugReportTool/ReportGPOValues.cpp
We decided to never implement a policy that disables periodic update checks. Therefore this code parts become obsolete.
> Remove prepared code for "Auto update" policy

- src/modules/peek/Peek.UI/Extensions/WindowExtensions.cs
- src/modules/peek/Peek.UI/NativeMethods.txt
Fix title bar state when Peek window is resized.
Pass `SWP_NOACTIVATE` instead of `SWP_SHOWWINDOW` to `SetWindowPos` since the method is just adjusting window size and there is no need to activate it.
Reference: https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-setwindowpos
- Preview a file
- Maximize window
- Navigate to next file using arrow
- Window is resized and title bar is not messed up
- With pinned button active the window stay maximized
> [Peek] Fix title bar with maximized window

- src/settings-ui/Settings.UI/SettingsXAML/Flyout/LaunchPage.xaml
This PR:
- Fixes: #30355
- Uses the Toolkit 8.x version of the `WrapPanel`
**Steps to validate:**
- Turn on 4 modules that have their icons in the flyout view to check if alignment is correct.
- Now turn 3 off so that only one is enabled, it should be left aligned now instead of centered.
@stefansjfw @jaimecbernardo I wasn't able to test this myself, but it should be a straightforward fix. This can get in after 0.78 so I'll keep it as a draft for now.
> [Flyout] Fix icon alignment bug

- src/settings-ui/Settings.UI.Library/KeysDataModel.cs
In the keyboard manager page in Settings, the data for the chord is being read as a signed 32 bit-integer, which causes load errors because some keys (like Numpad Page Up) will overflow a signed 32 bit integer.
This PR corrects this by declaring the chord as an unsigned int instead.
Mapped `Ctrl(Left) + Home(Numpad),PgUp(Numpad)` to `Ctrl(Left) + L` like in the issue and verified Settings loads the values correctly in the KBM screen without clearing the data.
> [Settings][KBM]Don't clear data with numpad chord

- src/modules/FileLocksmith/FileLocksmithUI/FileLocksmithXAML/Views/MainPage.xaml
Add multiline-wrap to "Selected file paths" pop-up in File-Locksmith Window. Tested through debug and working properly, not overlapping with the text (as mentioned in #26489).
Just added an `auto` scroll to the path instead of truncating it automatically if too long. 
Built and verified the behavior through Debug.
> [FileLocksmith] Wrap path into multiple lines in Selected file paths UI

- .pipelines/ESRPSigning_core.json
The new dll "PowerToys.FancyZonesEditorCommon.dll" added in https://github.com/microsoft/PowerToys/commit/f6e7635a4e143def0a6bb2ada4d562c0de318059 is currently not being sign in CI. Add it to the list of binaries to sign.
> [ci]Sign FancyZonesEditorCommon.dll

- src/settings-ui/Settings.UI/ViewModels/CmdNotFoundViewModel.cs
extending CommandNotFound to detect PowerShellPreview installations
if normal PowerShell installation isn't found (7.4 or greater), a check is added to detect PowerShell Preview installations.
tested locally
> [CommandNotFound] extending to detect PowerShellPreview installations

- .pipelines/ci/templates/build-powertoys-steps.yml
- .pipelines/ci/templates/run-ui-tests-ci.yml
- .pipelines/loc/loc.yml
This simply changes the pipelines to use "Pipeline Artifacts" instead of "Build Artifacts". Basically two different implementations of the same general concept.
This brings the "Publish Build Artifacts" step of the pipeline from ~9 mins to ~20 secs. This also brings the "Download artifacts" step of the UI tests job from ~3 mins to ~1:20. So total this change speeds up the overall pipeline execution by ~15%.
Compare the existing: https://dev.azure.com/ms/PowerToys/_build/results?buildId=559316&view=logs&j=0f660c0a-4423-5c5d-276b-f98b39c69e13&t=be2e0fe3-12af-5e69-3062-a884288b2c3e
With the new: https://dev.azure.com/ms/PowerToys/_build/results?buildId=559377&view=logs&j=8051a522-456e-5530-e7a5-d1cd88f6bb77&t=0f481525-d1c6-4f2f-81b2-c139993c688c
> Use pipeline artifacts instead of build artifacts

- .pipelines/ci/templates/build-powertoys-steps.yml
- .pipelines/release.yml
This adds the `-graph` MSBuld parameter in the pipelines. This parameter causes MSBuild to evaluate the dependency graph and build "bottom up" instead of "top down". This can lead to better machine utilization since all dependencies are known up front and can start immediately, as opposed to being discovered just-in-time as a project needs them.
In practice for this repo I did not see a huge impact, but it may be helping a little so why not.
> Opt-into MSBuild -graph param for pipelines

- src/common/Common.UI/SettingsDeepLink.cs
- src/runner/settings_window.cpp
On 0.80.0, links from Text extractor util to its Settings page or from PowerToys plugin of PT Run were broken.
This seems to have been caused by the change from "PowerOCR" to "PowerOcr" to help in the DSC PR.
This PR converts the other strings that stayed as "PowerOCR" to "PowerOcr".
From Text Extractor util, press the settings button and verify it opens Settings in the Text Extractor page.
From PT Run PowerToys plugin, search for Text Extractor and press the Settings button.
From Dashboard, press the Text Extractor entry and verify it opens the Text Extractor Settings page.
From OOBE, press the button that opens the Text Extractor settings page.
> [Settings]Fix links to the Text Extractor page

- Directory.Build.props
[Caching] Allow file accesses under windir
See: https://dev.azure.com/ms/PowerToys/_build/results?buildId=560673&view=logs&j=b6b44f60-477e-5b36-eeeb-589df0c177de&t=f5043f15-036d-5d3b-8695-92dff4115778
> File access reported from process `ProcessId: 1844` after the project finished. This may lead to incorrect caching. Node Id: SRC_DSC_POWERTOYS.SETTINGS.DSC.SCHEMA.GENERATOR_POWERTOYS.SETTINGS.DSC.SCHEMA.GENERATOR.CSPROJ_BUODDESOY_YECINYO98HZQ, Path: C:\Windows\System32\ci.dll
This file access is happening from MSBuild.exe itself and appears benign for cacheability.
> [Caching] Allow file accesses under windir

- src/dsc/PowerToys.Settings.DSC.Schema.Generator/DSCGeneration.cs
Switch from WMI to registry query to improve DSC apply performance.
```pwsh
PS D:\david\Downloads> Measure-Command { winget configure .\powertoys.dsc.yaml --accept-configuration-agreements }
...
Minutes           : 0
Seconds           : 41
PS D:\david\Downloads> Measure-Command { winget configure .\powertoys.dsc.yaml --accept-configuration-agreements }
...
Minutes           : 0
Seconds           : 9
```
Tested with both machine and user installer.
> [DSC] Use registry instead of WMI to improve performance

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Add [WebSearchShortcut](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut) to Third-Party plugins for powertoy run
> [PTRun][Docs] Add WebSearchShortcut to Third-Party plugins

- src/modules/launcher/Plugins/Microsoft.Plugin.Folder.UnitTests/DriveOrSharedFolderTests.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Sources/Path/FolderHelper.cs
Allow to query UNC paths that starts with `//`.
Note that `//` is the default activation keyword for the URI plugin.
I don't think we should change it since it's been like this for years but `//` should work if the activation keyword is changed or the plugin is disabled.
> [Run][Folder] Allow UNC starting with //

- src/modules/imageresizer/ui/App.xaml
- src/modules/imageresizer/ui/Properties/Resources.Designer.cs
- src/modules/imageresizer/ui/Properties/Resources.resx
- src/modules/imageresizer/ui/Views/AccessTextToTextConverter.cs
- src/modules/imageresizer/ui/Views/InputPage.xaml
Set missing `AutomationProperties.Name` in order to make narrator announce sizes ComboBox and options CheckBoxes.
Added a converter to remove the `_` from the access text used for the CheckBoxes.
Accessibility Insights for 0.80
Accessibility Insights for this branch
Note that the remaining 4 failures are related to WPF-UI CheckBoxes.
Manually tested and verified that narrator correctly announce image sizes ComboBox and options CheckBoxes.
> [ImageResize] Narrator announcing sizes ComboBox and CheckBoxes

- Directory.Build.props
Avoid using the Test SDK for Arm64 builds
This is a workaround until https://github.com/dotnet/msbuild/pull/9984 ships to unblock people developing on Arm64 machines.
> Avoid using the Test SDK for Arm64 builds

- src/settings-ui/Settings.UI.UnitTests/ViewModelTests/General.cs
- src/settings-ui/Settings.UI/Helpers/WindowHelper.cs
- src/settings-ui/Settings.UI/Services/ThemeService.cs
- src/settings-ui/Settings.UI/SettingsXAML/App.xaml.cs
- src/settings-ui/Settings.UI/SettingsXAML/MainWindow.xaml.cs
- src/settings-ui/Settings.UI/SettingsXAML/OobeWindow.xaml.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/GeneralPage.xaml.cs
- src/settings-ui/Settings.UI/ViewModels/DashboardViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/GeneralViewModel.cs
Fix settings app theme override:
- Apply theme override to OOBE window
- Make theme override even if settings window isn't opened in the Dashboard page (e.g. opened from another utility)
- Decouple from the listener based on `System.Management` that fail in case of missing .NET 4
TODO
Verified that setting the immersive dark mode apply only on classic title bar and doesn't have any effect on modern title bar
Not changing flyout behavior in this PR: this have been discussed on #23831 and in the relative PR
- Theme override is applied when app is opened
- Theme override is applied to both main and OOBE window
- Theme override is applied even if settings app isn't opened on Dashboard page but on the settings page of an utility
- When theme is overwritten (dark or light), app theme doesn't …
> [Settings] Theme override fix and cleanup

- src/dsc/Microsoft.PowerToys.Configure/examples/README.md
- src/dsc/Microsoft.PowerToys.Configure/examples/configuration.dsc.yaml
- src/dsc/Microsoft.PowerToys.Configure/examples/configureLauncherPlugins.dsc.yaml
- src/dsc/Microsoft.PowerToys.Configure/examples/disableAllModules.dsc.yaml
- src/dsc/Microsoft.PowerToys.Configure/examples/enableAllModules.dsc.yaml
- src/dsc/Microsoft.PowerToys.Configure/examples/installAndConfiguration.dsc.yaml
Adds an index file for the DSC samples.
Adds a sample that installs and then configures PowerToys.
Improves the samples for DSC, according to best practices from https://github.com/microsoft/devhome/tree/main/docs/sampleConfigurations/DscResources :
- Add the `yaml-language-server` header.
- Use the full resource name to improve time for winget to find the resource.
- Make the configure step depend on the install step.
- Use PowerToys package full name for the install step.
> [DSC]Improve samples

- .pipelines/ci/ci.yml
Enable caching in CI pipeline
Some rough numbers suggest that on average this can save ~10 mins of the build.
> Enable caching in CI pipeline

- .pipelines/ci/ci.yml
There appears to be some bugs in this feature for pipeline runs triggered from forks.
> Disable project caching for forks

- .pipelines/ci/templates/build-powertoys-steps.yml
This change uses [Pipeline Caching](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops) to cache NuGet packages.
This should improve pipeline performance. It adds ~2 mins to pull the packages from the cache, but save ~3 mins from the restore, netting about 1 min of savings.
Before:
After:
> Cache nuget packages using pipeline caching

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Adds a new plugin, [UnicodeInput](https://github.com/nathancartlidge/powertoys-run-unicode), (developed by myself) to the third-party plugins list for PowerToys Run.
This plugin allows for the rapid input of some unicode characters and symbols
> [PTRun][Docs] Updated Third party plugins to include UnicodeInput

- src/settings-ui/Settings.UI/ViewModels/PluginAdditionalOptionViewModel.cs
The settings app crashes when the user clears the number box and presses enter or moves the focus away from it. This happens because the value is not a valid number and converting this to `double` produces `double.NaN`. The `double.NaN` then leads to the app crash.
To fix this we now check the value of the number box against `NaN` and if the check is true we send a `NotifyPropertyChanged()` command. This lets the NumberBox reload its binding value and resets the NumberBox to the last valid number input.
**We should consider this PR in a HotFix if we need one after releasing v0.81.0!**
> [Settings > PT Run > PluginAdditionalOptions] Fix crash on empty number box

- .github/actions/spell-check/allow/code.txt
- README.md
Readme update for the 0.81 release.
> 0.81 changelog

- .pipelines/ci/templates/run-ui-tests-ci.yml
Updates the VsTest folder for the 17.10 release of Visual Studio, in order to properly run the UI tests in CI.
> [ci][Tests]Fix vstest location for VS 17.10 release

- src/runner/centralized_kb_hook.cpp
Apparently, left-clicking Slack systray icon sends None (vkCode = 0) keyboard input. As all of the modifier keys are false (if not pressed) this is the same as key combination as default non-set Hotkey{}. therefore, whatever non-set hotkey was not set - was triggered. 
Without this fix:
- Copy some text
- Left click slack systray icon and observe that text is pasted into slack input text box
With the fix:
- Follow the same steps and observe that nothing is pasted into slack
> [runner]Fix triggering non-set hotkeys

- src/modules/launcher/PowerLauncher/MainWindow.xaml
There's this option on Windows, called "Show accent color on title bars and windows borders":
It makes PowerToys Run look like this:
WPF UI doesn't seem to give much tools in terms of overriding that, so we make the search box opaque instead:
> [PTRun]Fix accent on title bar bleed into UI

- src/modules/Hosts/Hosts/HostsXAML/MainWindow.xaml
- src/modules/Hosts/HostsUILib/HostsMainPage.xaml
The old ui definition causes the host names column to hid. Now it is not hiding anymore and the Address column has a smaller min width.
**Before:**
**After:**
**Before:**
**After:**
- Set min width for the first two columns.
- Updated the min width of he window that the last columns not hiding on resizing.
- Set fixed column width for the icons of the entries to have them vertical aligned.
- Fixed the bug that the icons and buttons can get misaligned on resizing.
Manual tests.
> [Hosts] Improve Resizing behavior

- PowerToys.sln
PR #29453 removed the `src/tests/win-app-driver` folder, but missed removing the sln file reference to the folders `README.md` file.
Remove the outdated file reference.
* Manually: Opened Solution in VS. Trying to open README.md fails with missing file. After this change, the file is no longer listed.
> Drop outdated sln win-app-driver README.md file reference

- src/modules/Hosts/Hosts/HostsXAML/App.xaml.cs
- src/modules/Hosts/Hosts/Settings/UserSettings.cs
- src/modules/Hosts/HostsUILib/Helpers/DuplicateService.cs
- src/modules/Hosts/HostsUILib/Helpers/IDuplicateService.cs
- src/modules/Hosts/HostsUILib/Helpers/IHostsService.cs
- src/modules/Hosts/HostsUILib/Settings/IUserSettings.cs
- src/modules/Hosts/HostsUILib/ViewModels/MainViewModel.cs
The duplicate check logic degraded overtime with the additional logics introduced (max 9 hosts per line, etc..).
- This PR aims to move the current logic from the view model to a dedicated service and make it async.
- Since a typical usage of the hosts file is to block domains mapping them to `0.0.0.0` I have added `0.0.0.0` (and IPv6 equivalent) to the list of loopback addresses in order to skip the check.
- Manually tested with a hosts file containing more than 100K entries:
- Verified that duplicate check is working as before but in an async way
- Tested file reload
- Tested "Consider loopback addresses as duplicate" enable/disable (it does trigger a hosts file reload)
- Edited an entry with a huge number of duplicates and verified that UI doesn't freeze
> [Hosts] Duplicate check improvement

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Add a new PTRun third-party plugin to open Microsoft Edge workspaces: https://github.com/quachpas/PowerToys-Run-EdgeWorkspaces/
The plugin adds support for [Microsoft Edge workspaces](https://www.microsoft.com/en-us/edge/features/workspaces).
> [PTRun][Docs] Add EdgeWorkspaces to Third-Party plugins

- src/modules/poweraccent/PowerAccent.Core/Languages.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerAccentPage.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerAccentViewModel.cs
Adds characters for the International Phonetic Alphabet
Adds IPA to Quick Accent as a separate language. The table with all the characters is in #25860
Observing
> [Quick Accent] Add IPA

- .github/workflows/msstore-submissions.yml
Looks like we've been sending the default to store to be machine wide, this will shift to PowerToysUserSetup based installer instead.  The machine wide does a UAC dialog which is not ideal.
PowerToysUserSetup-0.81.1-arm64.exe vs PowerToysSetup-0.81.1-arm64.exe
As store does not actively update Win32 apps, this should be a 'foward moving' update
> shifting Store to user based vs machine

- src/modules/MeasureTool/MeasureToolModuleInterface/dllmain.cpp
- src/settings-ui/Settings.UI.Library/MeasureToolProperties.cs
Update default activation shortcut and resolve #32623 
The default activation shortcut for the Screen Ruler (MeasureTool) has been updated so as to no longer conflict with the built-in Windows Explorer shortcut used to restore windows minimized with `⊞ Win`-`M`:
* Old shortcut: `⊞ Win`-`Shift`-`M`
* New shortcut: `⊞ Win`-`Ctrl`-`Shift`-`M`
* Installed the package on a fresh virtual machine
* Launched PowerToys
* Pressed `⊞ Win`-`Ctrl`-`Shift`-`M` 
* Observed that this caused the MeasureTool UI to appear and function normally
> [MeasureTool] Update default activation shortcut to resolve conflict with Windows Explorer built-in shortcut

- .pipelines/ci/templates/build-powertoys-ci.yml
- .pipelines/ci/templates/build-powertoys-precheck.yml
- .pipelines/ci/templates/run-ui-tests-ci.yml
We are no longer exclusively using one organization named "ms" and one organization not named "ms".
This change flips the sense of the organization comparison so the `OSS` agents can be used for every collection except very specifically the Microsoft one. I also switched to using its ID.
> build: make the agent pool selection more robust

- .config/dotnet-tools.json
- Adjust XML Escaping to allow for incomplete xmlns inside a comment 
- Add support for Rider 2024.1
- Better handle internal VS exceptions relating to .csproj files
- Expand console support for axaml
- Handle unhandled FileNotFoundException in XamlStylerConsole.cs
- Fix entry in About window
- Set minimum install target to match version of referenced SDK
- adds support for Rider 2023.3
- Adds support for ARM64 version of Visual Studio 2022 
- Adds support to write formatted output to stdout in XamlStyler.Console
- Fixes issue preventing configuration files from getting picked up properly
- adds support for Rider 2023.2
- adds support for Rider 2023.1
- Adds option to ignore design-time reference prefix when reordering
- Adds support for Avalonia (.axaml) file extensions
- adds support …
> Update Xamlstyler.console to 3.2404.2

- Directory.Packages.props
- NOTICE.md
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/UnitHandler.cs
- Add operators for ReciprocalLength/-Area
- Change nuget license from MIT to MIT-0
- Add operator to convert from TemperatureDelta to TemperatureChangeRate.
- Add MagenticField and Acceleration for .NET nanoFramework
- Change DataMember ordering to 1-indexed
- Add VolumeFlow prefixes Deca
- Add Btu/ft² in irradiation
- Add radiation equivalent dose
- Fix precision of Volume.CubicInch
- Add radiation exposure
- Add radioactivity
- Add units for Molality
- Add Kilo prefix to yards
- Improve precision of PR 1334
- Add density unit PoundsPerCubicYard + Kilo prefix
- Bump nanoFramework refs
- ci: 🔧Update pipelines for v4
- Added some nullability annotations to v4
- Add Femto prefixes to density
- Add micro and nano prefixes
- Added Gigameter (1e+9 meters)
- Fix force conversion rates
- Set …
> [DEPS] Update Unitsnet to 5.50.0

- .pipelines/installer-steps.yml
Tested and working in PowerToys Signed YAML Release Build_2407.11003
> Disable project references so CustomActions doesn't rebuild during MSI

- src/settings-ui/Settings.UI/SettingsXAML/Views/MouseWithoutBordersPage.xaml
- src/settings-ui/Settings.UI/ViewModels/MouseWithoutBordersViewModel.cs
This PR fixes two bugs for the info bars on the MWB settings page:
- The bars are shown if module is disabled.
- Some bars can be closed.
- Some bars are reacting to tab stop on closed state.
Manual build of PowerToys settings and tested behavior.
> [Settings > MWB] Fix infobars to hide when moduls is disabled and beeing not closable

- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerLauncherPage.xaml
There is a layout bug that cause the info bar to overlap the space between the settings cards.
> [Settings > PowerToys] Fix Layout bug affecting the Action Keyword info bar

- .github/actions/spell-check/expect.txt
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/InputInterpreter.cs
This PR introduces abbreviations for the units - `kph` that gets converted to `km/h` and `cph` that gets converted to `cm/h`.
- Added abbreviations for `kph` to `km/h`
- Added abbreviations for `cph` to `cm/h`
- Ran and tested myself locally
> [PT-Run] Unit converter - Can´t use abbreviations

- .github/workflows/package-submissions.yml
The [release tag](https://github.com/microsoft/PowerToys/tags) for `0.82.1` contained a capital `V` instead of the usual `v` that was used in versions prior. The winget submission action trims a lowercase `v` from the start and uses it as the PackageVersion to be submitted to WinGet. Since a capital V was used, the PR came through with an incorrect PackageVersion.
This PR updates the CI to case-insensitively trim the version prefix from the release tag.
See WinGet PR:
- https://github.com/microsoft/winget-pkgs/pull/162724
> [ci]: Case insensitively replace version prefix for winget's PackageVersion

- Cpp.Build.props
- PowerToys.sln
- src/modules/FileLocksmith/FileLocksmithContextMenu/FileLocksmithContextMenu.vcxproj
- src/modules/FileLocksmith/FileLocksmithContextMenu/FileLocksmithContextMenu.vcxproj.filters
- src/modules/ShortcutGuide/ShortcutGuide/ShortcutGuide.vcxproj
- src/modules/imageresizer/ImageResizerContextMenu/ImageResizerContextMenu.vcxproj
- src/modules/powerrename/PowerRenameContextMenu/PowerRenameContextMenu.vcxproj
Fix the solution warning related to wildcards items in vcxproj.
https://learn.microsoft.com/cpp/build/reference/vcxproj-files-and-wildcards#list-all-items-explicitly
Since wildcards where used for assets that doesn't change frequently I have added `ReplaceWildcardsInProjectItems` for CPP projects. This will make VS automatically expand wildcards.
- Verified that the warning is fixed
- Tested with a local build
- Verified that all the expanded assets are present as expected in the output dir (compared with 0.82.1 installation dir).
> [Build] Remove wildcards items in vcxproj

- .github/actions/spell-check/expect.txt
- src/common/GPOWrapper/GPOWrapper.cpp
- src/common/GPOWrapper/GPOWrapper.h
- src/common/GPOWrapper/GPOWrapper.idl
- src/common/utils/gpo.h
- src/gpo/assets/PowerToys.admx
- src/gpo/assets/en-US/PowerToys.adml
- src/modules/MouseWithoutBorders/App/Class/Setting.cs
- src/modules/MouseWithoutBorders/App/Class/SocketStuff.cs
- src/modules/MouseWithoutBorders/App/Form/frmMatrix.Designer.cs
- src/modules/MouseWithoutBorders/App/Form/frmMatrix.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/MouseWithoutBordersPage.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/MouseWithoutBordersViewModel.cs
- tools/BugReportTool/BugReportTool/ReportGPOValues.cpp
The TransferFile setting depends on ShareClipboard setting. This is now visually shwon.
**Before the change:**
**After the change**
Name | Supported states | Id | Behavior
------------ | ------------- | ------------ | -------------
Clipboard sharing enabled | disabled | MwbClipboardSharingEnabled | Disables the feature if set to disabled.
File transfer enabled | disabled | MwbFileTransferEnabled | Disables the feature if set to disabled.
Original user interface enabled | disabled | MwbUseOriginalUserInterface | Disables the feature if set to disabled. |
Disallow blocking screensaver on other machines | enabled | MwbDisallowBlockingScreensaver | Disables the feature if set to enabled. |
Connect only in same subnet | enabled & disabled | MwbSameSubnetOnly | Enables the feature if set to …
> [MWB > Settings + GP] Add new MWB GPs and improve settings ui for TransferFile setting

- Directory.Packages.props
- NOTICE.md
Updating to latest sqlite, can hold until .84
VS Code workspaces is the only item that uses this.
> Getting latest sqlite

- .pipelines/ci/templates/build-powertoys-steps.yml
- installer/PowerToysSetup/PowerToysBootstrapper.wixproj
- installer/PowerToysSetup/PowerToysInstaller.wixproj
This PR aims for fix some CI build warnings.
Fix warning NU1503 for wix toolset projects marking them as restorable and adding an empty restore target.
Skip publishing of test results for ARM64 since pipeline isn't running ARM64 tests
- CI built successfully
- Warnings are fixed
> [Build][Installer]Fix NU1503 build warnings

- packages.config
Update MSBuildCache to 0.1.283-preview
Notable change is this one, which should avoid under-builds when the build tooling updates: https://github.com/microsoft/MSBuildCache/pull/77
Full release notes:
* [0.1.283-preview](https://github.com/microsoft/MSBuildCache/releases/tag/v0.1.283-preview)
* [0.1.273-preview](https://github.com/microsoft/MSBuildCache/releases/tag/v0.1.273-preview)
> Update MSBuildCache to 0.1.283-preview

- src/modules/previewpane/GcodePreviewHandler/Program.cs
- src/modules/previewpane/GcodePreviewHandlerCpp/GcodePreviewHandler.cpp
- src/modules/previewpane/MarkdownPreviewHandler/Program.cs
- src/modules/previewpane/MarkdownPreviewHandlerCpp/MarkdownPreviewHandler.cpp
- src/modules/previewpane/MonacoPreviewHandler/Program.cs
- src/modules/previewpane/MonacoPreviewHandlerCpp/MonacoPreviewHandler.cpp
- src/modules/previewpane/PdfPreviewHandler/Program.cs
- src/modules/previewpane/PdfPreviewHandlerCpp/PdfPreviewHandler.cpp
- src/modules/previewpane/QoiPreviewHandler/Program.cs
- src/modules/previewpane/QoiPreviewHandlerCpp/QoiPreviewHandler.cpp
- src/modules/previewpane/SvgPreviewHandler/Program.cs
- src/modules/previewpane/SvgPreviewHandlerCpp/SvgPreviewHandler.cpp
- src/modules/previewpane/common/cominterop/NativeMethods.cs
- src/modules/previewpane/common/controls/FormHandlerControl.cs
- src/modules/previewpane/common/controls/IPreviewHandlerControl.cs
This PR aims to fix some positioning issues of the form used as preview handler.
It fixes the following issues:
1. The floating window, detached from Explorer that sometimes appears: #33491 #27475 #24985
2. The **CoreWebView2 members cannot be accessed after the WebView2 control is disposed** crash: #27276
3. `PowerToys.*.PreviewHandler.exe` process leak
- Navigate through files in a folder invoking their preview handler
- Minimize/Restore Explorer quickly (spam WIN+D usually works)
- 2 weird issues happen:
- Some `PowerToys.*.PreviewHandler.exe` processes are leaked
- Some `PowerToys.*.PreviewHandler.exe` are started with a `NULL` `HWND`
This happens because [IPreviewHandler::DoPreview](https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ipreviewhandler-dopreview) …
> [PreviewPane] Fix form positioning issues

- src/common/interop/KeyboardHook.idl
Cleans a build warning about WPARAM when building the idl file. Seems like typedef is not liked too much when compiling for winrt/Cpp.
> [Build]Clean the WPARAM warning on IDL

- src/dsc/Microsoft.PowerToys.Configure/examples/installAndConfiguration.dsc.yaml
- src/dsc/PowerToys.Settings.DSC.Schema.Generator/DSCGeneration.cs
- src/settings-ui/Settings.UI.Library/ImageSize.cs
- src/settings-ui/Settings.UI.Library/Utilities/SetAdditionalSettingsCommandLineCommand.cs
- src/settings-ui/Settings.UI.UnitTests/ViewModelTests/ImageResizer.cs
- src/settings-ui/Settings.UI/Converters/ImageResizerFitToIntConverter.cs
- src/settings-ui/Settings.UI/Converters/ImageResizerUnitToIntConverter.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/ImageResizerPage.xaml
- do not use ints for enums in ImageSize struct
- add required converters
- extend setAdditional functionality
- add relevant sample
- applied `installAndConfiguration.dsc.yaml` (with the install step commented out) and verified in the settings that the sizes are appended/changed
- applied `configureLauncherPlugins.dsc.yaml` and verified that Launcher plugins configuration still works
> [DSC] Add support for ImageresizerSizes property

- src/modules/Workspaces/WorkspacesSnapshotTool/SnapshotUtils.cpp
> [Workspaces] Fix snapshotting Steam

- .github/policies/resourceManagement.yml
Added new policy bot trigger to recognize new Workspaces bugs and label them with Product-Workspaces label. Will expand this to all modules if it works properly.
> Added bot trigger to add Product-Workspaces label to new issues-bugs

- src/settings-ui/Settings.UI/Helpers/NativeMethods.cs
- src/settings-ui/Settings.UI/SettingsXAML/FlyoutWindow.xaml
- src/settings-ui/Settings.UI/SettingsXAML/FlyoutWindow.xaml.cs
- src/settings-ui/Settings.UI/ViewModels/Flyout/FlyoutViewModel.cs
- This PR aim to fix a flyout issue caused by the WinAppSDK 1.6 https://github.com/microsoft/PowerToys/pull/34622#pullrequestreview-2287475001
- This will also revert #24907 since the workaround isn't needed anymore
- Applied the same fix used for Screen Ruler https://github.com/microsoft/PowerToys/pull/34622#pullrequestreview-2285814240
- Reverted the W10 workaround
Tested the flyout with light/dark theme.
_0.84.1 (left) - PR (right)_
> [Settings] WinAppSDK 1.6 Flyout Fix

- src/modules/peek/Peek.Common/Models/IFileSystemItem.cs
The Peek image preview shows an infotip on hover, including a Date Modified field. This was incorrectly set to the file's creation date.
This was a simple change to return `GetLastWriteTime` for the file.
Manual validation by using Peek on an image file where the creation datetime was different to the modified date.
> [Peek] Fix for DateModified tooltip property showing file creation date

- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml.cs
- src/modules/peek/Peek.FilePreviewer/Peek.FilePreviewer.csproj
Fixes the Peek PowerToy leaking unmanaged resources associated with bitmaps when using the `ImagePreviewer`. Also ensures any Previewer implementing `IDisposable` will be correctly disposed.
The Peek PowerToy creates a Previewer for each item as the user navigates a folder. For the ImagePreviewer, a `Clear` method is provided which cleans up unmanaged resources, including bitmaps created for preview thumbnails. Unfortunately, `Clear` is not called on the old Previewer before a new instance is created, leading to unreachable resources which are never freed. This PR ensures `Dispose` is called on a Previewer if it implements `IDisposable`. ImagePreviewer calls `Clear` within its `Dispose`, which fixes the leak.
Manual validation:
1. Attached to the `PowerToys.Peek.UI` exe in VS, where the …
> [Peek] Fix memory leak caused by unmanaged bitmaps not being freed

- src/modules/Workspaces/WorkspacesLauncher/main.cpp
check project id when launching from editor. In edge case the temporal json file might contain a different workspace
> [Workspaces] add check on project id when launching from editor

- src/modules/peek/Peek.FilePreviewer/Controls/ShellPreviewHandlerControl.xaml
- src/modules/peek/Peek.FilePreviewer/Controls/ShellPreviewHandlerControl.xaml.cs
Issue is 100% reproducible on latest stable PT release: when the first previewed file uses the PreviewHandler (e.g. Office) the preview doesn't work, requiring a window resize or a second activation to be displayed.
This happen because for some weird reason the `EffectiveViewportChanged` event is fired before the loading of the user control: at that point the `containerHwnd` isn't created yet.
- Moved the creation of `containerHwnd` outside the `Loaded` event handler.
- Ensure the `containerHwnd` has been created before using it.
- Added an extra check to ensure the parent window (Peek) is valid.
Verified that the PreviewHandler is displayed at the first preview after Peek activation.
> [Peek] Fix PreviewHandler previewer not visible on first activation

- src/modules/launcher/PowerLauncher/Plugin/PluginManager.cs
- src/modules/launcher/PowerLauncher/Properties/Resources.Designer.cs
- src/modules/launcher/PowerLauncher/Properties/Resources.resx
- src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
This is not a fix to the error, but an improvement to MessageBox error title since it's not clear to the user that the it's related to PT Run.
This was partially addressed by https://github.com/microsoft/PowerToys/pull/25095, but not for all the errors.
- Assessed the `MessageBox.Show(...)` errors that could be triggered on startup, detecting which need to explicit call out "PT Run"
- Aligned loading/initialization error messages.
- Don't think that `IPublicAPI.ShowMsg(...)` dialogs need "PT Run" in title since they are usually showed as a response to a user interaction (example click on a result or action).
> [Run] Improve error MessageBox

- src/modules/AdvancedPaste/AdvancedPaste/ViewModels/OptionsViewModel.cs
- src/modules/AdvancedPaste/AdvancedPasteModuleInterface/dllmain.cpp
- src/settings-ui/Settings.UI/SettingsXAML/Views/AdvancedPaste.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/AdvancedPasteViewModel.cs
Fixes issues with custom actions not being fully disabled when "Paste with AI" is disabled.
- Disabled "Add custom action" button and list of custom actions when Paste with AI is disabled.
- Prevented registering keyboard shortcuts in module interface or propagating them to Paste window when Paste with AI is disabled.
- Added further redundant checks in Paste window.
- Tested fix while transitioning from enabled and disabled "Paste with AI" states.
- Sanity check of Advanced Paste.
> [AdvancedPaste] Check "Paste with AI" enabled state for custom actions

- src/modules/AdvancedPaste/AdvancedPaste/AdvancedPasteXAML/MainWindow.xaml.cs
- src/modules/AdvancedPaste/AdvancedPaste/ViewModels/OptionsViewModel.cs
- src/modules/AdvancedPaste/AdvancedPasteModuleInterface/dllmain.cpp
Hides custom actions on Paste menu when "Paste with AI" is disabled, as discussed [here](https://github.com/microsoft/PowerToys/pull/35026#issuecomment-2371820618)
- Tested fix while transitioning from enabled and disabled "Paste with AI" states.
- Sanity check of Advanced Paste.
> [AdvancedPaste] Hide custom actions on Paste menu when Paste with AI disabled

- doc/devdocs/modules/launcher/plugins/community.unitconverter.md
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter.UnitTest/InputInterpreterTests.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/InputInterpreter.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/UnitHandler.cs
`f` and `c` would previously get converted to `°f` and `°c`, now they get converted to `°F` and `°C`.
Also removes the `FeetToFt()` function, as it's not needed anymore
**Before**:
**After**:
Manually trying it in PTRun.
> [Run-UnitConverter] Use capital letters in DegreePrefixer

- src/settings-ui/Settings.UI/ViewModels/NewPlusViewModel.cs
Fixed crash when cancelling template folder selection from settings.
See linked issue.
- Reproduced crash before fix.
- Tested fix does not crash.
- Tested hitting cancel does not alter template folder.
- Tested choosing folder does alter template folder.
> [Settings > New+] Fixed crash when cancel template folder selection

- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesWindowProcessing.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesWindowProcessing.h
- src/modules/fancyzones/FancyZonesLib/WindowMouseSnap.cpp
- src/modules/fancyzones/FancyZonesTests/UnitTests/WindowProcessingTests.Spec.cpp
Allow to manually snap windows to FancyZones launched by Workspaces.
When the window is created, FancyZones will still ignore it.
> [FancyZones] Allow snapping apps launched by Workspaces

- src/settings-ui/Settings.UI/ViewModels/NewPlusViewModel.cs
Prevents a crash when running a Dev build of Settings.exe by removing an assumption of a initially valid template location created by the Runner.
- Reproduced issue by running Dev build of Settings.
- Fixed issue and then:
- Ran Dev build of Settings, ensured it did not crash and settings on NewPlus were correctly populated. Toggled enabled state a few times. Made Settings changes.
- Then ran Runner, ensured it did not crash.
- Toggled enabled state again a few times.
- Reran the above steps while first running Runner (which makes it create a default settings file).
> [Settings > New+] Crash when running Dev build of settings

- .pipelines/v2/ci.yml
- .pipelines/v2/templates/pipeline-ci-build.yml
This may have been able to be imputed by the presence of `Cache@1`, but we might as well make it explicit.
> build: reintroduce variables.EnablePipelineCache

- src/modules/Workspaces/WorkspacesLauncher/main.cpp
Ensure one launcher instance is running.
The issue of launching an incorrect workspace appears when trying to launch a workspace when the previous one is not finished.
> [Workspaces] Fix launching incorrect workspace via shortcut

- .github/actions/spell-check/allow/names.txt
- .github/actions/spell-check/expect.txt
Trying to resolve the warning for 8LWXpg user name
> Adjusting 8LWXpg user name in so it doesn't throw a spell check

- .pipelines/v2/templates/job-ci-precheck.yml
- .pipelines/v2/templates/pipeline-ci-build.yml
This should prevent the tests from running (and failing) when PreCheck skips the build.
> ci: move the precheck dependency+condition up to the stage

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/translation_issue.yml
Microsoft added issue types to their GitHub org. This PR adds those to the corresponding issue templates.
> Add support for new issue types of Microsoft Organisation

- doc/thirdPartyRunPlugins.md
Add [HackMD](https://github.com/8LWXpg/PowerToysRun-HackMD) to third-party plugins.
> [PTRun][Docs] Add HackMD to Third-Party plugins

- .pipelines/v2/ci.yml
Currently, we enabled a check that all CI steps must pass.  The CI system actively ignores certain file changes to enable a faster cycle for certain files.  These two rules conflict with one another and requires an admin override.  With new pipelines and build caching now, we feel this is a happy middle ground for speed as well.
This change removed the exclusion of the `doc/*`, `temp/*`, `tools/*`, and `**.md` paths from the CI pipeline.
> Removing Markdown exclude

- .github/actions/spell-check/allow/names.txt
- .github/actions/spell-check/expect.txt
Yet another attempt at trying to get this warning to go away for spelling errors.
> Trying to correct spelling error around having leading numeric value for user name

- .pipelines/v2/templates/job-build-project.yml
After we've upgraded Windows App SDK to 1.6, Dev Files Preview on Peek has been broken on ARM64.
For .86, we've added WebView2 to Registry Preview in order to have Monaco Editor as the text editor, which is also broken on ARM64.
After a lengthy investigation, it seems we've found the core issue, PowerToys has been shipping with a x64 Microsoft.Web.WebView2.Core.dll in the ARM64 installer, which fails at runtime.
We seem to have hit a version of https://github.com/microsoft/WindowsAppSDK/issues/4826
When we build PowerToys in Dart for release, we publish some of the C# WinUI3Apps after building PowerToys and before signing / building the install. This means that the WindowsAppSDK build will recopy its WebView2 dependency, which for some reason is ARM64. On local builds of PowerToys, …
> [ci][Arm64]Manually copy WebView2 core dll after building and publishing

- .pipelines/ESRPSigning_core.json
After https://github.com/microsoft/PowerToys/commit/6b3bbf7e8f94f47d9881e32a1b8ed6f11920db41 was merged, the new "PowerToys.WorkspacesCsharpLibrary.dll" dll isn't being signed.
This PR signs it.
> [ci]Fix signing new Workspaces dll in Dart

- src/common/FilePreviewCommon/MonacoHelper.cs
The `MonacoHelper` class in `FilePreviewCommon` handles locating the Monaco assets directory so the Monaco language file and template HTML file may be loaded. This PR corrects an issue whereby `GetRuntimeMonacoDirectory()` would return an incorrect folder location if an empty `INSTALLDIR\WinUI3Apps\Assets\Monaco` existed in addition to the correct `INSTALLDIR\Assets\Monaco` location.
The function now does an explicit check to see if the calling assembly lies within the WinUI3Apps folder, and if so it navigates to the parent directory before continuing resolution of the assets path.
I reproduced the failure case by creating an empty `\AppData\Local\PowerToys\WinUI3Apps\Assets\Monaco` folder and then using Peek to preview files supported by Monaco, such as source code files. This confirmed …
> [Peek] Fix Monaco assets folder discovery

- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/ResultHelper.cs
The score was already calculated by the plugin but was not passed to the launcher's Result.
I tried to recreate a situation similar to the open issue
Before:
After:
> [WindowWalker]Added Score to the results returned by WindowWalker

- src/modules/poweraccent/PowerAccent.Core/Languages.cs
- src/modules/poweraccent/PowerAccent.Core/Services/SettingsService.cs
- src/settings-ui/Settings.UI.Library/PowerAccentLanguageGroupModel.cs
- src/settings-ui/Settings.UI.Library/PowerAccentLanguageModel.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerAccentPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerAccentPage.xaml.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerAccentViewModel.cs
- Updated Language enum, method signatures, and settings to support multiple language selections.
- Remove ALL language and added special characters language instead.
- Modified UI to use ListView with checkboxes for language selection, including a "Select All" option.
- Adjusted ViewModel and code-behind to handle multi-selection logic.
- Updated Resources.resw and PowerAccentViewModel.cs to reflect these changes.
Added an ability to select multiple languages. 
This UI is the best I can do right now as my experience with Desktop UI development is limited, so if someone wants to make it better, be my guest. 
Manually tested the app.
> PowerAccent with multi-language selection

- src/modules/previewpane/GcodePreviewHandler/GcodePreviewHandler.csproj
- src/modules/previewpane/MarkdownPreviewHandler/MarkdownPreviewHandler.csproj
- src/modules/previewpane/MonacoPreviewHandler/MonacoPreviewHandler.csproj
- src/modules/previewpane/PdfPreviewHandler/PdfPreviewHandler.csproj
- src/modules/previewpane/QoiPreviewHandler/QoiPreviewHandler.csproj
- src/modules/previewpane/SvgPreviewHandler/SvgPreviewHandler.csproj
On a setup with 2 monitors using different DPI I have been able to reproduce and fix the issue reported from some users.
The introduced property is used by `ApplicationConfiguration.Initialize();` in `Program.cs`.
Seems that pdf, gcode and qoi had no issues but I think it's good to have all the PreviewPane project aligned.
Manually tested preview panes for gcode, qoi, svg, md, pdf and source code files.
Verified that the preview pane is rendered as expected for both monitor.
Verified that no issues occur when the Explorer window is moved between monitors.
> [PreviewPane] Use PerMonitorV2 DPI mode

- src/modules/Workspaces/WorkspacesEditor/App.config
- src/modules/Workspaces/WorkspacesEditor/MainWindow.xaml.cs
- src/modules/Workspaces/WorkspacesEditor/Properties/Settings.Designer.cs
- src/modules/Workspaces/WorkspacesEditor/Properties/Settings.settings
Storing the editor window's size and position in the settings. 
tested locally
> [Workspaces] Implement store of app window's size and position

- .github/CODEOWNERS
- .github/actions/spell-check/allow/names.txt
Phase 1 of 2 for updating code owners.  Will create new team and just have these pointed to that.
> Update CODEOWNERS to include gordon, jerry and kayla

- .github/CODEOWNERS
- .github/actions/spell-check/allow/names.txt
1. Migrated the users below to the powertoys-code-owners team
2. Migrated the list of users to team in code owner file
3. Gave team write access
> Making the powertoys-code-owners team code owners

- src/modules/launcher/PowerLauncher/MainWindow.xaml
- src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
Added a border on W10 since only W11 had it.
Screenshots of the new  look in W10.
ResizeMode="NoResize" removes the border which on W11 was added back by enabling round corners 
<pre> 
if (OSVersionHelper.IsWindows11())
{
WindowInteropHelper(GetWindow(this)).EnsureHandle(); 
DWMWINDOWATTRIBUTE attribute = DWMWINDOWATTRIBUTE.DWMWA_WINDOW_CORNER_PREFERENCE; 
DWM_WINDOW_CORNER_PREFERENCE preference = DWM_WINDOW_CORNER_PREFERENCE.DWMWCP_ROUND;  
DwmSetWindowAttribute(hWnd, attribute, ref preference, sizeof(uint)); 
}  </pre>
Added a gray border on W10.
Tested On W10 and W11 on dark,light and all high contrast modes.
> [Laucher] Added border on W10

- src/modules/AdvancedPaste/AdvancedPaste/Helpers/JsonHelper.cs
This PR aims to fix the bug #35225 by introducing a new method `IsJson` to determine if a given text is in JSON format. 
The `IsJson` method is then utilized in the `ToJsonFromXmlOrCsvAsync` method to optimize the processing logic. 
If the text is already in JSON format, it is returned directly without further conversion from XML or CSV.
1. Added `System.Text.Json` namespace.
2. Implemented `IsJson` method to check if the text is in JSON format.
3. Updated `ToJsonFromXmlOrCsvAsync` method to use `IsJson` and return the text directly if it is already JSON.
> [Bug fix] Add a format validation step before format conversion.

- .configurations/configuration.dsc.yaml
- .configurations/configuration.vsEnterprise.dsc.yaml
- .configurations/configuration.vsProfessional.dsc.yaml
- .github/actions/spell-check/expect.txt
The Microsoft.WinGet.DSC module is GA so prerelease: true is no longer needed.
Removes prerelease directive for WinGet DSC resources in WinGet Configuration files
Cloned repository and ran `winget configure validate <configuration file>`
> Remove "prerelease: true"

- src/modules/PowerOCR/PowerOCR/OCROverlay.xaml
- src/modules/PowerOCR/PowerOCR/OCROverlay.xaml.cs
- src/settings-ui/Settings.UI/ViewModels/PowerOcrViewModel.cs
- Made narrator announce languages
- Made narrator announce the cancel button
- Changed languages list to show the first letter as upper case
- Fixed margin in order to center the buttons in the top bar
_0.86 - PR_
Manually tested using Narrator
> [TextExtractor] Minor UI/Accessibility fixes

- src/modules/fancyzones/FancyZonesLib/WindowUtils.cpp
Removing Workspaces Editor from the Fancy Zone's excluded app list -> enabling the WS Editor to snap to zones.
> Fix snapping Workspaces Editor to Fancy Zones

- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/Main.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/Properties/Resources.resx
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/plugin.json
This pull request addresses and resolves [Issue #35773](#35773) by introducing the `ContextMenuResult` functionality to the `Run.Plugin.VSCodeWorkspaces` plugin.
Fix ✅[Issue #35773](#35773)
All good from my perspective ☺️.
> add: contextMenu items for `Run.Plugin.VSCodeWorkspaces`

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest/ExtendedCalculatorParserTests.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest/QueryTests.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/CalculateEngine.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/CalculateHelper.cs
* Make the division by zero check aware of binary and octal numbers (see #36390)
* Allow octal numbers in `CalculateHelper.InputValid()`
* Allow uppercase base notation (as in `0X`) in `CalculateHelper.InputValid()`
* Make division by zero in another base trigger the division by zero check (solves https://github.com/microsoft/PowerToys/pull/36390#issuecomment-2568085139)
The Mages dep has been recently upgraded to v3.0.0, introducing support for octal numbers and hence requiring this PR. Therefore it would be great if it got merged in this release cycle, so that there wouldn't be a release with v3.0.0 that doesn't properly support it.
Manually tested in PTRun + added tests
> [PTRun][Calc]Improve handling of non-base 10 numbers

- src/modules/peek/Peek.UI/PeekXAML/MainWindow.xaml.cs
Allows the UI to be presented even if it was previously minimized. Solves #36098.
Fixes issue #36098 and allows the Peek UI to be restored from a minimized state if the hotkey is toggled on a new file.
Simply added an Activate() call to bring Window into foreground if AppWindow.IsVisible.
Validated behavior manually. Willing to add additional unit tests to test this behavior if given some direction.
> Bring Peek.UI Window into foreground if previously minimized #36098

- src/common/FilePreviewCommon/Formatters/FilePreviewJsonSerializerContext.cs
- src/common/FilePreviewCommon/Formatters/JsonFormatter.cs
After https://github.com/microsoft/PowerToys/commit/20a5f67222f74c687a08aa4d3bf1ba8c978faf86 , the option to "Try to format the source for preview" started failing for json files in both the dev file preview handler and when previewing json files in Peek.
This fixes two issues:
1 - `[JsonSourceGenerationOptions(WriteIndented = true)]` was not applied, so used `WriteIndented = true,` in the `JsonSerializerOptions` like it was before the AOT changes to make it work.
2 - After the first fix, the Json formatting was being applied only once, creating an error in the logs:
```
[Error] MonacoHelper::InitializeIndexFileAndSelectedFile
Failed to apply formatting
System.InvalidOperationException: JsonSerializerOptions instances cannot be modified once encapsulated by a JsonSerializerContext. Such …
```
> [Monaco]Fix Json format preview setting

- src/common/FilePreviewCommon/MonacoHelper.cs
After https://github.com/microsoft/PowerToys/commit/20a5f67222f74c687a08aa4d3bf1ba8c978faf86, when trying to run Peek Monaco preview on a release installer, there's a crash on WebView 2.
This seems to be caused by the MonacoHelper not recognizing it's on the WinUI3Apps directory.
`Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)` was replaced by `AppContext.BaseDirectory` on https://github.com/microsoft/PowerToys/commit/20a5f67222f74c687a08aa4d3bf1ba8c978faf86 , but the latter includes a stray directory separator at the end that must be removed for the remaining logic to make sense.
Built a release installer and tested Monaco on both Peek and the file preview handler.
> [Peek]Fix using the correct Monaco assets at runtime

- src/modules/registrypreview/RegistryPreviewUILib/ClipboardHelper.cs
- src/modules/registrypreview/RegistryPreviewUILib/RegistryKey.xaml.cs
- src/modules/registrypreview/RegistryPreviewUILib/RegistryPreviewMainPage.Utilities.cs
- src/modules/registrypreview/RegistryPreviewUILib/RegistryPreviewMainPage.xaml
- src/modules/registrypreview/RegistryPreviewUILib/RegistryPreviewMainPage.xaml.cs
- src/modules/registrypreview/RegistryPreviewUILib/RegistryValue.xaml.cs
- src/modules/registrypreview/RegistryPreviewUILib/Strings/en-US/Resources.resw
This PR...
- fixes line break parsing for REG_MULTI_SZ
- adds a tool tip to show the multiline version of value data.
- adds context menu with various copy actions to Key tree and Value list.
Manual testing.
> [Registry Preview] Copy context menu, data toltip, MULTI_SZ fix

- .github/actions/spell-check/allow/code.txt
- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
a new PTRun third-party plugin to read oauth OTP from yubikey.
> [PTRun][Docs] Add YubicoOauthOTP to Third-Party plugins

- src/modules/ZoomIt/ZoomIt/Zoomit.cpp
Now that there's a build flag to distinguish ZoomIt shipped in PowerToys from ZoomIt shipped By Sysinternals, ZoomIt that's shipped in PowerToys can react to the gpo setting even when running directly from the PowerToys installation location.
> [ZoomIt]React to gpo setting when run as standalone

- src/settings-ui/Settings.UI.Library/ImageSize.cs
- src/settings-ui/Settings.UI.UnitTests/ViewModelTests/ImageResizer.cs
- src/settings-ui/Settings.UI/Converters/ImageResizerFitToStringConverter.cs
- src/settings-ui/Settings.UI/Converters/ImageResizerSizeToAccessibleTextConverter.cs
- src/settings-ui/Settings.UI/Converters/ImageResizerUnitToStringConverter.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/ImageResizerPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/ImageResizerPage.xaml.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/ImageResizerViewModel.cs
- Added accessible name for the image size preset settings card group, giving additional context to the Add button when it is narrated.
- Replaced the Add button's "Add new size" accessible name with "Add new preset", as suggested.
- Added dynamic Name and FullDescription accessible fields for Edit and Remove buttons. Instead of just being "Edit" and "Remove", the Name properties now also refer to the preset name, e.g. "Edit the Small preset". New description fields give a complete summary of all the preset properties, e.g. "Removes the Large preset, which fits to 1920 by 1080 pixels".
- Fixed the fit and unit text being absent in the card description field.
- Refactored `ImageResizerFitToStringConverter` and `ImageResizerUnitToStringConverter` to create lookups instead of querying for …
> [Settings] ImageResizer settings accessibility updates, fixes and refactor

- src/common/ManagedTelemetry/Telemetry/DataDiagnosticsSettings.cs
- src/common/SettingsAPI/settings_helpers.cpp
Registry value was not being set properly ending with invalid registry value. When other apps try to read the value, crash was occurring.
- Close PT
- Disable data diagnostic in gpo
- Start PT
- Make sure all modules work
> [runner] Fix crashes caused by wrong setting AllowDataDiagnostics registry value

- src/modules/ZoomIt/ZoomIt/Zoomit.cpp
- src/modules/ZoomIt/ZoomItSettingsInterop/ZoomItSettings.cpp
- src/settings-ui/Settings.UI.Library/ZoomItProperties.cs
While testing the release candidate with ZoomIt, we found an error that caused the draw mode to not work after changing a Setting.
It turns out we were missing the code that sets opacity after loading the settings from PowerToys.
This PR adds that code.
This PR also identifies some other settings that are used internally by ZoomIt as state only and removes them from the settings the Settings application knows, so that we don't keep status for those while manipulating other settings and end up overwriting the changes the running ZoomIt has done to that internal state.
1 - Start ZoomIt.
2 - Verify Draw works.
3 - Change any Setting.
4 - Verify Draw still works. (Before this fix it would try to draw with transparent ink)
5 - Change pen color (Press G or B in draw mode for Green or Blue, for …
> [ZoomIt]Fix transparent draw after changing another setting

- README.md
Readme update for the 0.88 release.
> 0.88 changelog

- .pipelines/v2/templates/job-build-project.yml
- .pipelines/verifyAndSetLatestVCToolsVersion.ps1
Re-adds the workaround to get the current VC tools version, that was removed on: https://github.com/microsoft/PowerToys/commit/2c069ce708fcec23f3012c6434003908bead332c
Adopts the same changes to the workaround as happened on the Terminal project: https://github.com/microsoft/terminal/pull/18468
Dart CI passes.
> [ci]Proper workaround for the vc tools version check

- src/common/utils/package.h
When installing as user and then updating, the Win11 context menus msix entries aren't properly updated, meaning the context menu entries won't appear.
This PR checks if the package is at the right version or it will still run the msix install logic.
It also allows updating to older versions in the case of downgrades, just in case.
- Install 0.87.1 user installation.
- Verify the context menu entries are working.
- Run `Get-AppxPackage -Name *powertoys*` in Powershell, to make sure the context menu entries are installed.
- Install user installation from Dart with the updated code.
- Verify the context menu entries are still working.
- Run `Get-AppxPackage -Name *powertoys*` in Powershell, to make sure the context menu entries are installed and at the updated version.
> [ContextMenus]Update win11 msix menus if wrong version

- src/common/updating/updating.cpp
- src/common/updating/updating.h
C++23 <expected> has been introduced in VS17.3.6, and std::expected has conflict/inconsistent with the makeshift (expected-lite)
> [Build] compatibility with VS17.3 and later, for C++23 <expected> has conflict/inconsistent with the makeshift (expected-lite)

- src/modules/ZoomIt/ZoomIt/Zoomit.cpp
There is an assignment inside an if condition. This generates a warning C4706 on my Visual Studio 2022 17.12.4 . The warning is then considered as an error C2220. Added an explicit comparison != 0.
> [Zoomit]Fix warning C4706 and related error C2220

- src/modules/registrypreview/RegistryPreviewUILib/MonacoEditorControl.xaml
- src/modules/registrypreview/RegistryPreviewUILib/MonacoEditorControl.xaml.cs
- src/modules/registrypreview/RegistryPreviewUILib/Strings/en-US/Resources.resw
Open the system default web browser when clicking links in Monaco in the Registry Preview editor. 
The system web browser opens instead of the seperate WebView2 window.
Handled the `CoreWebView2.NewWindowRequested` event to open the system default web browser rather than a seperate WebView2 window when clicking links in the Monaco editor that it built in to Registry Preview.
Opens the default web browser selected through Windows Settings when clicking links in the Registry Preview editor.
> Use system default web browser when opening links through Monaco in RegistryPreview

- src/modules/poweraccent/PowerAccent.Core/Languages.cs
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.h
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.idl
Added  ` (backtick) and ~ (tilde) to VK_OEM_5 key (#20333). Note that as with many VK_OEM_* keys, the location of the key changes based on the keyboard. On ITA keyboards it is on the left of the 1 key. I've added the tilde character (already present in the VK_MINUS key) because as a programmer I think having both (relatively rarely used) characters together is easier to remember than having them hidden under two different keys. I think a better solution would be to have a Custom set of mappings that persons can configure through a json file. I don't like the idea of mixing QuickAccent together with Keyboard Manager because they are "different".
> [QuickAccent]Added ` (backtick) and ~ (tilde) to VK_OEM_5 (#20333)

- doc/devdocs/runner.md
runner.md file is out of date, update them to reflect newest code structure
The runner documentation is out of date,  powertoys_events.cpp,lowlevel_keyboard_event.cpp, win_hook_event.cpp
does not exist any more, and make simple document for newly added files for their functionality.
> Update runner.md to catch runner structure change.

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest/ExtendedCalculatorParserTests.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/CalculateEngine.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/CalculateHelper.cs
Added a function to the PowerToys Run calculator plugin to allow for a value to be treated as a certain angle unit. For example,  in `rad(pi / 2)`, `pi / 2` is treated as being in radians, which need converting to the user selected unit.
Added conversion functions for the PowerToys Run Calculator plugin. This allows the use of `rad`, `deg`, and `grad` to specify how to interpret a value. For example, `rad(pi / 2)` would treat the value `pi / 2` as being in radians, and convert it to the angle unit currently selected as default in the settings, by prepending the mathematical conversion (e.g. `(180 / pi) *`). This allows for quick conversions between the different angle units.
**Demonstration**:
When degrees is selected as the user specified unit:
This would convert the radians value `pi / …
> PowerToys Run Calculator: Add trigonometric angle unit conversion functions

- doc/devdocs/modules/launcher/new-plugin-checklist.md
- Change target framework
- Remove duplicate statement
- Move statement closer to something similar
- The target framework for plugins should be `net9.0-windows10.0.22621.0`.
- Should we link here? https://github.com/microsoft/PowerToys/blob/5ef918750d384b76d4db3b82fde8942396c6f3d5/src/Common.Dotnet.CsWinRT.props#L6
> [PTRun][Docs] Update new plugin checklist

- src/modules/powerrename/PowerRenameUILib/PowerRenameXAML/MainWindow.xaml.cpp
- src/modules/powerrename/PowerRenameUILib/Strings/en-us/Resources.resw
Adds these hints to the Regex cheatsheet:
* `^`: Start of the string
* `$`: End of the string
* `+`: Matches one or more of the preceding token
* `?`: Matches zero or one of the preceding token
* `*`: Matches zero or more of the preceding token
Also updates the `\S` description to remove an unnecessary backslash (resw doesn't need escapes)
(The typo is fixed)
> [PowerRename]Add `$`, `^` and quantifiers to RegEx cheatsheet

- src/modules/imageresizer/ui/App.xaml
- src/modules/imageresizer/ui/Views/AutoDoubleConverter.cs
- src/modules/imageresizer/ui/Views/InputPage.xaml
- src/modules/imageresizer/ui/Views/NumberBoxValueConverter.cs
- src/modules/imageresizer/ui/Views/ZeroToEmptyStringNumberFormatter.cs
- src/settings-ui/Settings.UI/Converters/ImageResizerDoubleToAutoConverter.cs
- src/settings-ui/Settings.UI/Converters/ImageResizerNumberBoxValueConverter.cs
- src/settings-ui/Settings.UI/Converters/ImageResizerZeroToEmptyStringNumberFormatter.cs
- src/settings-ui/Settings.UI/SettingsXAML/Controls/ImageResizerDimensionsNumberBox.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/ImageResizerPage.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
This fixes some related issues with the Width and Height NumberBox controls for the Custom preset. The issues were:
1. Users could not clear existing numbers from the field and move away from the field without a databinding error being displayed. (Red border.)
2. Settings were not saved if Width or Height were blank, leading to the _previous_ value for that dimension being used in the resize operation. This would result in incorrect sizes for the resulting image, and the UI not showing the actual value used.
3. Empty/auto values were not saved to the settings file, meaning the previous value of Width or Height was loaded in again when Image Resizer was re-launched.
The issue centred around the fact that emptying a NumberBox bound to a non-nullable double value will result in a data …
> [ImageResizer] Fix issues with blank Width and Height controls

- src/modules/poweraccent/PowerAccent.Core/Languages.cs
This adds the final sigma character ( ς ) to the Greek language.
I have changed the line of characters under the Greek language to include a new character, ς which is a symbol used in Greek if the final letter is a sigma.
I am able to use ς in the quick accent after running the debug binary. Nothing seems to be broken, I only made a single string change
> Adds final sigma ( ς ) to quick accent under Greek language.

- .pipelines/v2/templates/job-build-project.yml
- .pipelines/v2/templates/job-test-project.yml
- .pipelines/v2/templates/pipeline-ci-build.yml
Forked repositories cannot obtain an access token for authentication due to the SFI requirement.
ARM experiences an out-of-memory issue when use download task.
Skipped the test stage for ARM testing on forked repositories.
Used the download task for X64 to ensure X64 tests always run successfully.
> [CI] Use Download Task for X64 and Bypass ARM Testing for Forked Repositories

- src/modules/launcher/Wox.Infrastructure/ShellLinkHelper.cs
This PR extends the IpersistFile Load method with parameters to make no change on the loaed item --> to not block other programs (MSI installer) modifying the item. 
See: https://github.com/microsoft/WSL/issues/11276#issuecomment-2680560973
The STGM_TRANSACTED parameter is added, which ensures that any changes are buffered. Without this parameter the issue persists, adding this parameter solves the issue.
Tesed locally with https://github.com/avjts/powerlauncher-bug
> [PTRun]Fix locking link files for MSI installers. Warning 1946

- doc/thirdPartyRunPlugins.md
Add [FirefoxBookmark](https://github.com/8LWXpg/PowerToysRun-FirefoxBookmark) to Third-Party plugins.
> [PTRun][Docs] Add FirefoxBookmark to Third-Party plugins

- src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
No longer applies round corners on W11 build 22000 since it crashes.
Changed the condition for setting round corners from W11 to W11 greater than 22000.
Tested by manually changing the if to force it to not use round corners.
> [Run] Fix round corners crashing on 22000

- src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Storage/Win32ProgramRepositoryTest.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/Win32ProgramRepository.cs
In order to solve the concern about this PR: https://github.com/microsoft/PowerToys/pull/37924/files#diff-5f8702652973666fc4791347d4370d8cbb7f6cb63574cbfede0b493790a5fca7
TL;DR:
Fire and forget is better than block the current thread. This could cause another issue.
> [PT Run] Async the OnRename to unblock thread

- .pipelines/v2/templates/job-build-project.yml
After https://github.com/microsoft/PowerToys/pull/37574 was merged, Dart signing tasks started failing, since those still require .NET 6
This PR brings back .NET 6.
Triggered Dart CI and waiting for it to succeed.
> [CI]Bring back .NET 6 for signing tasks to fix pipelines

- src/modules/cmdpal/CmdPalModuleInterface/dllmain.cpp
- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
Related to https://github.com/microsoft/PowerToys/pull/37908
> Do not show CmdPal on startup

- src/settings-ui/Settings.UI.Library/CmdPalProperties.cs
- src/settings-ui/Settings.UI.Library/Utilities/Helper.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/CmdPalPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/CmdPalPage.xaml.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/CmdPalViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/DashboardViewModel.cs
Related to https://github.com/microsoft/PowerToys/pull/37908
> [settings] Show uneditable shortcut in CmdPal page 

- installer/PowerToysSetup/Product.wxs
- installer/PowerToysSetupCustomActions/CustomAction.cpp
- installer/PowerToysSetupCustomActions/CustomAction.def
Currently, when PowerToys does an upgrade, it uninstalls the previous CmdPal package and installs the new one.
This is not the correct way to do a packaged application update, as that will reset all Settings, since local state gets deleted when a msix package is uninstalled.
This PR adds a custom action specific to remove CmdPal package only on an uninstall that's not part of an upgrade.
Waiting for the 2 release builds:
0.89.55 PowerToys with 0.0.5 CmdPal https://microsoft.visualstudio.com/Dart/_build/results?buildId=118699807&view=results
[10:48](https://janea.slack.com/archives/D4G3P9N73/p1742510934946949)
0.89.56 PowerToys with 0.0.6 CmdPal https://microsoft.visualstudio.com/Dart/_build/results?buildId=118699834&view=results
Will test the upgrade scenario to make sure it doesn't clear …
> [Installer]Properly update CmdPal on upgrade

- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/InstallPackageListItem.cs
I don't know why defaultInstalledVersion becomes null. But, at least we need to fix it...
Test case: vscode.
Closes https://github.com/zadjii-msft/PowerToys/issues/572
> [cmdpal] Fix winget extension crash issue

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/CommandBar.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/Tag.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Strings/en-us/Resources.resw
- Removing the redundant icon + text in the bottom left corner
- Minor styling tweaks
- Adding subtle show/hide animations
- Improved narrator support for Settings button
- Minor design tweaks to the tags for better visibility (still needs more work in the future)
> [cmdpal] UX tweaks

- src/modules/cmdpal/Microsoft.CmdPal.UI/Helpers/WindowExtensions.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/ExtensionPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/ExtensionsPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/GeneralPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/SettingsWindow.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/SettingsWindow.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ToastWindow.xaml.cs
Settings window UI polishing:
- Make the navigation view toggle button move in the title bar when navigation view mode is compact or minimal
- Center settings card in the window
- Properly set windows icon in order to make it visible in task manager and task view
_main branch_
_PR_
> [CmdPal] Settings UI polishing

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsViewModel.cs
Clicking the Reset button on the Activation Shortcut control sets it to null. Should set to the default hotkey instead.
This PR sets it to the default value instead and notifies the property changed so that UI is updated too with the reset instead of just showing a clean hotkey.
With the default hotkey set, try resetting. Verify nothing changes.
With another hotkey set, try resetting. Verify it's now default.
> [CmdPal]Fix resetting the hotkey in Settings

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Registry/Helpers/RegistryHelper.cs
Calling `string.Replace` with an empty string as the first parameter was raising an exception. Added a check to prevent this.
> [CmdPal] Registry: typing "\" causes the page to throw an exception

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Calc/CalculatorCommandProvider.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Shell/FallbackExecuteItem.cs
Icons for the fallback commands of the calculator and run command extensions were wrong. This PR uses the correct icons for the fallback commands.
Screenshot with the changes from this PR:
Run Command Palette and verify icons are good.
> [CmdPal]Fix Calc and Command extension fallback command icons

- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/SettingsWindow.xaml.cs
What we were doing only worked in English. The `.ToString` would get you the text of the nav item, not the `Tag`
`InvokedItemContainer` gets you the `NavigationViewItem`.
> CmdPal: Fix opening SUI pages in other languages

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandManager.cs
This only repros on my desktop, so I suppose that means a slower machine is needed
I was mistaken, and assumed we were already operating on a copy here. We weren't. That meant that it was possible for another extension to be detected, change the list, and crash the whole palette.
No longer does my desktop crash on startup
> Fixes a race in extension startup

- src/modules/cmdpal/Microsoft.CmdPal.UI/Package-Dev.appxmanifest
- src/modules/cmdpal/Microsoft.CmdPal.UI/Package.appxmanifest
- `appLicensing` avoids the issue where installation requires access to the store servers for licensing.
- It was decided that PowerToys would manage CmdPal's startup.
> CmdPal: add appLicensing for offline install; disable startup

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
This is a much tidier solution. Don't default _everything_ to a weight of 1 if the query is whitespace. Instead, do a simple string contains check (because FuzzySearch will beef it on just whitespace)
Closes #38133
I originally based this off of #38157, so I know these two won't collide
> Hide commands with whitespace only names better

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelViewModel.cs
The problem: 
> * we need to go update all the Fallback commands. (these are ones that extensions can use to react to the search text - basically, "what the user typed wasn't found immediately, but here's something they can fall back on"
>   * this is wacky, because the way I had it, I update each item, and if it "changes visibility", then we need to update the main list, because we've already removed it from the list. So we need to re-update the list to account for that
>     * you missed it reading that (and i missed it writing it) but that basically means we re-populate the list F={num fallbacks} times, because each one sends the "do it again" message
>     * That results in us basically creating (F+1)*(N=num items+apps) view models, initializing them, and not needing most of them
The …
> Update Fallback commands async, once

- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/InstallPackageCommand.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/InstallPackageListItem.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/WinGetExtensionPage.cs
It appears there are two issues in WinGet regarding the installation of dependencies.
https://github.com/microsoft/winget-cli/issues/4661 https://github.com/microsoft/winget-cli/issues/4679
For CmdPal 0.1, we're going to skip installing dependencies to make extension installation more robust. This will mostly work because extensions will depend on the same frameworks as the command palette itself (for now).
We will revert this once these two issues are fixed.
> cmdpal: Skip dependency installs for extensions

- .github/workflows/msstore-submissions.yml
Update the Github Action to install .NET 9 to unblock the release
> Install .NET 9 for MSStore release

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/NativeMethods.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/NativeMethods.txt
- src/modules/cmdpal/Microsoft.CmdPal.UI/ToastWindow.xaml.cs
Ah of course, AppWindow.Resize doesn't use DIPs. Why would it? It's not like literally everything else in XAML does.
Related to half of https://github.com/zadjii-msft/PowerToys/issues/508
> Scale the toast window for DPI

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsSettings/WindowsSettings.json
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/WindowsSettings.json
In CmdPal and PT Run, if you currently try to go to mouse pointer, it fails.  This looks to be due to capitalization in the command.  This can be validated via run dialog also.
shifting to lowercase fixes the bug.
> Fixing settings for mouse pointer for pt run and cmdpal

- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/Pages/InstallPackageListItem.cs
- src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WinGet/WinGetStatics.cs
This is a fix for a pair of related crashes. 
Basically, we'd crash on startup if we failed to initialize WinGet. This could happen in two different places:
* If WinGet wasn't installed, then we'd explode, cause obviously we can't call its APIs
* If we're running as Admin, we won't be able to instantiate it's COM server. 
Regardless of how it happens, I've defaulted us to just _not enabling the winget built-in_. That's the simplest solution here. 
As I was helpfully reminded, there's also an elevated WindowsPackageManagerFactory we could use too - though, that wouldn't solve the case of "winget isn't installed"
Closes #38460
Closes #38440 (most likely)
> Fix the WinGet missing / Admin crash

- src/settings-ui/Settings.UI/SettingsXAML/OobeWindow.xaml.cs
Small quality of improvement for users that want to maximize OOBE.  I think this was a design choice we all made for pure design.  I don't see any good reason to not allow the window to maximize.
> empowering users to maximize OOBE to their heart desire

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/SystemTrayIconChangedMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/GeneralPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Strings/en-us/Resources.resw
Added a settings to enable/disable the system tray icon (enabled by default).
Adopter the term "system tray icon" for consistency with Windows 11 settings.
> [CmdPal] Tray icon settings

- .config/configuration.vsEnterprise.winget
- .config/configuration.vsProfessional.winget
- .config/configuration.winget
Setting developer mode, installing Visual Studio 2022 & fetching and installing VS components all require elevation. Added `securityContext: elevated` for these resources. These configurations can now be invoked from user context, and will prompt for a single UAC to run resources that require elevation in a separate process.
Ran the configurations in a clean VM and noticed that all these resources required elevation
> Add securityContext to configuration files

- src/modules/keyboardmanager/KeyboardManagerEditorLibrary/EditorHelpers.cpp
- src/modules/keyboardmanager/KeyboardManagerEngineLibrary/KeyboardEventHandlers.cpp
- src/modules/keyboardmanager/KeyboardManagerEngineLibrary/trace.cpp
- src/modules/keyboardmanager/common/Helpers.cpp
- src/modules/keyboardmanager/common/Helpers.h
- src/modules/keyboardmanager/common/KeyboardManagerCommon.vcxproj
- src/modules/keyboardmanager/common/KeyboardManagerCommon.vcxproj.filters
- src/modules/keyboardmanager/common/Modifiers.h
- src/modules/keyboardmanager/common/RemapShortcut.h
- src/modules/keyboardmanager/common/Shortcut.cpp
- src/modules/keyboardmanager/common/Shortcut.h
When shortcut set a modifier key without left or right, It sticks. For example, for shift if right shift is pressed we don't send right shift but VK_SHIFT instead which causes right shift to get stuck. The fix is to keep a status of which keys are pressed and correctly sending the correct key.
Keep a status of which key( left or right) is pressed for the Ctr, Alt and Shift key not just Win key.
Tested using:
Ctr + Q->t both left ctr and right ctr works
Alt + Q ->t both left and right alt works
Shift + Q ->t both left and right shift works
Alt+Ctr+Q->t any combinations of alt and ctr + q works
> [KeyboardManager] Fix modifier Key (Not right or left) stuck 

- src/modules/colorPicker/ColorPickerUI/Helpers/AppStateHandler.cs
- src/modules/colorPicker/ColorPickerUI/Keyboard/KeyboardMonitor.cs
Only closes the Color Picker editor if the window has focus. Also unifies the esc/backspace behavior.
* Removed the closing logic for ESC from `KeyboardMonitor.cs`, both ESC and Backspace now use `HandelEscPressed()`
* `HandleEscPressed()` closes the app if:
* Closing with escape isn't blocked by the adjust color flyout
* Either color picker is shown, or the editor window is focused
Manually tested:
* Color picker closes on <kbd>Esc</kbd>/<kbd>Backspace</kbd>
* Editor closes on <kbd>Esc</kbd>/<kbd>Backspace</kbd> if it has focus
* Editor doesn't close on <kbd>Esc</kbd>/<kbd>Backspace</kbd> if it doesn't have focus
* Editor doesn't close on <kbd>Esc</kbd>/<kbd>Backspace</kbd> if the adjust color popup is active
* Everything works the same after reactivating the color picker from the editor
> [ColorPicker]Only close on escape if focused

- .github/workflows/dependency-review.yml
- .github/workflows/msstore-submissions.yml
- .github/workflows/spelling2.yml
This pull request implements security best practices by pinning all GitHub Action tags and Docker tags to their full-length commits, following recommendations from GitHub's Security Hardening Guide. Pinning ensures that the actions used in workflows are immutable, reducing the risk posed by unintended or malicious changes.
Additionally, this PR integrates the **Dependency Review Workflow**, which scans for vulnerable dependency versions introduced by pull requests. This feature provides early warnings about security vulnerabilities, increasing visibility into changes and preventing vulnerabilities from being introduced into the repository.
References:
- [GitHub Security Guide](https://docs.github.com/en/code-security)
- [Open Source Security Foundation (OpenSSF) Security …
>  Apply security best practices for GitHub Actions / Dependency 

- src/modules/powerrename/PowerRenameUILib/PowerRenameXAML/MainWindow.xaml.cpp
- src/modules/powerrename/PowerRenameUILib/Strings/en-us/Resources.resw
- src/modules/powerrename/lib/Helpers.cpp
- src/modules/powerrename/unittests/PowerRenameRegExBoostTests.cpp
- src/modules/powerrename/unittests/PowerRenameRegExTests.cpp
Add support for 12-hour time format patterns in PowerRename. This adds new patterns:
- `$HH` - Hours in 12-hour format with leading zero (01-12)
- `$H` - Hours in 12-hour format without leading zero (1-12)
- `$TT` - AM/PM indicator in uppercase (AM or PM)
- `$tt` - AM/PM indicator in lowercase (am or pm)
- Midnight (12:00 AM / 00:00)
- Noon (12:00 PM)
- Single-digit hours
- AM/PM transitions
- Mixed format patterns
This PR enhances PowerRename's time formatting capabilities by adding support for 12-hour time formats. Changes include:
1. Added new time patterns (`$HH`, `$H`, `$TT`, `$tt`) for 12-hour format support
2. Updated `GetDatedFileName` to handle 12-hour time conversion
3. Added unit tests for both standard and Boost regex implementations
4. Added string resources for pattern …
> [PowerRename] Add 12-hour time format patterns with AM/PM support (#30703)

- src/modules/launcher/PowerLauncher/Plugin/PluginManager.cs
- src/modules/launcher/PowerLauncher/Properties/Resources.Designer.cs
- src/modules/launcher/PowerLauncher/Properties/Resources.resx
- src/modules/launcher/PowerLauncher/SettingsReader.cs
- src/modules/launcher/Wox.Plugin/PluginMetadata.cs
- src/modules/launcher/Wox.Plugin/PluginPair.cs
- src/modules/launcher/Wox.Plugin/Properties/Resources.Designer.cs
- src/modules/launcher/Wox.Plugin/Properties/Resources.resx
This PR add versions to the following plugin error messages:
- Loading error.
- Init error.
> [PowerToysRun] Add version info to plugin error messages

- .github/actions/spell-check/expect.txt
- src/modules/cmdpal/CmdPalModuleInterface/dllmain.cpp
- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
- src/settings-ui/Settings.UI/SettingsXAML/OobeWindow.xaml.cs
- tools/build/self-sign.ps1
Build and run powertoys runner would result in an error: 
-- Of course, disable&enable that would cause the error too.
dev_commandPal is not found.
This is because:
1. We do not produce a msix file for installation at normal build time.
2. 1 can be solved by remove the condition for generateMsixFile, while
3. If you don't sign it with a trusted certificate, it would not be registerd.
So this pr 
1. Handles the launch problem for command palette from runner
2. Self sign the msix file to make it available during dev_commandpalette registration
Dev experience may be not straight forward though.
I'd like to check in a one stop build script to make build&sign work in local environment.
> [cmdpal] Run cmdpalette from runner locally

- .pipelines/ESRPSigning_core.json
There are 2 files newly added last week and cause build break for a week:
1. CmdPalKeyboardService.dll
2. Testably.Abstractions.FileSystem.Interface.dll
Kick off the signing build and verified.
> Fix build break because of miss Signing for new files

- .pipelines/v2/release.yml
We were previously publishing all symbols, even for internal/private builds, for 100 years.
> release: don't publish private symbols for 100 years

- src/modules/poweraccent/PowerAccent.Core/PowerAccent.cs
- src/modules/poweraccent/PowerAccent.UI/Selector.xaml.cs
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.cpp
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.h
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.idl
Now cancel the task of ShowToolbar if another is started,
ShowToolbar  would start a task with the delay of the normal input delay, this is an issue since if you release the activation key and then press it again a new task would be created, then the previous task could end and show the toolbar. This creates scenarios where showing of the toolbar is not always at the same time.
Tested by using 300ms delay.
Tested by using 5000ms delay. Hold the spacebar for 3 seconds release and then hold it again for 5 seconds. Previously the taskbar would be triggered at the second hold after holding it for 2 seconds, Now it is shown after holding it for 5 seconds.
> [PowerAccent] Cancel previous ShowToolbar task if a new one is triggered

- .pipelines/v2/templates/job-test-project.yml
This pull request makes a small but significant change to the `.pipelines/v2/templates/job-test-project.yml` file by adding a timeout setting for test jobs.
* [`.pipelines/v2/templates/job-test-project.yml`](diffhunk://#diff-c974373b0fb1357dfc0d236a86c304ad1d95acb861f83d472db3a7193e1d88a6R21): Added a `timeoutInMinutes` parameter with a value of 300 to ensure that test jobs have a maximum runtime limit.
> Add timeout for ui test job

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandBarViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ContentPageViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
If we don't slow-initialize the whole menu when it changes, then we won't see that there's secondary (& more) commands.  
Tested this with the extension from [waaverecords/CmdPal.Ext.Spotify#4](https://github.com/waaverecords/CmdPal.Ext.Spotify/pull/4)
Closes #38959 
Also seemingly closes #38347 - seems that needed additional bumping of the `EmptyContent`'s
> Fully initialize context menus when they change

- src/modules/cmdpal/CmdPalModuleInterface/dllmain.cpp
> Retry in another thread

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/FallbackTimeDateItem.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/Helpers/AvailableResultsList.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/Helpers/SettingsManager.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/Helpers/TimeDateCalculator.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/Properties/Resources.Designer.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/Properties/Resources.resx
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/TimeDateCommandsProvider.cs
This PR adds fallback functionality to the TimeDate extension for Command Palette. With this change, users can directly enter time/date-related queries without first selecting the TimeDate command. The fallback command processes the query and displays date/time information directly in the results list when appropriate.
Added new `FallbackTimeDateItem` class to handle fallback command processing
Updated resources to include a display title for the fallback command
Modified `TimeDateCommandsProvider` to expose the fallback command
Reuses existing calculation logic from `TimeDateCalculator`
Added option in setting for fallback enabling/disabling
> [CmdPal] Added fallback for time and date

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Calc/Microsoft.CmdPal.Ext.Calc.csproj
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Registry/Microsoft.CmdPal.Ext.Registry.csproj
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Shell/Microsoft.CmdPal.Ext.Shell.csproj
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/Microsoft.CmdPal.Ext.TimeDate.csproj
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WindowWalker/Microsoft.CmdPal.Ext.WindowWalker.csproj
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WindowsServices/Microsoft.CmdPal.Ext.WindowsServices.csproj
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WindowsTerminal/Microsoft.CmdPal.Ext.WindowsTerminal.csproj
Safe change, no testing needed.
This pull request adds an import statement for `Common.Dotnet.AotCompatibility.props` across multiple project files to improve AOT compilation support. 
- **Microsoft.CmdPal.Ext.Calc.csproj**: Added import for `Common.Dotnet.AotCompatibility.props`.
- **Microsoft.CmdPal.Ext.Registry.csproj**: Added import for `Common.Dotnet.AotCompatibility.props`.
- **Microsoft.CmdPal.Ext.Shell.csproj**: Added import for `Common.Dotnet.AotCompatibility.props`.
- **Microsoft.CmdPal.Ext.TimeDate.csproj**: Reordered imports, adding `Common.Dotnet.AotCompatibility.props` and re-adding `CmdPal.pre.props`.
- **Microsoft.CmdPal.Ext.WindowWalker.csproj**: Added import for `Common.Dotnet.AotCompatibility.props`.
AOT Checklist after this change:
**UI:**
- See 61bad789f
**Ext Sdk:** …
> [cmdpal] Ref to AotCompatibility in some cmdpal project.

- src/settings-ui/Settings.UI.Library/CmdPalProperties.cs
Handle CmdPal HotKey initialization.
I have been able to reproduce it removing HotKey from CmdPal settings.json.
Don't know the root cause, but the fix fallback to default HotKey preventing settings app from crashing when HotKey  is null.
Verified that settings app doesn't crash after removing HotKey from CmdPal settings.json
> [Settings] Fix null CmdPal HotKey crash

- src/modules/AdvancedPaste/AdvancedPaste/Helpers/OcrHelpers.cs
Fix advanced paste failing to create ocrEngine on some English language tags. (en-CA, others)
When attempting to use AdvancedPaste Image to Text, and error was shown with stack trace in logs. 
Method GetOCRLanguage compared the current language tag (en-CA) to OcrEngine.AvailableRecognizerLanguages. The returned list on my PC was en-GB, en-US. Both of these should work for OCR against en-CA. 
Added check if GetOCRLanguage returned null, call TryCreateFromUserProfileLanguages. In my cases, this succeeds, however I do not know what that behaviour may lead to in other language combinations.
Built installer
Installed in a fresh vm with language set to en-CA
Attempted Image to Text
OCR was successful
> 37405 Advanced Paste: Image To Text doesn't work with English (Canada)

- src/modules/launcher/PowerLauncher/ViewModel/ResultsViewModel.cs
- src/modules/launcher/Wox.Plugin/Result.cs
- src/modules/launcher/Wox.Plugin/UserSelectedRecord.cs
Implement an additional functionality on the Result model allowing the prevention of selected count retrieval.
This PR adds an additional property to the `Result.cs` model which allows for disabling the functionality which fetches the `SelectedCount` data from PowerToys. This enables the ability for plugins to prevent the `SelectedCount` property from being populated for individual results meaning that the sort order can be manipulated as desired by the Plugin giving more control back to the plugin developers.
> [PTRun] Allow preventing usage based ordering results

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/PageViewModel.cs
Closes #38829
If we always `UpdateProperty` here, then there's a possible race condition, where we raise the `PropertyChanged(SearchText)` before the subclass actually retrieves the new `SearchText` from the model. In that race situation, if the UI thread handles the `PropertyChanged` before `ListViewModel` fetches the `SearchText`, it'll think that the old search text is the _new_ value.
> Wait to update SearchText until we've actually updated SearchText

- .pipelines/ESRPSigning_core.json
- src/modules/keyboardmanager/KeyboardManagerEditorLibraryWrapper/KeyboardManagerEditorLibraryWrapper.cpp
- src/modules/keyboardmanager/KeyboardManagerEditorLibraryWrapper/KeyboardManagerEditorLibraryWrapper.h
- src/modules/keyboardmanager/KeyboardManagerEditorUI/App.xaml.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Helpers/EditorConstants.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Helpers/ValidationErrorType.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Helpers/ValidationHelper.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Interop/KeyType.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Interop/KeyboardManagerInterop.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Interop/KeyboardMappingService.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Pages/Remappings.xaml
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Pages/Remappings.xaml.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Styles/InputControl.xaml
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Styles/InputControl.xaml.cs
> [Target feature branch ``feature/KeyboardManagerWinUI3``]
- Add delete remapping function
- Fix the problem that Keyboard Hook is not cleaned properly when the toggle button lost focus (user clicked other checkbox or switched to another app)
- Make sure original toggle button is checked for InputControl by default on Editor launch
- Disable app setting for single key remapping to keep consistent behavior as current editor
- Ensuring the Modifier Keys that user input don't repeat
- Make sure the shortcut takes at most 4 modifier keys and show notification to the user
- Add validation to show teaching tip for reserved illegal shortcuts - Win+L and Ctrl+Alt+Delete
- Add validation to check if the user is trying to remap a key or shortcut that's already mapped for the same app context
- Add …
> [Keyboard Manager] New Keyboard Manager - Keys Remapping Window, Keyboard Hook and Input Validator

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/AppCache.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/ReparsePoint.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Storage/FileSystemWatcherWrapper.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Storage/PackageRepository.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Storage/Win32ProgramFileSystemWatchers.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Storage/Win32ProgramRepository.cs
Just do some safe change. To avoid dup operation during testing in the future.
> [cmdpal][AOT] clean up some AOT related issue

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
I cannot find an issue for this. I swear I filed it somewhere.
If you open winget, search for "terminal", wait till it loads, then hit `esc`, we'll clear the search and empty the list, but never actually hide the details pane. That looks weird.
This fixes that.
Closes _nothing i guess_.
> Dismiss the details pane when the list gets emptied

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.System/FallbackSystemCommandItem.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.System/Pages/SystemCommandPage.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.System/Properties/Resources.Designer.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.System/Properties/Resources.resx
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.System/SystemCommandExtensionProvider.cs
On a reload, the system commands fallback would leave the "restart" fallback behind, for the same reason as what we found around e40372c & ef264d9 in #38455
closes nothing, these are just nits
> cmdpal: unset the command if we don't find a command

- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/NativeMethods.txt
Prevent CmdPal window from maximizing when user double-click the title bar area.
Verified that window doesn't maximize anymore
> [CmdPal] Prevent maximizing

- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/NativeMethods.txt
This avoids the few frames of "flicker in" that XAML does when the window is SW_SHOW'n
closes #38384
closes #38404
closes #38438
> CmdPal: Cloak the window instead of hiding it

- .pipelines/v2/templates/job-test-project.yml
- .pipelines/v2/templates/pipeline-ui-tests-automation.yml
This pull request introduces enhancements to the pipeline configurations for testing different platforms, with a focus on Windows 10 and Windows 11 for x64 architecture. The changes aim to improve flexibility and clarity in platform-specific test configurations.
* [`.pipelines/v2/templates/job-test-project.yml`](diffhunk://#diff-c974373b0fb1357dfc0d236a86c304ad1d95acb861f83d472db3a7193e1d88a6R23-R42): Updated the `BuildPlatform` variable to explicitly set `x64` for `x64Win10` and `x64Win11` platforms, ensuring consistent naming in artifact generation. Added conditional demands for `SHINE-W11-Testing` when running UI automation pipelines on `x64Win11`.
* [`.pipelines/v2/templates/pipeline-ui-tests-automation.yml`](diffhunk://#diff-68219acb736b89e7c4ce1939130f504198cbc8c077aa540d5e1b5649f206 …
> Support pipeline running on win11 x64

- .pipelines/v2/release.yml
This was just... silly, in 2025.
> release: stop hardcoding version numbers for the telemetry package

- .pipelines/v2/templates/job-build-project.yml
This will ensure that the command palette package is copied to the artifact directory.
If code signing was enabled, the final copied package will be the signed version.
Minor build rule rearranging was required to collect the command palette package path for the staging step when signing was _disabled_. I did this solely so that we could verify the results in CI.
Review with whitespace disabled.
> build: stage the command palette as a separate artifact

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs
This was especially noticeable with the icons extension.
Turns out in #39051, when I was experimenting with getting AoT clean, I accidentally called this twice. Then we actually committed that straight up.
This PR reverts that. It also moves a similar case where we were initializing all the tags on the UI thread. That's wrong too - we need to fetch properties off the UI thread, then update the list on the UI thread.
Closes nothing, I didn't file this yet.
> CmdPal: fix a perf regression loading pages

- src/modules/MouseWithoutBorders/ModuleInterface/dllmain.cpp
Fixes the firewall rule configuration for Mouse Without Borders to allow incoming remote connections from IP addresses outside the local subnet, addressing connectivity issues when devices are on different subnets.
Previously, the firewall rule for Mouse Without Borders limited access to the LocalSubnet, which prevented connections between devices on different network segments. This change updates the rule to remove the remote IP restriction, and keep the control logic in code.
This change helps improve usability in environments where devices are logically separated across VLANs, VPNs, or different Wi-Fi networks.
Manually removed the existing rule and applied the updated one
Verify the newly created one is not subnet only
> MWB: Fix firewall rule to allow remote connections from IPs outside the local subnet

- src/common/UITestAutomation/Session.cs
- src/modules/Hosts/Hosts.UITests/HostsSettingTests.cs
This pull request introduces improvements to the window attachment process in the `Session.Attach` method and removes a hardcoded delay in the `TestWarningDialog` test. The changes enhance reliability and maintainability by implementing a retry mechanism and eliminating unnecessary delays.
* [`src/common/UITestAutomation/Session.cs`](diffhunk://#diff-5bb9c8f423afc54b5ad5efd4a530027f691a770d449697a6027a1468e7a20e7bL483-R504): Updated the `Session.Attach` method to include a retry mechanism with a 2-minute timeout and 5-second intervals when searching for a window by its title. This ensures more robust handling of scenarios where the target window is not immediately available.
* [`src/modules/Hosts/Hosts.UITests/HostsSettingTests.cs`](diffhunk://#diff-3782109c99cd66a2c1b870a83d1f9d9807422479 …
> Add retry in attach

- src/common/FilePreviewCommon/QoiImage.cs
Make sure we account for Bitmap row length being a multiple of 4 when reading Qoi files.
Built and run and restarted file explorer.
Sample files from my comment on the issue (after rewriting each one to force the thumbnail to regenrate):
> [peek, explorer] Update QOI reader for 3-channel images

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Shell/FallbackExecuteItem.cs
Corrected the Run fallback handler to provide the same context items as it does on the run page.
**Closes:** #39092
> CmdPal: Display correct context items for run fallback

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WindowsSettings/Pages/WindowsSettingsListPage.cs
The search results when finding settings with `$` was sorted alphabetically. Updated this behavior to sort them based on relevance to the query.
Original search results with query provided in issue:
New search results with query provided in original issue:
Example of results when giving a query that matches many, but is also an exact match.
Closes #38615
> CmdPal: Improving order of results from settings search

- .config/configuration.vsEnterprise.winget
- .config/configuration.vsProfessional.winget
- .config/configuration.winget
Using the [Microsoft.Windows.Settings](https://www.powershellgallery.com/packages/Microsoft.Windows.Settings/) module is the now the recommended way of configuring Windows Settings, including developer mode.
Verified that setting developer mode with the new resource works as intended
> Use Microsoft.Windows.Settings module for enabling developer mode

- doc/thirdPartyRunPlugins.md
This PR introduces the **SpeedTest** plugin—a new PowerToys Run extension that lets you run internet speed tests instantly, without opening a browser or separate application. Also was problem with formating previous Plugin "Linear"
🔗 **Learn more**  
| Plugin | Author | Description |  
|:-------|:------:|:------------|  
| [SpeedTest](https://github.com/ruslanlap/PowerToysRun-SpeedTest) | [ruslanlap](https://github.com/ruslanlap) | One-command internet speed tests with real-time results, modern UI, and shareable links. |
---
- **One-command tests**  
Run a full speed test (download, upload, ping, server) via PowerToys Run ().   and hit Enter! (or change to  or any other keyword in the settings)
- **Modern, theme-aware UI**  
WPF-based window adapts automatically to light or dark Windows …
> 🚀 Add SpeedTest Plugin for PowerToys Run to Third-Party plugin

- .github/actions/spell-check/expect.txt
- .github/workflows/package-submissions.yml
Few updates to the WinGet publish workflow action
- Use GitHub release event instead of manually making an API call to GitHub API and then fetching the target release. The target release is directly accessible via the event. The refactor is similar to the GitHub action of [microsoft/edit](https://github.com/microsoft/edit/blob/main/.github/workflows/winget.yml) repo's workflow
- With the latest winget-create release, the preferred method for providing the GitHub token in CI/CD environment is via the environment variable `WINGET_CREATE_GITHUB_TOKEN`. Removed use of `--token` and switched to environment variable. See https://aka.ms/winget-create-token for details.
> Updates to WinGet publish script

- .github/actions/spell-check/expect.txt
- src/modules/colorPicker/ColorPickerUI/Helpers/AppStateHandler.cs
- src/modules/colorPicker/ColorPickerUI/Mouse/IMouseInfoProvider.cs
- src/modules/colorPicker/ColorPickerUI/Mouse/MouseHook.cs
- src/modules/colorPicker/ColorPickerUI/Mouse/MouseInfoProvider.cs
- src/modules/colorPicker/ColorPickerUI/Settings/IUserSettings.cs
- src/modules/colorPicker/ColorPickerUI/Settings/UserSettings.cs
- src/modules/colorPicker/ColorPickerUI/ViewModels/MainViewModel.cs
- src/settings-ui/Settings.UI.Library/ColorPickerProperties.cs
- src/settings-ui/Settings.UI.Library/ColorPickerPropertiesVersion1.cs
- src/settings-ui/Settings.UI.Library/ColorPickerSettings.cs
- src/settings-ui/Settings.UI.Library/Enumerations/ColorPickerActivationAction.cs
- src/settings-ui/Settings.UI.Library/Enumerations/ColorPickerClickAction.cs
- src/settings-ui/Settings.UI.Library/SettingsUtils.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/ColorPickerPage.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/ColorPickerViewModel.cs
Enables the users to choose what left, right, and middle click does when color picker is open.
Adds option to choose from 3 click behaviors for each standard mouse button:
* **Pick color and open editor**: Copies color to clipboard, saves it to the color history and opens the editor
* **Pick color and close**: Copies color to clipboard, saves it to the color history and exits
* **Close**: Closes color picker without copying the color
Pressing <kbd>Enter</kbd> or <kbd>Space</kbd> does what clicking the primary button would.
Left and middle click actions execute on mouse down, right click on mouse up for reasons discussed previously (I can't find the conversation now)
Default settings are chosen in such a way that very little or nothing changes by updating.
Tested:
* Migrating settings from …
> [ColorPicker]Add option to choose what clicking individual mouse buttons does

- src/modules/cmdpal/CmdPalModuleInterface/dllmain.cpp
- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
CmdPal is leaking extensions processes as the process is immediately killed.
This PR fixes the 1.5s wait for the process to end correctly and also close extensions.
- Verified that if CmdPal closes in 1.5s, extensions and process are closed (note that GitHub extension doesn't close probably due to https://github.com/microsoft/PowerToys/pull/39209)
- Verified that if CmdPal doesn't close in 1.5s the process is killed and extensions aren't closed (tested adding a delay in the code)
> [CmdPal] Close Gracefully

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Commands/CopyPathCommand.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/UWPApplication.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/Win32Program.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Properties/Resources.Designer.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Properties/Resources.resx
Adds a *Copy path* command to the <kbd>Ctrl</kbd>+<kbd>K</kbd> menu in the All apps extension
Copies the exe full path for standard programs. Copies the package directory for UWPs.
Shows a *Copied to clipboard!* toast on a successful copy and closes.
Shows a toast when copying fails, keeps CmdPal open.
Manually tested copying for UWPs and Win32 programs
> [CmdPal][Apps]Add copy path command

- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml
- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml.cs
This PR fixes an issue where the warning message in Peek was always displayed, even when not applicable.
**Root cause**
When non-video files were triggered, the logic did not call
`IsWarningMessageVisible(string? missingCodecName)`
as expected. As a result, the default UI state caused the warning message to always appear.
**Fix**
Updated the method signature and call sites to:
`public Visibility IsWarningMessageVisible(IPreviewer? previewer, PreviewState? state)`
This ensures that the logic is consistently triggered across different preview handlers and has access to the necessary context to determine whether the warning message should be shown.
> Fix Peek always showing warning message by updating IsWarningMessageVisible logic

- src/modules/Hosts/HostsUILib/HostsMainPage.xaml.cs
- src/modules/Hosts/HostsUILib/Strings/en-us/Resources.resw
Adds a *Learn more* link pointing [here](https://aka.ms/PowerToysOverview_HostsFileEditor) (the same as in the settings) to the warning dialog that shows up when Hosts File Editor starts
Tested the UI manually
> [Hosts]Add learn more link to warning dialog

- src/modules/registrypreview/RegistryPreviewUILib/RegistryPreviewMainPage.Events.cs
- src/modules/registrypreview/RegistryPreviewUILib/RegistryPreviewMainPage.Utilities.cs
- src/modules/registrypreview/RegistryPreviewUILib/Strings/en-US/Resources.resw
1. Adds an unsaved file indicator in the title bar like in Notepad. (As indicator we show the * character before the file title.)
2. The save button behaves like a "save as" button, if the file does not exist on disk like in Notepad. (Without fix when running as non-admin you get an access denied error message.)
3. If the app gets closed without saving and the file does not exist on disk, then the user is now asked for the path. (Fixes crash on clicking save button while closing the app.)
4. Failed save actions are handled now correctly on dirty closing, opening files and all other actions that require saving the current state. They will stop the process.
5. A fix for an incorrect enabled state of the save button after opening, reloading and saving a file.
6. Reuse file name on save as …
> [RegPreview] Various improvements on how files are saved

- src/modules/peek/Peek.FilePreviewer/Previewers/ShellPreviewHandlerPreviewer/ShellPreviewHandlerPreviewer.cs
CsWin32 0.3.183 broke preview through preview handlers in Peek.
`Error in UpdatePreviewAsync, falling back to default previewer: Unable to cast COM object of type 'System.__ComObject' to class type 'System.IntPtr'. Instances of types that represent COM components cannot be cast to types that do not represent COM components; however they can be cast to interfaces as long as the underlying COM component supports QueryInterface calls for the IID of the interface.`
Signature of `CoGetClassObject` changed for last argument from `void*` to `object`.
Thanks @AArnott 🙂 
Tested Preview of Office files in Peek.
> [Peek] Fix ShellPreviewHandler Previewer

- src/modules/cmdpal/extensionsdk/README.md
found this bad link, fixing it to help others
Used markdown preview in VSCode, clicked the link, it works!
> fix bad link in cmdpal sdk README.md

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/Pages/TimeDateExtensionPage.cs
When we call RaiseItemsChanged, it will trigger function GetItems. So if you enter this function through typing query, it will trap in an inf loop. Eventually leading to crash.
related change: https://github.com/microsoft/PowerToys/pull/40050
> [cmdpal] Fix TimeAndDate extension crash issue when typing query

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandBarViewModel.cs
ok... it seems didn't work since 0.91.
Maybe we forgot to send message when command has more commands?
> [cmdpal] Fix primary button doesn't work issue

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs
A memory leak was identified where activating a Command Palette extension via a hotkey would lead to a linear increase in resource consumption and a corresponding decrease in search performance.
Each activation created a new `PageViewModel` instance for the extension's UI. However, the `ShellViewModel` did not dispose of the previous `PageViewModel` instance when a new one was created.
The fix is implemented in `Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs` by ensuring that `PageViewModel` instances are correctly disposed of when they are no longer active.
1. Installed [Workspace Launcher for Visual Studio / Code](https://github.com/tanchekwei/WorkspaceLauncherForVSCode)
2. Configured a global hotkey for the extension (e.g., Alt + Q).
3. Ran the following AHK script. Pressing F1 …
> Fix: Prevent memory leak in view model lifecycle

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Calc/Helper/CalculateEngine.cs
The ExprTk result was previously parsed with CurrentCulture, which means that calculator was broken on every device which's culture info differed from what ExprTk returns.
It would probably be better to just obtain the result as a double directly, but that can wait.
ExprTk, the math library that CmdPal's Calculator uses, returns the result as a string formatted in `en-US`, therefore we need to also parse it as `en-US`.
Small and large numbers work correctly with all decimal separators
> [CmdPal][Calc]Parse result returned by ExprTk correctly

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/BeginInvokeMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/CmdPalInvokeResultMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/GoBackMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/NavigateToPageMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/ShowConfirmationMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/ShowToastMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Helpers/TelemetryForwarder.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
ref #40113
Moves a lot of the "model" logic out of `ShellPage.xaml.cs` into
`ShellViewModel`.
The LARGE majority of this code is copy-paste moving code. We're now using a couple more messages to pass navigation between the VM and the page. And a couple new messages for passing ETW events.
> CmdPal: Pull out VM bits from ShellPage.xaml.cs

- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
Otherwise, it silently fails to hide the window.
The problem is not visible to naked eye, since the window is already cloaked.
Tested with an extension that return CommandResult.Dismiss and then works with focused app (https://github.com/CoreyHayward/CmdPal-InputTyper).
> CmdPal: Ensure that DismissMessage handler calls HideWindow on UI thread

- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
Also runs the code through UI thread. it will ensure correct access to _acrylicController, and also because the method touches UI element.
> CmdPal: Remove backdrop targets from existing backdrop controller before assigning a new one

- nuget.config
_This madness has gone on too long, I say_
This replaces our default nuget.org feed with a public azure artifacts feed in the shine-oss org. This is what literally everyone else does, I don't know why we don't. 
This should unblock _wait where'd that issue go_ since we can just add the community toolkit labs feed as an upstream
This has the negative side effect that it did prompt me to log in to azure artifacts with my MSA. I've cancelled like 5 prompts now, but it seems to still be working on it?
> Replace our nuget.org feed with a public azure artifacts feed

- .github/pull_request_template.md
- doc/devdocs/readme.md
Presented for discussion.
Currently, the PR template doesn't actually link a issue to be closed by a PR. The magic "closes #foo" doesn't work, if "**Closes**" is bold.
> meta: Change the PR template to link & close issues by default

- src/modules/cmdpal/Microsoft.CmdPal.Core.ViewModels/ShellViewModel.cs
Yea this was real dumb.
I removed the `HandleCommandResultMessage` handler from `ShellPage`, and never put it on `ShellViewModel`. Just first-grade kind of mistake.
Closes #40776
Regressed in #40479
re: #40113
> CmdPal: fix handling form submits

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Shell/FallbackExecuteItem.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Shell/Pages/ShellListPage.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Shell/PathListItem.cs
We were being too clever with `\`; and yet simultaneously not clever enough. 
* When we saw `c:\users`, we'd treat that as a path with a Title `users\`
* but when we saw `c:\users\`, we'd fail to find a file name, and the just treat the name as `\`. That was dumb.
* And we'd add trailing `\`'s even if there already was one.
* But then if the user typed `c:\users`, we would immediately start enumerating children of that dir, which didn't really feel right
This PR fixes all of that.
Closes #40797
> CmdPal: Fix paths to dirs on the Run fallback

- src/modules/cmdpal/Microsoft.CmdPal.Common/Helpers/SupersedingAsyncGate.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandManager.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelViewModel.cs
Fixes unsynchronized access to `LoadTopLevelCommands` in `TopLevelCommandManager.UpdateCommandsForProvider`, which previously led to `InvalidOperationException: Collection was modified`.
Addressing this also uncovered another issue: overlapping invocations of `ReloadAllCommandsAsync` were causing duplication of items in the main list -- so I'm fixing that as well.
- Fixes #38194 
- Partially solves #40776
Tested with bookmarks.
> CmdPal: Sync access to TopLevelCommandManager from UpdateCommandsForProvider

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Properties/Resources.Designer.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Properties/Resources.resx
Changes the placeholder in the filter box only on the main list page to "Search for apps, files and commands...":
The default value remains unchanged as "Type here to search..." for all other pages (both built-in and internal), unless the author overrides it:
> Change filter box placeholder for main list page only

- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
Properly disposes the old DesktopAcrylicController when replacing it with a new instance.
> CmdPal: properly dispose of the old backdrop controller 

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
Self-refresh of `MainListPage` introduced in #40132 causes unnecessary spawning of tasks by `ReapplySearchInBackground` and pushing the code down the scenic route instead of taking shortcut.
This drop-in fix introduces a single-worker coalescing refresh loop to eliminate thread-pool churn and syncs state in early-return paths.
> CmdPal: Coalesce top-level commands list changes into a single task

- src/modules/cmdpal/Microsoft.CmdPal.Common/Helpers/SupersedingAsyncGate.cs
Change SetCanceled to TrySetCanceled in OperationCanceledException handler to prevent InvalidOperationException when external and internal cancellation tokens complete the TaskCompletionSource simultaneously.
> CmdPal: Fix race condition in SupersedingAsyncGate cancellation handling [MSH]

- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
Adds extra BringToFront after Activate. Don't ask.
> CmdPal: Bring existing Settings window to the foreground when opened

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/CommandBar.xaml
Added `ShouldConstrainToRootBounds="False"` to the Flyout element, allowing it to extend beyond the bounds of its parent container. This allows the menu to always open with top-left corner at the cursor position as is common for the context menus.
This affects the menu only when opened as a context menu on the list item (e.g. mouse right-click), not when opened from the Command Bar (that opens same as before).
After screenshot:
> CmdPal: Remove constrain that keeps the context menu flyout in the bounds of the window

- .github/actions/spell-check/expect.txt
- src/modules/cmdpal/Microsoft.CmdPal.UI/Helpers/LocalKeyboardListener.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Helpers/LocalKeyboardListenerKeyPressedEventArgs.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/NativeMethods.txt
Listener registers a hook on WH_KEYBOARD and raises an event when a key is pressed down. Main window then uses it to handle the GoBack key that we can't reach any other way.
> CmdPal: Add local keyboard listener and use it to handle GoBack key

- src/settings-ui/Settings.UI/SettingsXAML/App.xaml.cs
Quality of life improvement for the dev loop: removing the dialog in Settings, since we have a DEBUG header in the titlebar anyways.
> Remove debug dialog

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/AppCommand.cs
Closes #40978
All apps extension's "Run" command now has the apps icon if available.
> Adding app icon to run context menu item in all apps ext

- Directory.Packages.props
Updated UTF.Unknown from  2.5.1 to 2.6.0
2.5.1 is more than 3 years old and targeting old frameworks. That's fixed in 2.6.0
There are no breaking changes in 2.6.0
> [deps] Update UTF.Unknown

- src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/DynamicListPage.cs
- src/modules/cmdpal/extensionsdk/Microsoft.CommandPalette.Extensions.Toolkit/ListPage.cs
This stops us from raising a PropChanged(SearchText) in DynamicListPage when we're the ones to set it.
When we'd raise the PropChanged in response to a `set`, it could cause a race between CmdPal and the extension. It was totally possible that CmdPal could call
```
SearchText="foo";
SearchText="fool";
```
and in the extension, we'd raise the PropChanged for each of those, but then have CmdPal handle those events out-of-order.
This seems to entirely remove all the "jiggling" that I'd notice in the evil samples from #41158
Closes #38190
> CmdPal: Prevent some SearchText bouncing.

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/AliasManager.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelViewModel.cs
Closes #39709
- Only updating aliases when the alias has changed
- When an alias is used that is already in use, remove the alias from the previous TopLevelViewModel
- Don't crash if the previous TopLevelViewModel doesn't exist (e.g. it was uninstalled)
> CmdPal: Ensuring alias changes are propagated to related TopLevelViewModels

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
Rephrased the module description for Advanced Paste in settings to simplify, and fix styling issues.
Rephrased the Advanced Paste module description shown in settings to simplify, and fix styling issues.
**Existing**:
**Updated**:
This fixes issues including incorrect capitalisation on "markdown" and "json", and also shortens the description to make it quicker to read, by removing unnecessary detail.
> [Advanced Paste] Rephrase module description in settings

- src/modules/cmdpal/extensionsdk/nuget/Microsoft.CommandPalette.Extensions.SDK.nuspec
* The _toolkit_ is AnyCPU.
* the extensions interface itself `Microsoft.CommandPalette.Extensions` is c++, so it needs both ARM and x64
Technically I'm not sure there's anything of real value in just `.Extensions`, since that project is just there to build the winmd (we don't have any runtimeclasses), so not having the symbols for that shouldn't be the end of the world
> CmdPal: Add the pdb's for `.Extensions` too

- src/modules/poweraccent/PowerAccent.UI/Selector.xaml.cs
An attempt to fix a Quick Accent issue affecting laptops with 'Optimus' hybrid graphics modes, where the utility locks the machine into discrete graphics mode permanently.
This PR changes the Topmost behaviour for Quick Accent from always true to only being true when the selection window is displayed.
Topmost was set to `true` for the main application window on start, which persisted for the lifetime of the application. This PR change removes that, and instead dynamically toggles Topmost for the selection window as it is activated/deactivated. The assumption is that the FluentWindow-derived window is retaining graphics resources and presenting as an active GPU consumer because of the main application window's Topmost status, even if the selection window is hidden.
I've confirmed with …
> [QuickAccent] Update Topmost logic to attempt to fix hybrid graphics issues

- tools/build/BUILD-GUIDELINES.md
- tools/build/build-common.ps1
- tools/build/build-essentials.cmd
- tools/build/build-essentials.ps1
- tools/build/build-installer.ps1
- tools/build/build.cmd
- tools/build/build.ps1
This pull request refactors and standardizes the PowerToys build scripts to improve maintainability, reusability, and platform detection. The main changes are the introduction of a shared helper script (`build-common.ps1`), migration of build logic in individual scripts to use these helpers, and enhanced platform auto-detection. This makes the build pipeline more robust and easier to use from any directory within the repository.
As the result of our recent changes, use the following guidance when working in the PowerToys repo:
1. Use `build-essentials.ps1` before any development in general
- Purpose: restore NuGet packages for the full solution and build a small set of essential native projects (runner, settings). This is a fast way to ensure native artifacts required for local …
> Improve how to build the project in PowerToys easier

- src/settings-ui/Settings.UI/SettingsXAML/Views/DashboardPage.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- A few strings (on the ZoomIt page) were not using sentence casing.
- Header for the modules card was not localized.
> [Settings] String updates

- src/modules/Hosts/Hosts/HostsXAML/MainWindow.xaml
- src/modules/Hosts/Hosts/HostsXAML/MainWindow.xaml.cs
Using `TitleBar` instead of our custom XAML.
No visual changes:
> [Hosts File Editor] Using TitleBar

- src/modules/cmdpal/Tests/Microsoft.CmdPal.Ext.WebSearch.UnitTests/MockSettingsInterface.cs
- src/modules/cmdpal/Tests/Microsoft.CmdPal.Ext.WebSearch.UnitTests/QueryTests.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WebSearch/Commands/SearchWebCommand.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WebSearch/Helpers/ISettingsInterface.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WebSearch/Helpers/SettingsManager.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WebSearch/Pages/WebSearchListPage.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WebSearch/Properties/Resources.Designer.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WebSearch/Properties/Resources.resx
For WebSearch extension:
- Replaces localized string identifiers with invariant literal keys to ensure stable and consistent setting values, avoiding issues when switching cultures or if display strings change.  
- Renames the `ShowHistory` property to `HistoryItemCount`.  
- Changes the type from `string` to `int` and centralizes parsing logic in `SettingsManager`.  
- Retains backward compatibility by preserving the legacy settings key `"ShowHistory"` in `SettingsManager`.
> CmdPal: Replace localized strings used as setting values in WebSearch extension with literals

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/ExtensionPage.xaml
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.System/FallbackSystemCommandItem.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.TimeDate/FallbackTimeDateItem.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WindowsSettings/Pages/FallbackWindowsSettingsItem.cs
This PR ensures that fallback items consistently display an icon in Settings window:
- Adds a new `InitialIcon` property to `TopLevelViewModel` to store the first non-empty icon received.  
- Uses `InitialIcon` in the extension settings page when listing fallback items belonging to an extension.  
- Sets initial icons in the constructor for fallback items that were not previously initialized:  
- Date & Time extension  
- System Commands extension
- The Windows Settings extension had its icon initially set, but it was cleared when the item was updated for an empty search query. By persisting the initial icon, subsequent updates no longer affect how the fallback item is represented in Settings.
This change is considered a hotfix for the current state.  
The ideal long-term solution would …
> CmdPal: Make sure fallback items have icons visible in Settings window

- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Program.cs
This PR makes passing arguments from a new instance to the existing one more resilient:
- Fixes situations where `x-cmdpal://` links might not work as expected.  
Instead of performing the intended action (e.g., `x-cmdpal://background` or `x-cmdpal://settings`), they could incorrectly just summon the main window.  
- Refactors the `AppInstance.Activated` handler to be synchronous.  
- The handler blocks `AppInstance.RedirectActivationToAsync` in the caller.  
- If it runs asynchronously (or offloads work to another thread, including the UI thread), the calling instance may exit too soon, preventing the activation arguments from being read.  
- Adds a timeout and ensures the semaphore is always released so the application can exit gracefully under all conditions.  
- Adjusts handling for …
> CmdPal: Improve error handling and logging in activation process

- doc/devdocs/readme.md
Added the "long paths" to the prerequisites in the DevDocs
While setting up the PowerToys solution, I ran into repeated issues where files or SDKs could not be found when loading the solution. After a full evening of debugging, the root cause turned out to be Windows’ default path length limitation.
Even with a repository path like C:/Users/Micha/Development/PowerToys (which is not unusually long by itself), the combination of folder structure and file names exceeded the maximum allowed path length and caused the build problems.
> DevDocs: Add prerequisites to enable long paths in Windows

- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
Refactors the logic that determines whether to ignore keyboard shortcuts while in fullscreen mode. The check is now handled in `HandleSummon`, which centralizes all precondition checks before delegating the actual summoning to `HandleSummonCore`.
> CmdPal: Respect Ignore shortcut in fullscreen mode when using the low-level keyboard hook

- src/modules/poweraccent/PowerAccent.Core/Languages.cs
Extends the Welsh character set by vowels with acute, grave, and dieresis accents. Order is now circumflex, dieresis, grave, acute for all letters. Decision based on the last paragraph of [wikipedia's diacritics section](https://en.wikipedia.org/wiki/Welsh_orthography#Diacritics).
See original issue for sources.
Tested manually
> [QuickAccent] Add vowels with acute, grave, and dieresis to Welsh

- src/modules/ZoomIt/ZoomIt/Zoomit.cpp
This PR includes code-changes to restore some of the features of ZoomIt that existed in older versions and lost in later versions, such as when in Draw mode, after drawing, if an area is snipped, it doesn't clear the drawing immediately, giving the user an option to cancel snip and update the drawing. Also, in draw mode, when left mouse is clicked, it results in a dot, as it was in previous versions. This PR also addresses some race conditions during Recording that results in error when the Recording is saved.
Manually tested and validated the draw and snip modes.
> zoomit bug fixes

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/FiltersDropDown.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Converters/FilterTemplateSelector.cs
Drop-in fix for two issues with search filter separators:
- Separator visual template is not applied when AOT compilation is enabled.
- Separator template uses a different brush then other separators.
Pictures? Pictures!
> CmdPal: Fix filter separators (two in one)

- src/modules/cmdpal/Microsoft.CmdPal.Core.ViewModels/ExtensionObjectViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.Core.ViewModels/FiltersViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/FiltersDropDown.xaml
This PR declaratively binds FilterDropDown.SelectedValue to CurrentFilterId (one-way only; updates in the opposite direction are handled within the drop-down’s code). It also removes observable properties and reverts to the UpdateProperty style to ensure property change notifications are raised on the UI thread, aligning the handling style with other classes.
- Fixed a crash that could occur on pages with filters
- The filter drop-down now correctly syncs with the initially selected filter when loading a page
> CmdPal: Bind FilterDropDown selection to the current filter and ensure notifications are raised on UI thread

- .github/actions/spell-check/expect.txt
This PR changes expected word from 'advapi32' to 'advapi' to fix spellchecker error (forbidden-pattern)
Regressed in 0edf06b
> Fix spellchecker error by changing expected word advapi32 to advapi

- src/common/UITestAutomation/UITestAutomation.csproj
- src/modules/cmdpal/Microsoft.CmdPal.Common/Microsoft.CmdPal.Common.csproj
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ContentTreeViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
`TextToSuggest` has been nothing but pain. We need another approach.
I'm leaving the code, but just disabled behind an env flag. Same as actions.
Closes #41659
> CmdPal: Remove support for "selection" TextToSuggest

- src/common/ManagedCommon/Logger.cs
- src/modules/peek/Peek.UI/Helpers/FileExplorerHelper.cs
- src/modules/peek/peek/dllmain.cpp
- src/modules/peek/peek/trace.cpp
- src/modules/peek/peek/trace.h
- src/settings-ui/Settings.UI.Library/PeekProperties.cs
- src/settings-ui/Settings.UI.Library/PeekSettings.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/PeekPage.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PeekViewModel.cs
Closes: #26143
This pull request introduces a new "single Space key activation" mode for the Peek PowerToy, allowing users to open Peek with just the Space key when File Explorer or the Desktop is focused. The implementation includes settings UI changes, backend logic to enforce and manage this mode, eligibility checks for activation, and telemetry. It also enhances the user experience by disabling the activation shortcut control when space mode is enabled and providing appropriate tooltips and localization.
**Key changes:**
* Added a new setting (`EnableSpaceToActivate`) to allow users to enable Peek activation using only the Space key, restricted to File Explorer or Desktop focus. When enabled, the activation shortcut is forced to bare Space and the previous shortcut is stashed (not …
> Enable "Space" only to activate Peek

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
Read title. Making MainListPage materialize search results so enumerating doesn't rescore the item.
> Materializing lists to prevent rescoring

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/AllAppsCommandProvider.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/AllAppsPage.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/AppCache.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/IAppCache.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/JsonSerializationContext.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/PackageManagerWrapper.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/UWP.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/UWPApplication.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/Win32Program.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/State/PinStateChangedEventArgs.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/State/PinnedAppsManager.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Storage/ListRepository`1.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Storage/PackageRepository.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Storage/Win32ProgramFileSystemWatchers.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Utils/ShellCommand.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Utils/Theme.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Utils/ThemeHelper.cs
Beginning the process of removing System.Linq from CmdPal. This PR removes it from the All Apps extension.
> CmdPal: Linq clean-up (All Apps)

- src/modules/MouseUtils/MousePointerCrosshairs/MousePointerCrosshairs.vcxproj
- src/modules/MouseUtils/MousePointerCrosshairs/dllmain.cpp
Add low level keyboard hook to Gliding Cursor, this checks for 'Esc' being pressed when gliding is active and cancels gliding, the mouse hook passed keys down the hook chain.
No changes to the list of binaries, no new strings for localization. The Gliding Cursor functionality has 5 stages, these are: fast horizontal, slow horizontal, fast vertical, slow vertical, and mouse click - adding the keyboard hook and checking for 'Esc' allows this sequence to be interrupted and reset to ready state.
Validated Mouse Pointer Crosshairs (which Gliding Cursor is based on), confirmed that Gliding Cursor functionality is unchanged and that the 'Esc' key cancels/resets the gliding cursor state.
> Add key to cancel gliding cursor

- src/modules/cmdpal/Core/Microsoft.CmdPal.Core.ViewModels/ShellViewModel.cs
Regressed in #41358
We're synchronously waiting for the first FetchItems to return before actually navigating to the page. Yikes.
Closes #42157
drive-by:
Closes #42231
Closes #42156
> CmdPal: immediately move to page, while loading
