microsoft/PowerToys

- src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/Setting/Setting.xaml
- src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml
- src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml.cs
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml
- Smaller MaxWidth for Font and BitmapIcons, resolving #14599
- 'Learn about administrator mode' is now also available when not running as admin (it's shown in the warning InfoBar, and hidden in the settings card), resolving #14563
Elevated mode:
Non-elevated mode:
- Fixed Awake OOBE text, partially resolving (the { chars are replaced with **, so they render in bold) #14182
- Correct key or shortcut is now shown in Shortcut Guide OOBE, resolving #14610 #13398
Using Windows key:
Using shortcut:
> [Settings] Various bugfixes

- .github/actions/spell-check/expect.txt
- README.md
> 0.51 readme prep

- src/modules/launcher/PowerLauncher/Plugin/PluginManager.cs
We've had reports of duplicate plugins being loaded by PowerToys Run after a PowerToys upgrade.
This seems to happen when we change folder paths for some plugins, albeit it only happens for some users. It's not clear why the uninstall is not cleaning the older files for these users.
When loading the metadata for the plugins, try to de-dup the plugins by ID and pick the one with the higher dll product version.
- Build this branch with a higher version by changing the version number in `src\Version.props`. ( for example:`<Version>0.53.0</Version>`)
- Copy the plugins with a different path from a 0.49.1 local installation into `x64\Debug\modules\launcher\Plugins`. Examples of these from the 0.49.1 …
> [PTRun][Hotfix]Don't load duplicate plugins

- src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx
> Update Resources.resx for issue 12545

- README.md
> small verb change to 0.51.1

- src/modules/awake/Awake/Awake.csproj
- src/modules/colorPicker/ColorPickerUI/ColorPickerUI.csproj
- src/modules/launcher/PowerLauncher/PowerLauncher.csproj
Fix Company and Description
Fixes inconsistent names
Hover over file name and check description and company name
> Description and Company name Fixed

- .github/pull_request_template.md
Fix grammar in the PR template. 
↑Fix grammar for this line↑ 
From `include` to `included`
Not required. 
> Fix grammar in PR template

- doc/devdocs/readme.md
Update WiX visual extension link to direct download link. 
Update `doc/devdocs/readme.md` 
Not required. 
> Update WiX VS extension link

- .github/ISSUE_TEMPLATE/translation_issue.yml
Just adding mouse utilities to translation issue template
> [meta]Add mouse utilities to translation issue template

- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.WebSearch/Main.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.WebSearch/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.WebSearch/Properties/Resources.resx
- Improved plugin description: `Search the web.` => `Search the web in your default browser using your default search engine.`
- Fixed browser name in error message: `the default browser` => `<Name of the browser>` or `the default browser`
- Improved logging: Added additional web-search plugin error msg.
```
[2021-12-25 15:41:24.1490] [ERROR] [D:\AppDev\Github\htcfreek\PT_WebSearchDesc\src\modules\launcher\Wox.Infrastructure\Helper.cs::151]
-------------------------- Begin exception --------------------------
Message: Unable to open C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe: The system cannot find the file specified.
Exception full name  : System.ComponentModel.Win32Exception
Exception message    : The system cannot find the file …
```
> [PT Run] Web-search plugin: Fix strings and improve log msg

- doc/devdocs/readme.md
Added in submodule note for compiling.  #15181  does reference this
> Update to include submodule note for dev docs

- .github/actions/spell-check/expect.txt
Spellcheck work for #15242 
Update expect.txt 
GitHub Actions will do the test. 
> Fix the spellcheck for #15242

- .pipelines/ESRPSigning_core.json
Add instructions to fix signing for always on top.
> [ci]sign always on top

- src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml
Changed some margins, no visual changes however. Solves: #15220
> [FZ Editor] Fix text clipping

- .github/actions/spell-check/allow/names.txt
- .github/actions/spell-check/excludes.txt
- .pipelines/ci/ci.yml
- README.md
> Update README.md for .55 release

- installer/PowerToysSetup/Product.wxs
- src/runner/main.cpp
> [runner] If process elevated and --dont-elevate arg - run non elevated

- .gitattributes
`*.gcode` files in this repository are large (27k lines) and only used in testing. So, I feel it's unnecessary to have them mentioned in github's linguist.
Modifies the `.gitattributes` file to let github linguist ignore .gcode 
Check out my forked repository: https://github.com/U-C-S/PowerToys
Here's how it looks like after ignoring .gcode files
> [Meta] Ignore .gcode files in GitHub linguist

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/AwakePage.xaml
- src/settings-ui/Settings.UI/Views/PowerPreviewPage.xaml
> adding in attribution in settings

- src/common/utils/elevation.h
- src/runner/general_settings.cpp
- src/runner/main.cpp
> [runner] Add logging

- .github/actions/spell-check/allow/names.txt
- .github/actions/spell-check/expect.txt
- README.md
This will be copy / pasted for release notes
> 0.56 change log.

- src/common/Telemetry/TelemetryBase.cs
> [Telemetry] fix analyzer warnings

- src/modules/previewpane/MonacoPreviewHandler/MonacoPreviewHandlerControl.cs
This should fix the error, that kept the file in use.
1. Build dev file preview
2. Select file to preview
3. Test with renaming it
4. Test with deleting it
5. 3 and 4 while dev file preview is loading
> [HOT FIX][Developer Preview]Fixed file in use issue

- src/modules/colorPicker/ColorPickerUI/Helpers/ColorRepresentationHelper.cs
- src/modules/colorPicker/ColorPickerUI/Helpers/SerializationHelper.cs
- src/modules/colorPicker/ColorPickerUI/Properties/Resources.Designer.cs
- src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx
- src/modules/colorPicker/ColorPickerUI/Telemetry/ColorPickerSession.cs
- src/modules/colorPicker/ColorPickerUI/ViewModelContracts/IColorEditorViewModel.cs
- src/modules/colorPicker/ColorPickerUI/ViewModels/ColorEditorViewModel.cs
- src/modules/colorPicker/ColorPickerUI/Views/ColorEditorView.xaml
Addresses [](https://github.com/microsoft/PowerToys/issues/9520) which requests the ability to export colors to a file for use elsewhere. Addresses [](https://github.com/microsoft/PowerToys/issues/8336) which offers a "Delete multiple colors".
- multi-selecting by pressing ctrl/shift  of colors in the history
- delete the selected colors
- export the selected colors to a text/json files grouped either by color or format
- avoid adding the same colors to the history
- ctrl/shift+click to select multiple/ctrl+A to select all, context menus are adapted based on the discussions in [this](https://github.com/microsoft/PowerToys/pull/10250) and referenced posts:
- selected colors can be exported to …
> [Color Picker] remove and export multiple colors from history

- src/runner/tray_icon.cpp
> Open PT settings only on tray icon double click

- Directory.Build.props
- src/common/ManagedCommon/ManagedCommon.csproj
- src/common/ManagedTelemetry/Telemetry/ManagedTelemetry.csproj
- src/common/interop/interop-tests/Microsoft.Interop.Tests.csproj
> [Common] Move shared keys into central props file

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/WindowsSettings.json
Adding new settings:
- Screen saver
- Connect wireless display pannel
Local build.
> [PT Run] [Settings plugin] New settings

- .github/actions/spell-check/allow/names.txt
- .github/actions/spell-check/expect.txt
- README.md
Readme update for the 0.57 release.
> 0.57 changelog

- tools/BugReportTool/BugReportTool.sln
> [ARM64] add arm64 configurations to BugReportTool sln

- .github/actions/spell-check/allow/names.txt
- .github/actions/spell-check/expect.txt
- README.md
Readme update for the 0.58 release.
> 0.58 changelog

- doc/devdocs/readme.md
Added some instructions that explain to install the WAS workloads and runtime.
> Added additional WAS 1.0.3 instructions

- .github/ISSUE_TEMPLATE/bug_report.yml
**What is this about:** Minor grammatical issue
**What is included in the PR:** removal of "a" from "a screenshots"
**How does someone test / validate:** Review YAML
> Fix grammar issue

- .pipelines/ESRPSigning_core.json
- .pipelines/ESRPSigning_installer.json
- .pipelines/release.yml
- .pipelines/versionAndSignCheck.ps1
Sign PowerToysSettingsCustomAction.dll in the new release pipelines, so it's not blocked by Smart App Control.
Originally fixed in https://github.com/microsoft/PowerToys/pull/12746 , now ported for the new pipelines.
This PR adds a new task to build the dll and sign it before building the MSI.
Built the signed installer with the released pipelines, extracted the msi from inside and verified the PowerToysSetupCustomActions.dll binary blob was signed.
In case one wants to verify it, one way is checking that the PTCustomActions.dll inside the msi is signed, using Orca.
1 - Orca can be installed from inside Windows SDK. `C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\Orca-x86_en-us.msi` is where mine was, for example.
2 - Run Orca, and open the msi with it.
3 - In the binary …
> [ci][build]Sign PowerToysSetupCustomActions.dll

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/Main.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.TimeDate/Main.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.TimeDate/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.TimeDate/Properties/Resources.resx
- Add a comment to resx of system plugin.
- Fix translation of examples in Time and Date plugin description.
- Prevent translation of number examples in calc plugin settings.
Local build to validate strings.
> [PT Plugins] Translation fixes and improvements

- .github/actions/spell-check/expect.txt
- tools/MonitorReportTool/MonitorReportTool.cpp
Adds additional logs to the monitor report tool.
Recent issues like #19203 and #19233 were debugged thanks to some additional logs sent by the users with these changes to the tool. Let's make these permanent.
This will exhaustively Enumerate every display device available.
Built and ran the tool.
> [Tool]Exhaustively check every monitor in the Monitor Report Tool

- .pipelines/release.yml
Makes the CI release output the symbols artifacts with the version number of the build.
Ran the release CI and verified the artifact had the version in its name.
> [ci]Add version number to symbols artifact

- src/modules/alwaysontop/AlwaysOnTop/WindowBorder.cpp
Border is flickering when applied.
0.60.0
PR
Show frame drawer, apply border position and property in order to render the border correctly before starting the timer for redraw it.
- Pin a window
- Press CTRL + D
- Press CTRL + D again
- Border shouldn't flicker when applied
> [AOT] Fix for flickering border

- .gitattributes
Make GitHub display `.vs-config` as a JSON file, as it is formatted in JSON.
This adds `.vs-config linguist-language=json` to `.gitattributes`.
Check my fork on github.com. GitHub hasn't been updated yet as of this PR's creation, so we'll have to wait and see. :)
> Make GitHub display .vsconfig as a JSON file

- .github/actions/spell-check/advice.md
- .github/actions/spell-check/excludes.txt
- .github/actions/spell-check/expect.txt
- .github/actions/spell-check/line_forbidden.patterns
- .github/actions/spell-check/patterns.txt
- .github/workflows/spelling2.yml
Upgrade check-spelling to [v0.0.20](https://github.com/check-spelling/check-spelling/releases/tag/v0.0.20)
This is a fairly minor update.
- I'm reducing the scope of the excludes to just spelling's own workflow. It seems that most files in .github/ are worth checking. I've added two patterns for `fabricbot.json`.
- Upon review, the dictionaries are only needed for the check phase, so I've removed them from the comment job.
- I'm refreshing line_forbidden.patterns based on recent experience.
- I'm updating the advice based on recent experience -- I'm still collecting implementation experience on it.
> Upgrade check-spelling to v0.0.20

- src/runner/UpdateUtils.cpp
Removes a useless namespace use because it was already called before in this file.
> Remove redundant namespace inclusion

- .github/actions/spell-check/expect.txt
- README.md
Readme update for the 0.61 release.
> 0.61 changelog

- README.md
> Fix a wrong url in README.md

- src/Update/PowerToys.Update.cpp
- src/common/updating/updateState.h
- src/runner/main.cpp
- Required to handle the case when the PT downloads the update but the user updates from GitHub or WinGet.
- Cleanup `%LOCALAPPDATA%\Microsoft\PowerToys\Updates` at PT startup.
- Cleanup bootstrapper and msi log files from `%LOCALAPPDATA%\Microsoft\PowerToys` for old versions of PT.
- Removed cleanup logic from the updater.
- Copy an exe and an msi in `%LOCALAPPDATA%\Microsoft\PowerToys\Updates`
- Create 2 log file in `%LOCALAPPDATA%\Microsoft\PowerToys\Updates`: `powertoys-bootstrapper-msi-0.60.0.log` and `powertoys-bootstrapper-msi-0.0.1.log`
- Edit `%LOCALAPPDATA%\Microsoft\PowerToys\UpdateState.json` and set `"state":3` (update ready for installation)
- Run PT: exe, msi and log files shouldn't be deleted
- Edit `%LOCALAPPDATA%\Microsoft\PowerToys\UpdateState.json` and set `"state":0` …
> [Runner] Cleanup updates directory at startup

- src/modules/previewpane/UnitTests-GcodeThumbnailProvider/UnitTests-GcodeThumbnailProvider.csproj
- src/modules/previewpane/UnitTests-PdfThumbnailProvider/UnitTests-PdfThumbnailProvider.csproj
- src/modules/previewpane/UnitTests-StlThumbnailProvider/UnitTests-StlThumbnailProvider.csproj
- src/modules/previewpane/UnitTests-SvgThumbnailProvider/UnitTests-SvgThumbnailProvider.csproj
Removed Castle.Core nuget package
> [Chore] Remove obsolete package Castle.Core

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest/ExtendedCalculatorParserTests.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest/QueryTests.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/CalculateEngine.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/CalculateHelper.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/Properties/Resources.resx
In the input validation method we block results for inputs that ends with some binary operators to not throw errors when the user didn't finished typing. This PR adds the following ones to the list: `/`, `*`, `%`
As addition this PR adds a division by zero check to show a better information to the user.
Build local and test functionality. And run unit tests.
> [PT Run > Calculator] Input validation improvements

- .github/ISSUE_TEMPLATE/bug_report.yml
> Add PowerOCR to issue template

- COMMUNITY.md
Maintenance: Update `Community.md` with the PowerOCR and PowerAccent contributions.
> [docs]Update COMMUNITY.md with PowerOCR and PowerAccent

- .github/actions/spell-check/allow.txt
- README.md
Readme update for the 0.61 release.
> 0.62 changelog

- src/modules/PowerOCR/PowerOCR/OCROverlay.xaml.cs
The PR is fixing the redundant rectangle selection described in https://github.com/microsoft/PowerToys/issues/20141#issuecomment-1231522870
**Root cause analysis**
RegionClickCanvas_MouseDown and RegionClickCanvas_MouseMove start simultaneously after right click.
Since clickedPoint is set in RegionClickCanvas_MouseDown after IsSelecting is set, there is race condition:
RegionClickCanvas_MouseMove uses previous value.
**Fix description**
The fix is to set IsSelecting after the clickedPoint is set, which prevents RegionClickCanvas_MouseMove to use the unset value.
TextExtractor manual test steps
> [TextExtractor] Fix redundant screen select after mouse right click (#20141)

- installer/PowerToysSetup/PowerToys.wxs
> [Installer] Clarify dotnet installation step name

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/PowerAccentPage.xaml
> Make QA strings less ambiguous

- README.md
Readme update for the 0.63 release.
> 0.63 changelog

- src/modules/MeasureTool/MeasureToolUI/MeasureToolUI.csproj
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.OneNote/Microsoft.PowerToys.Run.Plugin.OneNote.csproj
- src/modules/poweraccent/PowerAccentModuleInterface/PowerAccentModuleInterface.vcxproj.filters
- src/modules/poweraccent/PowerAccentModuleInterface/packages.config
- src/modules/previewpane/common/PreviewHandlerCommon.csproj
> consolidate nugets

- .pipelines/release.yml
Creating the hash for PowerToys for when we release on the server.
> Release.yml hash creation

- CppRuleSet.ruleset
- src/modules/MeasureTool/MeasureToolCore/ScreenCapturing.cpp
- src/modules/ShortcutGuide/ShortcutGuide/d2d_window.h
- src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.h
- src/modules/ShortcutGuide/ShortcutGuide/tasklist_positions.h
- src/modules/fancyzones/FancyZonesLib/EditorParameters.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesData/CustomLayouts.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesDataTypes.h
- src/modules/fancyzones/FancyZonesLib/JsonHelpers.h
- src/modules/powerrename/PowerRenameUILib/ExplorerItem.h
- src/modules/videoconference/VideoConferenceModule/Toolbar.h
Based on pull request #21085 this pull request turns on the code analysis rule "C26495 - A member variable isn't initialized" as **error** and fix all errors.
Based on pull request #21085 this pull request turns on the code analysis rule "C26495 - A member variable isn't initialized" as **error** and fix all errors.
The errors are fixed by using default member initialization.
The unit test were run and all passed.
The CI job passes.
> Code analysis c26495 as error

- src/modules/Hosts/Hosts/Views/MainPage.xaml
This PR adds a ScrollViewer control and moves the StackPanel into it.
This PR contains the code changes to add the ScrollViewer and moves the StackPanel with the controls into it.
Test with local build.
> [Hosts] Entry dialog: Add ScrollViewer

- .pipelines/ci/templates/build-powertoys-steps.yml
Fixes Hosts tests currently not running in the pipeline.
> Run hosts tests 

- src/settings-ui/Settings.UI.Library/SettingsBackupAndRestoreUtils.cs
Default location proposed for backup/restore should honor user documents directory.
_My settings_
_Before (don't have this folder on my PC)_
_After_
- Open settings
- Default location for backup/restore should be user documents directory
> [Settings][Backup/Restore] Honor user documents directory

- src/modules/launcher/Wox.Infrastructure/Image/ImageLoader.cs
Enhanced loading of the image files - the files are released after loading (and not blocked).
The possible reason for the missing image files might be, that at startup the PowerToys application reads them but keeps them blocked. That might later lead to the observed problem. This modification releases the image files after they are loaded.
I could not reproduce the problem or prove that the modification fixes the issue.
> Enhanced loading of the image files

- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/ContextMenuHelper.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/Window.cs
- src/modules/launcher/PowerLauncher/ViewModel/IMainViewModel.cs
- src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
- src/modules/launcher/PowerLauncher/ViewModel/ResultViewModel.cs
- src/modules/launcher/PowerLauncher/ViewModel/ResultsViewModel.cs
- src/modules/launcher/Wox.Plugin/ContextMenuResult.cs
- src/modules/launcher/Wox.Test/ResultViewModelTest.cs
- src/modules/launcher/Wox.Test/ResultsViewModelTest.cs
- src/modules/launcher/Wox.Test/Wox.Test.csproj
Hide PowerToys Run if the context menu result action returns `true`, otherwise keep it open.
I introduced a new interface `IMainViewModel`, that are passed down to new instances of `ResultViewModel`. Then they can call the `Hide` method when needed.
I have only made sure that the code compiles and the tests are green.
> PowerToys Run: Fix always show after executing context menu result

- README.md
Readme update for the 0.64 release.
> 0.64 changelog

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/translation_issue.yml
Changed list item to a string.
Before:
Now:
> Fix bugged out issue templates:

- README.md
Fixes a typo I saw in the **What's new** page after the latest release installed.
> Release notes typo fix

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/translation_issue.yml
Added Hosts File Editor to GitHub issue templates.
> [Issue Template] Add Hosts File Editor

- src/modules/fancyzones/FancyZonesLib/Layout.cpp
- src/modules/fancyzones/FancyZonesTests/UnitTests/Layout.Spec.cpp
Fixed showing spacing when it's disabled in the editor for the grid layout.
* Apply grid layout
* Disable spacing on the applied layout
* Verify there is no spacing between zones while dragging the window
> [FancyZones] Fix: 'Space around zones' toggle does not turn off spacing

- src/modules/colorPicker/ColorPickerUI/Settings/UserSettings.cs
Blocking endless loop on property change which led to very high memory consumption
From the provided logs it is clear that there is an endless loop calling the settings save method. It is called from one place, from a property change handler. And indeed, inside the property changed handler method the property is updated. Security code added to avoid the endless loop.
Could not reproduce the original problem but the found endless loop is blocked.
> ColorPicker: Adding safety code to property modification - Fix for issue #21462

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
This PR changes the settings name form "... language" to "... character set".
Build locally and checked the new ux content.
> [Settings][Quick Accent] Change name of language setting

- .pipelines/ci/templates/build-powertoys-ci.yml
- .pipelines/ci/templates/build-powertoys-steps.yml
- .pipelines/release.yml
Trying to conditionally turn off multi tasking build just for ARM64.
Also apply the fix to the release CI.
> [TEMP][ci]Conditionally turn off multi tasking for arm64

- src/modules/poweraccent/PowerAccent.Core/Services/SettingsService.cs
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.cpp
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.h
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.idl
- src/settings-ui/Settings.UI.Library/PowerAccentProperties.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerAccentViewModel.cs
- src/settings-ui/Settings.UI/Views/PowerAccentPage.xaml
> PowerAccent-21531: support excluded apps

- src/modules/alwaysontop/AlwaysOnTop/AlwaysOnTop.cpp
- src/modules/alwaysontop/AlwaysOnTop/trace.cpp
- src/modules/alwaysontop/AlwaysOnTop/trace.h
Added telemetry for user-initiated events (pinning/unpinning).
> [AlwaysOnTop] Telemetry

- .pipelines/ESRPSigning_core.json
- .pipelines/versionAndSignCheck.ps1
Fix signing for the Pinyin dependency that was recently taken in.
Also add it to the version check exceptions, since its version is 1.0.0.0.
Waiting for release CI to finish building and checking it succeeds.
> [CI]Fix pinyin dependency signing and version

- README.md
Update link version for v0.64.1
> Update link version for v0.64.1

- .github/fabricbot.json
now the question is do i remember how to do regex
> make feedback hub item be agnostic to casing

- src/modules/poweraccent/PowerAccent.Core/Languages.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerAccentViewModel.cs
- src/settings-ui/Settings.UI/Views/PowerAccentPage.xaml
Add accents for Kurdish language
> [QuickAccent] Add accents for Kurdish language (#21700)

- COMMUNITY.md
Adds @dend back to the microsoft employees in the community.md file.
> Adding Den Delimarsky back to the Microsoft Employees section in the Community file

- src/modules/peek/Peek.Common/Converters/BoolConverter.cs
- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml
- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml.cs
- src/modules/peek/Peek.FilePreviewer/Peek.FilePreviewer.csproj
- src/modules/peek/Peek.FilePreviewer/Previewers/IBitmapPreviewer.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/IPreviewer.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/ImagePreviewer/ImagePreviewer.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/PreviewerFactory.cs
add plugin pattern
todo: investigate reflection to resolve type
> [Peek] Plugin pattern to enable any file type previewing

- src/modules/peek/Peek.FilePreviewer/Previewers/ImagePreviewer/Helpers/PropertyHelper.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/PreviewerFactory.cs
Simplifying property store creation and changing creation mode to handle offline files (cloud storage).
For more on the property flags, see here: https://learn.microsoft.com/en-us/windows/win32/api/propsys/ne-propsys-getpropertystoreflags
Tested on OneDrive pictures to ensure the property store is created properly.
> [Peek] Enable PropertyStore for offline files

- src/modules/peek/Peek.Common/Helpers/ReadableStringHelper.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/Helpers/IconHelper.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/Helpers/ReadableStringHelper.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/UnsupportedFilePreviewer/UnsupportedFilePreviewer.cs
- src/modules/peek/Peek.FilePreviewer/UnsupportedFilePreview.xaml
- src/modules/peek/Peek.FilePreviewer/UnsupportedFilePreview.xaml.cs
- src/modules/peek/Peek.UI/Strings/en-us/Resources.resw
- Use and format strings from resw files
- Moved ReadableStringHelper to Peek.Common
> [Peek] Unsupported File Previewer - Formatting string from resources

- src/modules/peek/Peek.UI/Extensions/WindowExtensions.cs
- src/modules/peek/Peek.UI/MainWindow.xaml.cs
- src/modules/peek/Peek.UI/Native/NativeMethods.cs
Foregrounding wasn't working under certain scenarios so fixing it.
There are lots of APIs that deal with foregrounding but none of them are perfect right out of the box.  I found this method of dealing with threads from a Powershell Tool which does something similar.
Tested a scenario that didn't work before and validated that it is fixed.
> [Peek] Fix foregrounding

- src/modules/peek/Peek.UI/Views/TitleBar.xaml
> [Peek] Refine titlebar adaptive width

- src/modules/peek/Peek.UI/Helpers/FileExplorerHelper.cs
- src/modules/peek/Peek.UI/Native/NativeMethods.cs
- src/modules/peek/Peek.UI/NativeMethods.txt
- compare window titles to grab focused FE Tab
> [Peek] New File Explorer tabs break Shell API to get selected files

- src/modules/peek/Peek.Common/Helpers/ReadableStringHelper.cs
- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml
- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml.cs
- src/modules/peek/Peek.UI/Strings/en-us/Resources.resw
Adds tooltip when hovering over images
> [Peek] Add tooltip to File

- src/modules/peek/Peek.FilePreviewer/Previewers/PngPreviewer/PngPreviewer.cs
> [Peek] add full image quality for PNG

- src/modules/poweraccent/PowerAccent.Core/Services/SettingsService.cs
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.h
- src/settings-ui/Settings.UI.Library/PowerAccentProperties.cs
- src/settings-ui/Settings.UI.Library/PowerAccentSettings.cs
- src/settings-ui/Settings.UI/ViewModels/PowerAccentViewModel.cs
Increase the default input delay to 300ms.
> [Quick Accent] increase default input delay to 300ms

- src/modules/poweraccent/PowerAccent.UI/Selector.xaml.cs
Set selection to first character when the key change.
Repro on issue.
- Trigger QuickAccent
- Trigger QuickAccent with another character
- First character of the list should be selected
> [QuickAccent] Set selection when character change

- doc/devdocs/readme.md
Getting started developing docs have drifted from what is truly needed for a new user.  Removed one of the steps and added 
Started on blank VM and did steps to setup with only the VS Config file.
1. Blank SV2 image
2. installed VS 2022 Community 17.4
3. cloned powertoys off Main.  (suggest you use the "stable" branch as that is what is in the releases
4. Clicked "Install" from the solution menu (This is powertoy's .vsconfig)
5. ![image](https://user-images.githubusercontent.com/1462282/206803174-02156b29-309e-4f2d-b121-aef83a885335.png)
6. turn on dev mode
7. Make sure you `Build solution` (without this first step, you will get errors)
8. F5 application
> Update to dev setup readme.md

- CppRuleSet.ruleset
The goal here is to add the C++core guidelines rules to the rule set.
all that can has no occurrence are added as error, the rest is added as info.
> [Analyzers][CPP] - rewrite the ruleset to include cpp core guidelines rules

- .github/actions/spell-check/expect.txt
- src/common/ManagedCommon/ColorFormatHelper.cs
- src/settings-ui/Settings.UI/Controls/ColorFormatEditor.xaml
- src/settings-ui/Settings.UI/Controls/ColorFormatEditor.xaml.cs
- src/settings-ui/Settings.UI/Converters/ColorFormatConverter.cs
- src/settings-ui/Settings.UI/PowerToys.Settings.csproj
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/ColorPickerViewModel.cs
- src/settings-ui/Settings.UI/Views/ColorPickerPage.xaml
- src/settings-ui/Settings.UI/Views/ColorPickerPage.xaml.cs
This PR introduces the following changes:
- Custom format cards can now be clicked to edit - improves keyboard accesibility.
- Remove button is now in the ... menu.
- When clicked on the remove button, a dialog will show first instead of directly deleting.
- The colorformat dialog now contains a usercontrol that contains all of the textboxes and instructions for easier maintaince.
- The user control now loads the instructions parameters from code behind so it's easier to maintain / add (before this was all hardcoded in XAML.
- Parameters are now selectable so they can be copied-and-pasted in the textbox. (closing #22781)
- Minor label tweaks.
@donlaci I know #22771 is coming in - so feel free to merge that one first and I'll rebase and resolve conflicts!
> [Settings] Custom color format UI tweaks

- CppRuleSet.ruleset
- src/runner/main.cpp
Do not assign gsl::span or std::string_view to a reference. They are cheap to construct and are not owners of the underlying data. (gsl.view)
This is part of the core guidelines code analyzer
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#gslview-views
> [Analyzers][CPP] Turn on warning 26445

- src/common/ManagedCommon/ColorFormatHelper.cs
Fix typo.
```
occurence -> occurrence
```
> Fix typo in ColorFormatHelper.cs

- src/common/interop/interop-tests/Microsoft.Interop.Tests.csproj
- src/modules/Hosts/Hosts.Tests/Hosts.Tests.csproj
- src/modules/colorPicker/UnitTest-ColorPickerUI/UnitTest-ColorPickerUI.csproj
- src/modules/imageresizer/tests/ImageResizerUITest.csproj
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter.UnitTest/Community.PowerToys.Run.Plugin.UnitConverter.UnitTest.csproj
- src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter.UnitTest/InputInterpreterTests.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.Folder.UnitTests/Microsoft.Plugin.Folder.UnitTests.csproj
- src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Microsoft.Plugin.Program.UnitTests.csproj
- src/modules/launcher/Plugins/Microsoft.Plugin.Uri.UnitTests/Microsoft.Plugin.Uri.UnitTests.csproj
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker.UnitTests/Microsoft.Plugin.WindowWalker.UnitTests.csproj
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest.csproj
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry.UnitTest/Microsoft.PowerToys.Run.Plugin.Registry.UnitTests.csproj
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System.UnitTests/Microsoft.PowerToys.Run.Plugin.System.UnitTests.csproj
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.TimeDate.UnitTests/Microsoft.PowerToys.Run.Plugin.TimeDate.UnitTests.csproj
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.TimeZone.UnitTests/Microsoft.PowerToys.Run.Plugin.TimeZone.UnitTests.csproj
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsTerminal.UnitTests/Microsoft.Plugin.WindowsTerminal.UnitTests.csproj
- src/modules/launcher/Wox.Test/Wox.Test.csproj
- src/modules/previewpane/UnitTests-GcodePreviewHandler/UnitTests-GcodePreviewHandler.csproj
- src/modules/previewpane/UnitTests-GcodeThumbnailProvider/UnitTests-GcodeThumbnailProvider.csproj
- src/modules/previewpane/UnitTests-MarkdownPreviewHandler/UnitTests-MarkdownPreviewHandler.csproj
- src/modules/previewpane/UnitTests-PdfPreviewHandler/UnitTests-PdfPreviewHandler.csproj
- src/modules/previewpane/UnitTests-PdfThumbnailProvider/UnitTests-PdfThumbnailProvider.csproj
- src/modules/previewpane/UnitTests-PreviewHandlerCommon/UnitTests-PreviewHandlerCommon.csproj
- src/modules/previewpane/UnitTests-StlThumbnailProvider/UnitTests-StlThumbnailProvider.csproj
- src/modules/previewpane/UnitTests-SvgPreviewHandler/UnitTests-SvgPreviewHandler.csproj
- src/modules/previewpane/UnitTests-SvgThumbnailProvider/UnitTests-SvgThumbnailProvider.csproj
- src/settings-ui/Settings.UI.UnitTests/Settings.UI.UnitTests.csproj
upgrading the unit test nuget packages.
The unit conversion unit tests had to be slightly adjusted to remove the double array boxing.
> unit tests nugets updated

- src/modules/PowerOCR/PowerOCR/OCROverlay.xaml.cs
- src/modules/PowerOCR/PowerOCR/Settings/IUserSettings.cs
- src/modules/PowerOCR/PowerOCR/Settings/UserSettings.cs
- src/settings-ui/Settings.UI.Library/PowerOcrProperties.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerOcrViewModel.cs
- src/settings-ui/Settings.UI/Views/PowerOcrPage.xaml
- src/settings-ui/Settings.UI/Views/PowerOcrPage.xaml.cs
[TextExtractor] Extend settings with preferred language
Extended settings class, settings page with a combo box.
Tested locally
> [TextExtractor] Extend settings with preferred language

- README.md
Readme update for the 0.66 release.
> 0.66 changelog

- src/modules/previewpane/MonacoPreviewHandler/Formatters/JsonFormatter.cs
Don't escape HTML-sensitive characters when JSON is formatted.
Ref: https://learn.microsoft.com/en-us/dotnet/api/system.text.encodings.web.javascriptencoder.unsaferelaxedjsonescaping?view=net-7.0#remarks
- Build PT
- Enable "try to format the source for preview" option
- Preview a JSON file that contains special characters like: `>` `<` `&`
- Characters shouldn't be escaped
> [Monaco Preview] JSON formatting: don't escape HTML-sensitive characters

- .github/actions/spell-check/expect.txt
- src/modules/poweraccent/PowerAccent.Core/Languages.cs
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.h
- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.idl
Adds some basic combining characters to the numpad 0 key.
> [Quick Accent] Add combining characters

- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj
- src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj.filters
- src/modules/fancyzones/FancyZonesLib/HighlightedZones.cpp
- src/modules/fancyzones/FancyZonesLib/HighlightedZones.h
- src/modules/fancyzones/FancyZonesLib/MonitorUtils.cpp
- src/modules/fancyzones/FancyZonesLib/MonitorUtils.h
- src/modules/fancyzones/FancyZonesLib/WorkArea.cpp
- src/modules/fancyzones/FancyZonesLib/WorkArea.h
- src/modules/fancyzones/FancyZonesTests/UnitTests/WorkArea.Spec.cpp
* init WorkArea with a rectangle
* keep the highlighted zones state in a separate class
> [FancyZones] Improve code quality (part 2)

- src/modules/fancyzones/FancyZonesLib/DraggingState.cpp
- src/modules/fancyzones/FancyZonesLib/DraggingState.h
- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj
- src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj.filters
- src/modules/fancyzones/FancyZonesLib/WindowMoveHandler.cpp
- src/modules/fancyzones/FancyZonesLib/WindowMoveHandler.h
- src/modules/fancyzones/FancyZonesLib/WorkArea.cpp
Moved the dragging state out of the `WindowMoveHandler` into a separate class.
> [FancyZones] Improve code quality (part 3)

- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml
- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/IBitmapPreviewer.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/ImagePreviewer/ImagePreviewer.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/PngPreviewer/PngPreviewer.cs
- src/modules/peek/Peek.UI/MainWindow.xaml
- src/modules/peek/Peek.UI/MainWindow.xaml.cs
- src/modules/peek/Peek.UI/MainWindowViewModel.cs
Set max width/height to prevent small images from stretching. 
Just changing the small image Stretch to None won't work here, since on monitors with >100% scaling picture still looks blurry.
**Here is how it looks with MaxWidth/MaxHeight set:**
100%
200%
**To compare, with Stretch.None:**
100%
200%
> [Peek] Small images

- README.md
I've fixed a typo and a weird sentence in the Readme
> Fixed typo and weird sentence in Readme

- installer/PowerToysSetup/Core.wxs
- installer/PowerToysSetup/FileLocksmith.wxs
- installer/PowerToysSetup/ImageResizer.wxs
- installer/PowerToysSetup/PowerRename.wxs
- installer/PowerToysSetup/Run.wxs
Moving reg entries to HKCU broke installing PowerToys as SYSTEM
> [hotfix] Revert HKCU to HKLM

- doc/devdocs/readme.md
> Fixed typo in the devdocs ReadMe

- .github/actions/spell-check/expect.txt
- src/modules/launcher/Wox.Infrastructure/Image/ImageLoader.cs
- src/modules/launcher/Wox.Infrastructure/Image/WindowsThumbnailProvider.cs
**This PR fixes the dispatcher crash in thumbnail loading code caused by the thumbnail preview handler of Adobe Reader and Acrobat Pro.** With the changes the crash doesn't happen anymore and it shows the file type icon for PDF files if the thumbnail provider is set to Acrobat Pro or Adobe Reader.
The codes supports the following cases:
- Acrobat thumbnail provider. => Show only icons.
- Different thumbnail provider (Foxit, PT, ...). => Show thumbnails.
- Acrobat provider is installed, but PT, Foxit or an other provider has precedence. => Show thumbnails.
- Acrobat provider is installed, but not associated. => Show thumbnail if there is an other provider installed and associated.
**How to reproduce the crash:**
1. Install Acrobat Reader, enable thumbnail provider.
2. Exit PT.
3. Delete …
> [PT Run > Wox.Infrastructure.Image] Fix dispatcher crash

- src/common/GPOWrapper/GPOWrapper.cpp
- src/common/SettingsAPI/settings_objects.cpp
- src/common/SettingsAPI/settings_objects.h
- src/common/Themes/icon_helpers.cpp
- src/common/Themes/theme_helpers.cpp
- src/common/Themes/theme_listener.cpp
- src/common/Themes/windows_colors.cpp
- src/common/interop/keyboard_layout.cpp
- src/common/interop/two_way_pipe_message_ipc.cpp
- src/common/utils/HDropIterator.h
- src/common/utils/HttpClient.h
- src/common/utils/UnhandledExceptionHandler.h
- src/common/utils/elevation.h
- src/common/utils/gpo.h
- src/common/utils/process_path.h
- src/common/utils/registry.h
- src/common/utils/timeutil.h
- src/common/utils/winapi_error.h
- src/common/utils/window.h
This change is split into several PRs. This does not turn on the rule only fixes the code under "src/common".
Most of the changes are replacing the C-style cast with static_cast.
Some of the C-style needed to be changed to reinterpret_cast.
There is a rule to be turned on to avoid reinterpret_cast so this should be re-evaluated in the future.
> [Analyzers][CPP] Changes to fix warning 26493 on src/common

- doc/devdocs/readme.md
Current link for the Wix3 toolset in the dev docs redirects to Wix4.
This PR Updates the WiX3 links to the correct ones.
Clicked the new links in the markdown preview and verified they work.
> [Docs]Update WiX3 links

- .github/actions/spell-check/expect.txt
- doc/devdocs/modules/launcher/plugins/windowssettings.md
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Helper/ResultHelper.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Main.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Properties/Resources.resx
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/WindowsSettings.json
This PR adds
- the missing cpl command names als alternative names.
- MMC.exe as result.
- all MMC snap-ins as result.
Local build and Unit tests.
> [PT Run > Settings plugin] Add missing cpl names and MMC/MSC commands

- doc/gpo/README.md
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/GeneralPage.xaml
This PR
- fixes the GPO docs.
- changes the layout of the disabled Experiments setting when GPO is configured. (To be aligned with all the other GPOs.)
Includes a small text fix for the Utility GPO information.
> [GPO; Enterprise] Experimentation GPO: Small fixes

- tools/BugReportTool/BugReportTool/ReportGPOValues.cpp
Some new gpo rules were recently added. Let's get those with the bug report tool as well.
> [BugReport]Add new gpo rules to the reporting

- Directory.Build.props
- src/common/interop/PowerToys.Interop.vcxproj
- src/common/version/version.h
Update the copyright year to 2023
View PowerToys.exe Properties/Details and see the new copyright year.
> Update copyright year

- src/modules/Hosts/Hosts.Tests/EntryTest.cs
- src/modules/Hosts/Hosts.Tests/HostsServiceTest.cs
- src/modules/Hosts/Hosts/Helpers/ExpressionExtensions.cs
- src/modules/Hosts/Hosts/Helpers/HostsService.cs
- src/modules/Hosts/Hosts/Models/AddressType.cs
- src/modules/Hosts/Hosts/Models/Entry.cs
- src/modules/Hosts/Hosts/Settings/IUserSettings.cs
- src/modules/Hosts/Hosts/Settings/UserSettings.cs
- src/modules/Hosts/Hosts/ViewModels/MainViewModel.cs
- src/modules/Hosts/Hosts/Views/MainPage.xaml.cs
- src/settings-ui/Settings.UI.Library/HostsProperties.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/HostsViewModel.cs
- src/settings-ui/Settings.UI/Views/HostsPage.xaml
Improved duplicate hosts finding according to users feedback.
Use `AdvancedCollectionView` to improve filters responsiveness and memory usage.
- Renamed settings section from Files to Behavior
- Added option to don't consider loopback addresses as duplicates (default off)
- Allow to use the same hosts for IPv4 and IPv6 address without marking the entries as duplicates
- Add/Update entry form still validating IPv4 and IPv6 address
- Use the same hosts for 1 IPv4 and 1 IPv6 entries: entries aren't duplicates
- Turn on the new option: entries with same hosts for `127.0.0.1` and `::1` addresses are duplicates
- Turn off the new option: entries with same hosts for `127.0.0.1` and `::1` addresses aren't duplicates
- Turn on/off the new option update entries without restaring the editor
- Test …
> [Hosts] Improved duplicate hosts finding

- CONTRIBUTING.md
Adds a section about localisation in the contributing.md file.
> Add information about localisation in contributing.md

- src/settings-ui/Settings.UI/MainWindow.xaml
- src/settings-ui/Settings.UI/MainWindow.xaml.cs
- src/settings-ui/Settings.UI/OOBE/Views/OobeShellPage.xaml
- src/settings-ui/Settings.UI/OobeWindow.xaml
- src/settings-ui/Settings.UI/OobeWindow.xaml.cs
- src/settings-ui/Settings.UI/Views/ShellPage.xaml
This PR introduces the following changes by switching Window to WindowEx
- Mica for Settings and OOBE windows
- MinWidth/MinHeight for Settings and OOBE windows
Before:
After:
Before:
After:
> [Settings / OOBE] Adding Mica

- src/modules/launcher/Wox.Plugin/PluginPair.cs
- src/modules/launcher/Wox.Plugin/Properties/Resources.Designer.cs
- src/modules/launcher/Wox.Plugin/Properties/Resources.resx
This PR updates the plugin loading error message to show where it is comming from.
> [PT Run] Improve plugin loading error

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PastePlainViewModel.cs
- src/settings-ui/Settings.UI/Views/PastePlainPage.xaml
Add/show warning when shortcut is "Ctrl+V" oder "Ctrl+Shift+V".
> [Settings > PastePlain] Add shortcut warning

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/translation_issue.yml
ref https://github.com/microsoft/PowerToys/pull/23709
> [Registry Preview] Add Registry Preview to github issue template

- src/modules/peek/Peek.UI/MainWindow.xaml.cs
- src/modules/peek/Peek.UI/Strings/en-us/Resources.resw
- src/modules/peek/Peek.UI/Views/TitleBar.xaml
- src/modules/peek/Peek.UI/Views/TitleBar.xaml.cs
When pinned, the window stays where it was placed (the center point is fixed), otherwise, it's re-centering each time.
https://user-images.githubusercontent.com/8949536/226295385-384b9a92-f563-42a4-b6ac-7f4b8e45051f.mp4
> [Peek] Pin the window position 

- src/gpo/assets/PowerToys.admx
This PR fixes the admx version property for v0.69.0 and updates the "last changed" comment.
Not manually tested.
> [Enterprise > GPO] Fix ADMX property

- .pipelines/release.yml
Generate hash for all 4 installers in separate files:
hash_user_x64.txt
hash_machine_x64.txt
hash_user_arm64.txt
hash_machine_arm64.txt
> [ci] Fix release pipeline installers hash generator

- src/settings-ui/Settings.UI/OOBE/Views/OobeWhatsNew.xaml.cs
> [Settings][OOBE] Update RemoveInstallerHashesRegex to match new installers list

- src/modules/previewpane/SvgPreviewHandler/Settings.cs
- src/modules/previewpane/SvgPreviewHandler/SvgHTMLPreviewGenerator.cs
- src/modules/previewpane/SvgPreviewHandler/SvgPreviewControl.cs
- src/modules/previewpane/SvgPreviewHandler/SvgPreviewHandler.csproj
- src/settings-ui/Settings.UI.Library/Enumerations/SvgPreviewCheckeredShade.cs
- src/settings-ui/Settings.UI.Library/Enumerations/SvgPreviewColorMode.cs
- src/settings-ui/Settings.UI.Library/PowerPreviewProperties.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerPreviewViewModel.cs
- src/settings-ui/Settings.UI/Views/ColorPickerPage.xaml
- src/settings-ui/Settings.UI/Views/PowerPreviewPage.xaml
This MR adds a background to the preview pane so that the visibility of white/transparent svg's is improved. This is just a proof of concept which can be extended, if the proposed solution is fine for the core contributors.
| Before  | After |
| ------------- | ------------- |
|  ![image](https://user-images.githubusercontent.com/8336867/231181692-26de5026-9acb-463b-ac4e-54c119a9b506.png) | ![image](https://user-images.githubusercontent.com/8336867/231181232-61f19e08-b040-400f-9d81-54f7ca190348.png) ![image](https://user-images.githubusercontent.com/8336867/231987512-2ed0e6db-7675-46f5-a982-bf28afa42cda.png) ![image](https://user-images.githubusercontent.com/8336867/231987702-54b791b3-e0c8-41c8-abfe-294b401acf20.png)|
> SvgPreviewControl: Add Background so that white .svg are visible

- .github/actions/spell-check/allow/names.txt
- .github/actions/spell-check/expect.txt
- COMMUNITY.md
Add myself to `community.md`
Clint asked me to add myself to the `community.md` like 2 weeks ago and I finally got around to doing it.
Just updating one markdown file.
> Add TheJoeFin to Community.md

- COMMUNITY.md
@crutkas asked me to add a note about myself to the contributors list in ```COMMUNITY.md```
- N/A
- N/A
- N/A
- N/A
- N/A
- added myself to COMMUNITY.md
> [Community] - adding @mikeclayton per @crutkas request - ready for review

- Directory.Packages.props
- NOTICE.md
- src/settings-ui/Settings.UI/Views/ColorPickerPage.xaml
We have fixed multiple issues with `SettingsCard` and `SettingsExpander` with https://github.com/CommunityToolkit/Labs-Windows/pull/413
By upgrading to `0.18` we can now close multiple accessibility issues.
> [Settings] A11y fixes

- Directory.Packages.props
- NOTICE.md
- src/modules/MeasureTool/MeasureToolCore/PowerToys.MeasureToolCore.vcxproj
- src/modules/MeasureTool/MeasureToolCore/packages.config
- src/modules/powerrename/PowerRenameUILib/PowerRenameUI.vcxproj
- src/modules/powerrename/PowerRenameUILib/packages.config
Noticed a unconsolidated package so added an update.
> updating webview2 and consolidating winappsdk

- .pipelines/release.yml
making is so i don't manually have to add the version number to the zip
> Making the GPO folder include version number by default.

- src/modules/fancyzones/editor/FancyZonesEditor/App.xaml
- src/modules/fancyzones/editor/FancyZonesEditor/HeadingTextBlock.cs
- src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml
- src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs
Text 'Edit layout' of the edit layout dialog should be defined as heading.
> [Fancy zones editor - Edit layout] Wrong text definittions

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/translation_issue.yml
Adding new utilities Peek and Mouse Without Borders to issue templates.
Additional this PR updates the version number in the templates.
> [Github templates] Add Peek and MouseWithoutBorders

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/Views/MouseWithoutBordersPage.xaml
- src/settings-ui/Settings.UI/Views/PeekPage.xaml
- Adding/fixing documentation links for Peek and MWB (as they were missing)
- Improvements to the MWB layout UI reflecting OS display management:
Before vs. after
> [Settings] MWB and Peek improvements

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/MouseWithoutBordersViewModel.cs
- src/settings-ui/Settings.UI/Views/MouseWithoutBordersPage.xaml
Add an advanced option from the original MWB UI to our Settings.
- Added an entry to the text box
- Pressed refresh connections
- set bp in StartNewTcpClient, the mapped IP is successfully picked up
> [MWB] add Name2IP field to Settings

- src/common/Common.UI/NativeEventWaiter.cs
In NativeEventWaiter global event is opened which is previously created from c++ (created with ManualReset = FALSE), so ManualReset option here was overridden. If for any reason, C# creates this event before C++, ManualReset takes precedence and it ends up going into an infinite loop. Therefore, aligning AutoReset with c++ should fix the issue.
I couldn't reproduce the issue, I could only force creating C# event first to experience the same behavior as reported in the issue.
Test all events manually and ensure everything still works as expected
> AutoReset global event in NativeEventWaiter

- src/modules/peek/Peek.UI/MainWindow.xaml
- src/modules/peek/Peek.UI/MainWindow.xaml.cs
Hide Peek window pressing ESC key
ESC key should hide Peek window
> [Peek] Hide with ESC key

- src/modules/peek/Peek.FilePreviewer/Controls/BrowserControl.xaml.cs
Set transparent default background color to avoid blinking while loading the page.
> [Peek] Fix blinking while loading dev files 

- src/modules/peek/Peek.UI/Extensions/HWNDExtensions.cs
- src/modules/peek/Peek.UI/Extensions/WindowExtensions.cs
- src/modules/peek/Peek.UI/MainWindow.xaml.cs
- src/modules/peek/Peek.UI/NativeMethods.txt
Center Peek on the monitor where the activated File Explorer is situated.
> [Peek] Center Peek window on File Explorer activated monitor

- src/modules/peek/Peek.FilePreviewer/FilePreview.xaml.cs
Won't harm to reset to avoid possible issues as with video source.
> [Peek] Reset Image and Browser sources

- src/modules/peek/Peek.UI/Helpers/FileExplorerHelper.cs
- src/modules/peek/Peek.UI/MainWindow.xaml.cs
* Select any image file and preview it with peek
* Click on the directory background so Peek loses focus and none of the files from the directory is selected
* Press Peek activation shortcut
* Check there is no Peek crash in the EventViewer
> [Peek] crash fix

- src/modules/peek/peek/dllmain.cpp
After #26222, Peek stopped closing on pressing the activation shortcut again while the Peek window is focused. This PR makes it so that the activation key still sends the event to Peek when it is the foreground window.
Verified that the Peek window closes while pressing the activation shortcut and it is focused.
> [Peek]Close on activation shortcut if focused

- src/modules/MouseWithoutBorders/App/Class/InputHook.cs
- src/modules/MouseWithoutBorders/App/Class/InputSimulation.cs
- src/modules/MouseWithoutBorders/App/Class/Program.cs
- src/modules/MouseWithoutBorders/App/Class/Setting.cs
- src/modules/MouseWithoutBorders/App/Form/frmMatrix.Designer.cs
- src/modules/MouseWithoutBorders/App/Form/frmMatrix.cs
- src/settings-ui/Settings.UI.Library/MouseWithoutBordersProperties.cs
- Remove UseVKMap/VKMap.
- Thanks to @dtaylor84 for the investigation!
> [MWB] disable deprecated functionality

- src/settings-ui/Settings.UI/ViewModels/MouseWithoutBordersViewModel.cs
- src/settings-ui/Settings.UI/Views/MouseWithoutBordersPage.xaml
When running as admin:
before:
after:
> [MWB] improve UX for Uninstall service when it's inaccessible

- Directory.Packages.props
- NOTICE.md
- src/modules/Hosts/Hosts/Helpers/HostsService.cs
- src/modules/Hosts/Hosts/Models/Entry.cs
- src/modules/Hosts/Hosts/ViewModels/MainViewModel.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/WebBrowserPreviewer/WebBrowserPreviewer.cs
- Upgraded CommunityToolkit.Mvvm to 8.2.0
- Fixed warnings
- QOL improvements of hosts view models using the newly introduced source generators
Minimal test of the following utilities:
- FileLocksmith
- Peek
- Hosts (test the show duplicates filter and entry validation on add/update)
> [Chore] Bump CommunityToolkit.Mvvm to 8.2.0

- src/runner/UpdateUtils.cpp
- src/runner/settings_window.cpp
- src/runner/tray_icon.cpp
There is a lag when check for updates button and report bug button in tray icon is clicked. Both functions are moved to thread.
> Runner]updating and bug report lags

- src/common/FilePreviewCommon/index.html
Switched copy and toggle text wrap options, as copy is more used as switching text wrapping. So now it's more intuitive.
> [Monaco] Switch context menu items

- src/modules/Hosts/Hosts.Tests/HostsServiceTest.cs
- src/modules/Hosts/Hosts/Helpers/HostsService.cs
- src/modules/Hosts/Hosts/Settings/IUserSettings.cs
- src/modules/Hosts/Hosts/Settings/UserSettings.cs
- src/settings-ui/Settings.UI.Library/Enumerations/HostsAdditionalLinesPosition.cs
- src/settings-ui/Settings.UI.Library/Enumerations/HostsEncoding.cs
- src/settings-ui/Settings.UI.Library/HostsProperties.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/HostsViewModel.cs
- src/settings-ui/Settings.UI/Views/HostsPage.xaml
New setting to chose the encoding of the hosts file between UTF8 (default) and UTF8 with BOM.
CC @crutkas 
- Start the editor
- Make a change: file should be saved with UTF8 encoding
- Open settings (don't close editor)
- Change encoding to UTF8 BOM
- Make a change: file should be saved with UTF8 BOM encoding
- Close editor
- Start editor
- Make a change: file should be saved with UTF8 BOM encoding
> [Hosts] Encoding setting

- src/modules/imageresizer/ui/ViewModels/InputViewModel.cs
- src/modules/imageresizer/ui/Views/InputPage.xaml
- src/modules/imageresizer/ui/Views/InputPage.xaml.cs
> [Image Resizer] HandleEnterKeyPress event added for image resizer.

- src/common/Themes/theme_helpers.cpp
On current main, building from Visual Studio is failing.
https://github.com/microsoft/PowerToys/pull/26660 added this build error.
It does build from MSBuild command line, though.
This seems to be caused by using a static library that requires us to link a library on the parent project. Adding a pragma to the static library code as well seems to fix it.
PowerToys builds again on Visual Studio.
> [Build]Fix dwamapi.lib linking error on VS

- Directory.Packages.props
- NOTICE.md
Upgrading latest Microsoft.Windows.Compatibility nuget package
> Upgrading to latest Microsoft.Windows.Compatibility

- src/settings-ui/Settings.UI.Library/ColorPickerProperties.cs
- src/settings-ui/Settings.UI.Library/ColorPickerPropertiesVersion1.cs
- src/settings-ui/Settings.UI.Library/MeasureToolProperties.cs
- src/settings-ui/Settings.UI.Library/MouseHighlighterProperties.cs
- src/settings-ui/Settings.UI.Library/MouseJumpProperties.cs
- src/settings-ui/Settings.UI.Library/MousePointerCrosshairsProperties.cs
- src/settings-ui/Settings.UI.Library/PastePlainProperties.cs
- src/settings-ui/Settings.UI.Library/PeekProperties.cs
- src/settings-ui/Settings.UI.Library/PowerLauncherProperties.cs
- src/settings-ui/Settings.UI.Library/PowerOcrProperties.cs
- src/settings-ui/Settings.UI.Library/ShortcutGuideProperties.cs
- src/settings-ui/Settings.UI.Library/VideoConferenceConfigProperties.cs
- src/settings-ui/Settings.UI/Controls/ShortcutControl/ShortcutControl.xaml
- src/settings-ui/Settings.UI/Controls/ShortcutControl/ShortcutControl.xaml.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/ColorPickerViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/MeasureToolViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/MouseUtilsViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/PastePlainViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/PeekViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/PowerLauncherViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/PowerOcrViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/ShortcutGuideViewModel.cs
- src/settings-ui/Settings.UI/ViewModels/VideoConferenceViewModel.cs
- Add Default value to Properties
- Add Reset button in shortcut dialog
> [Settings] Reset Activation Key to Default Value

- src/modules/peek/Peek.FilePreviewer/Controls/UnsupportedFilePreview/InformationalPreviewControl.xaml
- src/modules/peek/Peek.UI/MainWindow.xaml
This PR defines a minimal window size and adds tool tips to `FileInfoPreview`.
Local build and test of the functionality.
> [Peek] Window improvements

- .pipelines/ESRPSigning_core.json
> [release ci] Fix signing Peek/SharpCompress.dll

- Directory.Packages.props
- NOTICE.md
This fixes Peek crashing with https://github.com/dotnet/runtime/issues/81400 on ARM64.
> Bump System.Management to 7.0.2

- README.md
Readme update for the 0.72 release.
> 0.72 changelogs

- src/common/utils/elevation.h
Successful calls to CoInitialize must be balanced by calls to CoUninitialize.
I doubt the try/catch is required here since it is all COM but I don't know the code well enough to pull the trigger.
> Missing CoUninitialize

- src/runner/main.cpp
- src/runner/restart_elevated.cpp
adding parameter to restart process with elevated mode to detect the restart loop.
Also on startup check presence of the parameter and start without elevation if it isn't possible as described in the issue 19307 
Detecting restart loop with a newly included parameter. Breaking loop by starting non-elevated.
1. Making you user to an admin account.
2. Disable UAC.
3. Run PT as Admin and enable the following settings: Run at startup, Always run as admin
4. Changing you user profile back to normal user.
5. in hklm\software\microsoft\windows\currentversion\policies\system set 
- "ConsentPromptBehaviorAdmin": 0
- "ConsentPromptBehaviorUser": 3
- "EnableLua": 0
6. Reboot.
> [Runner] adding param when restarting to detect restart loop

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/translation_issue.yml
Add Crop and Lock to the issues templates on GitHub.
> [GitHub]Add Crop and Lock to the issues templates

- .github/actions/spell-check/allow/names.txt
- COMMUNITY.md
The core team in COMMUNITY.md has been outdated for a while. This PR updates it.
> [Docs]Update core team in COMMUNITY.md

- .github/actions/spell-check/patterns.txt
- .pipelines/ci/templates/build-powertoys-ci.yml
- .pipelines/ci/templates/build-powertoys-installer.yml
- .pipelines/ci/templates/build-powertoys-steps.yml
- .pipelines/installer-steps.yml
- .pipelines/release.yml
Removes standalone NuGet restore tasks and adds restore to msbuild targets in Build tasks
> [CI] Condense NuGet Restore into MSBuild Tasks

- doc/devdocs/settingsv2/ui-architecture.md
To quote the subject line: 
> Update ui-architecture.md: Fix .xaml links
I used "Preview" in the github editor to open the links in new tabs, and they both worked.
> Update ui-architecture.md: Fix .xaml links

- .github/policies/resourceManagement.yml
Adds a new fabric bot command: `/helped`.
> Add /helped command

- doc/devdocs/modules/launcher/plugins/community.valuegenerator.md
Follow-up doc PR for https://github.com/microsoft/PowerToys/pull/27835
> [doc] Add Base64DecodeRequest description in community.valuegenerator.md

- README.md
Revert PR merged by accident.
This reverts commit ac0677bdeecc398a6763a2850d1052cfe15fc7b9.
> Revert "Updated Release Notes for KBM Note (#28131)"

- .github/policies/resourceManagement.yml
> /helped markdown bug fix

- src/common/interop/keyboard_layout.cpp
> [KBM] Display VK_SUBTRACT key as "- (Substract)" to distinguish from VK_OEM_MINUS ("-")

- SECURITY.md
With https://github.com/microsoft/repo-templates/pull/13 merged we can now take the new security.md file
> Update SECURITY.md from 0.0.2 to 0.0.9

- src/.editorconfig
- StyleCop SA1633 wants header in .cs files
- Added header to editorconfig to have it automatically inserted in new .cs files
> [Chore] Automatically add header to .cs files

- src/modules/launcher/PowerLauncher/SettingsReader.cs
- src/settings-ui/Settings.UI.Library/PowerLauncherProperties.cs
- src/settings-ui/Settings.UI.UnitTests/ViewModelTests/PowerLauncherViewModelTest.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerLauncherPage.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerLauncherViewModel.cs
Add a toggle to turn on pinyin.
Open PowerToys, select PowerToys Run, find Use pinyin, toggle to on, see chinese characters in search.
> UI for Pinyin

- README.md
- doc/devdocs/readme.md
This PR updates the main readme and developer documentation for clarity and completeness.
- [n/a] **Closes:** #xxx
- [n/a] **Communication:** I've discussed this with core contributors already. If work hasn't been agreed, this work might be rejected
- [n/a] **Tests:** Added/updated and all pass
- [n/a] **Localization:** All end user facing strings can be localized
- [n/a] **New binaries:** Added on the required places
- [n/a] [JSON for signing](https://github.com/microsoft/PowerToys/blob/main/.pipelines/ESRPSigning_core.json) for new binaries
- [n/a] [WXS for installer](https://github.com/microsoft/PowerToys/blob/main/installer/PowerToysSetup/Product.wxs) for new binaries and localization folder
- [n/a] [YML for CI pipeline](https://github.com/microsoft/PowerToys/blob/main/.pipelines/ci/te …
> Update documentation for clarity and completeness

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/WindowsSettings.json
The PR copies the existing settings entry in the json and updates the value for Windows 11.
> [PT RUN > Settings plugin] Fix update search setting for windows 11

- .github/actions/spell-check/expect.txt
- README.md
Readme update for the 0.74 release.
> 0.74 changelogs

- doc/devdocs/modules/launcher/plugins/system.md
Fixes simple typo/grammar error.
It's easier to understand if it is spelled correctly. This is especially important for those for whom english may not be their first language
Used a dictionary ;)
> devdocs typos

- src/common/interop/keyboard_layout.cpp
- map these characters to other symbols and verify it works
-
> [KBM] Visually distinguish between decimal dot and period characters

- doc/gpo/README.md
- src/common/utils/gpo.h
- src/gpo/assets/PowerToys.admx
- src/gpo/assets/en-US/PowerToys.adml
This PR adds a "global enabled state for all utilities" policy. It can be overridden using the individual utility policies.
> [Enterprise] Global enabled state for all utilities GPO

- .pipelines/release.yml
I legitimately don't know how I missed this.
> Remove PR trigger from release.yml (!)

- .github/actions/spell-check/expect.txt
~Fixes simple typo error~
Second attempt. Remove the incorrect spelling from the exclude list
No point in having a spell checker action if it has incorrect spellings
It's easier to understand if it is spelled correctly. This is especially important for those for whom english may not be their first language.
Used a dictionary
> Spell Check correction

- src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
- src/modules/fancyzones/FancyZonesLib/FancyZonesWindowProcessing.cpp
Follow-up for https://github.com/microsoft/PowerToys/pull/28956.
Removing temporary solution for the hotfix, and updating the generally used filter of processable windows.
> [FancyZones] Filtering popup windows - follow up PR

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/translation_issue.yml
- README.md
Add the mention to Environment Variables to the list of utilities in README.md and to the GitHub templates.
> [GitHub]Add EnvVars to README and templates

- src/common/interop/keyboard_layout.cpp
> Corrected typo in "Subtract"

- .github/actions/spell-check/expect.txt
- README.md
Readme update for the 0.75 release.
> 0.75 changelogs

- README.md
Fixes #29531 
Fixed the typos in Readme.md file.
> Fixed the typos in Readme.md

- src/gpo/assets/PowerToys.admx
- src/gpo/assets/en-US/PowerToys.adml
> [GPO] Add Environment Variables to admx/amdl files

- Directory.Packages.props
- NOTICE.md
- Keep WebView2 dependency up to date
- See if the new version help with flaky tests in CI (probably not 😄)
- Preview Pane
- SVG
- Markdown
- Source code (Monaco)
- Thumbnails generation
- SVG
- Peek
- SVG
- Markdown
- Source code (Monaco)
- PDF
> [Chore] Bump WebView2 to latest release

- src/gpo/assets/en-US/PowerToys.adml
This PR makes some improvements on the ADML file and fixes some typos.
> [Enterprise] ADML file: Text improvements and typo fixes

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.TimeDate.UnitTests/TimeDateResultTests.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.TimeDate/Components/AvailableResultsList.cs
- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.TimeDate/Components/TimeAndDateHelper.cs
This PR fixes the parsing of Windows File Time inputs.
Additional the code for converting to Windows File Time and converting from/to Unix Epoch Time is updated to use the official CSharp methods instead of custom calculations.
1. Validate the correct output using the information from the issue.
2. Updated and run the tests.
> [Run] Date & Time plugin: Fix and improvements for Windows File Time and Unix Epoch Time

- Cpp.Build.props
- src/Version.props
Making the SDL and sha checks to be Globals.
> SDL and SHA tweaks for dll creation

- Directory.Packages.props
- NOTICE.md
Bumper `WpfUi` to `preview.10`:
- this version contains a few bugfixes for theme switching on W10 and HC mode background mode
- first `WpfUi` preview that supports .NET8
> Bump wpf-ui to preview.10

- .github/actions/spell-check/expect.txt
- README.md
Readme update for the 0.76 release.
> 0.76 changelogs

- src/modules/fancyzones/FancyZonesLib/FancyZonesWindowProcessing.cpp
- src/modules/fancyzones/FancyZonesTests/UnitTests/WindowProcessingTests.Spec.cpp
* Verify Facebook messenger app can be snapped
> [FancyZones] Allow snapping Facebook messenger 

- src/modules/launcher/Wox.Infrastructure/Image/WindowsThumbnailProvider.cs
- Clean icons cache from LocalAppData/PowerToys
- Start PT Run
- Search for different apps, .lnk files. Check if icon is correct
> [PT Run] Do not get target file icon for .lnk files

- src/modules/launcher/PowerLauncher/LauncherControl.xaml
- Switch OS language to Hebrew
- Make sure keyboard language is also Hebrew
- Start typing something in PT Run
- Observe that suggest text and type text are aligned
> [PT Run] Fix margin when FlowDirection is RightToLeft

- src/modules/launcher/PowerLauncher/App.xaml.cs
Test different values of PT Run theme setting.
Also test OS high contrast themes
> [PT Run] Fix theme setting

- README.md
> update hashes to 76.1

- Directory.Packages.props
- NOTICE.md
> Bump WPF-UI package version

- README.md
> Update hashes - 76.2

- src/runner/Resources.resx
Adds a comma between *computer* and *when possible* in the update notification.
> Fix typo in version change notification

- README.md
user directly was asking about x86 support
> Update README.md to directly state x64 & ARM proc

- .pipelines/sdl.gdnbaselines
Chore: update sdl.gdnbaselines to take the boost dependency upgrade into account.
Waiting for Dart CI to pass.
> [ci]Update sdl baselines after boost upgrade

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Added an entry to the documentation for my Scoop plugin for PowerToys Run.
> Add Scoop plugin to thirdPartyRunPlugins.md

- Directory.Packages.props
> Note for props file to prevent accidently rev

- src/settings-ui/Settings.UI/SettingsXAML/Flyout/LaunchPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/EnvironmentVariablesPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/FancyZonesPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/HostsPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/KeyboardManagerPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/MouseUtilsPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerLauncherPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/RegistryPreviewPage.xaml
Some still had FontFamily or FontSize declared.
> remove obsolete UI Fonticon properties

- Directory.Build.props
- src/common/version/version.h
Update copyright year to 2024.
> [Chore]Update copyright year for 2024

- src/gpo/assets/PowerToys.admx
- src/gpo/assets/en-US/PowerToys.adml
> [gpo] Update revisions

- Directory.Packages.props
- NOTICE.md
- src/modules/cmdNotFound/CmdNotFound/CmdNotFound.csproj
> Upgrading Microsoft.Extensions.ObjectPool from v5 to v8

- Directory.Packages.props
- NOTICE.md
- Updated StyleCop to lastest release that include improvements to support .NET8 / C#12 syntax.
> [Chore] Update StyleCop

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Add the third party plugin I developed to the list.
The plugin makes it possible to search and control Spotify.
> [Run] Add Spotify third party plugin to third party Run plugin list.

- nuget.config
- src/modules/EnvironmentVariables/EnvironmentVariables/EnvironmentVariables.csproj
- src/modules/FileLocksmith/FileLocksmithUI/FileLocksmithUI.csproj
- src/modules/registrypreview/RegistryPreviewUI/RegistryPreviewUI.csproj
- src/settings-ui/Settings.UI.UnitTests/Settings.UI.UnitTests.csproj
- src/settings-ui/Settings.UI/PowerToys.Settings.csproj
This should i think remove the need for #28965
> Remove Toolkit labs and leverage RTM toolkit

- .pipelines/release.yml
Revert https://github.com/microsoft/PowerToys/commit/c7315c695cfdc608a05156538b2359fb9b9f200f now that 1ES pipelines are taking sdl baselines into account in the latest stable release.
Verified by the fact that release CI is passing.
> [ci]Use latest 1ES pipeline release

- doc/thirdPartyRunPlugins.md
Add two new plugins developed by myself to the `thirdPartyRunPlugins.md` docs
> [PTRun][Docs] Updated Third party plugins to include two plugins InputTyper + ClipboardManager

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/translation_issue.yml
CNF wasn't added into templates.  found via https://github.com/microsoft/PowerToys/issues/31039
> Adding CNF into issue templates

- .github/actions/spell-check/allow/names.txt
- doc/devdocs/modules/mousewithoutborders.md
Added documentation in the dev docs section, describing the status codes for the Mouse Without Borders modules
- [X ] **Localization:** All end user facing strings can be localized
https://github.com/MicrosoftDocs/windows-dev-docs/pull/4815
> Added markdown file for mouse without borders documentation

- src/settings-ui/Settings.UI/Helpers/ModuleHelper.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/DashboardPage.xaml
- src/settings-ui/Settings.UI/ViewModels/DashboardListItem.cs
- src/settings-ui/Settings.UI/ViewModels/DashboardViewModel.cs
Fixing accent color and border radius for the button
Fixed version:
> Fixing accent brush and corner radius on dashboard

- tools/BugReportTool/BugReportTool/ReportGPOValues.cpp
The PR add the new updater policies to the Bugreport tool:
- `getDisableNewUpdateToastValue`  (PR #30794)
- `getDisableShowWhatsNewAfterUpdatesValue` (PR #30609)
I have missed that in the implementation PRs.
> [Bugreport Tool] Add new update policies

- src/settings-ui/Settings.UI/SettingsXAML/Flyout/AppsListPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/AlwaysOnTopPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/AwakePage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/CmdNotFoundPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/ColorPickerPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/CropAndLockPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/DashboardPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/EnvironmentVariablesPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/FancyZonesPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/FileLocksmithPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/GeneralPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/HostsPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/ImageResizerPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/KeyboardManagerPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/MeasureToolPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/MouseUtilsPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/MouseWithoutBordersPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/PastePlainPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/PeekPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerAccentPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerLauncherPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerOcrPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerPreviewPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerRenamePage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/RegistryPreviewPage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/ShortcutGuidePage.xaml
- src/settings-ui/Settings.UI/SettingsXAML/Views/VideoConference.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerPreviewViewModel.cs
This PR makes several improvements for the GPO infoboxes:
- Aligned uid name scheme.
- Aligned info box text.
- Less boxes on the file explorer pages.
- Fix for the file explorer pages: Now the users can change settings like word-wrap for monaco if the module ist force enabled.
> [Settings ux > GPO] Improvements and fixes

- .github/actions/spell-check/allow/names.txt
- .github/actions/spell-check/expect.txt
- doc/thirdPartyRunPlugins.md
I and many community members wanted a currency converter option directly in PowerToys Run, but due to several issues mentioned in many of the issues created by several members, it is not possible to support it officially. Therefore, I took the liberty to create a community-maintained plugin that does the same. I hope this gets merged into the official repo.
> [PTRun][Docs] Add CurrencyConverter plugin

- README.md
Readme update for the 0.78 release.
> 0.78 changelog

- Directory.Build.props
- nuget.config
- packages.config
Update MSBuildCache to 0.1.258-preview
Another small change is to fix the malformed NuGet.Config file.
> [Build]Update MSBuildCache to 0.1.258-preview

- .pipelines/verifyAndSetLatestVCToolsVersion.ps1
Updated VCToolsVersion script to move from looking at the VC.Redist version and instead use the VC.Tools version returned from vswhere.
> [CI] Point VCToolsVersion to latest VC.CRT version instead of VC.Redist version

- Directory.Packages.props
- NOTICE.md
> upgrading test adapter and framework to 3.2

- .pipelines/installWiX.ps1
- doc/devdocs/readme.md
Old links are dead. Moving to GitHub links latest release. Tested CI build. Works well.
> [CI & Docs]Update Wix urls and hashes

- Directory.Packages.props
- NOTICE.md
Update System.Drawing.Common to 8.0.2
Will fix current CI issues.
> [Deps]Update System.Drawing.Common to 8.0.2

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
Add .txt as description as it caused confusion.
> Add .txt to Monaco description

- doc/devdocs/readme.md
Update /doc/devdocs/readme.md fix 2 broken links on line 167
The issue occured line 167:
--> the "json.h" file has moved under the "utils" folder under "/src/common"
--> the "two_way_pipe_message_ipc.h" file has moved under the "interop" folder under "/src/common"
1- Preview the readme.md
2- Move my mouse over the link
3- Carreful use your prefer finger, position it on top of the left click of your mouse
4- Perform a click
5- Wait github to redirect you to the right page
6- Repeat the 5 previous steps for the other link
> Update broken links in /doc/devdocs/readme.md

- .github/actions/spell-check/expect.txt
- README.md
Readme update for the 0.79 release.
> 0.79 changelog

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Add a new plugin developed by myself to `thirdPartyRunPlugins.md` docs
> [PTRun] [Docs] Add FastWeb plugin to third party Run plugin list.

- .github/ISSUE_TEMPLATE/config.yml
removing since security.md handles this.  that link predates security.md
This PR will remove the bottom link as [security.md](https://github.com/microsoft/PowerToys/blob/main/SECURITY.md) handles this.
> Removing security link in preference for security.md

- doc/thirdPartyRunPlugins.md
From https://github.com/microsoft/PowerToys/pull/31655, I want to separate generic plugins and plugins that are not official plugins.  I do not want someone to assume a plugin for a piece of software was written by that company.
I believe we have a great community but end users of the plugin should not be mistaken.
> Directly calling out unofficial plugins

- src/modules/keyboardmanager/KeyboardManagerEditor/KeyboardManagerEditor.vcxproj
- src/modules/keyboardmanager/KeyboardManagerEditor/packages.config
- src/modules/keyboardmanager/KeyboardManagerEditorLibrary/KeyboardManagerEditorLibrary.vcxproj
- src/modules/keyboardmanager/KeyboardManagerEditorLibrary/packages.config
> Consolidation of WebView2

- src/modules/peek/Peek.FilePreviewer/Previewers/MediaPreviewer/ImagePreviewer.cs
- src/modules/peek/Peek.FilePreviewer/Previewers/MediaPreviewer/VideoPreviewer.cs
Add support for `.webp` and `.webm` files.
- `.webp` require https://apps.microsoft.com/detail/9PG2DK419DRG
- `.webm` require https://apps.microsoft.com/detail/9n4d0msmp0pt
Tested with some sample files downloaded from the internet.
> [Peek] Add webp/webm support

- src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs
- src/settings-ui/Settings.UI.Library/PluginAdditionalOption.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerLauncherPage.xaml
- src/settings-ui/Settings.UI/ViewModels/PluginAdditionalOptionViewModel.cs
- This PR adds the new type CheckboxAndMultilineTextBox:
- This PR adds the alias property `TextValueAsMultilineList` for the property `TextValue` to have the line break handling in PT Runs' code.
> [PT Run] PluginAdditionalOptions: Add CheckboxAndMultilineTextBox type and improvements to multiline text handling

- .github/actions/spell-check/allow/names.txt
- .github/workflows/similarIssues.yml
Adds a similar issues bot which determines similarity based on the issue title and issue body and outputs that to users.
See previous PR that was closed as it was missing the ability to use issue body: https://github.com/microsoft/PowerToys/pull/29869
We should now be able to merge since we take issue body into account.
> Create similarIssues.yml to make a similar issues bot 

- .pipelines/ci/templates/run-ui-tests-ci.yml
> [UI Tests] Update VsTest path

- src/dsc/PowerToys.Settings.DSC.Schema.Generator/DSCGeneration.cs
Deprecated Get-WmiObject cmdlet is replaced with Get-CimInstance.
> [DSC] Deprecated Get-WmiObject cmdlet is replaced.

- README.md
Readme update for the 0.80 release.
> 0.80 changelog

- Directory.Packages.props
- NOTICE.md
Fixes CI build for the .NET 8.0.4 upgrade.
> [Deps]Update System.Drawing.Common to 8.0.4

- .github/actions/spell-check/allow/names.txt
- COMMUNITY.md
Added the rest of the team to the COMMUNITY.md doc
> Update COMMUNITY.md with core team members

- src/modules/powerrename/PowerRenameUILib/PowerRenameXAML/MainWindow.xaml.cpp
Fix regex help, strings flipped
> [PowerRename] fix regex help

- .github/CODEOWNERS
Adding in a few more items into code owner
> Update CODEOWNERS to add a few more items

- .github/copilot-workspace/policy.json
> Add GitHub Copilot Workspaces policy

- Directory.Packages.props
- NOTICE.md
Fixes CI build for the .NET 8.0.5 upgrade.
> [Deps]Update System.Drawing.Common to 8.0.5

- README.md
> adjusted readme for clarifying advanced paste

- src/settings-ui/Settings.UI/SettingsXAML/Views/AdvancedPaste.xaml
- src/settings-ui/Settings.UI/ViewModels/AdvancedPasteViewModel.cs
Don't allow enabling/disabling the Clipboard History in Settings if the user has it disabled by GPO.
Tested the behavior with the GPO enabled/disabled/not configured.
Message only shows on disabled, as expected.
> [Settings][AdvPaste]Check clibboard history gpo

- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
Issues have been opened about worrying that Advanced Paste uses AI, which might be against policies in some companies. This PR updates the description of the tool in Settings and OOBE to clarify that the AI parts are opt-in.
> [Settings][AdvPaste]Clarify AI features are optional

- Directory.Packages.props
- NOTICE.md
> [Deps] Update System.Drawing.Common to 8.0.6

- src/modules/Hosts/HostsUILib/HostsMainPage.xaml
Disables word-wrap and adds horizontal scroll bar.
> [Hosts] Additional lines dialog: Replace word-wrap with horizontal scroll bar

- src/modules/AdvancedPaste/AdvancedPaste/Strings/en-us/Resources.resw
Small spelling fix of a string of the Advanced Paste UI. This should help for better translation.
- [] **Tests:** Added/updated and all pass
> [Advanced Paste > UX] Small spelling fix

- doc/thirdPartyRunPlugins.md
This PR removes a link to the deprecated [guid](https://github.com/skttl/ptrun-guid) plugin from the third-party run plugins document, which was archived on December of last year and the readme now says "DEPRECATED".
> Removed link to deprecated third-party plugin

- src/modules/AdvancedPaste/AdvancedPaste/Helpers/JsonHelper.cs
This PR improves the delimiter handling in the CSV parser:
-  We now can parse CSV with `,`, `;` and `Tab` as delimiter and we support the `sep=x` property like MS Excel.
-  We can detect invalid lines that have not enough delimiter and skip csv parsing.
If the text is not CSV and not XML we now can parse as plain text.
Adds a CSV delimiter detection code, improves the CSV parser and adds a plain text parser.
Behavior tested with local build.
> [Advanced Paste > Paste as JSON] Improve delimiter handling for CSV and add plain text parser

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Add [PowerHexInspector](https://github.com/NaroZeol/PowerHexInspector) to Third-Party plugins for powertoy run
> [PTRun][Docs] Add PowerHexInspector to Third-Party plugins

- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/ResultHelper.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/Window.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Components/WindowProcess.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Properties/Resources.Designer.cs
- src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Properties/Resources.resx
- src/modules/launcher/Wox.Plugin/Common/Win32/NativeMethods.cs
This PR fixes the #32343 issue. It resolves the hanging of the application while closing an unresponsive task, by creating another thread and running the function on it.
This PR introduces the following changes -
1. Added `SendMessageTimeout` method in the Win32 namespace
2. Added a `Responding` variable signifying if the process is responding or not
3. Changed the subtitle text of the process which is not responding
4. Created a `CloseThisWindowHelper` method which helps in closing the window and it is called in a separate thread
5. Created an entry for a localizable string for "Not Responding"
1. Ran an unresponsive task for more than 5 seconds. The task doesn't quit after becoming responsive, thereby, confirming the result.
2. Ran an unresponsive task for less than 5 seconds. The task …
> Resolved hanging of the program while closing an unresponsive task

- doc/devdocs/settingsv2/communication-with-modules.md
Fixes a broken link
Clicking on the link in my fork
> [Docs] Fix broken link in `communication-with-modules.md`

- src/modules/previewpane/MonacoPreviewHandler/MonacoPreviewHandlerControl.cs
Removed duplicate application of sticky scroll in preview pane.
Closes #33288
> [Preview Pane] Sticky scroll setting is handled twice #33288

- README.md
> Updated hashes for 82.1

- Directory.Packages.props
- NOTICE.md
> upgrading Microsoft.Windows.Compatibility to latest

- Directory.Packages.props
- NOTICE.md
- src/modules/AdvancedPaste/AdvancedPaste/AdvancedPaste.csproj
- src/modules/EnvironmentVariables/EnvironmentVariables/EnvironmentVariables.csproj
- src/modules/EnvironmentVariables/EnvironmentVariablesUILib/EnvironmentVariablesUILib.csproj
- src/modules/Hosts/Hosts/Hosts.csproj
- src/modules/MouseWithoutBorders/App/Service/MouseWithoutBordersService.csproj
- src/modules/launcher/PowerLauncher/PowerLauncher.csproj
- src/modules/launcher/Wox.Plugin/Wox.Plugin.csproj
- src/modules/peek/Peek.UI/Peek.UI.csproj
- src/settings-ui/Settings.UI/PowerToys.Settings.csproj
Sets the System.Text.Json version to 8.0.4
> [Deps]Set System.Text.Json version to 8.0.4

- src/gpo/assets/PowerToys.admx
- src/gpo/assets/en-US/PowerToys.adml
1. The "Allow Experimentation" policy is moved into a new category "General Settings".
2. The order of utility policies is changed that the global policy shows at the top on opening the edit dialog.
The oder change does not take any effect in the HTML reports.
These changes improve the visibility of some policies.
**⚠These changes do not break configured Group Policies. But the changes WILL BREAK EXISTING INTUNE POLICY CONFIGURATION SETS. ⚠**
Validated that the changes do not break existing group policy configurations.
> [Enterprise > Policies] Reorder ADMX to make it easier to find some policies

- src/modules/MouseWithoutBorders/App/Class/Setting.cs
- src/modules/MouseWithoutBorders/App/Form/frmMatrix.cs
This PR disables the check boxes for settings that we do not support in the PowerToys implementation.
> [MWB > Original UI > Settings] Disable setting that we do not support

- src/settings-ui/Settings.UI/SettingsXAML/Views/MouseWithoutBordersPage.xaml
Add icon to `Easy Mouse` feature.
Fix icon of `Switch Between Machine Shortcut`.
> [Settings > MWB] Align glyphs in Shortcut settings section

- src/modules/poweraccent/PowerAccent.Core/Languages.cs
- src/settings-ui/Settings.UI/SettingsXAML/Views/PowerAccentPage.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
- src/settings-ui/Settings.UI/ViewModels/PowerAccentViewModel.cs
Adds Bulgarian to Quick Accent
Adds Cyrillic letter short I (й)
Using Quick Accent
> [QuickAccent] Add Bulgarian

- doc/thirdPartyRunPlugins.md
Add RDP plugin  information to thirdPartyRunPlugins.md.
> Add RDP plugin to thirdPartyRunPlugins.md

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Add [GitHubRepo](https://github.com/8LWXpg/PowerToysRun-GitHubRepo) and [ProcessKiller](https://github.com/8LWXpg/PowerToysRun-ProcessKiller)
> [PTRun][Docs] Add GitHubRepo and ProcessKiller third-party plugins

- src/modules/keyboardmanager/common/KeyboardManagerCommon.vcxproj
This looks to have been added years ago for some reason.  It used to be 2000 and was pushed to 200.  If a user needed to do the /Zm flag, shouldn't they pick what they want?
> KBM Common had a compiler limitation for some reason

- src/common/UnitTests-CommonLib/UnitTestsVersionHelper.cpp
- src/common/version/helper.cpp
The latest fix pushed with tag `V0.82.1` (uppercase V) isn't detected by the PT internal updater.
Handle release tag with uppercase V during update.
- Added unit test
- Tested in a local build
```
[2024-07-13 14:20:03.555873] [p-18340] [t-19948] [trace] Check for updates callback invoked
[2024-07-13 14:20:03.816895] [p-18340] [t-19948] [trace] Discovered new version v0.82.1
[2024-07-13 14:20:03.818588] [p-18340] [t-19948] [trace] Downloading installer for a new version
```
> [Runner] Handle release tag with uppercase V during update

- .github/CODEOWNERS
> Update CODEOWNERS w/ correct casing on markdown files

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Components/Commands.cs
Adds support for auto-logon after reboot when using the reboot command in system plugin.
The behavior after reboot depends on the system setting for auto-logon after reboot/updates.
https://learn.microsoft.com/windows-server/administration/windows-commands/shutdown
> [PT Run > System plugin] Support automatic logon after reboot 

- Directory.Packages.props
- NOTICE.md
Upgrading testing frameworks to latest
> Upgrading NuGet testing frameworks to latest

- src/modules/AdvancedPaste/AdvancedPaste/Helpers/JsonHelper.cs
This PR fixes the csv parsing related to quotation marks according to csv standard rules:
- An empty data value can be written as `""`. => Remove both quotation marks.
- Enclosing data by starting and ending with `"` if they contain the delimiter. => First and last quotation mark has to be removed.
- Escape quotation mark with second quotation mark. => Replace pairs of two with a single one.
```csv
A,B,,"","my ""nice"" string","""zz""","""""double quotes"""""
```
```json
[
[
"A",
"B",
"",
"\"\"",
"\"my \"\"nice\"\" string\"",
"\"\"\"zz\"\"\"",
"\"\"\"\"\"double quotes\"\"\"\"\""
]
]
```
```json
[
[
"A",
"B",
"",
"",
"my \"nice\" string",
"\"zz\"",
"\"\"double quotes\"\""
]
]
```
```
A,B,,"","my ""nice"" string","""zz""","""""double quotes"""""
[
[
"A",
"B",
"",
"",
"my \"nice\" string", …
```
> [Advanced Paste > To JSON] CSV parser: Handle control characters (quotation marks) correctly

- README.md
Readme update for the 0.83 release.
> 0.83 changelog

- Directory.Packages.props
- NOTICE.md
- src/modules/MouseWithoutBorders/App/MouseWithoutBorders.csproj
- src/modules/poweraccent/PowerAccent.Core/Models/Point.cs
- src/modules/poweraccent/PowerAccent.Core/NativeMethods.txt
- src/modules/poweraccent/PowerAccent.Core/PowerAccent.Core.csproj
- src/modules/poweraccent/PowerAccent.Core/Tools/WindowsFunctions.cs
- Removed `Vanara.PInvoke.*` packages used in Quick Accent in favor of `Microsoft.Windows.CsWin32` that is already in use for other utilities.
- Removed `Microsoft.Windows.SDK.Contracts` package instanned only on MWB. This is not needed: https://learn.microsoft.com/windows/apps/desktop/modernize/desktop-to-uwp-enhance#modify-a-net-project-to-use-windows-runtime-apis
- Cleaned up obsolete packages from `Directory.Packages.props`: I realized that uninstalling a NuGet package from all projects doesn't remove it from `Directory.Packages.props`.
- Manually tested Quick Accent
> Dependencies cleanup

- Directory.Build.props
Setting NuGet Audit Mode to Direct since VS 17.12 sets default mode to transitive packages. Many packages have transitive references to older System.* packages that aren't used in the build, but instead pulled in from the current .NET Runtime libraries.
Setting the NuGet Audit Mode back to direct, resolves build issues. 
https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#nugetaudit
> [Build] Set NuGet Audit Mode to Direct to revert changes made with VS 17.12 

- src/modules/Hosts/Hosts.Tests/HostsServiceTest.cs
- src/modules/Hosts/HostsUILib/Helpers/HostsService.cs
- src/modules/Hosts/HostsUILib/Helpers/IHostsService.cs
- src/modules/Hosts/HostsUILib/ViewModels/MainViewModel.cs
- Prevents a save failure when the hosts file is hidden
- Added a unit test for the scenario
Replaced `WriteAllLinesAsync` with `FileStream` + `StreamWriter`.
The code is very similar to what the previous method was doing internally, except for how the `FileStream` is created.
`FileMode.OpenOrCreate` is needed to prevent `UnauthorizedAccessException` when the hosts file is needed.
`WriteAllLinesAsync` internally uses `FileMode.Create` that is causing the issue.
Tested manually.
> [Hosts] Handle hidden hosts file

- .github/actions/spell-check/excludes.txt
- .github/actions/spell-check/expect.txt
- doc/planning/awake.md
- src/modules/awake/Awake/Core/Constants.cs
- src/modules/awake/Awake/Core/Manager.cs
- src/modules/awake/Awake/Core/Models/ProcessBasicInformation.cs
- src/modules/awake/Awake/Core/Native/Bridge.cs
- src/modules/awake/Awake/Core/TrayHelper.cs
- src/modules/awake/Awake/Program.cs
- src/modules/awake/Awake/Properties/Resources.Designer.cs
- src/modules/awake/Awake/Properties/Resources.resx
Fixes:
- PID binding now correctly ignores irrelevant parameters (e.g., expiration, interval) and only works for indefinite periods.
Enhancements:
> Awake - `VISEGRADRELAY_08152024`

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Simply adds mention of my ChatGPTPowerToys plugin in the third-party plugin section
> Update thirdPartyRunPlugins.md to add ChatGPTPowerToys plugin

- src/gpo/assets/en-US/PowerToys.adml
Removes duplicated string ids, unused strings and fixes revision number
> Fix PowerToys.adml for 0.84.0 release

- tools/BugReportTool/BugReportTool/Main.cpp
> [BugReportTool] Omit custom actions data

- README.md
Readme update for the 0.84 release.
> 0.84 changelog

- README.md
> Update installers hashes in README.md

- doc/thirdPartyRunPlugins.md
Minor Typo Correction / Removing extra closing parenthesis from the RDP entry on the list
> Removed extra closing parenthesis from the RDP entry

- src/modules/Workspaces/WorkspacesLib/AppUtils.cpp
Added searching for installed app by name in addition to app path.
Added searching for installed app by name in addition to app path.
> [Workspaces] Fix snapping Discord

- src/settings-ui/Settings.UI/SettingsXAML/OOBE/Views/OobeWorkspaces.xaml
> [Settings] Fix workspaces URI

- src/modules/Workspaces/WorkspacesSnapshotTool/SnapshotUtils.cpp
A follow-up to fix the incorrect process paths for Discord.
> [Workspaces] Discord and Steam fixes - follow up

- src/modules/Workspaces/WorkspacesEditor/MainPage.xaml
- src/modules/Workspaces/WorkspacesEditor/WorkspacesEditorPage.xaml
UI adjustments
changes From 
to
tested locally
> [Workspaces] fix button borders

- README.md
> Update README.md to include 0.84.1 hashes

- .github/policies/resourceManagement.yml
The regex previously used was incorrect, now it is corrected. Also adds support for a couple more phrases.
The regex was validated manually, otherwise nothing.
> Fix RegEx in I would like to contribute bot

- src/settings-ui/Settings.UI/SettingsXAML/Views/NewPlusPage.xaml
- src/settings-ui/Settings.UI/ViewModels/NewPlusViewModel.cs
⚠ This PR will conflict with #35000 if merged later.
---
This PR fixes two things:
- Page crashes if no settings file exists.
- Some controls are disable if module is enabled by policy.
> [New+ > Settings page] Init fix and fix for enabled state of controls

- src/common/utils/gpo.h
This PR...
- fixes wrong policies to use the correct method.
- improves the code order/structure to avoid this mistakes in the future.
> [Enterprise, GPO] gpo.h: Fixes and code order improvements

- tools/BugReportTool/BugReportTool/ReportGPOValues.cpp
Add new policy for enabled state of New+ utility to BugReport tool.
> [BugReport Tool] Add new policy for enabled state of New+ utility

- .pipelines/tsa.json
Quite literally, ship the org chart
> build: fix the TSA configuration

- src/modules/Workspaces/WorkspacesEditor/Models/Application.cs
Adding monitor detection for the case when the monitor setup was changed and the original monitor (when workspace was captured) is not present anymore.
> [Workspaces] add monitor detection

- README.md
Updated unified pipelines broke the badges.  In addition, the release pipelines won't display for non-logged in users.  As PRs show CI failures and we get release pipeline failure emails, we feel there is still proper coverage.
> Removed build status from readme

- src/common/ManagedCommon/Logger.cs
I have noticed that Exception type are lost when logged using the C# Common Logger.
- Log type for Exception and InnerException
- Removed the empty line if InnerException is null
_main_
```
[20:53:30.2160042] [Error] <LoadPreviewAsync>d__13::MoveNext
UnsupportedFilePreviewer error.
Access to the path 'C:\Windows\CSC' is denied.
Inner exception: 
Stack trace: 
at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
...
```
_PR_
```
[22:11:17.6777067] [Error] <LoadPreviewAsync>d__13::MoveNext
UnsupportedFilePreviewer error.
System.UnauthorizedAccessException: Access to the path 'C:\Windows\CSC' is denied.
Stack trace: 
at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, …
```
> [Chore] Common Logger: Log missing Exception type

- .github/actions/spell-check/expect.txt
- DATA_AND_PRIVACY.md
> Adding in our "Data and Privacy" documentation

- README.md
Readme update for the 0.86 release.
> 0.86 changelog

- .github/actions/spell-check/allow/names.txt
This PR removes duplicate entries from SpellCheck's allowed names list.
> SpellCheck > Allowed names: Remove duplicates 

- CONTRIBUTING.md
Streamlined language, clarified sections, and enhanced instructions for a more concise, user-friendly contributor guide.
1. **Headings for Clarity**:
- Created a clearer heading for the “Filing an Issue” section to emphasize its importance.
- Changed "How to Tell the PowerToys Team This is an Interesting Thing to Focus On" to “Indicating Interest in Issues” for conciseness.
2. **Revised Filing Instructions**:
- Broke down filing instructions into concise, actionable points.
- Clarified when and why users should file issues and conduct a quick search before filing.
3. **Simplified "Contributing Fixes/Features" Section**:
- Added clear instructions to comment on interest before starting work.
- Reworded to avoid redundancy, especially around the team’s guidance and multiple contributors.
4. …
> Simplify language and structure for clarity and ease of use.

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Add [Bilibili](https://github.com/Whuihuan/PowerToysRun-Bilibili) to Third-Party plugins
> [PTRun][Docs] Add Bilibili to Third-Party plugins

- Directory.Packages.props
- NOTICE.md
- src/modules/MeasureTool/MeasureToolCore/PowerToys.MeasureToolCore.vcxproj
- src/modules/MeasureTool/MeasureToolCore/packages.config
- src/modules/powerrename/PowerRenameUILib/PowerRenameUI.vcxproj
- src/modules/powerrename/PowerRenameUILib/PowerRenameUI.vcxproj.filters
- src/modules/powerrename/PowerRenameUILib/packages.config
Upgrade Windows App SDK to the latest version
Upgraded WindowsAppSDK to [the latest stable version 1.6.3](https://github.com/microsoft/WindowsAppSDK/releases/tag/v1.6.3)
Manually validated.
> Upgrade Windows App SDK to the latest version

- PowerToys.sln
- src/Common.Dotnet.AotCompatibility.props
This pull request introduces a set of MSBuild props for AOT compatibility validation, which projects can import once they are fully AOT-compatible.
AOT Compatibility Check: The props file enables AOT compatibility checks in projects, ensuring that only AOT-supported code is included. This prevents non-AOT code from being added once AOT support is fully implemented. The props are specifically designed for projects that will eventually support AOT.
No AOT Publish Enabled Yet: Currently, the AOT publish functionality is not enabled. The focus is on performing AOT compatibility checks for now, and the actual AOT publishing will be activated once all required AOT configurations are in place.
> [AOT compatible] Add Common MSBuild Props for AOT Compatibility Validation to Be Imported by Projects for Future AOT Support

- src/common/interop/keyboard_layout.cpp
Add IME on and IME off to Keyboard Manager.
> [Keyboard Manager] Add IME On, IME Off

- .github/actions/spell-check/allow/names.txt
- COMMUNITY.md
Adding in new friends and amazing community members to the `COMMUNITY.md` file.
> adding in new friends and amazing community members

- COMMUNITY.md
> Adding Jerry to community.md

- COMMUNITY.md
Shifting to different user name
> Adjust to community.md, shifting jerry's github user name

- src/settings-ui/Settings.UI/SettingsXAML/Views/AdvancedPaste.xaml
Fixed issue #34470 
Fixed the issue by making the `ContentDialog` scrollable. 
Manually tested the fix by opening the advanced paste config page.
> [Bug fix] Making the OpenAI key configuration page scrollable.

- .github/actions/spell-check/allow/names.txt
- COMMUNITY.md
Add more STCA team members as contributors.
Update both Community.md and names.txt accordingly.
Manually validating the updated community.md file.
> Add more STCA team members

- .github/actions/spell-check/allow/names.txt
- COMMUNITY.md
Add team member as contributors.
Update both Community.md and names.txt accordingly.
Manually validating the updated community.md file.
> Add team member

- src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest/QueryTests.cs
Fixes a bug with incorrect interpretation of the decimal separator in the unit tests of Calculator plugin.
Run unit tests on my system with German culture and format settings.
> [PT Run > Calculator] Fix unit tests on non-englisch systems

- COMMUNITY.md
You are forever part of the team 😢
Connor, Ethan, and Jordi, you all were serious the best.
> Goodbye friends, you are forever part of the team

- README.md
Just a tiny fix to the version number in the What's Planned section header.
> Update README.md - update What's Planned to 0.89

- .pipelines/v2/release.yml
- .pipelines/v2/templates/steps-esrp-signing.yml
This is in support of some identity changes we need to make.
> build: add a couple more signing variables to ESRP

- doc/devdocs/settingsv2/runner-ipc.md
Fix broken file links, reflecting change in directory structure.
> [Docs] Update runner-ipc.md to fix broken links

- src/settings-ui/Settings.UI/SettingsXAML/Views/ShellPage.xaml
- src/settings-ui/Settings.UI/ViewModels/DashboardViewModel.cs
ZoomIt won't be "new" in 0.89, so we should remove the labels :)
> Remove "new" label from ZoomIt

- src/modules/Workspaces/WorkspacesCsharpLibrary/Models/BaseApplication.cs
For packaged app, workspaces could no draw the icon. That's because of the mismatch for packaged app path.
Local test:
Before fix 
| ![image](https://github.com/user-attachments/assets/d1ab3781-1b91-4f9a-b6fd-0f556ba0bee5) | 
After fix
> [Workspaces][ARM64] Bring icon to packaged apps

- README.md
Readme update for the 0.89 release.
> 0.89 changelog

- .github/actions/spell-check/allow/code.txt
- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
A new PowerToys Run third-party plugin to search, browse & copy SVG logos via svgl..
Closes: #36788
> [PTRun][Docs] Add SVGL to Third-Party plugins

- Directory.Packages.props
- NOTICE.md
- src/Common.Dotnet.CsWinRT.props
- src/modules/MeasureTool/MeasureToolCore/PowerToys.MeasureToolCore.vcxproj
- src/modules/MeasureTool/MeasureToolCore/packages.config
- src/modules/powerrename/PowerRenameUILib/PowerRenameUI.vcxproj
- src/modules/powerrename/PowerRenameUILib/packages.config
- Upgrade Windows App SDK to 1.6.250205002
- Upgrade CsWinRT to 2.2.0
- Upgrade WindowsSdkPackageVersion to 10.0.22621.57 so it uses the same WinRT dll versions as CsWinRT 2.2.0
Built a Dart build and did a sanity check.
> [Deps]Upgrade Windows App SDK to 1.6.250205002 and CsWinRT to 2.2.0

- NOTICE.md
Looks like this was missed, adding in
> Adding in monaco usage for Reg preview

- src/modules/cmdpal/.editorconfig
Related to https://github.com/microsoft/PowerToys/pull/37908
> [cmdpal] Bring back editorconfig

- src/settings-ui/Settings.UI/SettingsXAML/Views/ShellPage.xaml
- src/settings-ui/Settings.UI/ViewModels/DashboardViewModel.cs
Add the "New" badge to Command Palette:
Ran Settings and verified the badge was there.
> [Settings]Add the New badge to CmdPal

- NOTICE.md
This PR corrects the structure of Notice.md and adds the new utility to the list at the top of the file.
> Fix NOTICE.md

- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/ExtensionPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/GeneralPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/SettingsWindow.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Strings/en-us/Resources.resw
- tools/FancyZone_HitTest/FancyZone_HitTest/App.xaml
- tools/FancyZone_HitTest/FancyZone_HitTest/MainWindow.xaml
> Localize CmdPal settings page

- src/settings-ui/Settings.UI/SettingsXAML/OOBE/Views/OobeCmdPal.xaml
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
This is the OOBE text I got from @cinnamon-msft.
I actually apparently can't built the Settings.UI project locally, so I'm gonna need to tap someone in to sanity check this
> Update the OOBE text for CmdPal

- src/common/interop/shared_constants.h
- src/modules/cmdpal/CmdPalModuleInterface/dllmain.cpp
- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Events/BeginInvoke.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Events/CmdPalDismissedOnEsc.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Events/CmdPalDismissedOnLostFocus.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Events/CmdPalHotkeySummoned.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Events/CmdPalInvokeResult.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Events/CmdPalProcessStarted.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Events/ColdLaunch.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Events/OpenPage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Events/ReactivateInstance.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Program.cs
Related to https://github.com/microsoft/PowerToys/pull/37908
Closes https://github.com/zadjii-msft/PowerToys/issues/520
> [cmdpal] WIP add telemetry

- src/settings-ui/Settings.UI/SettingsXAML/OOBE/Views/OobeCmdPal.xaml
- src/settings-ui/Settings.UI/SettingsXAML/OOBE/Views/OobeCmdPal.xaml.cs
- src/settings-ui/Settings.UI/Strings/en-us/Resources.resw
Update OOBE's CmdPal page to show the actual hotkey and style it similar to other OOBE pages.
Open OOBE and verify it looks like other OOBE pages.
> [OOBE]Show actual CmdPal hotkey

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Indexer/Commands/CopyPathCommand.cs
The original code not work. It will throw com exception. 
I prefre to use ClipboardHelper one.
> [cmdpal] Fix "copy file path" function in file search extension 

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Registry/Properties/Resources.Designer.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Registry/Properties/Resources.resx
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Registry/RegistryCommandsProvider.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsServices/Properties/Resources.Designer.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsServices/Properties/Resources.resx
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsServices/WindowsServicesCommandsProvider.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsSettings/Properties/Resources.Designer.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsSettings/Properties/Resources.resx
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsSettings/WindowsSettingsCommandsProvider.cs
Fix some i18n issues for built-int extensions.
> [cmdpal] Fix some i18n issues for built-in extensions

- src/common/utils/package.h
> [installer] Fix packages removal for per-user installer

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/SettingsWindowClosedMessage.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/SettingsWindow.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/SettingsWindow.xaml.cs
Make settings window single.
Manual test.
- Open settings windows multiple times
- Activate minimized settings window
> [CmdPal] Single settings window

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Pages/ShellPage.xaml.cs
Calling Win32 APIs from C# is usually easy! but mixing C#+WinRT+COM is dark and full of terrors
Closes https://github.com/zadjii-msft/PowerToys/issues/546
> Pass FG rights to extensions when we access them

- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsServices/Helpers/ServiceHelper.cs
- src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsServices/Properties/Resources.resx
https://github.com/microsoft/PowerToys/issues/38137
> [CmdPal] Windows Services restart kb shortcuts

- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml
Attempt to fix `Layout cycle detected. Layout could not complete` exception when CmdPal is moved on a screen with different DPI.
I can repro almost 100% and no longer occurs after switching tags `ItemsView` with `ItemsControl`.
Doesn't seem to break visual and don't expect a huge number of tags so use an `ItemsControl` shouldn't be a problem.
> [CmdPal] Fix Layout cycle detected. Layout could not complete

- .github/ISSUE_TEMPLATE/bug_report.yml
> [CmdPlt] [Bug template] Update issue template for command palette

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/ExtViews/ListPage.xaml.cs
Fix #38337 and implement continuous navigation like PT Run v1
> [CmdPal] Fix Up/Down keyboard navigation + continuous navigation

- COMMUNITY.md
Pedro is a community member that was the core for the 3d file support.
> Adding Pedro for his hard 3D file work

- .github/ISSUE_TEMPLATE/bug_report.yml
I'm finding multiple issues being filed recently with "v0.70.0" as the version number, even though they are reporting having a newer version later in the description.
I'm changing the placeholder to reduce confusion that we're on v0.70.
> Update version placeholder in bug_report.yml

- README.md
> Adding in Hawker for CmdPal to Readme

- doc/devdocs/UITests.md
Add a missing period, replacing some trailing whitespace
> doc/devdocs/UITests.md: add missing period [skip ci]

- installer/PowerToysSetup/CmdPal.wxs
- src/common/utils/package.h
- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
https://microsoft.visualstudio.com/Dart/_build/results?buildId=119948804&view=results
Here is the installer artifacts for testing
> [CmdPal] [Install]do not install dependency if already satisfied.

- src/modules/keyboardmanager/KeyboardManagerEditorLibraryWrapper/KeyboardManagerEditorLibraryWrapper.cpp
- src/modules/keyboardmanager/KeyboardManagerEditorLibraryWrapper/KeyboardManagerEditorLibraryWrapper.h
- src/modules/keyboardmanager/KeyboardManagerEditorUI/App.xaml.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Helpers/EditorConstants.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Helpers/Remapping.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Interop/KeyboardManagerInterop.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Interop/KeyboardMappingService.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/KeyboardManagerEditorUI.csproj
- src/modules/keyboardmanager/KeyboardManagerEditorUI/MainWindow.xaml
- src/modules/keyboardmanager/KeyboardManagerEditorUI/MainWindow.xaml.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Pages/Programs.xaml
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Pages/Remappings.xaml
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Pages/Remappings.xaml.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Pages/Shortcuts.xaml.cs
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Pages/Text.xaml
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Pages/URLs.xaml
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Styles/InputControl.xaml
- src/modules/keyboardmanager/KeyboardManagerEditorUI/Styles/InputControl.xaml.cs
- Merge the new WinUI3 Keyboard Manager UX change into the **feature branch**.
- Implement Keyboard hook to get the user input of remappings.
- Make the Disable toggle button functional in shortcuts remapping page.
- Aggregate all constants into one central place.
- Update Key Remapping naming.
- Fix the key visual stretch out issue when the shortcut contains too many keys.
- Implement Reset for InputControl to make sure InputControl can have correct status for various dialog.
Current UX:
**_(Under discussion to change to delete button)_**
> [Keyboard Manager] Functional Improvements on new KBM UX

- .github/actions/spell-check/expect.txt
- COMMUNITY.md
Add our PM, Zhiwei, to Powertoys
> Add Zhiwei as part of PowerToys!

- Directory.Packages.props
- NOTICE.md
- src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
- src/settings-ui/Settings.UI/PowerToys.Settings.csproj
Getting some of the dependencies updated and newer.  This is just testing framework items
> Upgrading some of the Testing framework items

- src/modules/powerrename/PowerRenameUILib/PowerRenameUI.vcxproj
- src/modules/powerrename/PowerRenameUILib/packages.config
- src/modules/powerrename/dll/PowerRenameExt.vcxproj
- src/modules/powerrename/dll/packages.config
- src/modules/powerrename/lib/PowerRenameLib.vcxproj
- src/modules/powerrename/lib/packages.config
- src/modules/powerrename/testapp/PowerRenameTest.vcxproj
- src/modules/powerrename/testapp/packages.config
- src/modules/powerrename/unittests/PowerRenameLibUnitTests.vcxproj
- src/modules/powerrename/unittests/packages.config
> Upgrading Boost dependencies

- src/modules/poweraccent/PowerAccentKeyboardService/KeyboardListener.cpp
Fix on-screen keyboard activation of QuickAccent.
Refer to repro steps in the linked issue.
Manually tested using physical/on-screen keyboard and space/arrows activation.
> [QuickAccent] Fix on-screen keyboard activation

- .github/actions/spell-check/allow/names.txt
- doc/thirdPartyRunPlugins.md
Added Powertoys for Linear plugin
[powertoys-linear](https://github.com/vednig/powertoys-linear
)
> Powertoys for Linear plugin added

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ContentFormViewModel.cs
Card = AdaptiveCard.FromJsonString(cardJson) is called in catch block, if it fails, app will crash.
> [cmdpal] protect cmdpal from crash if adaptive card fails

- src/settings-ui/Settings.UI/SettingsXAML/Views/CmdPalPage.xaml.cs
> Fix settings crash issue when clicking "Open Cmdpal settings..."

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsModel.cs
> [cmdpal] Disable "ignore shortcut when full screen" by default

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandBarViewModel.cs
> [cmdpal] Fix winget cannot install after clicking "install" button issue

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WinGet/Pages/InstallPackageCommand.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WinGet/Pages/InstallPackageListItem.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WinGet/Pages/WinGetExtensionPage.cs
> [cmdpal] Add some logs for WinGet extension

- .pipelines/loc/loc.yml
- .pipelines/v2/templates/steps-fetch-and-prepare-localizations.yml
> Move to TouchdownBuild task v5

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/NewExtensionForm.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Properties/Resources.Designer.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Properties/Resources.resx
The Command Palette allows users to create extensions with dashes in their names, which is invalid for C# namespaces. This causes projects to fail during build because the name cannot be used as a valid namespace.
- Updated the validation regex in `NewExtensionForm.cs` to only allow valid C# identifiers
- Now only allows names starting with a letter or underscore, followed by letters, numbers, or underscores
- Explicitly prevents dashes, spaces, and other special characters
- Improved the error message to clearly explain the requirements for valid C# identifiers
Previously, the input only validated that no spaces were used:
```csharp
"regex": "^[^\\s]+$"
```
Now the input properly validates for C# namespace compatibility:
```csharp
"regex": "^[a-zA-Z_][a-zA-Z0-9_]*$"
```
This ensures that …
> Validate names for invalid for C# namespaces in cmdpal

- README.md
Updated the links in the README to reflect release 0.91.1
Previewed README and confirmed links are correct
> Update README with 0.91.1

- src/common/UITestAutomation/Doc/ui-automation-cover-list.md
- src/modules/MouseUtils/MouseUtils.UITests/FindMyMouseTests.cs
- src/modules/MouseUtils/MouseUtils.UITests/MouseHighlighterTests.cs
- src/modules/MouseUtils/MouseUtils.UITests/MouseJumpTests.cs
- src/modules/MouseUtils/MouseUtils.UITests/MousePointerCrosshairsTests.cs
> Update MouseUtils UI test doc

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Calc/Helper/CalculateHelper.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Calc/Helper/QueryHelper.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Calc/Properties/Resources.Designer.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Calc/Properties/Resources.resx
A simple fix. 
The original logic was migrated from PT run and is not suitable for cmdpal.
> [cmdpal] Fix calculator error when pressing Space

- .github/actions/spell-check/expect.txt
- src/common/UITestAutomation/Doc/ui-automation-cover-list.md
- src/common/UITestAutomation/VisualAssert.cs
- src/common/UITestAutomation/VisualHelper.cs
- src/modules/Hosts/Hosts.UITests/HostModuleTests.cs
- src/modules/MouseUtils/MouseUtils.UITests/Release-Test-Checklist-Migration-Progress.md
This pull request focuses on correcting typographical errors and improving clarity in the documentation and comments within the `src/common/UITestAutomation` directory. These changes enhance readability and ensure consistency across the documentation.
* Fixed multiple instances of misspelled words such as "trhough" to "through," "aplied" to "applied," and "coppied" to "copied" in `ui-automation-cover-list.md`. [[1]](diffhunk://#diff-54c8236ca8d09eccf3afd2d50043d0c33d069856b00bee526662f58f9c3f18c8L25-R28) [[2]](diffhunk://#diff-54c8236ca8d09eccf3afd2d50043d0c33d069856b00bee526662f58f9c3f18c8L875-R875) [[3]](diffhunk://#diff-54c8236ca8d09eccf3afd2d50043d0c33d069856b00bee526662f58f9c3f18c8L932-R947)
* Corrected the spelling of "whilw" to "while" in the description of a test scenario.
* …
> Fix spell error

- src/modules/cmdpal/README.md
Minor typo it's -> its
README-only change
n/a
> cmdpal README: minor typo

- src/modules/AdvancedPaste/AdvancedPaste/Strings/en-us/Resources.resw
This PR mainly add comments in src/modules/AdvancedPaste/AdvancedPaste/Strings/en-us/Resources.resw to solve issues raised by localization team.
> [Localization] Add comments in Resources.resw

- src/runner/auto_start_helper.cpp
Add log when error happen in setting startup 
Set error in code deliberately, and verify that the error appears in the log.
> Runner: Add log when error happen in setting startup 

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Indexer/Indexer/DataSourceManager.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Indexer/Indexer/Utils/QueryStringBuilder.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WindowWalker/Helpers/VirtualDesktopHelper.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WindowsTerminal/Commands/LaunchProfileAsAdminCommand.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WindowsTerminal/Commands/LaunchProfileCommand.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WindowsTerminal/Helpers/NativeHelpers.cs
We need to release it manually.
> Release ptr which get from CoCreateInstance to prevent memory leak

- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.ClipboardHistory/Helpers/ClipboardHelper.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.ClipboardHistory/Helpers/ClipboardThreadScheduler.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.ClipboardHistory/Helpers/NativeMethods.cs
Due to some windows sdk bugs, we can not use those API in main thread.
So, create a separate thread for clipboard.
history:
success to paste to chat:
> [cmdpal] Re-enable Clipboard History extention

- .github/actions/spell-check/allow/names.txt
- COMMUNITY.md
Adding Jessica and Michael to community.md
demoting myself to overhead :)
> Welcome new friends, Michael, Jessica, Gleb, Zachary, and Jaylyn

- src/modules/cmdpal/README.md
Fix links to sample folders.
Two links were broken in the Command Palette readme because of a folder name being "Exts" instead of "ext".
N/A
Manually confirmed the following links are correct:
https://github.com/microsoft/PowerToys/tree/main/src/modules/cmdpal/ext/SamplePagesExtension
https://github.com/microsoft/PowerToys/tree/main/src/modules/cmdpal/ext/ProcessMonitorExtension
> Command Palette: fix sample links in README.md

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/ExtensionPage.xaml
- src/modules/cmdpal/Microsoft.CmdPal.UI/Strings/en-us/Resources.resw
Fixes alias settings and add localization for Direct/Indirect.
> [CmdPal] Fix and localize alias settings

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WebSearch/Helpers/DefaultBrowserInfo.cs
- src/modules/launcher/Wox.Plugin/Common/DefaultBrowserInfo.cs
This actually fixes an issue with #39794. What I failed to mention in the original issue was the additional path under the registry that the new key is located under. Instead of the key being stored directly in `UserChoiceLatest` in a key named `ProgId`, the path also includes a second `ProgId` as well. 
Copilot tried to fix this issue in #40035, but because I had failed to mention the additional `ProgId` in the path, it was not included in Copilot's fix. 
Therefore, the true new path is 
`.../UserChoiceLatest/ProgId`
> Fix default browser detection for Windows 11 24H2 by checking UserChoiceLatest\ProgId registry key

- src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
Base on this discussion: https://github.com/microsoft/PowerToys/pull/39800
Currently, Flush still have some problem to use it. So, we need to consider to disbale it.
> [cmdpal] Disable clipboard history extension

- src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
> cmdpal: turn on condition package for cmdpal

- src/modules/cmdpal/ext/SamplePagesExtension/Program.cs
Fixed a simple English grammar error in SamplePagesExtension in CmdPal.
> [CmdPal] Fix correct comment typo in SamplePagesExtension

- installer/PowerToysSetupVNext/Directory.Build.props
- installer/PowerToysSetupVNext/PowerToysBootstrapperVNext.wixproj
- installer/PowerToysSetupVNext/PowerToysInstallerVNext.wixproj
> Fix wix build

- README.md
Simply updates the install links in the README.
- **Closes:** N/A
- **Communication:** This is a very minor change, for which communication would only waste time, even if the work is rejected. Communication is therefore unnecessary.
- **Tests:** None needed.
- **Dev docs:** No updates needed.
- **New binaries:** None needed
- [JSON for signing](https://github.com/microsoft/PowerToys/blob/main/.pipelines/ESRPSigning_core.json) for new binaries: not part of program
- [WXS for installer](https://github.com/microsoft/PowerToys/blob/main/installer/PowerToysSetup/Product.wxs) for new binaries and localization folder: Not part of program
- [YML for CI pipeline](https://github.com/microsoft/PowerToys/blob/main/.pipelines/ci/templates/build-powertoys-steps.yml) for new test projects: No tests …
> Update README links and labels for 0.92.1

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.WebSearch/Pages/WebSearchListPage.cs
Display full page message when the Web Search extension page is empty
--
Tested with and without enabled history.
> Use Empty content for empty Web search page

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/AppCache.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/UWP.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Storage/PackageRepository.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Storage/Win32ProgramRepository.cs
#40100 OP is hitting an `AggregateException`.
This PR aim to improve error handling and logging.
It also remove some dead code 😄
> [CmdPal][App] Handle app indexing errors

- src/modules/cmdpal/Microsoft.CmdPal.UI/Strings/en-us/Resources.resw
The tooltip for the "Back" button has been modified to include the keyboard shortcut "Back (Alt + Left arrow)" instead of the previous text "Back".
> CmdPal: Update Back button tooltip with shortcut information

- src/modules/cmdpal/Microsoft.CmdPal.UITests/BasicTests.cs
- src/modules/cmdpal/Microsoft.CmdPal.UITests/CommandPaletteTestBase.cs
- src/modules/cmdpal/Microsoft.CmdPal.UITests/IndexerTests.cs
1. Add some test cases to cover indexer extension's ability.
2. Add CommandPaletteTestBase class to make us can easily implement test case.
> [CmdPal][UI Tests] Add some indexer extension's test cases

- src/modules/cmdpal/README.md
Added more instructions to first time building command palette
- [X ] **Dev docs:** Added/updated
> More instructions to build CmdPal

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/Converters/ContextItemTemplateSelector.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI/rd.xml
Cherry-pick of 782ee47. That is probably over-aggressive, but it fixes it. 
Closes  #40633
previously: #40744
> CmdPal: try to fix the context menu crash, again.

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Models/ExtensionService.cs
Ensure that errors encountered while sending the extension disposal signal are handled gracefully. If an error occurs when disposing of a particular extension, continue signaling the remaining extensions rather than halting the entire process. This prevents a single failure from interrupting the disposal chain and improves overall robustness.
> CmdPal: Add error handling to extension disposal

- src/modules/cmdpal/Microsoft.CmdPal.Core.ViewModels/CommandItemViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.Core.ViewModels/ContentPageViewModel.cs
- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelViewModel.cs
Closes #40822
These are not the classes you are looking for.
Issue was we were comparing to classes rather than interfaces and WinRT no likey.
> Fixed issue with primary/secondary commands

- Directory.Packages.props
- NOTICE.md
- doc/devdocs/core/installer.md
> [Installer] Update installer related markdown

- src/modules/cmdpal/Microsoft.CmdPal.UI/Helpers/WindowExtensions.cs
> CmdPal: Update a code comment using a wrong member name [nit]

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Shell/FallbackExecuteItem.cs
Love that we have now environment variables expanding! 🚀 
Porting also few small features I implemented in Run Folder plugin a long time ago and I love:
- https://github.com/microsoft/PowerToys/pull/7711
- https://github.com/microsoft/PowerToys/pull/9579
Threat `/` and `\` as root of system drive (typically `C:\`)
Threat `~` as user home directory `%USERPROFILE%`
- Tested search starting with `~` `/` `\`
- Tested UNC network path starting with `\\...` and `//...`
> [CmdPal] Search PATH starting with ~ / \

- src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ContextMenu.xaml
Replace the brush used for the menu item separator in SeparatorContextMenuViewModelTemplate with the brush used by WinUI 3 for flyout menus.
The brush previously used is a legacy brush and a WinUI trap.
After screenshot:
> CmdPal: Replace the brush used for the menu item separator

- src/modules/cmdpal/Microsoft.CmdPal.Core.ViewModels/ListViewModel.cs
This just adds a simple `CancellationToken` around `ListViewModel.FetchItems()`. Now, when we start a second `FetchItems` (in responce to a `RaiseItemsChanged`), we'll cancel the old one first. That'll prevent a particularly long first `GetItems` call from returning after a second one has already set the list.
Closes #41149
No longer repros the evil sample from #41158
> CmdPal: cancel fetching new items when we get another one

- src/modules/previewpane/BgcodePreviewHandler/Program.cs
- src/modules/previewpane/powerpreview/CLSID.h
- tools/BugReportTool/BugReportTool/RegistryUtils.cpp
This is a follow up on #38667 and specifically addresses some of the comments that GitHub Copilot review pointed out.
(Manual validation only)
> Fixes bgcode handlers registration

- src/modules/alwaysontop/AlwaysOnTop/WindowBorder.cpp
This PR resolves an issue where the wait cursor was incorrectly displayed when the mouse hovered over the Always On Top window border.
_0.92.1_
_PR_
> [Always On Top] Wait cursor fix

- tools/BugReportTool/BugReportTool/ProcessesList.cpp
Adds `Microsoft.CmdPal.UI.exe` to the list of processes, so Bug Report Tool can pick Applications Logs for it when generating its report.
> CmdPal | Bug Report Tool: Allow collection of Command Palette events from Windows Event Logs by Bug Report Tool

- src/modules/cmdpal/custom.props
> CmdPal: Bump version to 0.5

- src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/AppStateModel.cs
Ensures the new state is saved even if the previous one is corrupted, which is then ignored. Improves error handling and code clarity in `AppStateModel`. Replaces Debug sink logging with structured Logger.
> CmdPal: Handle corrupted app state file when saving new state

- src/common/ManagedCommon/Logger.cs
Enhances `Logger.LogError` to log the exception HRESULT in addition to the exception type and message, improving traceability and debugging efficiency. For ~bug~ fun and profit!
> CmdPal: Make LogError include HRESULT in the log

- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/SettingsWindow.xaml
Fixes margin of the breadcrumb control in the Settings window:
> CmdPal: Fix breadcrumb misalignment in Settings window [nit]

- src/modules/cmdpal/Microsoft.CmdPal.Common/Helpers/WellKnownKeyChords.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/AppListItem.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/KeyChords.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Microsoft.CmdPal.Ext.Apps.csproj
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/UWPApplication.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Apps/Programs/Win32Program.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Indexer/Data/IndexerListItem.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Indexer/KeyChords.cs
Adds keyboard shortcuts to `IndexerListItem` commands to mirror those in **All Apps**.  
- Introduces a new `KeyChords` class that defines and manages key chords for all actions within individual projects, improving code organization and maintainability (similar to the `Icons` class).  
- Adds a `WellKnownKeyChords` class in the shared project that defines common shortcuts to be used consistently across the entire app.  
- Updates `IndexerListItem` to include new command context items with `RequestedShortcut` properties for:  
- Show in folder (`Ctrl+Shift+E`)  
- Copy path (`Ctrl+Shift+C`)  
- Open path in console (`Ctrl+Shift+R`)  
- Updates `AppListItem`, `UWPApplication`, and `Win32Program` to use the new key chord properties from the `KeyChords` class, ensuring consistency and …
> CmdPal: Add keyboard shortcuts to items in File Search extension

- .pipelines/v2/templates/job-build-project.yml
Fix spelling complain
Spell should pass without error
> Fix a CI forbidden pattern fallback to

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Indexer/Pages/IndexerPage.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Indexer/Properties/Resources.Designer.cs
- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.Indexer/Properties/Resources.resx
This PR improves the user experience when no indexed files match the query in the File Search extension.
- Show a hint on the empty results page when no indexed files are found.
- Provide fallback actions:
- Search entire PC – opens  new File Explorer window with the query searched in This PC.
- Open Windows Search settings – navigates to Windows Search settings to review indexed locations.
> CmdPal: Add actionable hint to empty results in File Search extension

- src/modules/cmdpal/Microsoft.CmdPal.UI/Settings/SettingsWindow.xaml.cs
> CmdPal: Fix NavView merge

- src/modules/cmdpal/ext/Microsoft.CmdPal.Ext.ClipboardHistory/Properties/Resources.Designer.cs
This PR adds changes missing from #42115 - RESX designer file wasn't changed to matched updated RESX (blame Skynet).
> CmdPal: Sync a RESX designer file with its RESX

- Directory.Packages.props
- src/settings-ui/Settings.UI/SettingsXAML/OOBE/Views/OobeWhatsNew.xaml
Bumping MarkdownTextBlock to `0.1.251002-build.2316` that includes the fix for this crashing bug.
cc @jiripolasek it seems to work?
> MarkdownTextBlock crash fix
