README.md
Just a few typos I noticed while reading through the ReadMe.
=> fix a couple typos

src/editor/main.cpp
WebView swallows key-events. Detect Alt-F4 one and close the window manually.
Manual
=> Make Alt-F4 always close the settings window

src/common/common.cpp, src/common/common.h, src/editor/main.cpp
This PR fixes the blank Settings window when the PowerToysSettings.exe is running elevated.
Improved error handling for the WebView control initialization.
At startup, checks if PowerToysSettings.exe is running elevated and in that case drop the access token admin privileges.
If a fatal error occur during the WebView initialization, shows an error message instead of showing a blank window.
Code refactoring for easier integration of the upcoming WebView2 support.
Fix some warnings.
Coding style.
**Note for the reviewers**: I made several small commits to isolate the important changes from the code refactoring/variables and functions renaming.
Manual test.
=> WebView fixes

src/runner/general_settings.cpp
The call to `load_general_settings` will throw an exception if the `settings.json` file for the general settings is not present. This leaves `settings_theme` variable uninitialized, resulting in no value selected in the general settings screen for users that did not make any changes to the general settings. This fixes this issue by initializing the value with a "system" default value.
Manual. Delete `%LOCALAPPDATA%\Microsoft\PowerToys\settings.json` to reproduce the issue without the fix.
=> Settings: fix default theme selected option

.github/pull_request_template.md
When merging a PR is preferable to not auto-close the referenced issue(s).
Instead, manually mark them as `resolved` and close them only after a release that contains the fix has been published.
Also removed the white-space for the `Checklist` check-boxes.
=> Don't auto close issues referenced in PR

src/runner/lowlevel_keyboard_event.cpp
I've experienced severe system-wide keyboard input lagging when debugging a `runner` process caused by `SetWindowsHookEx`. 
This PR allows to safely and easily toggling it in a debug environment.
=> Add switch to turn off keyboard hooks while debugging

src/common/on_thread_executor.cpp, src/common/on_thread_executor.h
- `_active` wasn't initialized, so sometimes `OnThreadExecutor` thread could exit instantly.
- renamed `_active` to `_shutdown_request` to clarify its purpose 
Launched the app multiple times both in debug and release configurations
=> initialize all OnThreadExecutor fields and clarify intent further

src/common/settings_objects.h
This makes the Hotkey settings object ignore the key value stored in JSON. Instead, it will be deduced from the current keyboard layout and the vk_code.
Manual
=> FancyZones settings: show proper hotkey even when wrong key was saved before

src/runner/tray_icon.cpp
`Shell_NotifyIcon` can fail when we invoke it during the time explorer.exe isn't present/ready to handle it. We'll also never receive `wm_taskbar_restart message` if the first call to `Shell_NotifyIcon` failed, so that changes reacts to `WM_WINDOWPOSCHANGING` which is always received on explorer startup sequence.
Launched PowerToys while there's/isn't explorer.exe present, restarted explorer.exe
=> Fix lack of tray icon #268 by handling initial Shell_NotifyIcon failure

src/common/common.cpp, src/common/common.h, src/runner/settings_window.cpp
When a non-admin user runs PowerToys as Adminstrator, the runner fails to start the Settings app.
https://github.com/microsoft/PowerToys/pull/884
Instead of just failing, if the runner can't get the Settings to run non-elevated, run it elevated and let the Settings handle that.
This is part one of the fix since the current way way of dropping elevated privileges in the Settings process doesn't work in this scenario. We'll make those changes in a different PR.
This change also applies to the changes made by https://github.com/microsoft/PowerToys/pull/884 since it simplify the way the Settings are executed when the runner is not running elevated.
=> Run Powertoys as administrator (part one)

src/common/hwnd_data_cache.cpp
This filters out TaskView and Win32 menus.
Manual using PaswordSafe, 1Password, TortoiseSVN, GOG Galaxy beta, GlassWire, VS Code and Battle.net launcher
=> FancyZones: filter out WM_POPUP windows if they dont have maximize/minimize button or a resizable frame

README.md
The Windows Store was renamed to the Microsoft Store back in 2017, best to keep things up-to-date to avoid potential confusion.
=> Change Windows Store to Microsoft Store in README

.pipelines/pipeline.user.windows.yml
Make sure BinSkim will not run on WiX binaries for current and future versions.
=> Update BinSkim exclude list

src/modules/powerrename/dll/dllmain.cpp
pClassFactory is always created as per the "new" statement in C++. Why are we checking for the object then?
Removed unneeded check
Manual
Automated
=> Remove unused check for pClassFactory

src/modules/windowwalker/app/Window Walker/Window Walker.csproj, src/modules/windowwalker/app/Window Walker/packages.config
Does what the title says, really. This was the last C# project that still used `packages.config`. The remaining users of this file are all C++ projects (which don't support PackageReference), and the WiX custom action project (which I understand is deprecated and will be removed soon).
Built and ran WindowWalker, program launches and is functional.
=> Switch WindowWalker C# project to use PackageReference

src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj, src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/GeneralViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml
Created a proof of concept General settings tab page with XAML layout. Fontsizes, margins and paddings are a 1:1 copy of the official Windows 10 settings app.
=> Added a General tab page with XAML layout and controls according to spec

.pipelines/ci/templates/build-powertoys-steps.yml
Disable CI unit tests due to continue failures in CI for no apparent reason.
We will re-enable once we have figured out what is causing the problem.
=> disable unit tests in CI

src/runner/main.cpp
This enables the Window Walker app (Alt-tab alternative) within Power Toys.
* ~~Tests added/passed~~
* ~~Requires documentation to be updated~~
Compiled locally and verified that Window Walker actually launches. Disabled it from settings and verified that it doesn't run. Enabled again and verified that it runs again.
=> Add Window Walker to module list

src/common/json.cpp
Enables serializing utf8 characters to file. This was not working before out of the box and was ending up with messing with both temporary json files (causing Editor to crash) and zones-settings.json file.
=> Enable non-ascii chars

src/runner/general_settings.h, src/runner/pch.h, src/runner/powertoy_module.cpp, src/runner/powertoy_module.h
Order of PowerToys was random in both Settings list and in General Settings enable's list. Now it's in alphabetical order.
* [] Applies to #1687 
Before:
Now:
=> Order PowerToys aplhabetically Settings

src/common/msi_to_msix_upgrade_lib/msi_to_msix_upgrade_lib.vcxproj, src/common/msi_to_msix_upgrade_lib/pch.h, src/common/notifications_winrt/BackgroundHandler.idl
- fix idl warning in notifications (interface is declared *implicitly* if you use its member in an arg)
- restore W4 and disable W5205 locally with respect to the 3rd party source header
=> chore: fix WinRT-related warnings

src/modules/windowwalker/dll/dllmain.cpp
Stop the Window Walker process on exit of PowerToys
Before this change, the launched Window walker keeps sitting in the background when PowerToys exits. This makes sure that the module stops the process on PowerToys exit.
Ran it and verified that when exiting PowerToys using the exit menu, Window Walker is also stopped.
=> Stop Window Walker on exit

src/modules/windowwalker/app/Window Walker/App.xaml.cs
This PR implements a check in Window Walker which should prevent it from having multiple running instances - #1691. This is done at C#/App level, so it should even work when users start the module manually.
Manually tested by running multiple instances from Explorer, and also by quitting/restarting PowerToys. There's still going to be an issue with Window Walker persisting after quitting PowerToys.
=> Prevent Window Walker from having multiple running instances

src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj, src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Styles/TextBlock.xaml, src/core/Microsoft.PowerToys.Settings.UI/Styles/_Thickness.xaml, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/PowerLauncherViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/PowerRenameViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/ShortcutGuideViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml.cs, src/modules/windowwalker/app/Window Walker/Window Walker.csproj
Summary of the Pull Request
- Added styles for common margins + textblocks
- Added ShortcutGuide page
- Added PowerRename page
- Added PowerLauncher page
- Added a sidepanel that could include links about the feature and contributors (in Shellpage)
- Minor styling updates to ShellPage
#889 #1484 #1482 #1579
- Not sure if the sidepanel should live in the ShellPage or on the separate pages. Makes it easier for the VisualState/resizing stuff.
- Do we have a control that we can re-use across settings / editor that take in …
=> Improvements to settings shellpage and added new XAML layouts for PowerRename, Shortcut Guide, PowerLauncher

src/modules/windowwalker/dll/dllmain.cpp
The `m_enabled` variable was defaulted to `true` instead of `false`. This resulted in the settings window showing enabled irrespective of the value in settings.json after every relaunch.
Built Debugx64 and installed with MSI. Checked both cases were settings.json does not exist - Window Walker should be enabled by default, and once it exists then it should follow the value in the json on every launch.
=> Fixed WW disable not working as expected after relaunch

src/common/UnitTests-CommonLib/UnitTestsVersionHelper.cpp, src/common/VersionHelper.cpp, src/common/msi_to_msix_upgrade_lib/msi_to_msix_upgrade.cpp
To test change:
- main.cpp:144 to 
std::this_thread::sleep_for(std::chrono::seconds(1));
- msi_to_msix_upgrade.cpp:114  
VersionHelper current_version(VERSION_MAJOR , VERSION_MINOR, VERSION_REVISION);
Set different major, minor and revision
=> Version helper compare operator fix

src/modules/windowwalker/app/Window Walker/MainWindow.xaml, src/modules/windowwalker/app/Window Walker/MainWindow.xaml.cs
Allow scrolling the list of windows in Window Walker using the tab key
~~[]Tests added/passed~~
Ran it and tried tabbing through a list of windows and it works fine.
=> [Window Walker] Enable tabbing to scroll

src/modules/windowwalker/app/Window Walker/MainWindow.xaml, src/modules/windowwalker/app/Window Walker/MainWindow.xaml.cs
If the user selects an item from the result windows in Window Walker using the mouse, the next invocation does not have the text box selected by default. This change sets the focus on the text box every time the window gets focus.
While this fixes a specific issue, it will also hopefully fix the general bug reported in #1800.
* ~~[] Tests added/passed~~
Tried out the scenario of mouse clicking and checking for focus and it works fine.
=> [Window Walker] Set focus on text box control on hotkey invoke

src/modules/windowwalker/app/Window Walker/ViewModels/WindowWalkerViewModel.cs
I have changed the info text in search box to indicate the user also can search for windows.
* nothing
* <strike>[] Requires documentation to be updated</strike>
At the moment users see the text `Search for running processes...` which indicates the user to enter a process name. We coul add the string `or windows` so the user knows that he also can search for window titles.
* nothing
=> window walker: changed info text in search box

src/runner/main.cpp
Opening settings when user is opening already running Powertoys
=> Opening settings when user is opening already running Powertoys

src/modules/windowwalker/app/Window Walker/Components/InteropAndHelpers.cs, src/modules/windowwalker/app/Window Walker/Components/Window.cs
UWP apps only showed the hosting process `ApplicationFrameHost.exe` for the process name. Following the code sample referenced in #1766, this should now correctly show the process names.
* ~~[] Tests added/passed~~
* ~~[] Requires documentation to be updated~~
There were 3 options that were helpfully outlined by @arjunbalgovind and @enricogior provided a working C++ code sample I was able to translate. Its worth mentioning that @arjunbalgovind suggested using method 3 as more reliable and better documented but for now, this solution should be fine.
Searching for UWP apps works as expected (both title and process names are reasonable). Performance also seems fine since the child enumeration happens on a child thread.
=> [Window Walker] Handle UWP process names

src/settings-web/package-lock.json, src/settings-web/package.json
Updates nested dependencies so that a vulnerable version of minimist is not being used.
Updates some nested dependencies in the web settings so that a vulnerable version of minimist is not used.
`npm audit` finds 0 vulnerabilities after this change.
Fixes: https://github.com/microsoft/PowerToys/issues/1921
As `react-snap` has received no updates yet for this vulnerability and it's locking down a version of `mkdirp` which is vulnerable, a `preinstall` npm hook is used to force `mkdirp` resolve a version which fixes this vulnerability.
The fact that …
=> settings: fix minimist package vulnerable version

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/KeyboardManagerPage.xaml
- Set the right styles and margins for all UI elements inline with the other pages.
- Updated the visuals of the ListViews (emphasizing the new key stroke and changes to the width to represent the key shape).
* [] Applies to #889 
=> Updated KeyboardManager page with the right styles/margins.

src/modules/keyboardmanager/common/KeyDelay.cpp, src/modules/keyboardmanager/common/KeyDelay.h, src/modules/keyboardmanager/common/KeyboardManagerCommon.vcxproj, src/modules/keyboardmanager/common/KeyboardManagerCommon.vcxproj.filters, src/modules/keyboardmanager/common/KeyboardManagerState.cpp, src/modules/keyboardmanager/common/KeyboardManagerState.h, src/modules/keyboardmanager/common/Shortcut.cpp, src/modules/keyboardmanager/common/Shortcut.h, src/modules/keyboardmanager/dll/dllmain.cpp, src/modules/keyboardmanager/ui/ShortcutControl.cpp, src/modules/keyboardmanager/ui/SingleKeyRemapControl.cpp
Apply/Discard changes on the Detect SingleKey/Shortcut ContentDialog by holding down Enter/Escape.
* When the detect single key/shortcut content dialog is created, two KeyDelays objects are registered to track the Escape and Enter keys.
* For each KeyDelay object, three callbacks are provided, one for Short Press, and two for Long Press (when pressed initially and when released).
* Long Press triggers when the user holds the key for more that 0.9 seconds.
* When the callback function needs to close the window, the UnregisterKeyDelay code should be run from a different thread, otherwise there would be a deadlock.
* The Detect shortcut content dialog takes into account single key remapping when tracking Escape and Enter. 
* Holding down the Escape key has the same effect as clicking on …
=> Detect Shortcut: Hold Esc/Enter to Cancel/Accept

src/core/Microsoft.PowerToys.Settings.UI.Lib/EnabledModules.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/FZConfigProperties.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/FancyZonesSettings.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/GeneralSettings.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/HotkeySettings.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/KeyBoardKeysProperty.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/SndFancyZonesSettings.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/StringProperty.cs, src/core/Microsoft.PowerToys.Settings.UI/Controls/HotkeySettingsControl.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj, src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/Commands/ButtonClickCommand.cs, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/FancyZonesViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml.cs
- Added ViewModel implementation of the FancyZones settings.
- Move Text in XAML to a localized string resource.
- Added Flag to disable UI controls when the PowerToy is disabled.
Demo: https://github.com/microsoft/PowerToys/blob/user/laius/temp/doc/images/FZ_Settings_V2_Demo_GIF.gif
- Verified changes in the JSON settings file and the UI itself.
=> added Fancy Zones Settings

src/modules/keyboardmanager/common/Helpers.cpp, src/modules/keyboardmanager/common/Helpers.h, src/modules/keyboardmanager/common/Shortcut.cpp, src/modules/keyboardmanager/dll/dllmain.cpp
- This PR adds a check for extended keys which include RAlt and RCtrl. For these keys an extended key flag is included during SendInput in order to work properly. If that wasn't added you would get weird behaviour if you remapped LShift to RCtrl, held down LShift and switch to another window and then release LShift, it would act as if RCtrl was still held down.
- Another issue that was fixed was for shortcuts containing Ins, Home, Pg keys, Del, End and Arrow keys. It was observed that the shortcuts would not get remapped if Num lock was turned on. It turns out that this was because for shortcut remappings we ensure that no other key states are set to "down" but when num lock is pressed, an undocumented `0xFF` is set to down. Now we don't check the 0xFF key code.
- …
=> Handle RAlt, RCtrl and other extended keys correctly (dev/build-features)

src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml
- Increased the vertical margins between the 3 settings since they are not related to each other.
- Added a Release notes link.
#2138 #889
=> [Settings V2] Release notes link + minor styling fixes

installer/PowerToysSetup/Product.wxs
Creating a new pull request, implementing suggestions from #1992
=> Implementing changes suggested in #1992

src/modules/fancyzones/editor/FancyZonesEditor/GridEditor.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/GridZone.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/RowColInfo.cs, src/modules/fancyzones/editor/FancyZonesEditor/SplitEventArgs.cs, src/tests/win-app-driver/FancyZonesTests/EditorGridZoneResizeTests.cs, src/tests/win-app-driver/FancyZonesTests/FancyZonesEditor.cs
FancyZones Editor: fixed splitted zones positioning in grid layouts
In grid layouts zone size is represented in percentage of useful screen area (without splitters and borders). When we split zone useful area is reduced. Since it is expected that zone size shouldn't be changed, all zones percents have to be recalculated.
* manually tested with different layouts and different display scaling
* added WinAppDriver tests
=> FZ editor: Splitted zones positioning

src/modules/fancyzones/lib/ZoneWindow.cpp
This PR resolves the issue described in #2105, i.e. adds a mutex to the ZoneWindow class and ensures no data races occur. 
I used a std::shared_mutex, because, for example, std::recursive_mutex does not allow concurrent reading, which is required in the OnPaint function.
Manually tried some basic features of FancyZones and ensured no crashing or weird artifacts happen. Also all unit tests pass.
=> Added a mutex to ZoneWindow, ensured no data races occur

src/modules/launcher/PowerLauncher.UI/App.xaml, src/modules/launcher/PowerLauncher.UI/ResultList.xaml
This PR removes default transitions from UWP Listview control.
Manually validated that list view animation is no longer triggered.
Example repro : Type `Maps` and change it to `Ma`. The fly in effect should not be present.
=> Remove list view animation

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/FancyZonesLib.vcxproj, src/modules/fancyzones/lib/FancyZonesLib.vcxproj.filters, src/modules/fancyzones/lib/VirtualDesktopUtils.cpp, src/modules/fancyzones/lib/VirtualDesktopUtils.h, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/ZoneWindow.h
Since handling of virtual desktop switch is asynchronous, event indicating that new window is created can appear in the meantime resulting in window being assigned to invalid zone. Compare virtual desktop id on which window is created with the currently active virtual desktop id, and continue handling window created event only in case these two match.
1. Make sure you have `Move newly created windows to their last known zone` on.
2. Create a custom layout with two zones and apply it to both virtual desktops.
3. On first virtual desktop snap Notepad on zone 1.
4. On second virtual desktop snap Notepad on zone 2.
4. Switch back and forth between virtual desktops.
Expected result: Both windows stay assigned to their zones on different virtual desktops.
=> Compare window desktop id with currently active work area desktop id.

src/common/common-md-flag/common-md-flag.vcxproj, src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj, src/core/Microsoft.PowerToys.Settings.UnitTest/Microsoft.PowerToys.Settings.UnitTest.csproj
* Added missing c++17 compile flag to common-md-flag
* Removed .Net Native compilation from Release config in Settings.UI and Settings.UnitTests
* This was necessary because .Net Native does not support mixed assemblies, like PowerToysInterop.
* We can restore this flag in the future by preventing Settings.UI from using PowerToysInterop through Settings.Lib, and instead separate the UWP Interop in its own Windows Runtime Component.
=> Fix compilation problems related to the Interop project

src/modules/launcher/Plugins/Wox.Plugin.Shell/Main.cs
* This is happening because of the code in the shell plugin.
The Shell plugin has it's own code to override the Win+R key and because of the way they are creating and handling hooks, once we press Win+R, the Win key must be pressed again to release it. So basically, they're trying to simulate the Win key press, however since simulating only the win key press would pop up the start menu, they are simulating Win+Ctrl which is the same shortcut as that of ww.
To unblock us and mitigate this issue for now, I used the BackSpace keystroke instead of Control, so we would be simulating a Win+BackSpace keystroke.
**NOTE** Wox uses [`NHotkey.wpf`](https://www.nuget.org/packages/NHotkey.Wpf) nuget package for handling hotkeys and we would like the code for modifying hotkeys to be the same across all …
=> Win+R shouldn't launch WindowWalker

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
* This PR selects the text whenever visibility of launcher is set to visible after being hidden.
* Text is selected every time the window is made visible.
* Manually validated it.
=> Select text whenever launcher is set to visible after being hidden

src/modules/launcher/Plugins/Wox.Plugin.Shell/Main.cs, src/modules/launcher/Plugins/Wox.Plugin.Shell/Settings.cs
- Run as admin is off by default
- Process.Start will get called by the name of the exectuble. 
- If the user types in a file or directory path, we will launch explorer at that location
**NOTE: Settings are cached under %AppData%\PowerLauncher\Settings\Plugins\Wox.Plugin.Shell**.  You will need to delete these setting to see the change. 
Validated locally -- see screenshots below:
=> Making Shell plugin behave more like Win+R

src/modules/launcher/PowerLauncher.UI/ResultList.xaml, src/modules/launcher/Wox/ViewModel/ContextMenuItemViewModel.cs, src/modules/launcher/Wox/ViewModel/ResultViewModel.cs, src/modules/launcher/Wox/ViewModel/ResultsViewModel.cs
The Fade behavior was exposed to race conditions because Pointer events were conflicting with keyboard input.  This PR does the following: 
1. Removes the fade animation, and sets visibility property. 
2. Encapsulates context button activation inside the resultviewmodel, which knows how to respond to both pointer events and keyboard input
1.  Verified that PointerExit on the selected item doesn't hide the buttons. 
2.  Verified that accelerator keys trigger the selected result, not the result in the pointer over state.
3.  Verified that pressing the buttons initiates the context action. 
4.  Verified that each result has context menu buttons (except window walker items).
=> Fix - issue 2301 buttons showing inconsistently

src/modules/launcher/Wox/ViewModel/MainViewModel.cs, src/modules/launcher/Wox/ViewModel/ResultsViewModel.cs
Fix for program executing when there is no query text in search box and `Enter` is pressed. 
- Verified that last selected program is not executed again if we press `Enter` in empty search box.
- Manually validated the working of plugins.
=> Fix for program executing when there is no query text in search box

src/modules/launcher/PowerLauncher.UI/LauncherControl.xaml, src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
- This just adds the binding back to the querytext box, so that plugins can update the query text field. 
- Cursor Position is also updated to the end when plugins update the text.
- Note this also will automatically add the '> ' when pressing Win-R, however we will want to not select the '> ' when bringing it up a consecutive time.
=> Folder Plugin 

src/modules/launcher/Plugins/Wox.Plugin.Program/Programs/UWP.cs, src/modules/launcher/Plugins/Wox.Plugin.Program/Programs/Win32.cs
Note the LNKs here are being pulled from the search plugin, not the program plugin
=> Deduping results for program plugin

src/modules/launcher/Plugins/Wox.Plugin.Shell/Main.cs, src/modules/launcher/Plugins/Wox.Plugin.Shell/Settings.cs
* [] Applies to #2379
alt-space works, WinR no longer fires
=> disabling WinR

src/modules/launcher/Wox/ViewModel/MainViewModel.cs
Push program execution to a background thread.
Whenever a search result was executed through Enter/click, `Process.start` was freezing the UI thread till it's completion. This PR pushes this operation to a background thread and hides the launcher window. 
- Validated that the launcher hides without waiting for process to start.
- Manually validated working of all plugins.
=> Push program execution to background thread

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/modules/launcher/Wox/ViewModel/MainViewModel.cs
This PR fixes dll's being loaded when first query is made.
**Dll's loaded when plugin is queried for first time :** 
1. Microsoft.Search.Interop.dll
2. System.Data.OleDb.dll.
3. System.Transactions.Local.dll
4. System.Diagnostics.PerformanceCounter.dll
**Dll's loaded when the List view is populated for the first time :** 
1. Windows.ApplicationModel.winmd
2. System.Globalization.dll
3. System.Reflection.dll
4. System.Reflection.Extensions.dll
5. Windows.Storage.winmd
Manually validated that dll's are loaded before first query.
Steps to compare : 
1. Run in debug mode as the difference can be easily compared. 
2. Open current 'dev/powerlauncher' and when the searchbox is visible for first time type one single letter. 
3. Repeat step 2 with this PR.
=> Fix dll loading at runtime 

src/modules/launcher/Plugins/Wox.Plugin.Folder/Main.cs, src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/modules/launcher/Wox/MainWindow.xaml.cs, src/modules/launcher/Wox/PublicAPIInstance.cs, src/modules/launcher/Wox/ViewModel/MainViewModel.cs
This issue fixes the cursor jumping around.  
The root cause was that due to a delay there was a disconnect between the text that was in the textbox, and what was being queried.   As a result the cursor was being set to a position that didn't match what was being queried.
PR Checklist
- Separating the ability to set the text from initiating a query.
- Plugins have to explicitly request the query be updated.
- Updating Folder plugin to explicitly update the query on folder selection.
- Removing unused changes from 'Wox' that don't compile.
- Don't set delay on system updated query text.
1. Manually typed long queries and watched out for cursor changing position. 
2. Validated that the folder plugin still behaves the same as before.
=> Fixes cursor jumping around issue.

src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs, src/modules/launcher/Plugins/Wox.Plugin.Folder/Main.cs, src/modules/launcher/PowerLauncher.UI/LauncherControl.xaml, src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/modules/launcher/Wox.Plugin/Result.cs, src/modules/launcher/Wox/ViewModel/MainViewModel.cs, src/modules/launcher/Wox/ViewModel/ResultViewModel.cs
This change makes the directory navigation behave more like search and the runner. 
- Arrow keys or tab to select will update the query text to the path of the folder. 
- Enter on the folder will launch explorer
1.  It became apparent when using the arrow keys to update the query text programatically, that there were holes in the logic to prevent updating the query when we change the text.  To fix this it was broken into to TextChanged event handlers one to deal with programatic input and the other to deal with user text changes.  Because the property changed event and the text changed are on different dispatchers, we can't check the boolean flag inside the event handler. 
Manually tested. 
- Navigating to a folder from the folder plugin.
- Navigating to a folder from the search indexer …
=> Issue 2383 update folder and selection behavior

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
This was causing an exception.  It was fixed by initializing query text in #2392, but it's better to be defensive as someone could assign null to querytext at any point.
=> Defensive check for QueryText being null

src/modules/launcher/Plugins/Wox.Plugin.Program/Main.cs
This PR watches for all files and directories being created and deleted out of the `Program Files` directory. This will trigger the application to reindex after a delay. 
I don't think this is a permanent solution, and we will have to put more though into how to do this in a less intrusive way. 
This is not perfect.  We get multiple  writes on installing or uninstalling the uwp app.   The idea is an initial write will trigger a timed delay of the reindex, if another write is detected within that time span it resets the timer.   If the install has delays between file writes we will reindex multiple times (not good). 
Also there seems to be thread contention that causes stalls if we are querying for apps while the UWP apps are being reindexed.
- Launch the app.  Verify no "Reindexing" is a …
=> Reindex UWP Apps when apps are installed or uninstalled.

src/core/Microsoft.PowerToys.Settings.UI.Lib/Microsoft.PowerToys.Settings.UI.Lib.csproj, src/core/Microsoft.PowerToys.Settings.UI.Runner/Microsoft.PowerToys.Settings.UI.Runner.csproj
* Remove reference to TwoWayIPCLib
* Downgraded System.Text.Json package in Settings.Lib
#2241
=> Fix incompatible assemblies building issues

src/common/VersionHelper.cpp, src/common/VersionHelper.h, src/common/notifications.cpp, src/common/notifications.h, src/common/updating/updating.cpp
- attempt to download the installer 3 times 
- toast cosmetic improvements
The screenshot was done before I've noticed the missed dots at the end of the sentence, that's also fixed.
- installed PT with a version set to 0.15.2, update the PT
=> runner: autoupdate improvements

src/runner/general_settings.cpp
…for non-admin users
- installed the PT as a non-admin user and observed "Visit"-type toast notification
=> runner: download_updates_automatically option is disabled by default for non-admin users

src/modules/shortcut_guide/shortcut_guide.cpp, src/modules/shortcut_guide/shortcut_guide.h
This PR represents the beginning of long-planned work to move the control over winhooks from the PT runner to the modules themselves. Shortcut Guide is probably the easiest module to start from.
Relevant issue: #961
The naming conventions may not follow the rest of the solution, but it's in line with the module itself.
Manually tested the Shortcut guide module, also tried disabling it and then enabling it again.
=> "Unhooked" the Shortcut guide module from the PT event dispatcher

src/modules/fancyzones/dll/dllmain.cpp
This PR moves the code which creates and uses WinHooks used in FancyZones from PowerToys to the FancyZones module, without affecting other modules.
Relevant issue: #961
Manually tested the FancyZones module, also tried disabling it and then enabling it again.
=> FancyZones now does its own event processing

src/modules/launcher/Plugins/Wox.Plugin.WindowWalker/plugin.json
This PR fixes issue with calculator results showing up results only once.
The plugin ID for WW and calculator was same. This caused results from calculator plugin to be overwritten with results from WW. 
Validated that calculator plugin works as expected.
=> Fix for calculator plugin not showing results

src/modules/keyboardmanager/dll/dllmain.cpp, src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp, src/modules/keyboardmanager/ui/EditShortcutsWindow.cpp, src/modules/keyboardmanager/ui/XamlBridge.cpp
The crash mentioned in the linked issue was happening because we use a single KeyboardManagerState variable for both of the windows, so when one of the windows is closed there is most likely something getting set to `nullptr` while a window is still open. The way the code was written was considering only one window open, so the best way to solve this with minimal changes is to ensure only one window can be opened at a time.
The PR changes the behavior of the buttons, such that when clicking either of the buttons - if Edit keyboard or edit shortcut either of them are open, it will bring that window in focus. Earlier if Edit keyboard was open and you clicked the same button again, it would just bring that to focus. By this change we ensure that only one window is open at a time, and by …
=> [KBM] Constrain the buttons such that only one of the windows can be opened

LICENSE
By removing `(MIT)` from the `LICENSE` file, the license type is displayed on the PowerToys start page.
=> Fix license file

src/modules/keyboardmanager/ui/XamlBridge.cpp, src/modules/keyboardmanager/ui/XamlBridge.h
~I got it to stop crashing by bypassing XamlBridge Window focus handling.~
It seems there was some initialization missing that was the root cause of the strange crashes in Windows Insiders.
* ~Xaml Bridge seems to not handle focus events properly, so this fix just bypasses it by handling the WM_SETFOCUS event directly.~
* ~This also solves another not documented crash that involved minimizing the window, then closing by pressing the X button without interacting with the window content itself.~
* Solved by calling `winrt::init_apartment` and `WindowsXamlManager::InitializeForCurrentThread()` in the constructor of the XamlBridge class.
*For Windows Insiders users*
1. Click on the Remap a key button with no key remappings.
2. Close the window by pressing the X button.
3. It shouldn't crash. …
=> [Keyboard Manager] Fix Remap buttons stop working 

src/modules/launcher/Wox/ViewModel/ResultsViewModel.cs
I noticed a crash when pressing tab if there is no selected item. 
I put in a guard that prevents us from attempting to select the next context menu item if there is no selected item in the results. 
- Steps to reproduce (Prior to this change).
- Type a string that will return no results such as 'asdfghjkl'. 
- Press 'Tab'.  
- Observe the crash. 
- Performed the above steps and verified …
=> fix for crash when tabbing with no selected item

src/runner/settings_window.cpp, src/runner/settings_window.h, src/runner/tray_icon.cpp
Settings Window gets closed whenever the user clicks Exit on the PowerToys system tray menu.
The settings window used to outlast the Runner executable. This fixes this by killing the Settings proecess when the runner window gets destroyed.
* Start PowerToys.
* Click on the Runner. A Settings window should show up.
* Right click on the system tray icon, then select exit.
* Both the Settings window and the runner should exit at the same time.
=> [Settings] Close Settings Window on runner exit

src/core/Microsoft.PowerToys.Settings.UI.Lib/GeneralSettings.cs
This is a work around fix for the Settings UnitTests failing caused by #2601 
Tests were failing because GeneralSettings uses the `interop` library to get version information. `interop` is a C++/CLI project, and can't be called by an UWP app. This is not a problem in the Settings.UI exe because we are using XamlIslands, but thats not so in the UnitTests.
The current fix is just to handle the exception, which solves the crashes that happened in the UnitTest project.
A more permanent solution could be to set up the UnitTest project in a similar fashion to the Main application, that is, by having a .NET Core runner invoking a XamlIsland. 
* Microsoft.PowerToys.Settings.UnitTest pass.
* The version number in the GeneralSettings page is displayed properly
=> [Settings] Workaround for Settings ViewModel tests

src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs
Fix for indexer throwing error in results when symbols are given as input.
This PR  prevents querying database with strings that contain symbols and result in error. It also removes adding error messages in indexer results.
Manually validated that Index doesn't throw error when symbols are given as input.
=> Fix for indexer symbol error

src/core/Microsoft.PowerToys.Settings.UI.Runner/Program.cs, src/runner/settings_window.cpp
This PR fixes a crash on launching Settings ~~due to an out of bound index error~~ due to an uninitialized theme string as identified by @laviusmotileng-ms. Verified the elevated argument is read on opening settings (adding in #2676 ).
=> Fixed SettingsV2 crash

src/core/Microsoft.PowerToys.Settings.UI/ViewModels/FancyZonesViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
Settings v2 changed fancy zones color picker json format to ARGB which caused crush on displaying fancy zones.
Also: Changing any color resets fancyzones_highlight_opacity.
Changing fancyzones_highlight_opacity resets colors (fancyzones_zoneHighlightColor, fancyzones_zoneBorderColor, fancyzones_zoneColor)
After the change:
- Color are saved in RGB
- Transparency options for each color are removed since we have global transparency option
- All fancyzones are now saved when changing colorpicker or other setting
- Buttons responsible for saving colors are removed to match instant save which applies to other settings
=> Fancy zones settings - Color pickers saved ARGB value fix (now saves RGB)

src/common/common-md-flag/common-md-flag.vcxproj, src/common/common-md-flag/common-md-flag.vcxproj.filters, src/common/common-md-flag/packages.config
* This should solve the solution not compiling issue.
* Added the Microsoft.Windows.ImplementationLibrary nuget package to the `common-md-flag` project.
* The PowerToys solution should build and run.
* This doesn't fix the MSI build problems.
=> [Hotfix] Add WIL to common-md-flag nuget packages

.pipelines/build.cmd
This seems to fix the missing Generated Files\version_gen.h error
* Built using `.pipeline\build.cmd` from a clean repo seems to work 
* Got a functioning run from the pipeline.
=> [Hotfix] Change build order in build.cmd

src/runner/main.cpp, src/runner/settings_window.cpp
- Powerpreview.dll output path changed. this PR loads the dll from the updated output folder.
- verified changes in the son file and loading of modules from specified folders.
=> [settings] loading powerpreview module from subfolder

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
noticed this on the wpf branch, surprised the call pattern wasn't in the island version as well.
=> adding in ignore for alt-space

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs
Added run as admin option for win32 packaged apps.
In Win32 packaged app, the main Application entry will be something like this:
`<Application Id="MSIXHero" Executable="MSIXHero.exe" EntryPoint="Windows.FullTrustApplication">`. The property `EntryPoint="Windows.FullTrustApplication"` ensures that it is a win32 packaged app which can be run as admin. 
Another scenario in which a packaged app could be run as admin is if it contains `TrustLevel=mediumIL"` property in the Application Manifest 
Manually validated that Run as admin works for Win32 packaged  apps like Spotify, Window terminal but not for traditional sandboxed apps like Mail, Calender etc.
=> Add support for win32 packaged apps to run as admin

src/core/Microsoft.PowerToys.Settings.UI.Lib/BoolPropertyJsonConverter.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/EnabledModules.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/PowerPreviewProperties.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/Telemetry/Events/SettingsEnabledEvent.cs, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/PowerPreviewViewModel.cs, src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/PowerPreview.cs
This PR does the following. 
1) Enables svg and markdown preview by default. 
2) Raises telemetry events when enabling or disabling the markdown. 
The following considerations were made in this PR
1) To be backwards compatible with .17 we need to serialize and deserialize as a BoolProperty.   I've added a BoolPropertyJsonConverter to serialize and deserialize bool Properties as the `BoolProperty` type.
2) Because we want to detect when the EnableSvg and EnableMarkdown properties are set we don't want to expose this type to calling methods.  Eg. `Settings.properties.EnableSvg.Value = value;` becomes `Settings.properties.EnableMd = value;` and we don't interact with the BoolProperty directly. 
Installed .17: 
- Verified that the settings are loaded into settings v2. 
Toggling EnableSvg and …
=> Adding Telemetry Events for svg and markdown enable/disable

src/core/Microsoft.PowerToys.Settings.UI/App.xaml.cs, src/modules/launcher/PowerLauncher.UI/App.xaml.cs
This PR hides the loading icon which appears for the Settings and Launcher xaml island projects. After these changes an icon symbol still quickly appears and then disappears but it's for a couple of milliseconds.
- Once the XamlApplication has been initialized we get the CoreWindow and set it's window state to SW_HIDE as suggested by @ocalvo
=> Hide xaml island loading icon for Settings and Launcher

src/core/Microsoft.PowerToys.Settings.UI.Lib/PowerRenameLocalProperties.cs, src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/PowerRenameViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml, src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/PowerRename.cs
"Maximum numbers of items to show in recently used list for autocomplete dropdown."  had:
- No default value in settings
- "Enable autocomplete and autosuggest of recently used list for autocomplete dropdown." was duplicated in settings
- Had no caption
- Had no limits for min and max value
- Could be edited while "Enable autocomplete and autosuggest of recently used list for autocomplete dropdown." was off
This PR fixes this problems.
=> PowerRename settings bugfix

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
This PR changes the text shown on the settings page of Shortcut guide from 'Choose Settings color' to 'Choose Shortcut Guide overlay color', as it used to be in 0.17.
#2839
Built the solution and verified that both the text on the General page and Shortcut Guide page are correct, as they used the same resource string before.
=> [Settings] Updated text shown on the settings page of Shortcut Guide

src/modules/keyboardmanager/common/KeyboardManagerConstants.h, src/modules/keyboardmanager/ui/Dialog.cpp, src/modules/keyboardmanager/ui/Dialog.h, src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp, src/modules/keyboardmanager/ui/EditShortcutsWindow.cpp, src/modules/keyboardmanager/ui/KeyboardManagerUI.vcxproj, src/modules/keyboardmanager/ui/KeyboardManagerUI.vcxproj.filters, src/modules/keyboardmanager/ui/Styles.cpp, src/modules/keyboardmanager/ui/Styles.h
* A confirmation dialog appears for single key remappings if there are orphaned keys.
* Apply button is changed to OK, and closes the window after applying the changes.
* A confirmation dialog appears for both single key and shortcut remappings if not all remappings are valid. 
* When remapping single keys, a confirmation dialog shows up if there is at least one orphaned key.
* When remapping either shortcuts or single keys, a confirmation dialog shows up if there is at least one invalid remapping.
=> [Keyboard Manager] Confirmation Dialog for orphaned keys and partial remappings.

src/common/interop/interop.h, src/core/Microsoft.PowerToys.Settings.UI.Lib/Utilities/Helper.cs, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/KeyboardManagerViewModel.cs, src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp
This PR adds the same preprocessing for the remapped keys list on the landing page as done on the C++ side. In the C++ side of the code, to make key handling easier since "VK_CONTROL" is never actually sent as a key message, it was decided that if a user remaps Ctrl_Left and Ctrl_Right to the same key then we combine it as Ctrl has been remapped, and similarly for all modifiers. However this was not reflected on the landing page.
- Restructured the C++ side of the logic to be clean and readable with code re-use.
- Added a Constants class to the interop namespace in order to access constants from common.
- Added this constant from interop to the Helper class in Lib.Utilities
- Duplicated the C++ preprocessing logic in the LoadProfile function on the C# side. I did not use it through …
=> Fix inconsistent landing page remap list

src/modules/keyboardmanager/common/KeyboardManagerConstants.h, src/modules/keyboardmanager/dll/dllmain.cpp, src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp, src/modules/keyboardmanager/ui/EditKeyboardWindow.h, src/modules/keyboardmanager/ui/EditShortcutsWindow.cpp, src/modules/keyboardmanager/ui/EditShortcutsWindow.h
This PR changes the disable behavior such that it closes all active KBM windows. This ensures that users do not see unexpected behavior on disabling KBM but continuing to use the UI since the hook would be disabled.
- Added functions to close active windows, which are called from dllmain
- Changed some constants data types to fix warnings
- Removed the minimize option from both windows to convey the idea of a dialog box. More details [here](https://docs.microsoft.com/en-us/windows/win32/winmsg/window-styles)
Verified that behavior is as expected if disabling when windows are open or closed. The one scenario I'm a bit concerned with is if the user clicks OK and then quickly goes and disables the saving to file could get interrupted, but I wasn't able to repro this.
=> Close KBM windows if the user disable KBM from Settings

src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Main.cs
* Fixed the issue by starting a new Thread and setting it to STA.
* Clipboard needs to be accessed from an STA thread https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.clipboard?view=netcore-3.1 (for some reason, this warning appears in the System.Windows.Forms.Clipboard msdn page but not in System.Windows.Clipboard, but it seems both are affected)
* Clipboard opeartions launched from the context menu are not affected because they use the Main application thread and not the Task pool, which is set to STA.
1. Launch Launcher and type 1 + 1
2. Click on the result
3. Paste somewhere. It should paste the number 2
=> [Launcher] Fix Copying of calculator value

src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp, src/modules/keyboardmanager/ui/EditShortcutsWindow.cpp, src/modules/keyboardmanager/ui/ShortcutControl.cpp, src/modules/keyboardmanager/ui/SingleKeyRemapControl.cpp
This PR changes the type key and type shortcut behavior to hold enter to accept instead of hold and release, so that it is consistent with the Esc behavior. It was also observed that in tab ordering for Remap Keyboard and Remap Shortcuts windows the Cancel key would get highlighted before OK which is not in the Left to Right order, so that has been swapped.
- The onAccept lambda was split into two parts, onPress and onRelease 
- In onPress we perform all the accept logic followed by `detectKeyBox.hide()` but we do not perform the `ResetUIState` and `unregisterkeys()`
- The resetting of UI state along with disabling the key delay handler is done in onRelease. Because of this, we stop swallowing input only when Enter key is released, and this allows us to avoid the issue where pressing …
=> KBM - Change behavior to hold enter to accept rather than hold and release

POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/FancyZonesPage.xaml, POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/FancyZonesPage.xaml.cs
- Made FancyZones Adaptive Layout
- On window resize to smaller window, the "About Feature" and corresponding GIF should appear on top of the regular settings
- On window resize to a larger window, the "About Feature" and corresponding GIF should appear in their own column at the right side
- Added Hover feature to show placeholder of Github link on Module Overview link hover
=> [intern] Adding FancyZones Adaptive Layout Feature for OOBE POC

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-web/src/components/GeneralSettings.tsx
This PR changes the title of the auto-download setting in the old and new settings ui.
The updates don't get automatically downloaded when the user is connected over a metered connection. This is something the user should known about. Because of not have to be afraid on having extra costs and to not being confused if it not works on metered connections.
Old title: `Download updates automatically`
New Title: `Download updates automatically (Except on metered connections, where charges may apply)`
Not validation steps done.
=> Change Auto-download settings' title

src/runner/settings_window.cpp
- In the event the runner takes time to launch the Settings UI, and if the user clicks the launch icon again while the runner is in the process of launching the first window, the runner will create another process to launch another settings window. To prevent this, I added a flag to tell if the runner is still launching the first window and to discard any clicks from the launch icon until the first settings window is launched. 
https://github.com/microsoft/PowerToys/issues/2900
- Added a loop (on line 218) to delay the launching of the first settings UI so the runner can start two processes to launch the settings UI.
```
for (int c = 1; c <= 32767; c++)
{
for (int d = 1; d <= 32767; d++)
{
}
}
```
- Without the flag, on …
=> [Settings V2] Remove multiple pop-ups on double tap

src/core/Microsoft.PowerToys.Settings.UI.Lib/ConfigDefaults.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/FZConfigProperties.cs, src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/FancyZones.cs
- Updated default values for Fancy Zones colors.
https://github.com/microsoft/PowerToys/issues/2964
* [] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #2964
- Deleted settings files and ran the settings ui to check if default values were set.
- ran tests.
=> [Settings V2] Updated default color values for fz

POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/App.xaml.cs, POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Services/NotificationService.cs, POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/MainPage.xaml.cs
- Create toasts that activate the OnInstall and OnUpdate functionality
- On launch, two toasts icons pop up
- Pushing Get Started with PowerToys opens up OnInstall pop-up
- Pushing New PowerToys update opens Update popup
- Pressing either icon will remove all toasts immediately
=> OnInstall and OnUpdate functionality via toast activation (OOBE POC)

src/modules/launcher/Wox.Infrastructure/Wox.cs
This PR fixes issue causing two sets of module name for powertoys run as indicated in the image below
Manually validated only one folder named "PowerToys Run" is produced for both settings and power toys run configuration using steps given below :  
1. Clean "Microsoft\\PowerToys\\PowerToysRun" folder in appdata folder, if present.
2. Build runner 
3. Verify that only one folder named "PowerToys Run" is produced for launcher.
=> Fixed folder naming for powertoys run

POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/App.xaml.cs, POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/MainPage.xaml.cs
- Add ApplicationSettings listeners so that *Update* popup and *First Install* popup only appear after an update or install
- Create a sandbox function in App.xaml.cs so that toast notifications will be triggered on launch
- Toasts can also trigger the appropriate popups
- Sandbox notification function is present to replicate the background activation that should trigger toasts
- Comment out final else statement in the MainPage.xaml.cs onNavigation (as described in comments) to prevent the *First Install* popup to appear on launch (as the current system properties will view your launch as a "firstlaunch"
- Two content dialogs cannot be open at the same time.
=> Activate OOBE experience based on app state

src/modules/fancyzones/dll/dllmain.cpp
This PR fixes a bug where FZ would not `CallNextHook` if it doesn't have to suppress the key event.
Instead of return the value of the HandleKeyboardHookEvent function, return 1 only if it is equal to 1.
=> Fix FZ not forwarding events to next hook

POC/ColorPicker/ColorPicker/MainWindow.xaml, POC/ColorPicker/ColorPicker/MainWindow.xaml.cs
This adds support for copying the RGB or HEX values from the textboxes when clicking on them. This makes the overall user experience much more enjoyable by adding the chosen color to your clipboard as quickly as possible.
Screenshot:
Flow:
- Select a color using the color selection mode (enabled on open, and then by clicking the "New Color" button after a first color is selected)
- Click on the textbox containing the desired color format (RGB or HEX)
- The text in the textbox is automatically selected, to give the user feedback, and copied to the clipboard
- A small pop-up appears below the clicked textbox to confirm that the color has been copied to the clipboard
=> [intern] Color picker clipboard support

src/modules/launcher/Wox.Infrastructure/UserSettings/Settings.cs
* By default we want four results to show and not six, before settings loads the json file.
* Delete the PowerToys Run Appdata folder and run Launcher to get four results at start-up.
**NOTE** - Delete the AppData PowerToys Run folder before validating.
=> [launcher] Default to four results

proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/MainWindow.xaml.cs, proofOfConcept/ColorPickerAlpha/README.md
Fix: The overlay window is the owner of the main window to make the main window always on top of the overlay. This was causing the overlay window to not be closed when the main window was closed.
=> [intern] Fix bug where the overlay window was not closing on exit

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32.cs, src/modules/launcher/Wox.Infrastructure/StringMatcher.cs, src/modules/launcher/Wox.Test/FuzzyMatcherTest.cs
* On typing `vim`, `Vim Diff` was showing up as the first result and instead of `Vim`. 
* This was happening because we assign a score to the results which is the max matching score of it's name, description and the executable name.
* However, since all of them had the same executable name `vim.exe` all the results were getting the same score.
* The score is increased by 10 when there is an exact match in the name of the search result.
* Tests added.
* Manually validated.
=> [launcher] - Increase the score for Exact matches in the Name of the Application

README.md
fixing images so they deep link to module overview versus the img
=> fixing images so they deep link to module overview versus the img in readme

src/modules/keyboardmanager/common/KeyboardManagerState.cpp
Fixes a scenario where a user could open Type key and switch to some other window but remappings would not be disabled.
Verified that keys appear as expected in each of the window states.
=> Added check for Type key/shortcut open but not in focus

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/util.cpp
While moving windows through zones with win + left/right arrow handle maximized windows as well.
1. Apply any zone layout to work area.
2. Take any window and maximize it.
3. Make sure `Override Windows Snap hotkeys (win+arrow) to move windows between zones` is ON.
4. Press win + left or right arrow.
Expected result: Window should be snapped out of maximized state and moved into correct zone.
=> [FancyZones] Snap out of maximized window into zones with win + left/right arrow

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
##Summary of the Pull Request
Fix for #3202 
New titles are now inline with other PowerToys modules ("Enable ..."):
#3202 
* [X ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/PowerToys) and sign the CLA
=> [Settings] Updated titles for the file explorer preview toggleswitches

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
This PR improves readability on the FancyZones page by:
- Separating the launch FZ editor button out of the Zone behavior section and directly below the module toggleswitch.
- Added the colorpickers to a DropDownButton so the selected colors are easier to identify, and a lot of space is saved.
- Minor changes to some resource strings.
#3601 
* [X ] Applies to #3601
* [X ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/PowerToys) and sign the CLA
=> [Settings] UX improvements to the FancyZones config page

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/JsonHelpers.cpp, src/modules/fancyzones/lib/JsonHelpers.h
Some application like outlook uses multiple windows. If application was zoned "Move newly created window to zone" all other windows were moved to the zone also.
After changes only one window of same application will be zoned on creation, rest will not be moved by fancy zones.
When one window of same application window is zoned, zoning other window can be zoned, but it will not be saved in zone-settings.json.
Edit: Now multiple instances of same application will be zoned based on process id. First window of aplication instance will be zoned, rest will be unzoned while starting app
- Manual testing
- Unit tests passed
=> [FancyZones] Outlook new message restore placement bug

src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
Using wrong resource for Shortcut Guide theme setting label wrong. Correct Resource was already there, only not used
=> [Settings] Use correct resource for Shourtcut Guide theme setting

src/modules/fancyzones/lib/JsonHelpers.cpp, src/modules/fancyzones/lib/JsonHelpers.h, src/modules/fancyzones/tests/UnitTests/FancyZones.Spec.cpp, src/modules/fancyzones/tests/UnitTests/FancyZonesSettings.Spec.cpp, src/modules/fancyzones/tests/UnitTests/JsonHelpers.Tests.cpp, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp
Unit tests no more affectes user settings files. 
Added explicitly set module name to `FancyZonesData` for testing to prevent changing users files.
Run unit tests, check if `zone-settings.json` remains the same.
=> [FancyZones] Unit-tests fix: keeping user settings unchanged  

src/modules/fancyzones/lib/ZoneSet.cpp, src/modules/fancyzones/lib/ZoneSet.h, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/tests/UnitTests/ZoneSet.Spec.cpp, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp
A recent PR #3132 was supposed to fix issue #3111 but it didn't. This PR fixes that by removing an argument from various functions. The argument was used inconsistently and is not needed anymore.
All unit tests pass and the scenario described in #3111 does not result in unexpected behavior.
=> [FancyZones] Removed the stampZone argument

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs
This was happening because of the way the `resource` was passed to the `SHLoadIndirectString` function.
For some apps like Camera, the resource is `LensSDK/Resources/AppTitle` whereas for most other applications it is just `AppTitle` or `AppDescription` and the code was written such that the `resources` keyword would be prefixed. However, this does not work when there is a namespace with Resources already defined like in the case of the Camera app.
Due to this the DisplayName and Description were not being retrived and hence the app was not displayed. Another app for which this was happening on my system is `XBox Console companion`.
* https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-shloadindirectstring?redirectedfrom=MSDN
* If the word `resource` is present in the …
=> Fix for Camera App not showing up

.pipelines/pipeline.user.windows.yml, installer/PowerToysSetup/Product.wxs, src/modules/keyboardmanager/common/KeyboardManagerCommon.vcxproj, src/modules/keyboardmanager/dll/KeyboardManager.vcxproj, src/modules/keyboardmanager/ui/KeyboardManagerUI.vcxproj
In order to organize build and installation directories, move KeyboardManager to it's own folder both for build and install.
Installed 0.18.1
Installed 0.18.2
Confirmed that KeyboardManager is in own installation folder under PowerToys/modules. Confirmed that it is working as expected. Confirmed that old KeyboardManager files are deleted by 0.18.2 installer.
=> [KeyboardManager&Installer] Move Keyboard Manager to separat build&install folder

src/modules/launcher/Wox.Infrastructure/StringMatcher.cs
Take space into consideration while calculating the first matched index. 
* The query `term` was showing up CharacterMap before Windows Terminal because the first match index in terminal was 8 whereas it was 6 for characterMap. 
* To mitigate this issue, setting the first start index relative to the preceeding space. This way windows terminal gets a higher weightage as the first match index is now 0.
- Task Manager would have previously got a low score. However, now it is higher as we are giving preference to the fact that it is the start of a new word.
=> Fix for Unexpected priority of search results for 'term'

src/runner/main.cpp
Added missing KeyboardManager folder declaration to runner. Otherwise the dll does not get loaded.
Build in debug locally, open PT Settings and clicked Remap keys/Remap shortcuts.
=> Added KeyboardManager directory to runner

installer/PowerToysSetup/Product.wxs, src/modules/fancyzones/dll/FancyZonesModule.vcxproj, src/modules/fancyzones/lib/FancyZonesLib.vcxproj, src/modules/fancyzones/tests/UnitTests/UnitTests.vcxproj
In order to organize build and installation directories, move FancyZones to it's own folder both for build and install.
Installed 0.18.1
Installed 0.18.2
Confirmed that FancyZones is in own installation folder under PowerToys/modules. Confirmed that it is working as expected. Confirmed that old FancyZones files are deleted by 0.18.2 installer.
=> [FancyZones&Installer] Move FancyZones to separate build&install dir

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
- Page header position corrected: now center aligned with the first navigation item, similar to W10 settings app. (#3837)
- Changed FZ opacity NumberBox to Slider (#3686)
- Set fixed widths for input elements, so they are consistent on every page and look better (#3692 and #3733 )
- Opacity value is now shown next to the opacity sliders for Shortcut Guide and FZ (#3234)
- Updated labels for PowerRename (#3906)
Centered header page + consistent widths for input controls
Slider for FZ + value is now shown
=> [Settings] Various UX tweaks

src/modules/fancyzones/lib/JsonHelpers.cpp, src/modules/fancyzones/lib/VirtualDesktopUtils.cpp
After implementing solution for handling 0000 GUID on primary desktop in https://github.com/microsoft/PowerToys/pull/2339 (first start, no virtual desktop switch occurred), workarounds for it are no longer needed.
=> [FancyZones] Remove workarounds related to 0000 dekstop GUID

doc/devdocs/readme.md
Microsoft changed the name of Fabric UI to Fluent UI. Updated title and URL (which still links to the same page, just with a direct link instead of a redirect).
=> Fabric UI reference update

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
In settings v2 option _Keep windows pinned to virtual desktop location_ was wrongly mapped to both itself and _Move newly created windows to their last known zone_. When removing that setting, we have removed both.
Turn flag _Move newly created windows to their last known zone_ and check if app zone history feature works as expected.
=> [Settings] Connect appZoneHistory settings with rest of the stack in settings v2

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/FancyZonesViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
- Added help text / tooltip for valid hotkeys.
- Updated logic to set the hotkey to : "w+`" in the case none is set.
* [x ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/PowerToys) and sign the CLA
- Manually updated the json file as in below:
and verified that the hotkey value is not set to null for FZ.
=> added error handling for FZ Hotkeys

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/JsonHelpers.cpp, src/modules/fancyzones/lib/JsonHelpers.h, src/modules/fancyzones/lib/MonitorWorkAreaHandler.cpp, src/modules/fancyzones/lib/MonitorWorkAreaHandler.h, src/modules/fancyzones/tests/UnitTests/JsonHelpers.Tests.cpp, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp
1. Add support to save zone history over multiple desktops for single app.
2. After virtual desktop is deleted, remove app zone history as well.
Multiple desktops app zone history:
1. Create more than one desktop and assign some layout to them.
2. Assign two instances of the same application to different desktops.
3. Close those instances.
4. Re-open them again.
5. Check `C:\Users\<user>\AppData\Local\Microsoft\PowerToys\FancyZones` files `app-zone-history.json`.
Expected result: Information about zone history of single application contains information for different desktops, after application is opened, it goes to the different zone based on which desktop it is.
App zone history data of deleted desktop:
1. Create more than one desktop and assign some layout to them.
2. Assign some …
=> [FancyZones] App zone history on multiple desktops

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/ShellLinkHelper.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32.cs
* Applications which take in no arguments should show up before others.
* Applications which take in no arguments are scored higher than the others.
* The IShellLink interface is used to extract the arguments that the object takes and if an application does not take any arguments, it's score is increased by 5.
* Solves the ranking of PWAs issue -
* Solves the command prompt issue -
=> Fix for PWAs and command prompt not showing up as the first result

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs
Some of the applications did not have an icon such as calculator, snip & sketch and windows security.
theme and Target size Ref - https://docs.microsoft.com/en-us/windows/uwp/app-resources/images-tailored-for-scale-theme-contrast#asset-size-tables
* We were previously checking only the paths with scale factor. Some of the UWP applications such as calculator did not have it in that format, rather the path either had `theme` or `targetsize` included.
* Therefore, included paths with contrast and targetsize as well. 
Windows Security - 
Calculator - 
Snip & Sketch -
=> Fix for UWP icons not showing up

src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml
Updated the PT Run icon in Settings to E771 (discussed in #4041)
Result:
=> [PT Run] Updated the PT Run icon to E771

src/modules/launcher/PowerLauncher/MainWindow.xaml, src/modules/launcher/Wox/ViewModel/MainViewModel.cs
Alt-f4 could close launcher.
Added an 'ignore' command and bound to alt-f4
=> making alt-f4 ignored

src/modules/launcher/PowerLauncher/MainWindow.xaml, src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
This PR solves issue with focus not being set on first launch. 
`onLoaded` callback is being fired on the first launch and we are registering ViewModel_PropertyChanged in `onLoaded` callback. And this causes property change event for visibility to be missed on first launch. We can solve this by moving this to `VisibilityChanged` callback of main window. 
Note: Using Activate() and UpdatePosition() in `Window_IsVisibleChanged` is interfering with WPF lifecycle and resulting in launcher never being visible.
Manually validated from MSI that focus issue is not being hit on first launch and subsequent launch.
=> Fixed initial focus on WPF issue

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32.cs
While calculating the hash code, the case was being taken into consideration leading some duplicates to appear. Changed that to be case invariant now. 
Before - the exe's were steam.exe and Steam.exe
After -
=> Case invariant hash code calculation for removing duplicates

src/common/common.vcxproj, src/common/common.vcxproj.filters, src/modules/launcher/Microsoft.Launcher/dllmain.cpp, src/runner/runner.vcxproj, src/runner/settings_window.cpp
This PR fixes the issue of PowerLauncher.exe getting launched on OS version less than 19H1 and also makes a few changes to the os-detection project structure.
- os-detect.cpp and os-detect.h references have been added to `common` project. That way we can use the functions in C++ executables/dlls directly by referencing and without requiring os-detection.dll in that folder.
- The reference to os-detection.dll in runner has been removed, and instead the method is accessed from common
- os-detection.dll is still required for Image Resizer so no change has been made to affect that. In the future we could merge os-detection.dll into the PowerToysInterop library to reduce the number of additional projects/dlls.
- In the Microsoft.Launcher project (which is the PowerToyModule project for PT …
=> Tweaked OS Detection project structure and added os check for PT Run

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs
Added support to search packaged apps which are in development mode
1. https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.isdevelopmentmode?view=winrt-18362#Windows_ApplicationModel_Package_IsDevelopmentMode
2. https://docs.microsoft.com/en-us/windows/win32/stg/stgm-constants
Packaged apps that are in development mode were previously ignored during indexing of programs. This PR removes this restriction. The `grfMode` for `SHCreateStreamOnFileEx` is also changed because `Stgm.ShareExclusive` was preventing a second read of the AppxManifest.xaml in the `IfApplicationcanRunElevated` function. 
Manually validated that apps in development mode are shown in PowerToys Run. Following steps were followed for validation : 
1. Create a Blank UWP project. 
2. Start a debugging …
=> Search packaged apps in development mode

src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Main.cs
Launcher is broken with network path and is opening documents folder instead of the searched path
The folder plugin is doing sanitization of the searched path removing duplicated slashes and backslashes but network path must start with `\\`
1. Open Launcher
2. Write a network path `\\localhost\c$\windows`
3. Press enter
=> Fix Launcher Network Path

src/modules/powerrename/lib/PowerRenameRegEx.cpp
When "Match All Occurrences" option is not selected, PowerRename was searching for the first occurrences manually and replacing it with the new string as raw text. Now it uses regex_replace() function with 'format_first_only' flag which makes the function replace only first occurrence.
=> [PowerRename] capturing groups fix

src/runner/main.cpp
When starting PT, general settings need to be applied to reflect actual settings from json file.
1)
Installed PT 0.17
Installed PT 0.18
Check that PT runs on restart without UAC prompt
2)
Delete all settings
Fresh install PT with "start at logon" checked
Check that `Run on startup` general setting is on
Check that PT actually runs at logon
=> [Runner] Apply general settings on runner startup

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/util.cpp
Since we are supporting app zone history on multiple work areas (virtual desktops, monitors) we need to distinguish on which monitor window should be opened (within same virtual desktop) and try to zone it there based on app zone history, if possible:
1. Use monitor on which cursors is currently possitioned and virtual desktop on which is window that we want to zone. If in that work area we have zone history for this process, zone it.
2. If we failed to zone window in previous step for any reason, fallback to previosus solution, which is primary monitor (windows is always opened on primary monitor).
1. Two (or more) monitor setup. Create two (or more) virtual desktops.
2. Open several instances of same application and zone it on different monitors / virtual desktops.
3. Check …
=> [FancyZones] Move window into last known position on active work area (if possible)

src/action_runner/action_runner.cpp, src/common/updating/updating.cpp, src/common/updating/updating.h, src/runner/main.cpp, src/runner/update_state.cpp, src/runner/update_state.h, src/runner/update_utils.cpp
- Try searching for .exe first, then fallback to .msi, since we may need to release early 0.19.X patches w/o implementing 
- Launch an .exe if it's found instead of using MSI Installation API
Test the updated code using custom .exe utility
=> Runner: autoupdate should prefer .exe installer instead of .msi

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32.cs
* The Description.Length is compared in apps which may not have it initialised leading to an exception.
This fixes that exception as the description is now initialized to an empty string object.
=> Fix exceptions thrown by uninitialized Win32 description

src/modules/fancyzones/lib/JsonHelpers.h, src/tests/win-app-driver/FancyZonesTests/EditorCanvasZoneResizeTests.cs, src/tests/win-app-driver/FancyZonesTests/EditorCustomLayoutsTests.cs, src/tests/win-app-driver/FancyZonesTests/EditorGridZoneResizeTests.cs, src/tests/win-app-driver/FancyZonesTests/EditorOpeningTests.cs, src/tests/win-app-driver/FancyZonesTests/EditorSettingsTests.cs, src/tests/win-app-driver/FancyZonesTests/EditorTemplatesApplyTests.cs, src/tests/win-app-driver/FancyZonesTests/EditorTemplatesEditTests.cs, src/tests/win-app-driver/FancyZonesTests/FancyZonesEditor.cs, src/tests/win-app-driver/FancyZonesTests/FancyZonesSettingsTests.cs, src/tests/win-app-driver/PowerToysSession.cs, src/tests/win-app-driver/PowerToysTrayTests.cs, src/tests/win-app-driver/TestShortcutHelper.cs
Removed assert from cleanup step that was able to stop program before settings files had been restored.
=> [WinAppDriver tests] Affection on user setting files fix

src/common/common.vcxproj, src/common/common.vcxproj.filters, src/common/debug_control.h, src/common/interop/KeyboardHook.cpp, src/modules/fancyzones/dll/dllmain.cpp, src/modules/fancyzones/lib/SecondaryMouseButtonsHook.cpp, src/modules/fancyzones/lib/ShiftKeyHook.cpp, src/modules/keyboardmanager/dll/dllmain.cpp, src/modules/shortcut_guide/shortcut_guide.cpp, src/runner/lowlevel_keyboard_event.cpp
Now we have a single switch to disable all KB/Mouse hooks for easier debugging.
* [x ] Applies to #4376
- verified that modules work with the switch disabled (FZ, SG, KM)
=> Runner: improve debugging experience with hooks

src/core/Microsoft.PowerToys.Settings.UI.Lib/ImageSize.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml, src/runner/main.cpp, src/runner/settings_window.cpp
- Added flags to hide and disable the "x" icon and the Hieght checkbox when unit is set to percentage. 
Question:
- Should we order by unit to group the percentage sizes so that the table looks consistent?
* [ x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/PowerToys) and sign the CLA
- Toggle the unit dropdown of the Image Sizes control to see if changes are applied
=> [Settings][Fix][Image Resizer ]  Unused text box when selecting custom percent in new settings

src/modules/fancyzones/lib/MonitorWorkAreaHandler.cpp
- do not return an address to a freed memory
=> FancyZones: fix possible crash in GetWorkAreasByDesktopId

installer/PowerToysSetup/Product.wxs, src/modules/launcher/Microsoft.Launcher/Microsoft.Launcher.vcxproj, src/runner/main.cpp, src/runner/powertoy_module.cpp, src/runner/powertoy_module.h
- move `Microsoft.Launcher.dll` to launcher module's folder
- simplify runner modules' dlls loading logic, now we only load known modules (since Settings V2 use a non-generated .xaml setting page for each module, we prefer to keep all toys developed in-tree etc.)
- build solution and installer, test that modules work
=> Runner: move Launcher to its own folder and simplify dll loading

src/common/common-md-flag/common-md-flag.vcxproj, src/common/interop/interop.vcxproj, src/runner/runner.vcxproj
- add include directories to a corresponding projects.
- build installer successfully
=> MSI: fix include dirs causing MSI pre-build event fail to build

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Settings.cs, src/modules/launcher/Wox.Test/Plugins/ProgramPluginTest.cs
This PR adds the functionality to index desktop programs and find games installed with Epic games gaming platform. 
1. Added functionality to index desktop programs. 
2. Added functionality to dedup .URL files. A dedup was caused when shortcut was present both in start menu and desktop.
3. Added support to find games installed through the Epic game platform. 
1. Manually validated that programs present on desktop are indexed.
=> Index Desktop Applications

src/core/Microsoft.PowerToys.Settings.UI.Runner/Microsoft.PowerToys.Settings.UI.Runner.csproj, src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj, src/modules/launcher/Wox.Infrastructure/Wox.Infrastructure.csproj, src/modules/launcher/Wox.Plugin/ContextMenuResult.cs, src/modules/launcher/Wox.Plugin/Wox.Plugin.csproj
1.) upgrade settings to latest WinUI package on 2.x branch
2.) upgrade xaml islands to 6.1.0
3.) Removed Xaml Host items inside launcher
tested both settings and PT run, both execute appropriately.
=> upgrade xaml based nuget packages

src/core/Microsoft.PowerToys.Settings.UI.Runner/MainWindow.xaml, src/core/Microsoft.PowerToys.Settings.UI.Runner/MainWindow.xaml.cs
This PR adds a workaround for the blank settings dialog issue. The issue was happening on machines with nView Desktop Manager, where it would intercept some window messages and cause WinUI to think the xaml island window was hidden. To work around this, in the WindowXamlHost when the ChildChanged event is called, if the window is not closed we call Show().
Since WPF does not have a property to check if the window is closing, we use the Closing event handler to set a bool variable to track if the window has started closing. This is required because Show throws an exception if the Closing or Closed handler have begun execution (more details [here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.closing?view=netcore-3.1))
Tested on a machine not reproducing the error and on …
=> Hotfix for blank settings dialog

src/common/interop/KeyboardHook.cpp, src/core/Microsoft.PowerToys.Settings.UI.Lib/HotkeySettingsControlHook.cs, src/core/Microsoft.PowerToys.Settings.UI/Controls/HotkeySettingsControl.xaml.cs
This PR fixes the issue of the Settings process not terminating when the FZ or PT Run page or opened. Because of the process not terminating, clicking the PowerToys icon from the systray wouldn't work. This was happening because there were threads created by the KeyboardHook object that weren't getting terminated. This was also resulting in new threads being created every time the FZ or PT Run page were opened, which could have perf/memory impact. With the changes in the PR, only one additional thread can be created at any point of time, and the thread is present only while the FZ or PT Run page are open.
- To fix this, in the Unloaded handler of the Hotkey user control we add a step to dispose the `KeyboardHook` object. This result in the KeyboardHook object's destructor getting called, …
=> Dispose keyboard hook object in Settings

installer/PowerToysSetup/Product.wxs, src/modules/launcher/PowerLauncher/PowerLauncher.csproj, src/modules/launcher/Wox/Wox.csproj
This PR fixes the build errors on PowerToysSetup and adds other missing dlls which would result in FZ, Settings and PT Run not working.
- Removed XamlHost dlls from launcher
- Added the Microsoft.Search.Interop nuget package back to the Wox project which was removed in #4423 since it is required to produce the dll when publishing the launcher project. For this a <NoWarn> tag had to be added to the package reference and the Wox project reference in the PowerLauncher project to prevent the warning being treated as error.
- Added ManagedCommon.dll to FZ, PT Run and Settings
- Added Telemetry.dll to FZ, and all the launcher plugin folders.
- Added Button.xbf to the Settings install files since that is generated in the output but was not copied in the installer.
- Installed and verified that …
=> Fix missing dlls in MSI for 0.19

src/modules/keyboardmanager/common/KeyDelay.cpp, src/modules/keyboardmanager/common/KeyDelay.h, src/modules/keyboardmanager/common/KeyboardManagerCommon.vcxproj, src/modules/keyboardmanager/common/KeyboardManagerConstants.h, src/modules/keyboardmanager/dll/KeyboardManager.vcxproj, src/modules/keyboardmanager/test/KeyboardManagerTest.vcxproj, src/modules/keyboardmanager/ui/KeyboardManagerUI.vcxproj
This PR enables code analysis on the Keyboard Manager projects and fixes the following warnings:
- GetTickCount overflow: To fix this, GetTickCount was changed to [GetTickCount64](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-gettickcount64) and all time variables were changed to DWORD64 instead of DWORD.
- Arithmetic casting overflow: To fix this, the constants used for UI dimensions were changed to DWORD64 instead of DWORD i.e. 8 byte values.
Manually validating by building and running on Debug/Release and checking if UI dimensions are correct in Edit Shortcuts (for 2nd warning fix), and if the hold Enter/Esc functionality is working as expected (for first warning fix).
=> Enable code analysis on Keyboard Manager projects

src/core/Microsoft.PowerToys.Settings.UI.Runner/Program.cs
This PR fixes the scenario of the settings process not terminating when the window is closed while FZ/PT Run pages are the current pages.
- The issue seemed to arise because even after the change in #4449, the Unloaded handler does not seem to get called when the window is closed and no destructor gets called either, even though the main thread was found to terminate.
- The ideal solution would be to find another event instead of Unloaded that would get fired in this scenario, but Window.Closed and Application.Suspending do not seem to get fired. This could be a xaml islands issue.
- The other alternative would be to modify the keyboardhook.cpp logic to add another thread which checks if the Settings window has been closed and if so it terminates the thread however that makes the code …
=> Fix settings process not terminating on FZ and PT Run pages

src/modules/launcher/Wox.Infrastructure/Image/ImageCache.cs, src/modules/launcher/Wox.Infrastructure/Image/ImageLoader.cs
* The memory used by PT Run was increasing on consecutive launches. One of the reasons for this to happen was that all the image icons were cached. 
* Even though the code had an upperlimit on the `maxCached` values which was set to 5000, this part of the code was never called unless powerToys was closed. 
* Therefore, since all the icons were being cached, the size of the dictionary continued to increase.
**Work around**-
* Instead of caching all images and increasing the size of the dictionary, the following changes have been made -
1. Reduce the number of cached images to 50.
2. If the number of images increase over the permissible factor (set to 2) of the cached images (ie. 2 * 50), then the ones which are infrequently used would be removed from the dictionary and there be 50 images …
=> Partial Fix for Memory issue - Limiting the number of ImageSources cached

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32.cs
* Some results were weighted higher than the others because of a match in the description name. So this PR temporarily fixes that issue by reducing the score of the description by half, while calculating the score of the result.
* Going forward, we need to decide a better weighting strategy. Some work regarding that is in this branch - https://github.com/alekhyareddy28/PowerToys/tree/prioritize_scoring, where the score is converted to a class object instead of an integer. It is a Work in progress.
Visual no longer pulls up excel.
=> Scoring Tweak - Reduced the description weight by half

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
This fixes the casing issue for the hint text. The fix involves using the same casing as the query for the part of the hint string that is matched.
Manually validated that it appears correctly
=> Fixed hint text casing

src/modules/launcher/Wox.Infrastructure/Image/ImageCache.cs
Resolves this exception which occurs after the dictionary is resized and app_error or app.png was removed.
- While resizing we skip the key if it matches either ErrorIcon or DefaultIcon.
Manually validated that the exception isnt hit in a repro scenario.
=> Skip ErrorIcon and DefaultIcon while resizing the dictionary

src/runner/general_settings.cpp, src/runner/general_settings.h, src/runner/main.cpp
This PR fixes the issue where settings.json `enabled` section gets reset when PowerToys is launched. This is happening because of the change in #4302 . When `apply_general_settings` is called, the modules() variable is empty (since that is loaded only after `runner()` is called), because of which the save to json step stores the enabled module set as empty. This results in all modules getting enabled. To avoid this an extra arg was added to that method, which is by default true. If it is set to false, we do not save to json. Since the default arg is true, the change only affects this particular function call.
- Launched PowerToys from clean settings, and from existing settings and verified that correct modules are enabled.
- Validated if the issue fixed by #4302 is still fixed.
=> Fix settings issue where settings.json would get reset on runner startup

src/modules/fancyzones/lib/WindowMoveHandler.cpp
Fixed shift behavior to disable zones when both mouse and shift checkboxes toggled off
1. Toggled off checkboxes "Hold Shift key..." and "Use a non-primary mouse..."
2. Checked that shift disables zones
=> [FancyZones] Fixed shift behavior

src/modules/launcher/PowerLauncher/ResultList.xaml
Fix for following error on startup : 
`System.Windows.Data Error: 40 : BindingExpression path error: 'MinHeight' property not found on 'object' ''ResultsViewModel' (HashCode=31815862)'. BindingExpression:Path=Results.MinHeight; DataItem='MainViewModel' (HashCode=12698356); target element is 'ListView' (Name='SuggestionsList'); target property is 'MinHeight' (type 'Double')
`
This error is being thrown because the corresponding Binding property is not present in `ResultsViewModel` class. 
!-- Describe how you validated the behavior. Add automated tests wherever possible, but list manual validation steps taken as well -->
Manually validated that error is not thrown on startup
=> Fix for Binding error on startup

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/modules/launcher/Wox.Test/MainViewModelTest.cs, src/modules/launcher/Wox.Test/Wox.Test.csproj, src/modules/launcher/Wox/ViewModel/MainViewModel.cs
Fix to update search box text with selected program name when navigating using the keyboard.  
Manually validated that search box text is updated with program name when navigating using the keyboard.
=> Added fix to update text on navigation using up/down arrow

src/modules/fancyzones/lib/ZoneWindow.cpp
See the referenced issue for details.
Instead of using one loop to draw both the active and inactive zones in a predefined order, draw the inactive zones in the first loop and the active zones in the second loop.
Manually tested with focus template and custom layouts.
=> [FancyZones] draw active zones on top of inactive zones

src/common/interop/HotkeyManager.cpp, src/common/interop/HotkeyManager.h, src/common/interop/KeyboardHook.cpp, src/common/interop/KeyboardHook.h, src/core/Microsoft.PowerToys.Settings.UI.Runner/Program.cs
This PR reworks the KeyboardHook and HotkeyManager interop classes to a much more simplistic form, which uses GetAsyncKeyState. The following behavior has been changed:
- Earlier the KeyboardHook class used to create a second thread, and the hook would add events to a queue and the thread would process these events. This could be a potential source of perf and concurrency issues when it comes to keyboard events. Now this has been avoided by directly processing the event in the low level hook itself rather than having an extra thread for it. (Similar to what is done for other hooks in PowerToys).
- Earlier the HotkeyManager would process every key event and and store its state in a variable. This had a major issue that it could cause hotkeys to be fired even with the incorrect order for …
=> Rework the HotkeyManager and KeyboardHook interop classes

src/modules/launcher/Plugins/Microsoft.Plugin.Folder/ContextMenuLoader.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Languages/de.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Languages/en.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Languages/pl.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Languages/tr.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Languages/zh-cn.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Languages/zh-tw.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/ContextMenuLoader.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Languages/de.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Languages/en.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Languages/ja.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Languages/pl.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Languages/tr.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Languages/zh-cn.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Languages/zh-tw.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Microsoft.Plugin.Indexer.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Languages/de.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Languages/en.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Languages/ja.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Languages/pl.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Languages/tr.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Languages/zh-cn.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Languages/zh-tw.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Languages/de.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Languages/en.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Languages/pl.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Languages/tr.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Languages/zh-cn.xaml, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Languages/zh-tw.xaml
- This PR adds the keyboard shortcut for all the context menu buttons.
- It adds a languages folder to the indexer plugin to localize the strings.
- Folder Plugin
- Indexer Plugin
- Program Plugin
- Shell Plugin
=> Add keyboard shortcut in tooltip for context menu items

src/common/os-detection/os-detect.cpp
As suggested in [this](https://github.com/microsoft/PowerToys/issues/4432#issuecomment-651280300) comment, there was a race condition in the os detection code making it thread unsafe. 
- https://github.com/microsoft/PowerToys/issues/4432#issuecomment-651280300
- I was able to reproduce the race condition using mutexes. When one thread calls `UseNewSettings` with value as 0 and the other calls with value as 1, one of the threads returns `true` and the other returns `false`.
- The below code forces one thread to set the `isAPIContractVxAvailableInitialized` value to `true` and yields to the other thread before setting the value for `isAPIContractVxAvailable`, leaving it to be `false`. Now the second thread has `isAPIContractVxAvailableInitialized` set to true, because of the other thread …
=> Mitigated the race condition in os detection

src/modules/keyboardmanager/dll/KeyboardEventHandlers.cpp, src/modules/keyboardmanager/test/OSLevelShortcutRemappingTests.cpp
This PR fixes a scenario where a user could remap Alt+A->Ctrl+A, Alt+V->Ctrl+V and if you press Alt+A, release A and press V, Ctrl+V was not getting invoked. This was happening because when we fixed Alt+Tab style shortcuts in #3965, we changed the behavior such that we release the remapped modifier only after a key apart from the invoked shortcut's keys are pressed. When this would happen, we would reset the keyboard state to whichever keys should be physically pressed at that time, however we were sending all the keys including the latest pressed key (V in the example), with the `KEYBOARDMANAGER_SHORTCUT_FLAG`, because of which when the system received Alt+V it would not remap it to Ctrl+V. The fix involves removing the flag for that particular key event. We still keep the shortcut flag …
=> Fix remapped shortcuts not getting activated in succession

src/core/Microsoft.PowerToys.Settings.UI.Lib/ImageSize.cs, src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/ImageResizer.cs
Added validation for Image resizer number Width and Height fields.
Checks includes checking negative numbers and non-number values.
#4701
- deleted the width and height value to see if the settings crash.
=> added null value handle for image resizer size input

src/modules/fancyzones/editor/FancyZonesEditor/GridEditor.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/Settings.cs
Applying e.g. 5-zones grid layout is different then shown in editor. Fix populating cell child map in Editor but without affecting zone numbers increasing from left to right.
- Apply 5-zones grid layout.
- Check that applied layout is the same as shown in Editor.
- Check that cycling window through zones via Win+number is following zones numbers
- Unit tests are passing
=> [FancyZones Editor] Fix odd-number zones Grid layout difference between Editor and engine 

src/modules/fancyzones/lib/FancyZones.cpp
We need to handle `WM_SETTINGCHANGE` (wparam indicating `SPI_SETWORKAREA`) and `WM_DISPLAYCHANGE` in such manner that cached work areas are deleted, and recreated again with up to date information.
1. Set one of the template zone layouts.
2. Assign window to one of the zones.
3. Change position of taskbar (left, top, right, bottom).
4. Change DPI and resolution of the screen.
Expected result: Work areas are updated on every change, so are the windows zoned into the layout (of course, for updates in window positions make sure You have _Keep windows in their zones when the screen resolution changes_ ON).
=> [FancyZones] Invalidate cached work areas when display resolution or taskbar position changes

src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/Settings.cs, src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/JsonHelpers.cpp, src/modules/fancyzones/lib/JsonHelpers.h, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/ZoneWindow.h, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp
- Removed 3 tmp paths from Editor cmd args.
- Editor now reads Custom Layouts from zone-settings.json itself (this enables debugging custom layouts as well)
- Introduce "Debug arguments" so Editor can be easily run as a standalone app for debugging purposes. (passing "Debug" as only cmd arg to Editor)
- Introduce checks for invalid arguments passed to Editor
Run Editor with all of the valid&invalid arguments passed. Tested whether FancyZones still works as expected.
=> [FancyZones] Remove Editor tmp files paths cmd args and make Editor 'debugable' easier 

doc/devdocs/readme.md
Due to changes in the directory structure of the `doc/images` folder, the link for `examples_settings.png` was broken and image was not showing up. I have fixed the link and image is showing up in the README.md file.
The image link was broken and it was not showing up. 
Checked if the link is properly displaying the image or not.
=> Fixed the broken link for example_settings.png

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/CanvasLayoutModel.cs, src/modules/fancyzones/lib/ZoneSet.cpp
When applying Focus layout, new (duplicate) custom layout is created. This should not happen. The issue was introduced with scaling logic for custom canvas layout where data was persisted (reported as a new custom layout) on applying all existing canvas layouts, but should be just for scaled ones.
Apply Focus layout and confirm that new custom layout is not created.
Run unit tests.
=> [FancyZones] Don't create new custom layout when applying Focus layout

src/modules/fancyzones/lib/JsonHelpers.cpp, src/modules/fancyzones/lib/JsonHelpers.h, src/modules/fancyzones/lib/WindowMoveHandler.cpp
If there are several windows of same application zoned in same work area, app zone history is remembered for only one of them. If that window is removed from zone, we need to try to update app zone history with zone set from some other window (of same application). If there are several options, windows are sorted by creation time and oldest (earliest started process).
1. Create zone layout on one of the monitors (it behaves same for both primary and secondary monitors). For example three zone column.
2. Assign window to zone 0.
3. Open on same monitor another window of same application (gets zoned on opening to zone 0).
4. Zone that new window to a zone 1. **History still shows zone 0 -> expected**
5. Move first window out of zone. **History updated, now history shows zone 1 (belonging to …
=> [FancyZones] Update app zone history on window removal

src/common/interop/HotkeyManager.cpp
This PR tweaks the HotkeyManager code such that a dummy key event is sent after invoking the shortcut. This is required to prevent Start Menu from popping up in the scenario where user releases Win key before Space (if Win+Space is the shortcut). The same procedure is done in Keyboard Manager when remapping shortcuts, because in case of Windows shortcuts Start menu appears, and if its an Alt based shortcut, the application's menu bar may get triggered.
Validated manually that Start menu doesn't open while releasing Win key before Space.
=> [PT Run] Added dummy key event to prevent Start Menu from popping up

README.md
In README.md the name of the msi installer was `PowerToysSetup-0.19.0-x64.msi` which was the old version, it has now been updated to the new version which is `PowerToysSetup-0.19.1-x64.msi`
=> upgraded the version number of .msi installer file in README

src/modules/fancyzones/lib/ZoneSet.cpp
The previous implementation prevented you from selecting multiple zones by hovering between them, even when they overlap by 1 pixel. Now you can do this.
Relevant issue: #4957
Overlap two zones by a few pixels and check if both are selected when the mouse is placed between them.
=> Allow selecting multiple adjacent zones even when they slightly overlap

src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Programs/UWPTests.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/PackageWrapper.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/PackageRepository.cs
- While trying to retrieve the installed location of a packaged app using `package.InstalledLocation.Path`, a FileNotFound Exception is thrown if the path does not exist. Added a catch block to capture that exception and to prevent PT from crashing.
=> Fix for File Not Found exception while indexing invalid Package App

src/modules/fancyzones/editor/FancyZonesEditor/FancyZonesEditor.csproj, src/modules/fancyzones/editor/FancyZonesEditor/GridData.cs, src/modules/fancyzones/editor/FancyZonesEditor/GridDragHandles.cs, src/modules/fancyzones/editor/FancyZonesEditor/GridEditor.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/GridResizer.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/GridLayoutModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/Settings.cs, src/modules/fancyzones/editor/FancyZonesEditor/RowColInfo.cs
* Fixed
* missing grid resizers
* moving grid resizers after merge
* gap between zones and taskbar
* Added possibility to move grid resizers along whole available space of row/column. 
* Refactored code and changed some data structures (raw arrays to lists)
* Missing grid resizers fix:
* Gap between zones was caused by calculation error after splitting zones. Zones are represented as a percentage of the whole screen, and after calculations total percentage could be less than original `10000`. 
* After merge zones redundant data wasn't removed. This caused the problem that users can't move dividers over the other dividers that are still present in data structures, but invisible for users.
* Dividers now can be moved through whole available area
=> [FZEditor] Grid layout resizers fixes

src/modules/launcher/Wox/ViewModel/MainViewModel.cs
Fix issue with results appearing on empty query. 
The issue happened because of incorrect sync between clearing and adding results. When results were delayed from a plugin they were added 
1. Query `Q1` is made which starts a new thread `T`. 
2. Query `Q2` is made which is an empty query causing clearing of results. 
3. Thread `T` writes back result of `Q1` since it has not been canceled in step 2.
1. Add `Thread.Sleep(1000)`  just before [this](https://github.com/microsoft/PowerToys/blob/master/src/modules/launcher/Wox/ViewModel/MainViewModel.cs#L431) line. 
Manually validated that all tests pass and results are not displayed on an empty query.
Note : No tests have been added for this because we cannot easily mock `PluginManager` which is a static class.  `PluginManager` cannot be made …
=> Fix for result on empty query

src/action_runner/action_runner.cpp
See original issue for why we need this fix.
tested multiple executables with that `ShellExecuteExW` invocation:
- which returns 0 
- which sleeps for 30s before exiting
- which crashes instantly
=> autoupdate: wait for the .exe updater to exit before restarting PowerToys

installer/PowerToysSetup/Product.wxs
This change adds a ContextMenuOptIn registry name which is required for shell context menu extensions to appear on the context menu for OneDrive placeholders. 
See https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/ne-shobjidl_core-default_folder_menu_restrictions.
Applies to https://github.com/microsoft/PowerToys/issues/708
=> Fix registration of PowerRename to work with OneDrive placeholders

src/modules/fancyzones/lib/WindowMoveHandler.cpp, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/ZoneWindow.h, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp
Removed unnecessary check that broke functionality during moving the window across monitors.
Moved part with checking if elevated window could be snapped to a zone outside the `UpdateDragState`. It's enough to call it once when dragging was started.
`ZoneWindow::MoveSizeEnter` has been called only from `WindowMoveHandler::MoveSizeStart` and required `m_windowMoveSize` not to be assigned. After some changes `ZoneWindow::MoveSizeEnter` call was added to `WindowMoveHandler::MoveSizeUpdate` that made this requirement invalid. 
- Have all FZ options on
- Create a zone layout on two adjacent monitors
- Drag a window from one monitor to another, then back to the first monitor
The dragged window should stay transparent until dropped.
=> [FancyZones] Dragging a window across monitors transparency fix

src/common/keyboard_layout.cpp
- Updated the name for `VK 93` to `Apps/Menu` instead of `Menu`, since it is documents as `Applications key` in [documentation page](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes), however it is also known as the Menu key.
- Added key names for all the IME keys which are documented in the msdn page. VK_IME_ON and VK_IME_OFF were not added since they do not exist in Windows SDK even though they are documented in the msdn page.
Checked if the correct key names appear in the KBM drop downs.
=> [KBM] Updated menu key name, and added missing IME key codes

src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditorWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditorWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/Settings.cs
Addresses issue #1653, resets the position of new zones that would appear more than halfway off the screen. Also made default zone size smaller
If a new zone was detected to be more than halfway across the screen (vertically or horizontally), then reset its position to (100,100) which is the starting coordinate of the first added zone. 
The default size of added zones was changed from WorkArea.Width/WorkArea.Height * 0.6 to WorkArea.Width/WorkArea.Height * 0.4. Also, the delta/offset decreased from 100 to 50. 
Manually Validated
**OLD:** 
**NEW:**
=> [FancyZones Editor] Prevent new zones from being unreachable

src/core/Microsoft.PowerToys.Settings.UI.Lib/ColorPickerProperties.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/FZConfigProperties.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/HotkeySettings.cs, src/core/Microsoft.PowerToys.Settings.UI/Controls/HotkeySettingsControl.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/FancyZonesViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml
- Adjusting key to be Win+Shift+C to match 
- This does conflict with "charms" but can't seem to find an app that uses this.
- adjusted location for Color Picker
- Redid how HotKeySettings works since Key is actually orphaned
- created a readonly static property for FancyZones so single default values
- disabling cursor override for now
=> Color picker tweaks

src/core/Microsoft.PowerToys.Settings.UI.Lib/BasePTModuleSettings.cs
This PR fixes the issue where all the JSON properties do not get serialized to the settings file from PT Settings.
If JsonSerializer is called drectly n the base class, only the properties in that class get serialized. More details here https://stackoverflow.com/questions/62498668/jsonserializer-serialize-only-serializes-the-properties-of-the-base-class
Validated after deleting the keyboard manager settings.json that it is created in the correct format.
=> Fix saving to JSON in PT Settings

src/modules/launcher/PowerLauncher.Telemetry/Events/LauncherColdStateHotkeyEvent.cs, src/modules/launcher/PowerLauncher.Telemetry/Events/LauncherHotkeyEvent.cs, src/modules/launcher/PowerLauncher.Telemetry/Events/LauncherWarmStateHotkeyEvent.cs, src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
This PR adds two telemetry events:
- Logging the cold state hotkey event time, i.e. after opening PowerToys the first time Alt+Space is pressed, till the PT Run window is visible.
- Logging the warm state hotkey event time, i.e. after the first hotkey event has been done, all successive Alt+Space hits till PT Run is visible. In both these events, the time is only recorded for making PT Run visible, not for hiding it.
Since the Stopwatch for measuring the time had to be started in the view model's `OnHotkey` method and stopped in the MainWindow.xaml.cs OnVisibilityChanged handler, the Stopwatch variable was added as a member to the view model, and it is accessed by public TimerStart/Stop methods.
Validated that the events are emitted using the steps provided in the telemetry Readme using …
=> Add telemetry event for measuring time taken to display PT Run

src/modules/launcher/Wox.Infrastructure/Storage/StoragePowerToysVersionInfo.cs
This PR adds additional checks in the `StoragePowerToysVersionInfo` `LessThan` method, to avoid exceptions if the version format is not correct in the version file. This was added because of the exceptions some users reported in their logs:
System.FormatException: Input string was not in a correct format.
Source: System.Private.CoreLib
TargetAssembly: System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
TargetModule: System.Private.CoreLib.dll
TargetSite: Void ThrowOverflowOrFormatException(ParsingStatus, System.TypeCode)
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
at Wox.Infrastructure.Storage.StoragePowerToysVersionInfo.Lessthan(String version1, String version2)
at …
=> [PT Run] Add additional checks in version info methods to avoid exceptions

src/modules/launcher/PowerLauncher/Languages/da.xaml, src/modules/launcher/PowerLauncher/Languages/de.xaml, src/modules/launcher/PowerLauncher/Languages/en.xaml, src/modules/launcher/PowerLauncher/Languages/fr.xaml, src/modules/launcher/PowerLauncher/Languages/it.xaml, src/modules/launcher/PowerLauncher/Languages/ja.xaml, src/modules/launcher/PowerLauncher/Languages/ko.xaml, src/modules/launcher/PowerLauncher/Languages/nb-NO.xaml, src/modules/launcher/PowerLauncher/Languages/nl.xaml, src/modules/launcher/PowerLauncher/Languages/pl.xaml, src/modules/launcher/PowerLauncher/Languages/pt-br.xaml, src/modules/launcher/PowerLauncher/Languages/ru.xaml, src/modules/launcher/PowerLauncher/Languages/sk.xaml, src/modules/launcher/PowerLauncher/Languages/sr.xaml, src/modules/launcher/PowerLauncher/Languages/tr.xaml, src/modules/launcher/PowerLauncher/Languages/uk-UA.xaml, src/modules/launcher/PowerLauncher/Languages/zh-cn.xaml, src/modules/launcher/PowerLauncher/Languages/zh-tw.xaml, src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/modules/launcher/PowerLauncher/ReportWindow.xaml, src/modules/launcher/PowerLauncher/ReportWindow.xaml.cs, src/modules/launcher/Wox.Infrastructure/Image/ImageLoader.cs, src/modules/launcher/Wox.Infrastructure/Wox.cs
- Many of the Event Viewer logs where users observed crashing of PowerToys have an exception as follows - 
`System.IO.IOException: Cannot locate resource 'images/app_error.png'.`
This is because we made the app icons theme aware and the image app_error.png no longer exists. Due to this whenever there is an exception in the Dispatcher thread, an error reporting window is supposed to pop up, but PT Run crashes instead of showing that window because the img file no longer exists.
The changes made in this PR are as follows -
- Modified the error icon so that the window pops up as expected.
- Changed the User facing name of app to PT Run in the error reporting window.
- `Process.Start(uri)` throws a file not found exception in .NET Core apps, hence it had to be changed to use ProcessStartInfo …
=> Fix for handling exceptions thrown by dispatcher which were crashing PT Run

src/modules/launcher/Wox.Infrastructure/Image/ImageCache.cs, src/modules/launcher/Wox.Infrastructure/Image/ImageLoader.cs
As a part of this PR - #5199, theme aware default icons were added. However, these default icons must be added to the usage dictionary without which an exception would be thrown.
- Manually validated that it does not throw that exception anymore.
=> Add theme aware default icons to usage dictionary

src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutModel.cs
If custom layout data is malformed for some reason (user entered data manually in zones-settings.json, some error in FZ malformed the data, etc..) error message is shown to user with appropriate message and malformed custom layout is not loaded into Editor.
Copy of https://github.com/stefansjfw/PowerToys/pull/23
Manually updated zones-settings file to contain malformed custom layouts and confirm that error message is shown & layout is not shown in Editor.
Unit tests.
=> [FancyZonesEditor] Don't load malformed custom layout and show appropriate message

src/core/Microsoft.PowerToys.Settings.UI.Runner/MainWindow.xaml, src/core/Microsoft.PowerToys.Settings.UI/Styles/_Sizes.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml
This PR adds back the NavigationView collapse button. With it, it comes with auto collapsing when resizing the window, which is great for smaller screen sizes. The default window width was increased to 1100 so the navview auto expands.
=> [Settings] Adding collapse button to settings navview

src/bootstrapper/bootstrapper.cpp, src/common/RcResource.cpp, src/common/RcResource.h
`<span>` isn't available on the older compilers
compile bootstrapper and launch it
=> CDPx: do not use span header

tools/build/build-essentials.ps1
- Implement helper PowerShell script which can be easily configured for your most used projects:
- VS tools should be available in %PATH%
- invocation dir isn't important
=> chore: add most used projects helper build script

src/runner/main.cpp
We've tried investigating [the issue mentioned here](https://github.com/microsoft/PowerToys/pull/5204#issuecomment-664419659) with @ivan100sic and it looks like atm we could only handle exceptions and report the error for visibility.
- update PT
=> autoupdate: handle exceptions in download_update

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/PackageWrapper.cs
In certain situations such as uninstall, the path of a UWP/packaged application will be invalid.  In this situation we still want to include the available information so that it can be compared to currently stored applications in the results. 
Performed the validation step included in #5372, and verified that we get the expected results.
=> Including valid package information when path is invalid. 

src/modules/launcher/PowerLauncher/Helper/ResultCollection.cs, src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs, src/modules/launcher/PowerLauncher/ViewModel/ResultsViewModel.cs
This PR improves query cancellation and performance of `ResultCollection`
1. https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.removeall?view=netcore-3.1#System_Collections_Generic_List_1_RemoveAll_System_Predicate__0__
2. https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1.remove?view=netcore-3.1#System_Collections_ObjectModel_Collection_1_Remove__0_
1. Changed `ResultCollection` base class from `ObservableCollection` to `List`. This was done to improve the bulk deletion of plugin results. `ObservableCollection` does not provide any bulk deletion function and each atomic remove operation is `O(n)`, resulting in `O(n^2)` overall complexity. `List` provides `RemoveAll` function which deletes all the elements matching a …
=> Improve query cancellation and ResultCollection performance

src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
Fixes #4624
Added scrollbar to the input field for excluded apps in the Fancy Zones settings page
In the Fancy Zones settings section, new vertical scrollbar for the excluded apps section
Launch Settings
Go to Fancy Zones
Scroll down to the excluded apps
Type several lines until vertical scrollbar shows up
=> Fancy Zones | #4624 Added scrollbar to the input field for excluded apps

src/modules/colorPicker/ColorPickerUI/Helpers/Logger.cs, src/modules/colorPicker/ColorPickerUI/Settings/UserSettings.cs
When there is an issue in reading settings and exception is thrown (other than IOException) it will loop infinitely and append logs non-stop.
I suspect this is the issue #5555
=> Fixing potentially infinite loop with logs in Color Picker

src/bootstrapper/bootstrapper.cpp, src/common/notifications.cpp, src/common/notifications.h, src/runner/main.cpp
Provide a default app id to fix FZ toast crash.
- installed PT
- bootstrapper toasts work
- "dragging elevated window" warning toast works
=> notifications: provide default app id to fix FZ toast crashes

src/common/common.cpp, src/common/common.h
We detect installed dotnet versions using `exec_and_read_output` function. It created a child process, waited for its termination, then read its stdout from an anonymous pipe. That didn't work for some users, causing `dotnet` process to hang indefinitely, specifically for those who had so many dotnet versions installed, that `dotnet --list-runtimes` output exceeded the default anonymous pipe buffer size - 4KB. 
That caused dotnet process to block on some printf/Writeline call until the pipe buffer has space again. However, we were waiting indefinitely for the process to terminate instead of reading from the pipe buffer, as a result, we've had a deadlock.
This PR fixes the issue by reworking `exec_and_read_output` to have a default `30s` timeout value and employs overlapped I/O, since …
=> Fix bootstrapper getting stuck on "installing dotnet"

src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
In 0.20, terminating PowerToys from the Task Manager results in an exception in PT Run, which prevents it from quitting properly. This fixes the exception.
Added a null check. This should have been there anyway.
Checked that PT Run exits when PowerToys.exe is terminated.
=> Fixed Launcher not exiting when PT is terminated

src/core/Microsoft.PowerToys.Settings.UI.Runner/Microsoft.PowerToys.Settings.UI.Runner.csproj
This configures the generated "AssemblyTitleAttribute" which is used in TaskManager / Right Click Task Menu
[assembly: System.Reflection.AssemblyTitleAttribute("PowerToys Settings")]
- Run Microsoft.PowerToys.Settings.UI.Runner
- Right click Taskbar icon and validated name
- Open Task Manager and validated name
Task Bar:
Task Manager:
=> [Settings] Right-clicking on Settings in taskbar shows the correct title 

src/modules/launcher/PowerLauncher/App.xaml.cs
While #5560 and #5588 fixed the null reference exceptions, if for some reason an exception occurs while disposing the PowerLauncher.exe process will not terminate. This can be reproduced easily by adding a `throw new Exception()` line at the end of the Dispose method, and exiting PowerToys.exe from task manager, the PowerLauncher process does not get terminated. This occurs because Dispose is being called from Task.Run in the WaitForPowerToysRunner method, and Task.Run does not rethrow exceptions on the main thread, unless a Task.Wait statement is present after it. However we cant add Task.Wait here since we dont want this thread to be blocking. To resolve this we can use try/finally and ensure Environment.Exit(0) is always called when runner exits.
protected virtual …
=> Fixed exceptions in dispose not allowing PT Run to terminate

installer/PowerToysSetup/PowerToysSetup.wixproj, installer/Version.props, src/Version.props, src/bootstrapper/bootstrapper.vcxproj, src/common/ManagedCommon/ManagedCommon.csproj, src/common/ManagedTelemetry/Telemetry/Telemetry.csproj, src/common/common.vcxproj, src/common/interop-tests/Microsoft.Interop.Tests.csproj, src/common/interop/interop.vcxproj, src/core/Microsoft.PowerToys.Settings.UI.Lib/Microsoft.PowerToys.Settings.UI.Lib.csproj, src/core/Microsoft.PowerToys.Settings.UI.Runner/Microsoft.PowerToys.Settings.UI.Runner.csproj, src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj, src/core/Microsoft.PowerToys.Settings.UnitTest/Microsoft.PowerToys.Settings.UnitTest.csproj, src/modules/colorPicker/ColorPickerUI/ColorPickerUI.csproj, src/modules/fancyzones/editor/FancyZonesEditor/FancyZonesEditor.csproj, src/modules/imageresizer/tests/ImageResizerUITest.csproj, src/modules/imageresizer/ui/ImageResizerUI.csproj, src/modules/launcher/PowerLauncher.Telemetry/PowerLauncher.Telemetry.csproj, src/modules/launcher/PowerLauncher/PowerLauncher.csproj, src/modules/previewpane/MarkdownPreviewHandler/MarkdownPreviewHandler.csproj, src/modules/previewpane/PreviewPaneUnitTests/UnitTests-MarkdownPreviewHandler.csproj, src/modules/previewpane/SvgPreviewHandler/SvgPreviewHandler.csproj, src/modules/previewpane/UnitTests-PreviewHandlerCommon/UnitTests-PreviewHandlerCommon.csproj, src/modules/previewpane/UnitTests-SvgPreviewHandler/UnitTests-SvgPreviewHandler.csproj, src/modules/previewpane/common/PreviewHandlerCommon.csproj, src/tests/win-app-driver/win-app-driver.csproj
MSB3052 throws warnings. 
1. migrated to src\Version.props instead of installer\Version.props
2. Migrated all project files to point to src\Version.props
3. moved var def for Versions that Installer used to that project file versus doing a daisychain props.
4. Testing build farm now - ~~https://github-private.visualstudio.com/microsoft/_build/results?buildId=9015&view=results~~ https://github-private.visualstudio.com/microsoft/_build/results?buildId=9025&view=results
Tested:
- Project SLN built
- Installer built
- Installer installed
=> Proper fix for MSB3052.  

src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
Adding null check before using the hotkeyManager.
Related to PR #5588 which added a check for the Dispose function of HotKeyManager but not the UnregisterHotKey function.
=> Adding null check for HotKey Manager before using unregister hotkey function

src/common/comUtils.cpp, src/common/comUtils.h, src/common/common.h, src/common/common.vcxproj, src/common/common.vcxproj.filters, src/runner/main.cpp, src/settings/main.cpp
To avoid `0x80070005` (Access denied) error in `wpnapps.dll` when trying to show toast in the context described in the title, it's crucial to add `L"(A;;0x7;;;IU)"` permission to the COM security descriptor and initialize COM with it.
- launched PowerToys from an elevated cmd shell from non-admin account
=> runner: initialize COM security, so toast notifications work in elevated context from non-admin account

src/core/Microsoft.PowerToys.Settings.UI.Runner/Microsoft.PowerToys.Settings.UI.Runner.csproj, src/runner/settings_window.cpp
- Path to settings executable is broken. This PR fixes it.
- Launched the settings from icon tray.
=> fix settings path

src/modules/fancyzones/lib/WindowMoveHandler.cpp, src/modules/fancyzones/lib/util.cpp, src/modules/fancyzones/lib/util.h
After window is moved away from zone into maximized state, we should not restore it back to original position, but rather keep it maximized.
Check show command from window placement, and skip resizing window if show command indicates maximized state.
1. Assign window to the zone.
2. Move window away from zone by dragging it to the top of the screen (essentially forcing it to go to maximized state).
Expected result: Window stays in maximized state.
=> [FancyZones] Do not restore maximized windows

src/modules/fancyzones/lib/util.cpp
Don't restore minimized windows after zone layout is updated. Update their placement information with modified position, but keep them minimized.
Show command from `WINDOWPLACEMENT` structure can only have one of the following values:
```
#define SW_HIDE             0
#define SW_SHOWNORMAL       1
#define SW_NORMAL           1
#define SW_SHOWMINIMIZED    2
#define SW_SHOWMAXIMIZED    3
#define SW_MAXIMIZE         3
#define SW_SHOWNOACTIVATE   4
#define SW_SHOW             5
#define SW_MINIMIZE         6
#define SW_SHOWMINNOACTIVE  7
#define SW_SHOWNA           8
#define SW_RESTORE          9
#define SW_SHOWDEFAULT      10
#define SW_FORCEMINIMIZE    11
#define SW_MAX              11
```
Checking show command should not be performed bit-wise since it could lead to undesired behavior.
1. …
=> [FancyZones] Don't restore minimized windows after layout is updated

src/modules/fancyzones/editor/FancyZonesEditor/Models/Settings.cs, src/modules/fancyzones/lib/ZoneSet.cpp
When applying focus layout, what was shown in Editor and what was actually applied was different. This PR fixes this behavior.
Apply focus layout
Open editor and confirm that layout preview matches with applied layout (hold shift and drag to show applied layout)
=> [FancyZones] Focus layout zones mismatch in Editor and applied layout

src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/IndexerSettings.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs
This PR fixes the MaxSearchCount being linked to the MaximumNumberOfResults in PT Settings. This was causing a 4 result cap on Indexer by default. This has been tweaked such that it is fixed to 30, and it can be changed in the future to be linked to some other appropriate setting.
- Remove the statement for updating the MaxSearchCount based on PT Run settings
- Set all default values to 30/
Validated by searching for files and checking the SQL query in the indexer plugin. In order to verify that it's working you will have to delete the Microsoft.Plugin.Indexer folder from AppData/Local/Microsoft/PowerToys/PowerToys Run/Settings/Plugins since it will try to load the value in that cache unless there is a …
=> Unlinked the MaxSearchCount value from Indexer Settings and set to fixed value of 30

installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp, installer/PowerToysBootstrapper/bootstrapper/pch.h, src/action_runner/action_runner.cpp, src/common/common.cpp, src/common/common.h
EXE installer now supports 3 cmd flags:
- `--no_full_ui` - uses reduced MSI UI, i.e. only the progress bar w/o dialogs and confirmations. toast progress bar is active
- `--silent` - no toast notifications, no MSI UI. UAC breaks MSI if the process isn't elevated, so we must relaunch installer elevated for it to work
- `--no_start_pt` - doesn't launch PowerToys after successful installation
- install PT with various flags combinations
- restart PT elevated
=> bootstrapper: add support for silent arg

src/runner/main.cpp
We now only notify the user that explorer may need restarting, instead of offering to restart it ourselves.
- compile powertoys
=> runner: don't try to restart explorer

src/core/Microsoft.PowerToys.Settings.UI.Runner/MainWindow.xaml, src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Styles/_Sizes.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/KeyboardManagerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
Especially on lower resolutions, the Settings page has some weird layout behavior when resizing the window. This PR fixes the following things:
- Improved layout behavior when resizing.
- Simplified the VisualStates
- Set a min window size for the WPF window, similar to min sizes for UWP apps (around 480px).
**Old behavior**
**New behavior**
=> [Settings] Updated adaptive trigger behavior

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml
- Moved the strings describing the various filename formatting options to the Resources file.
- Fixes incorrect label: #5518, #2795
=> [Settings] Localized image resizer filename formats

src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs, src/modules/launcher/PowerLauncher/ViewModel/ResultsViewModel.cs
Fix for clearing shell plugin results on updating query text
1. Current code only clears results for plugins which are returned by `PluginManager` for a given query. This causes an issue where if shell plugin was not valid for a query, results for it persisted in the list view. 
2. Changed naming of `_lastQuery` to  `_currentQuery` to make its use case clear.
Manually validated that shell plugin results are cleared.
=> Remove all plugin results on query change

src/common/on_thread_executor.h
If the `worker_thread` runs before the `_shutdown_request` is set to `false`, it could quit immediately, causing problems.
This PR makes sure that `_shutdown_request` is set to false before the thread starts.
Although we didn't verify it yet, this could change the behavior seen in #5626
Changed the initialization order. For more info, see [this reference](https://en.cppreference.com/w/cpp/language/constructor).
Built and ran PT, tested some basic functionality of FancyZones, turned it off/on, etc.
=> Potential fix for a crash in OnThreadExecutor

src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/SearchHelper/OleDBSearch.cs, src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
This PR handles the exceptions introduced in #5748 .
- On cancelling a query within the Parallel.ForEach loop the exception was not getting handled by the try catch block outside the loop, since it would appear as a System.AggregateException. This has been resolved by adding a try catch block for OperationCanceledException within the ForEach loop.
- When multiple indexer queries occur in parallel, the OleDbDataReader throws an exception. The exception is thrown on the older query, so we should ignore the exception. Earlier a check was added for whether `wDSResults` was closed and that solved the issue of the exception where we were calling HasRows or Read while the reader object was closed, however it didnt take account of the scenario where the reader gets closed …
=> [PT Run] Handled exceptions in indexer plugin and delayed execution logic

src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Microsoft.Plugin.Calculator.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Microsoft.Plugin.Folder.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Microsoft.Plugin.Indexer.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Microsoft.Plugin.Program.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Microsoft.Plugin.Shell.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Microsoft.Plugin.Uri.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Microsoft.Plugin.WindowWalker.csproj, src/modules/launcher/Wox.Core/Wox.Core.csproj, src/modules/launcher/Wox.Infrastructure/Properties/AssemblyInfo.cs, src/modules/launcher/Wox.Infrastructure/Wox.Infrastructure.csproj, src/modules/launcher/Wox.Plugin/Properties/AssemblyInfo.cs, src/modules/launcher/Wox.Plugin/Wox.Plugin.csproj, src/modules/launcher/Wox.Test/Wox.Test.csproj
A Type Load exception was being thrown by PowerLauncher as it expected the method `PushResults` to be implemented in `PublicAPIInstance`.
```
Application: PowerLauncher.exe
CoreCLR Version: 4.700.20.20201
.NET Core Version: 3.1.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException: Method 'PushResults' in type 'Wox.PublicAPIInstance' from assembly 'PowerLauncher, Version=0.20.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
at PowerLauncher.App.<>c__DisplayClass16_0.b__1()
at Wox.Infrastructure.Stopwatch.Normal(String message, Action action)
at PowerLauncher.App.OnStartup(Object sender, StartupEventArgs e)
at System.Windows.Application.OnStartup(StartupEventArgs e)
```
_What does …
=> Fix for PowerLauncher crash - Type Load Exception

src/settings/StreamUriResolverFromFile.h
Added default init value for `base_path` in `StreamUriResolverFromFile`.
=> Warning: uninitialized variable fix

src/common/common.vcxproj, src/common/dpi_aware.h
Removed `schwapi.lib`, `shcore.lib` from project dependencies, added link into the `dpi_aware.h`
=> Warning: additional dependencies in common project

src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Main.cs
Correcting floating point error.  Same tweak that Wox has.  Wonder why we didn't have it in.
https://github.com/Wox-launcher/Wox/blob/master/Plugins/Wox.Plugin.Calculator/Main.cs
=> Correcting floating point error on calculator

src/common/interop/KeyboardHook.cpp, src/common/interop/KeyboardHook.h
Changed calling convention of `KeyboardHook::HookProc`
=> Warning: calling convention changed

README.md
This adds an (unofficial) installation method for Scoop package manager users. Many developers using Windows (me included) use and love Scoop, so this would be a nifty addition to the Readme. 
I'm aware of the issues some users face because of installation from the 'extras' bucket, the reason being PowerToys does not have a portable installer yet. If that's a hurdle, I can make changes in this PR to install via the 'non-portable' bucket of Scoop instead. 
Changes to README.md file.
=> Add Scoop (Unofficial) installation method

src/core/Microsoft.PowerToys.Settings.UI.Lib/Microsoft.PowerToys.Settings.UI.Lib.csproj, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/Microsoft.PowerToys.Settings.UI.UnitTests.csproj
The `AnyCPU` configuration is not needed.
=> [Settings] Remove 'AnyCPU' build configuration

src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutModel.cs
If malformed custom layout is detected it gets deleted (only MessageBox was shown prior to this PR every time Editor was spawned - as layout wasn't deleted). 
- Open Editor
- Create Custom layout
- Make it malformed by manually editing zones-settings file (e.g. set any zone width to negative value)
- Open Editor again - Confirm that MessageBox is shown and that malformed custom layout is not shown in Editor
- Close Editor and open it once again to confirm that layout was properly deleted
=> [FancyZonesEditor] Delete custom layout if it has malformed data

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml
This PR fixes accessibility issues related to the general settings page of PowerToys Settings.
1. There was a tab related issue regarding the radio buttons where they were all not accessible by the keyboard. This was due to xaml islands. Replacing the `RadioButtons` control with a `StackPanel` and `TextBlock` fixed this issue. Now we can tab through all the elements and also use the arrow keys to navigate through the radio buttons in a cyclic manner.
2. When using a screen reader to read the entire content of the general settings page, only the word `Dark` was being read. Adding a label automation property so that whenever we tab into the radio buttons, the heading ie. `Settings Theme` is …
=> Fix accessibility issues related to the General Settings page

src/modules/launcher/PowerLauncher/Themes/Dark.xaml, src/modules/launcher/PowerLauncher/Themes/Light.xaml
This PR fixes the contrast issues indicated by the accessibility insights tool. 
1. Fixed subtitle contrast issue with background in light mode. 
2. Fixed subtitle contrast issue with background in dark mode. 
3. Fixed context menu glyph contrast issue with background in light mode. 
Manually validated using exact values (if possible) that contrast ratio is above the threshold.
=> Run UI contrast accessibility

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Main.cs
Fix `Sequence contains no elements` on calling max in program plugin.
`Sequence contains no elements` error was thrown when the program plugin returned empty results. This PR fixes this by explicitly checking for an empty list before calling this function. 
Manually validated that error is not thrown if the program plugin returns empty result.
=> Fix sequence empty exception on calling max in program plugin

src/modules/shortcut_guide/keyboard_state.cpp
Fix the range of virtual key codes when checking if any other key is pressed along with the `Win` key.
The new range only includes key codes that are well defined (see https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes)
See the fixed issues for repro steps and validation
=> [Shortcut Guide] fix Virtual-Key Code range

src/modules/fancyzones/lib/ZoneWindow.cpp
Capture strong reference in `ZoneWindow::ShowZoneWindow` to prevent this from being destructed during thread work.
Run `ZoneWindowUnitTests`, ensure that all tests passed without errors and exceptions.
=> [FancyZones] ZoneWindow: thread safety

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/FancyZonesLib.vcxproj, src/modules/fancyzones/lib/FancyZonesLib.vcxproj.filters, src/modules/fancyzones/lib/GenericKeyHook.cpp, src/modules/fancyzones/lib/GenericKeyHook.h, src/modules/fancyzones/lib/KeyState.h, src/modules/fancyzones/lib/WindowMoveHandler.cpp, src/modules/fancyzones/lib/WindowMoveHandler.h
Handle key state with Sticky Keys enabled.
* Update key state on window drag start in case if it was pressed before dragging was started.
* Moved hooks from `FancyZones` to `WindowMoveHandler`. 
_Prepare_
* Set FancyZones settings options
* _Optional_ Enable `Make dragged window transparent`
* Apply any FancyZones layout 
_Test with Sticky Keys enabled_
* Enable Sticky Keys (Settings -> Ease of Access -> Keyboard)
* Press and release 'Shift', drag any window. _Window should become transparent, possible to apply to a zone._
* Press and hold 'Shift', drag any window. _Window should become transparent, possible to apply to a zone._
_Test with Sticky Keys disabled_
* Press and release 'Shift', drag any window. _Window shouldn't become transparent, possible to apply to a zone._
* Press and …
=> [FancyZones] Shift + StickyKeys behavior fix 

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml
Accessibility issues of the image resizer settings page are fixed in this PR.
* Automation properties have been set for all the text blocks, combo boxes and number boxes. (Each commit corresponds to one element's accessibility issue being fixed).
* The Image has more context now.
* The remove button was previously being read out as only button. Now it has been labeled.
* Install NVDA (screen reader) and ensure that the correct information is being read out.
* Press Insert+B to read the entire app content.
=> Fix Accessibility issues of the Image Resizer settings page

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml
This PR fixes a couple of the PowerRename settings page.
1. The number box is now labeled by the text block so that the screen reader reads out `Maximum number of items` when the edit box is on focus. 
2. There is more information regarding the image. Previously, it was being read out as just 'graphic', but now it is going to be read as 'Power Rename graphic'.
* Install NVDA screen reader and press Insert+B to read the entire app content.
=> Fix Accessibility issues in the PowerRename settings page

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml
The image was previously being read as 'graphic' by the screen reader. Now we add more context by setting an automation property so that it says `File Explorer Preview graphic`.
Install NVDA screen reader and read the contents of the app by pressing Insert+B.
=> Fix Accessibility issues of the File Explorer Preview Settings page

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml
This PR fixes some of the accessibility issues of the color picker tab of the PT settings page.
The only change is this PR is that additional information has been set for the color picker image. It previously used to read out just `graphic`, now it is made more accessible by setting an automation property.
* Install NVDA screen reader.
* Press Insert+B to read all the entire app content.
=> Fix Accessibility issues in the color picker settings page

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
This PR fixes the accessibility issues of the shortcut guide pane in the settings page.
The following changes have been made in this PR to fix accesibility issues - 
1. Set the Automation property to the number box so that it is now being labeled by the text block.
2. Added a comment regarding the accessibility issue in the radio button and a link to the issue in the microsoft-ui-xaml repository.
3. Added more context to the image so that it now says 'Shortcut Guide graphic' instead of just graphic.
The rest of the issues have an external dependency on the controls being fixed by the microsoft-ui-xaml team - #6083.
* Install NVDA and listen to the screen reader on focusing on an item.
=> Fix Accessibility issues of the shortcut guide settings page

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Main.cs
Remove Loading and Saving of program plugin cache
This PR removes loading/saving cache to fix following issues : 
1. It will fix the issue #5998, which resulted in missing Packaged app icons when these apps were updated and pt run was disabled.
2. It will fix the issue #5905 with win32 apps not being detected, installed when pt run was disabled. On enabling pt run, it used the previous cache.
Manually validated that issues associated with #6048 are resolved.
=> Remove the code for saving/loadingprogram plugin cache

src/modules/powerrename/dll/PowerRenameExt.cpp, src/modules/powerrename/lib/Helpers.cpp, src/modules/powerrename/lib/PowerRenameInterfaces.h, src/modules/powerrename/lib/PowerRenameItem.cpp, src/modules/powerrename/lib/PowerRenameItem.h, src/modules/powerrename/lib/PowerRenameManager.cpp, src/modules/powerrename/lib/PowerRenameManager.h, src/modules/powerrename/lib/PowerRenameRegEx.cpp, src/modules/powerrename/lib/PowerRenameRegEx.h, src/modules/powerrename/testapp/PowerRenameTest.cpp, src/modules/powerrename/ui/PowerRenameUI.cpp, src/modules/powerrename/ui/PowerRenameUI.h, src/modules/powerrename/unittests/PowerRenameManagerTests.cpp, src/modules/powerrename/unittests/PowerRenameRegExTests.cpp
Adds filtering feature where you can click on the column headers to see certain type of files.
Current filters
* First column cycles between **Selected** and **Flags Applicable** filter
- **Selected**: An item is visible if it is checked in the interface.
- **Flags Applicable**: An Item is visible if current flags are applicable to the file.
* Second column toggles **Should Rename** filter on/off
- **Should Rename**: An item is visible if rename operation will be performed on it.
I am not sure about having two filters on first column, removing less desirable would be good. I would appreciate feedback about it.
PowerRename runs bulkier when a filter is on, that is because changing the number of items in the list view performs heavy memory operations. (Performance shouldn't be effected when …
=> [PowerRename] Add Filtering Feature

src/common/interop/interop.vcxproj
* [_common-md-flag_] Debug Information Format: /ZI ->/Zi
* [_interop_] c++17 standard
* [_interop_] `__cdecl` -> `__clrcall` for _KeyboardHook::HookProc_
* [_common_] removed additional dependencies
* [_updating_] removed additional dependencies
Rebuild solution, check if everything works as expected.
=> Fix FancyZones and common lib build warnings.

src/common/updating/updating.vcxproj
Removed Pathcch.lib from additional dependencies.
=> Warning: __NULL_IMPORT_DESCRIPTOR already defined in Pathcch.lib

src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ModelsTests/SettingsUtilsTests.cs
1) the same variables (actual_json) are being compared against each other.
2) BasePTSettingsTest doesn't override equals to Equals compares the objects. This change compares the json strings directly.
These unit tests weren't actually running the expected test.  Performing the proper check. 
=> Fixing Settings Util tests. 

tools/build/convert-resx-to-rc.ps1
Using ToUpper() in file generation script works different in some languages of Windows.
Use default English locale to avoid errors.
=> Use en-Us locale when using ToUpper()

src/modules/colorPicker/ColorPicker/dllmain.cpp
ColorPicker DllMain should call `Trace::UnregisterProvider();` only for DLL_PROCESS_DETACH
=> [ColorPicker] proper Trace::UnregisterProvider(); call

src/runner/PowerToys.exe.manifest
This PR fixes a crash which occurs on launching the keyboard manager UI from settings.
The error message that appears is `Exception thrown at 0x00007FFFA254A799 (KernelBase.dll) in PowerToys.exe: WinRT originate error - 0x8000FFFF : 'WindowsXamlManager and DesktopWindowXamlSource are supported for apps targeting Windows version 10.0.18226.0 and later.  Please check either the application manifest or package manifest and ensure the MaxTestedVersion property is updated.'.
Exception thrown at 0x00007FFFA254A799 in PowerToys.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000A9C3AFCFC8.`
This appears because the `maxVersionTested` attribute (removed in #6095 ) is required in the executable's manifest (in this case in runner), as described here …
=> Fix runner crashing on launching Keyboard Manager UI

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/WindowMoveHandler.cpp, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/util.cpp, src/modules/fancyzones/lib/util.h
Enable manual (using hotkey and shift+drag) zoning of child windows and do not keep them in zone app history.
=> [FancyZones] Enable to manually zone child windows

installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp, installer/PowerToysBootstrapper/bootstrapper/bootstrapper.rc, installer/PowerToysBootstrapper/bootstrapper/pch.h, installer/PowerToysSetup/Product.wxs, src/action_runner/action_runner.rc, src/common/UnitTests-CommonLib/UnitTestsVersionHelper.cpp, src/common/VersionHelper.cpp, src/common/VersionHelper.h, src/common/common.vcxproj, src/common/common.vcxproj.filters, src/common/d2d_svg.cpp, src/common/pch.h, src/common/string_utils.h, src/common/updating/dotnet_installation.cpp, src/common/updating/dotnet_installation.h
- add --help and --skip_dotnet_install commands
- do not accept invalid input in VersionHelper and add negative unit tests
- do not specify patch version of .net core in the notification msgs
Regarding #6069, it's a tentative fix, however, it looks like it'll fix it. We generate "old -> new" version toast using `current_version_to_next_version`. It's only used by the following functions (not taking error msg into account):
1. `show_available`
2. `show_visit_github` 
3. `show_version_ready`
Let's find out how they're used:
1. is called inside `check_new_version_available`, which shouldn't display a toast if `get_new_github_version_info_async` return nothing.
2. is called by `try_autoupdate`, which again returns if `check_new_version_available` returned nothing.
3. is also called by …
=> autoupdate improvements

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
Autocomplete text was not getting cleared when `Clear the Previous Query on Launch` option is enabled. 
The issue was happening because the code path for clearing query programmatically didn't set autocomplete text to empty.
Manually validated that autocomplete text is cleared.
=> Fix issue with autocomplete text not getting cleared 

src/modules/launcher/PowerLauncher/LauncherControl.xaml
Fix inconsistency in the color of QueryTextBox
The color of the QueryTextBox text was different when autocomplete text suggestion was available as show below : 
This issue was happening because of changes made in #6049, where `AutoCompleteTextBlock` was placed on top on `QueryTextBox` causing the lighter color of the former to be visible. This PR makes the following changes to fix this issue. 
1. Set z-index of `AutoCompleteTextBlock` to be strictly less than `QueryTextBox`. 
2. Set background color of `AutoCompleteTextBlock` to `SystemChromeLow` and of `QueryTextBox` to `transparent`.
Manually validated that color inconsistency is not present in QueryTextBox
=> Fix inconsistency in the color of QueryTextBox

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
This PR fixes the ArgumentOutOfRange Exception thrown by the listview.ScrollIntoview() function.
* An Argument Out of Range Exception was being thrown by the listview.ScrollIntoView function.
* This was happening because of the parent element not being updated as the layout update happens in a deferred manner by an algorithm which optimizes for performance and concurrency.
* To mitigate this issue, it was suggested in the documentation to call the `UpdateLayout` function before calling `scrollIntoView` if there are many elements being added or removed. However, the issue with this is that there is a performance impact and not ideal to do it for minor additions or deletions.
Hence, the following changes have been made - 
* Add a try-catch …
=> [PT Run] Fix for argument out of range exception

src/core/Microsoft.PowerToys.Settings.UI.Lib/ImageSize.cs
This PR fixes an issue where decimal values were not accepted for Image sizes. This was supported in the original Image Resizer and in 0.19.
- Since the Width and Height properties are of `double` type, `double.TryParse` has been used instead of `int.TryParse`
- Since `double.TryParse` behaves as per the current culture, it will accept , as decimal point as well for languages which use that if that is the current OS culture
- Type decimal value in Image Resizer settings page
=> [Settings] Changed ImageSize class to parse as double instead of int

src/core/Microsoft.PowerToys.Settings.UI.Lib/ViewModels/FancyZonesViewModel.cs, src/modules/fancyzones/lib/Settings.h
Fix Span Zones across monitors feature.
Fix enabling/disabling Span Zones across monitors feature in Settings.
=> [FancyZones] Fix span accross monitors feature

src/modules/fancyzones/lib/FancyZonesData.cpp, src/modules/fancyzones/tests/UnitTests/Util.cpp, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp
Instead of no-layout at FZ startup, now 3-zones PriorityGrid is applied by default.
1. Delete zone-settings.json file
2. Run FZ
3. Confirm that 3-zone PriorityGrid layout is applied on startup
4. Create new Virtual Desktop
5. Confirm that new Virtual Desktop has 3-zone PriorityGrid
6. Delete VD
7. Change layout on primary desktop to 4-zone Column
8. Create new VD
9. Confirm that new VD has 4-zone Column layout applied (Clone layout from parent feature still works)
=> [FancyZones] Set 3-zones PriorityGrid as default layout

src/core/Microsoft.PowerToys.Settings.UI/Views/KeyboardManagerPage.xaml
This PR removes the tab stops on the ListViews in the KBM settings page.
- As described on this comment https://github.com/microsoft/microsoft-ui-xaml/issues/3229#issuecomment-686086315 on the WinUI repo, in order to remove the tab stop from the ListView we have to set IsTabStop to false on the ItemContainerStyle for the ListViewItems.
- After doing this there was still an issue of extra tabs being required to reach the next control, even though the listview items did not explicitly get focus. This was happening because of the ItemsControl elements used in each row. This was resolved by settings IsTabStop to false for both of these controls.
- Tab through all the elements on the KBM settings page.
=> [Settings] Fix tabbing issues on KBM settings page

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/Resources.resx
Update Span Zones Across Monitors feature description in Settings app to
`Allow zones to span across monitors (all monitor must have the same DPI scaling)`
Add message box with warning on editor launch if monitors DPI's aren't all the same.
=> [FancyZones] Update 'span zones across monitors' feature description and add message box warning accordingly 

src/modules/fancyzones/lib/Zone.cpp, src/modules/fancyzones/lib/ZoneSet.cpp, src/modules/fancyzones/tests/UnitTests/ZoneSet.Spec.cpp
Validate zone rectangle before adding it into zone layout. If single zone rect is invalid, declare zone layout as invalid.
Extend `MakeZone` function to return `nullptr` if zone rectangle is invalid. Update unit tests to check implemented behavior.
All unit tests passed.
=> [FancyZones] Validate zone rect before adding it into layout

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/KeyboardManagerPage.xaml
This PR fixes the property related accessibility issues and screen reader related issues of the KBM settings page.
1. Accessible names have been added to the key remapping list and shortcut remapping lists.
2. Accessible names have been added to the individual list items as well. Without these two changes the name was set to the item source which was Microsoft.Settings.UI.Lib.KeysDataModel etc, this was causing a property related issue. The screen reader was also reading out this (Microsoft.Settings.UI.Lib.KeysDataModel) value on navigating to the list. These issues have been fixed now.
3. The arrow icons were not being read out previously. If we had the following remapping `A -> B`, A and B …
=> Fix KBM Settings page Property related and screen reader Accessibility issues

src/modules/launcher/PowerLauncher/ViewModel/ResultViewModel.cs, src/modules/launcher/Wox.Core/Plugin/PluginManager.cs, src/modules/launcher/Wox.Test/PluginManagerTest.cs
Fix for action keyword disappearing in search box when scrolling through results.
Manually validated that action keyword is present in textbox when scrolling through results.
=> Corrected querytext display on action keyword

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
Fix for `FileNotFoundException` in Win32 programs.
The `FileNotFoundException` is being thrown because an external program is creating an `exe` and quickly deleting the file. Creating an `exe` triggers file watcher and this inturn calls the code to add this `exe` in win32 programs. The code tries to fetch file version information, but since it has already been deleted, `FileNotFoundException` is thrown. It would be best to handle this error as it is happening due to an external factor.
Steps to repro : 
1. Put a breakpoint [here](https://github.com/microsoft/PowerToys/blob/master/src/modules/launcher/Wox.Infrastructure/FileSystemHelper/FileVersionInfoWrapper.cs#L20)
2. Paste an exe file on desktop. This will hit breakpoint in step 1. 
3. Delete exe file. 
4. Continue program execution. …
=> Fix for FileNotFoundException exception in win32 programs

.pipelines/ci/templates/build-powertoys-steps.yml, PowerToys.sln, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator.UnitTest/BracketHelperTests.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator.UnitTest/ExtendedCalculatorParserTests.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator.UnitTest/Microsoft.Plugin.Calculator.UnitTest.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/BracketHelper.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/CalculateEngine.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/CalculateHelper.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/CalculateResult.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/ResultHelper.cs
Currently the calculator plugin for PowerToys Run had no unit test (see  #5948). With this in place we can test the calculation engine separate. Currently I have also included the problems of #3488 and #3697 
I have made a start with the unit test. I had to change to structure of the parsing to a separate class. The culture is needed to mimmick the current output and for the unittest to be system agnostic.
Note:
Unit test `ParseValuesKnownIssues` has known bug unit tested. These are the limitations of teh 
* big decimals are parsed wrong #3488  
* (multiplying without operator #3697 
I did search for some test that were failing before the latest fix and put them into `ParseValues`.
Startup the unit test project `Microsoft.Plugin.Calculator.UnitTest` in …
=> Create unit tests for Calculator plugin

src/modules/fancyzones/lib/VirtualDesktopUtils.cpp
On a clean machine there is no information about virtual desktops in registry. Introduce several fallback scenarios when acquiring information about current virtual desktop to make sure we always have up to date information, and eliminate scenario of 0000 GUID appearing.
When acquiring information about virtual desktop try following things:
1. Get desktop identifier from current session (from registry `Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\SessionInfo\\<session-idx>\\VirtualDesktops`)
2. Use `IVirtualDesktopManager` [interface](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ivirtualdesktopmanager-getwindowdesktopid) and currently active window (foreground window).
3. Get array of virtual desktops from registry (not kept per session) …
=> [FancyZones] Introduce several fallback scenarios when obtaining GUID for current virtual desktop

src/core/Microsoft.PowerToys.Settings.UI.Lib/ViewModels/PowerLauncherViewModel.cs
There was a null reference exception in the PT Run settings page which was causing it to crash.
Steps to repro the bug:
* Delete the settings.json file inside the PowerToys Run folder.
* Launch settings and try to open the PT Run settings page, it would cause settings to crash.
Reason as to why this was happening:
* The `sendConfigMSG` was being accessed in the callback without being initialized.
* This entire block of code was encapsulated in a try-catch block, hence the `generalSettings` variable was not being initialized. 
* When the page was loaded, the toggle switch got it's value from a binding to the `EnablePowerLauncher` variable which was set to `generalSettings.Enabled.PowerLauncher` but since this generalSettings was not …
=> Fix Null Reference exception in PT Settings

src/modules/keyboardmanager/common/Shortcut.cpp
- Add a shortcut remapping and validate that it works normally on en-us
- Switch to Japanese IME and use the Shift+CapsLock, Ctrl+CapsLock, Alt+CapsLock shortcuts
- Validate that shortcut remapping still works
=> Fixed KBM shortcut remapping not working after using Japanese IME

src/modules/keyboardmanager/ui/ShortcutControl.cpp, src/modules/keyboardmanager/ui/SingleKeyRemapControl.cpp
This PR prevents Keyboard Manager from crashing in the target app textbox LostFocus handler due to a InvalidPointerRead exception.
To repro the exception easily, add `Sleep(5000)` in the handler like in this commit https://github.com/microsoft/PowerToys/commit/7064482e989c004170f07180ea83233ac7c449d7 and follow the steps in the gif. When this is done the WinRT error `input data cannot be processed in the non-chronological order` will also appear in the VS output.
The exception seems to occur if a user manages to press the delete and invoke LostFocus at the same time. Without the artificial `Sleep` this could happen if someone's system is running slow and hanging for some reason (most likely external to PowerToys).
- The …
=> [KBM] Prevent keyboard manager crash when index is not found

src/modules/fancyzones/lib/WindowMoveHandler.cpp, src/modules/fancyzones/lib/pch.h
e.g. merge Chrome tab into other Chrome window
If some of the window properties changed while drag&drop (durring MoveSize* FZ methods), that means that window is merged with other window or changed in some other way. Therefore, that window shouldn't be zoned.
=> [FancyZones] Do not zone window if it merges with other window

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
This PR catches the URI Format Exception in PT Run when an internet shortcut program with an incorrect uri is created.
This crash was observed in watson: https://github.com/microsoft/PowerToys/issues/6515.
When an internet shortcut program (steam or epic games app) is installed with an incorrect url, this exception is thrown. The following changes catch this exception and return an invalid program so that it does not get added to PT Run.
Based on the following references, the url='url' is always in a single line. Hence an incorrect uri format is the only cause of this exception.
Added a throw new UriFormatException() in the try block and ensured that the application does not crash.
=> To catch URI Format Exception in PT Run

src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.Designer.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx, src/modules/launcher/PowerLauncher/SettingsWatcher.cs
The disable drive detection warning checkbox in settings was not reflecting the correct response in PT Run.
Disabling or enabling it was not removing/adding the warning back in PT Run.
* The reason why this was happening is the name of the plugin was being changed during runtime based on the title in the internationalization.cs class line 190 https://github.com/microsoft/PowerToys/commit/1b598ad87e76ab01acbc261869f284d842f13486#diff-60d50d131e80e73cb462de1400f7ca49L190-L190.
* So even though the initial name of the plugin was `Windows Indexer`, after a few queries it is changed to `Windows Indexer Plugin` by the internationalization class.
* Due to this reason, if the checkbox is checked/unchecked in the initial few seconds, the name of the …
=> Fix for Drive detection warning checkbox from settings was not reflecting changes in PT Run

src/modules/fancyzones/editor/FancyZonesEditor/GridData.cs
This should fix the problem described in #5319
Make sure that the sum of numbers after the call to `FixAccuracyError` is exactly 10000,
This PR won't fix existing layouts whose sum of percent values is not 10000. Perhaps I should also add this to the PR?
Follow the scenario described in the issue.
=> [FZ Editor] Improved a function in GridData.cs

src/modules/launcher/PowerLauncher/App.xaml.cs
Fix null reference exception in Powertoys `Dispose` function.
PowerLauncher listens for `WM_CLOSE` event from runner to gracefully shut down WPF application. If the callback is invoked during `OnStartup` call in `App.xaml.xs`, `NullReferenceException` would be thrown since objects are not initialized.
Steps to repro : 
1. Call `Dispose` method right before [this](https://github.com/microsoft/PowerToys/blob/master/src/modules/launcher/PowerLauncher/App.xaml.cs#L83) line. 
Manually validated that powertoys exits without any crash using above repro steps.
=> Fix for null reference exception

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
This PR fixes the issue of the OnPropertyChanged handler for MainWindowVisibility getting invoked when the user clicks away from PT Run. When a user clicks away this is invoked while the window Visibility is Visible and MainWindowVisibility gets changed to Hidden. This was causing a flicker when a user clicked away to another screen because UpdatePosition would get invoked. The rest of the function calls in this handler such as BringProcessToForeground do not make sense either when the window is getting hidden, so a check was added to avoid that scenario.
- Run launcher and press the hotkey to show it and hide it. Validate that it gets focus even if an app like explorer was in the foreground.
- Switch mouse focus to another monitor …
=> Fixed Visibility OnPropertyChanged getting invoked on clicking away from PT Run

src/modules/launcher/PowerLauncher/MainWindow.xaml, src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
This PR fixes the scenario mentioned in #3886 where left clicking a result while a context menu item has tab focus results in the context menu item getting executed.
- Modified the OpenResultCommand to use a function which takes a boolean argument `isMouseClick`. The command has been split into two commands i.e. OpenResultWithKeyboardCommand and OpenResultWithMouseCommand.
- `OpenResultCommand` reference in the MainWindow InputBindings has been replaced with the Keyboard variant
- `OpenResultCommand` reference in the MainWindow `SuggestionsList_PreviewMouseLeftButtonUp` event handler has been replaced with the Mouse variant
- If the `isMouseClick` argument is true, the step for executing the selected context menu button is skipped
_How does …
=> [PowerToys Run] Fix mouse click handler for PowerToys Run results

src/modules/fancyzones/lib/WindowMoveHandler.cpp, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/util.cpp, src/modules/fancyzones/lib/util.h
This prevents Windows' maximize window feature colliding with FZ.
When there is a zone which top edge is touching screen' top edge, trying to maximize the window by dragging it to the top edge of the screen ended up with zoning the window instead of maximizing it.
This PR fixes this.
1. Disable FZ 'Hold Shift key to activate zones while dragging' option
2. Create custom layout which one of the zones is placed on the screen' top (touching screen' top edge)
3. Try to maximize some window by dragging it to the top of the screen in the area where the zone mention in #2 is touching the top edge of the screen
4. Release the window and confirm that window is maximized
=> [FancyZones] Do not zone window if it should be maximized

src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
Fix for ArgumentOutOfRange Exception caused to race condition in `Result` list.
The issue is caused due to race condition in `Results` List. `Results.SelectedItem = Results.Results[0]` is required because it activates context menu, and context menu of the first item needs to be activated by default. It was called in `UpdateResultsListViewAfterQuery` function. But we can't use a lock inside `UpdateResultsListViewAfterQuery` as it runs on UI thread and would end up blocking it. Hence, to fix this issue `Results.SelectedItem` was moved to synchronized block in `QueryResults` function.
Note : The issue is not hit frequently but the information in call stack gives a clear indication of the underlying cause. 
Validated that the cause of error is resolved based on the call stack in the issue.
=> Fix for ArgumentOutOfRange Exception in Result List

src/modules/fancyzones/lib/FancyZonesData.cpp, src/modules/fancyzones/lib/FancyZonesData.h
Do not migrate custom layouts from registry on first PowerToys run. Also, if FancyZones registry data is present in registry, delete it.
Scenario #1
1. Delete FancyZones JSON files
2. Confirm that there is some FancyZones data present in registry (Layouts subkey)
3, Start PowerToys
4. Open FancyZones JSON files and confirm that no data was migrated from registry
Scenario #2
1. Start PT with FZ enabled
2. (If there was any FZ data in registry) Confirm that SuperFancyZones registry key is deleted
=> [FancyZones] Remove migration from registry logic and delete registry data if present

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/PackageWrapper.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/PackagemanagerWrapper.cs
This PR adds code to fix the loading of program plugin due to failure in Packaged app load at startup.
This PR contains the following changes : 
1. Added exception handling for `DirectoryNotFoundException` when Packaged app is not found at location returned by PackageManager. This was the cause of issue #6673 as this exception was not handled before.
2. Added a try-catch to handle all exceptions when adding a new packaged app in `PackagemanagerWrapper.` All exceptions should be caught here because an issue in one program should not affect loading of entire program plugin.
1. Manually validated that throwing any exception while creating a packaged app does not result in failure in loading program plugin. 
2. MSI containing this PR changes were shared with users and they reported that the …
=> Handle exception in Packaged program loading at startup

src/common/string_utils.h
Noticed a bug in string_utils. reinterpret-casting char string literal as wchar_t string literal will trim `ठ਍` instead of the space symbols.
=> common: fix trim functions for wchar_t

.pipelines/build-localization.cmd, .pipelines/pipeline.user.windows.yml
Earlier the localization pipeline would read the LocProject.json files only from the `src` folder, but the changes in #6567 indicated that it needs to be enabled in `installer` as well. With the changes in this PR the root folder will be used instead.
- Validated on CDPX pipeline that the localization is done for all projects in `src` and `installer` folders. https://github-private.visualstudio.com/microsoft/_build/results?buildId=11908&view=artifacts&type=publishedArtifacts
=> Enable localization on all folders under PowerToys root

src/modules/launcher/Wox.Infrastructure/Storage/BinaryStorage`1.cs, src/modules/launcher/Wox.Infrastructure/Storage/JsonStorage`1.cs
Fix string format of `Log.Info` function
`Log.Info` accepts string containing two token seperated by `|`. The caching code instead provides 3 tokens which result in following error messages: 
`2020-09-11 16:41:04.2053|FATAL|FaultyLogger|Wrong logger message format <|JsonStorage.Save|Saving cached data| <C:\Users\divyan\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Settings.json>>`
Manually validated that logs are written correctly. 
The following logs are generated after changes : 
```
2020-09-18 11:56:49.2215|INFO|JsonStorage.Save|Saving cached data at <C:\Users\divyan\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Settings.json>
2020-09-18 11:56:49.2499|INFO|JsonStorage.Save|Saving cached data at <C:\Users\divyan\AppData\Local\Microsoft\PowerToys\PowerToys …
```
=> Fix logging string format

src/modules/keyboardmanager/dll/Resources.resx, src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp, src/modules/keyboardmanager/ui/KeyDropDownControl.cpp, src/modules/keyboardmanager/ui/KeyDropDownControl.h, src/modules/keyboardmanager/ui/ShortcutControl.cpp, src/modules/keyboardmanager/ui/ShortcutControl.h, src/modules/keyboardmanager/ui/SingleKeyRemapControl.cpp, src/modules/keyboardmanager/ui/SingleKeyRemapControl.h
This PR adds code to dynamically update the AutomationProperties.Name for each row/column pair in the grid in Remap Keys/Shortcuts. This solves the accessibility issue as sibling elements will always have different names.
The names for each stackpanel/textbox/button was given as `Row {rowNum}, ColumnName`, to make it uniform.
- The PR also makes a two line change to clean up some code for calculating rowIndex to be more scalable for future changes (using Grid.GetRow rather than manually calculating row index).
Remap Keys
- The stackpanel in the first column for each row is given the name "Row {rowNum}, Key:"
- The stackpanel in the second column for each row is given the name "Row {rowNum}, Mapped To:" (the old `Remapped to` string was …
=> [Keyboard Manager] Fix focusable elements should have different names accessibility issue

src/modules/keyboardmanager/ui/KeyDropDownControl.cpp, src/modules/keyboardmanager/ui/KeyDropDownControl.h
This PR adds in logic to prevent a crash in Keyboard Manager. With the changes in this PR, for Key to Shortcut remappings when they are loaded in on opening the KBM window or when the shortcut is adding from the Type button, the MapToSameKey error will be ignored.
- The crash in #6695 was occurring because of the key to shortcut remapping Shift(left) -> Shift(left) + [. 
- The `AddShortcutToControl` method (which is called while loading existing remappings while starting the remap windows, or from the handler of Type button), adds in the keys sequentially as if a person was entering them (so that the logic for using Type and entering by dropdowns is the same). The issue with this in the above example is that there is an intermediate state of …
=> [Keyboard Manager] Fix crash in Keyboard Manager by ignoring MapToSameKey warnings on loading

src/modules/keyboardmanager/common/KeyboardManagerConstants.h, src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp, src/modules/keyboardmanager/ui/EditShortcutsWindow.cpp
This PR fixes the accessibility issues in KBM UI where certain controls could not be accessed even by scrolling if the window width was reduced.
- Minimum width has been added to the Grids in both windows. This is to keep the UI organized and well-spaced when the window is made smaller (otherwise the arrow icons would touch the adjacent controls). Width values were determined by trial and error.
- Horizontal scrolling has been enabled on the scrollviewers
- Both scrollbars' visibility are set to Auto so that they appear only if content is not visible
- Moved the example and header text out of the scroll viewer in both windows. This was done because of the following reasons:
- Even though the textwrap property is set on these TextBlocks, if …
=> [Keyboard Manager] Enabled horizontal scroll on scroll viewers and tweaked ScrollViewer layout

src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml
1. A horizontal scroll bar has been added for the img resizer configurations. Previously there was no scroll bar and the components couldn't be accessed when the width of settings was reduced.
2. Reduced the width of the FZ text box because it was being cut.
Before:
After
Before:
After:
=> Fixed scaling Accessibility issues in Settings

src/core/Microsoft.PowerToys.Settings.UI.Lib/ViewModels/GeneralViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/ViewModels/ImageResizerViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/General.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/ImageResizer.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs
This PR fixes and complements the changes made in PR #6620.
1. GeneralViewModel did not require ISettingsUtils to be passed because the information was already encapsulated in settingsRepository. Hence, it has been removed.
2. All the module names were unified in 6620 using <PT>Settings.ModuleName, however the ImageResizerSetttings.ModuleName is "Image Resizer" and the name of the settings folder is "ImageResizer" (Without the space). This change would create a new folder and make img resizer backward incompatible. Hence, the name has been reset to "ImageResizer".
* All tests pass.
* Validated that restart as admin and check for updates functionalities …
=> Fix settings changes that were made in PR #6620

src/core/Microsoft.PowerToys.Settings.UI.Lib/Utilities/SystemIOProvider.cs
As per the arguments of the [`Directory.Delete` method](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.delete?view=netcore-3.1) the `recursive` bool argument has been set to `true` so that the directory can be deleted even if it is not empty.
- Make a corrupted PT Run settings file so that a JsonException occurs while PT Run reads it.
- PT Run should not crash when it tries to delete the settings and replace it.
=> [Settings] Added recursive delete for IOProvider DeleteDirectory to prevent crash on non-empty directory

src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Storage/ConcurrentQueueEventHandlerTest.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Storage/Win32ProgramRepositoryTest.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/ShellLinkHelper.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/EventHandler.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/Win32ProgramRepository.cs
This PR adds a delay to the File System watchers so that we don't try to get information about an app even before it is installed, which was leading to the Calibre not being installed issue.
The following approach has been taken for lnk and url files, both of which we try to get a handle on or open on installation.
When an app is installed, multiple events are created, they are of type `Created` and `Changed`.
The `Changed` events are triggered after the `created` events.
Previously, we were trying to immediately get a handle on the app as soon as it was created, however, this was before the installation process was complete. (Apps are created and written to in chunks, leading to a lot of events being triggered before the installation …
=> Add delay to File System watchers to prevent Calibre installation issue

src/core/Microsoft.PowerToys.Settings.UI.Lib/SettingsUtils.cs
This fixes the code path for upgradeconfiguration. The function was getting executed if the return value was false, whereas based on the actual return values it should have been for true. This was causing an infinite loop in KBM's filewatcher where it would keep trying to load the profile as the file watcher code was re-saving the file.
Tests passed, and KBM settings no longer glitched out.
=> Fix settings UpgradeSettingsConfiguration code path

doc/devdocs/readme.md
This PR fix the missing `preview` entry in the prerequisites install script
Only doc change
Test changed install script on my PC with Visual Studio 2019 16.8 Preview 3.1
=> Fix prerequisites install script to allow VS Preview versions

src/core/Microsoft.PowerToys.Settings.UI.Lib/ShortcutGuideProperties.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/ShortcutGuide.cs
When the settings.json file of shortcut guide does not exist, the runner starts shortcut guide with it's default configurations (ie. the ones present in shortcut_guide.cpp and shortcut_guide.h so it has it's background theme set to system). However, when settings starts off, it tries to get the configurations from the settings.json file of shortcut guide, but since the file does not exist, it creates a new file with it's default configurations of shortcut guide (and the default theme in the settings process for shortcut guide is light). 
This PR changes the defaut theme property of shortcut guide settings to 'system' instead of 'light'.
Ideally this information should be communicated to the runner once a new file has been created so that …
=> Changed default theme in settings to be consistent with that of shortcut guide

src/modules/fancyzones/editor/FancyZonesEditor/LayoutPreview.xaml.cs
Fix Editor crash with big `Space around zones` value.
Use `Math.Max` to prevent negative width and height.
1. Select grid layout.
2. Set some big enough `Space around zones` value (for 1920x1080 display and 3 zones 700 is enough).
3. Click Apply.
4. Open editor.
=> [FancyZones Editor] Crash with big 'Space around zones' values

src/modules/fancyzones/lib/WindowMoveHandler.cpp, src/modules/fancyzones/lib/WindowMoveHandler.h
Fix for #3536. This was fixed [(PR)](https://github.com/microsoft/PowerToys/pull/6549) but broken later with [this change](https://github.com/microsoft/PowerToys/commit/3d36779e19d3f2470585c3789b3cd9d728f4e8ec#diff-ff7794bdc47c8ebd8c1cecabe2f532fc).
Manually tested zoning and merging chrome tabs
=> [FancyZones] Fix stuck chrome tab when merging into existing window

src/modules/keyboardmanager/common/Shortcut.cpp
This PR tweaks the code that checks keys to be ignored during shortcut remaps to be more generic. Rather than ignoring the few problematic codes as issues are created (so far 0xF0, 0xF1, 0xF2, 0xF3), the PR ignores any key codes mentioned as unassigned, reserved, undefined or oem-specific on the official docs at https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes, similar to the fix done for shortcut guide at #6025
- Validate that shortcut to shortcut remappings work on En-US
- Validate on Japanese language that even after pressing Shift+Caps, Alt+Caps, Ctrl+Caps or Alt+` the shortcut remaps still work.
=> [KBM] Avoid checking reserved/unassigned/oem-specific/undefined key codes during shortcut remaps

src/modules/keyboardmanager/common/KeyDelay.cpp, src/modules/keyboardmanager/ui/ShortcutControl.cpp, src/modules/keyboardmanager/ui/SingleKeyRemapControl.cpp
This PR fixes a crash which occurs on using the Enter/Esc accessible keys for closing the Type UI.
Repro steps on master/0.23 are:
- Open Remap key/shortcut window
- Click Type
- Hold Enter/Esc.
- On closing the Type window we terminate the KeyDelay thread and delete the object by calling the destructor (`clear` is called on the `std::map` that stores them`). When we click the OK/Cancel button, this gets executed on the UI(dispatcher) thread, but when executed from the KeyDelay object this was getting called from the Delay thread. This causes re-entrancy on the queueMutex as it already has a lock on the mutex when it calls any of the shortPress, longPress or longPressRelease handlers, leading to a crash.
- Even if we remove the mutex usage …
=> [KBM] Moved unregistering of key delays to always run on the dispatcher thread to avoid mutex re-entrancy

src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj
This PR adds the AppxBundlePlatforms property as x64 to remove the warning that it is not set, as per this stackoverflow thread https://stackoverflow.com/questions/57643594/appx4001-warning.
The warning appears because the AppxBundle target is disabled in the solution (as it is a xaml islands project we don't want to deploy the UWP app). By adding this property we can suppress the warning without any user impact.
- Validated that the warning mentioned in #5100 does not appear while building Settings.UI (UWP)
- Validated that PowerToys runs and all pages in Settings appear correctly when running from VS and from local MSI.
=> [Settings] Add AppxBundlePlatform to remove warning

src/modules/launcher/Wox.Core/Plugin/PluginManager.cs, src/modules/launcher/Wox.Test/PluginManagerTest.cs
Fix issue in autosuggest due to incorrect text from `UpdateResultWithActionKeyword` when action keyword is not present.
Autosuggest was broken because `UpdateResultWithActionKeyword` returned an empty space at the beginning when the actionkeyword was not present, resulting in an incorrect match with the query. For example, If "Mail" is queried and no action keyword is present, `UpdateResultWithActionKeyword` returns " Mail".
Manually validated that autosuggest works as expected.
=> [Run] Fix autosuggest

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
Improving exception handling during indexing of Win32 apps to prevent the error in one application from affecting other programs.
This PR contains the following changes :
1. Added a try-catch block for `ProgramPaths` function. This function enumerates all files in the current folder and subfolders. `IOException` was being thrown when trying to call `Directory.EnumerateFiles` on OneDrive virtual folders. All exceptions should be caught here as this function is a bottleneck for a number of functions including `DesktopPrograms`, `StartMenuPrograms`, and `PathEnvironmentPrograms`.
2. Added a try-catch to handle all exceptions when adding a new `InternetShortcutProgram`, `LnkProgram`,`ExeProgram` and `CreateWin32Program`. All exceptions should be caught here because any unhandled exception …
=> Add exception handling in win32 program

src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
Fix for `IndexOutOfBoundsException ` exception due to race condition in modifying the underlying list view of `Results`.
`IndexOutOfBoundsException` is being thrown while modifying the underlying list view of `Results` in MainViewModel due to following reasons : 
1. `Results` was being indexed without a check on its size. This was fixed in PR #6934.  
2. Another possible cause of this is due to the race condition. The following line modifying Results should be synchronized using locks.
https://github.com/microsoft/PowerToys/blob/c219fe0d1d370158845953c8d33eb8e4d8164ba0/src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs#L609-L615
This PR fixes the following issues : 
1. Fixes race condition in clearing `Results`.
2. This PR also fixes a possible issue in telemetry which is …
=> [Run] Fix for IndexOutOfBounds exception

src/core/Microsoft.PowerToys.Settings.UI.UnitTests/Microsoft.PowerToys.Settings.UI.UnitTests.csproj, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ModelsTests/BasePTModuleSettingsTest.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ModelsTests/HelperTest.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ModelsTests/SettingsRepositoryTest.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ModelsTests/SettingsUtilsTests.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/FancyZones.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/General.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/ImageResizer.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/KeyboardManager.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/PowerLauncherViewModelTest.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/PowerPreview.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/PowerRename.cs, src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/ShortcutGuide.cs
Adding FxCop to the Microsoft.PowerToys.Settings.UI.UnitTests.csproj project, and fixing the resulting warnings and errors. 
Changes made to fix the warnings and errors include: changing method naming conventions, adding message for deprecated methods, marking non-instance-accessing methods as static, removing unused code, replacing usage of Count() method for Lists with the more efficient Count property, renaming unused arguments, validating arguments for public methods.
Check there are no fxcop warnings and the related tests pass.
=> [fxcop] Settings UI unit tests

src/modules/launcher/PowerLauncher/ViewModel/ResultsViewModel.cs
This PR fixes a null reference exception which occurs if you try to Shift+Tab on the launcher window when there are no results/no query.
- Validated that exception is not thrown on pressing Shift+Tab on empty launcher search box
- Validated that Shift+Tab works as expected when there are results
=> [PT Run] Add null check in SelectPrevTabItem

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/Win32ProgramFileSystemWatchers.cs
Fix for `Docker` application not showing up in PT Run.
The issue was happening because docker installs .lnk at location `C:\ProgramData\Microsoft\Windows\Start Menu`, which is not indexed by program plugin. 
Steps to repro : 
1. While installing `Docker` desktop, uncheck `Add shortcut to desktop` on Configuration screen.
The following locations needs to be indexed by program plugin to match start menu search : 
1. `StartMenu` : Added with this PR.
2. `Programs` : A subfolder of `StartMenu`, and will be indexed by program plugin during indexing of `StartMenu`
3. `CommonStartMenu` : Added with this PR. 
4. `CommonPrograms` : A subfolder of `CommonStartMenu` , and will be indexed by program plugin during indexing of `CommonStartMenu`.
5. User Desktop : This location is indexed by program …
=> Fix Docker desktop not found in program plugin issue

src/modules/launcher/Wox.Infrastructure/FileSystemHelper/FileWrapper.cs
This PR fixes the issue where PT Run crashed when a steam game was being installed.
Security exceptions and unauthorized access exceptions are caught while trying to create all programs as the file may not be accessible. This catch block is also there for the internet shortcut programs, however they are being read before using the FileSystem wrapper which does not catch the security and unauthorized access exceptions. This PR catches those exceptions and logs it.
- Changed the security permissions required to access a url file and removed read permissions for the current user.
- tried to rename /index the file.
- the exception is caught.
=> Catch security and unauthorized access exception while trying to read from file

src/modules/fancyzones/lib/FancyZonesData.cpp, src/modules/fancyzones/lib/FancyZonesData.h, src/modules/fancyzones/lib/ZoneWindow.cpp
Don't overwrite the VD layout for existing devices.
FancyZonesData::AddDevice() now returns a bool: true if the desktop has been added to the device list, false if it was already present.
- Assign a layout to the primary desktop
- Create a VD and assign a different layout
- Quit PT
- Restart PT
- Verify that both the VD didn't have the layout reset to the same layout as the primary desktop
=> [FancyZones] Clone parent data only for new VD

src/common/interop/KeyboardHook.cpp, src/common/interop/KeyboardHook.h, src/common/interop/interop.h, src/core/Microsoft.PowerToys.Settings.UI.Lib/HotkeySettings.cs, src/core/Microsoft.PowerToys.Settings.UI.Lib/HotkeySettingsControlHook.cs, src/core/Microsoft.PowerToys.Settings.UI/Controls/HotkeySettingsControl.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Helpers/NativeKeyboardHelper.cs, src/core/Microsoft.PowerToys.Settings.UI/Helpers/NativeMethods.cs, src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj
This PR fixes the tab trap in the settings hotkey control by ignoring shift+tab and Tab key presses.
* The `FilterKeyboardEvent` function has been added so that the hotkey can ignore some key presses.
* We have the information of the shift key when it was entering the control and whether it was modified in between. The following cases have been handled -
1. When shift was never pressed while entering or within the control and tab was pressed, in this case simply ignore the tab key press.
2. When shift was pressed while entering but it was released in between then the system still thinks that the shift key is pressed, therefore simulate a shift key up event and ignore the tab that was …
=> Fix Tab Trap in SettingsHotkey Custom Control

src/modules/keyboardmanager/common/Helpers.cpp, src/modules/keyboardmanager/common/Helpers.h, src/modules/keyboardmanager/common/KeyboardManagerConstants.h, src/modules/keyboardmanager/dll/KeyboardEventHandlers.cpp
This PR improves the compatibility of KBM remaps in more applications by modifying the dummy key event used for preventing modifier actions like start menu(win key) or menu bar(alt). Instead of sending 0xFF keyup message, the PR changes it to key down and key up. This is done because some applications (like Slack in this case) might filter key up messages.
This fixes the issue mentioned in #7133 with Slack. The issue with terminal is addressed in #7143 
- Remap a shortcut Alt+Left->Home
- Open Slack (https://slack.com/intl/en-ca/downloads/windows, requires creating an account to use it)
- In the message box window, type some text and use the Alt+Left hotkey to move to the start of the text.
=> [KBM] Modify dummy key event to send both key down and key up to improve compatibility

src/modules/imageresizer/tests/ImageResizerUITest.csproj, src/modules/imageresizer/tests/Models/ResizeOperationTests.cs, src/modules/imageresizer/ui/Models/ResizeOperation.cs
Detect potential errors copying metadata and avoid them. This fix will allow images with metadata exhibiting this issue to be successfully resized, however the metadata will not be copied across to the resized image.
* An image with metadata that errors when copying
* A code change that works around the error
* A test that shows how the change avoids the error.
One of:
* Run the unit test ExecuteCopiesFrameMetadataExceptWhenMetadataCannotBeCloned
* Run the resizer on the included file TestMetadataIssue2447.jpg
=> Detect potential errors copying metadata and avoid them (#2447)

src/modules/keyboardmanager/common/KeyDelay.h
Move `_delayThread` declaration to occur after all the members of the KeyDelay class. The reason for this being there could be cases where the thread starts before the other members are initialized, causing failures such as the mtx_do_lock exception in the linked issue as a result of the mutex not being initialized before the thread starts. (See highlighted point in the docs below)
These cpp docs https://en.cppreference.com/w/cpp/language/constructor mention the following:
**Initialization order**
The order of member initializers in the list is irrelevant: the actual order of initialization is as follows:
1) If the constructor is for the most-derived class, virtual bases are initialized in the order in which they appear in depth-first left-to-right traversal of the …
=> [KBM] Change declaration order of _delayThread member in KeyDelay

src/runner/settings_window.cpp
The return statement was not correctly placed in the [runner/settings_window.cpp](https://github.com/microsoft/PowerToys/blob/274c009f208a02515b6d5d405692b2e01bf439e5/src/runner/settings_window.cpp#L104). It's been taken out of the loop.
=> [PT runner] Misplaced 'return' statement fix.

src/common/on_thread_executor.cpp, src/common/on_thread_executor.h, src/modules/fancyzones/lib/ZoneWindow.cpp
This PR is the first step towards making the graphics of FZ more responsive. With this PR, dragging a window around will not stutter. There's still a small delay when the zone window is first shown.
We had stuttering because we didn't quickly return control to the OS in the mouse hook. This PR mostly takes care of that by offloading drawing (which is slow) to another thread.
Check that the dragged window doesn't stutter when it moves across zones. Ideally this should be checked on a fast monitor and with a zone layout with many (>20) rows/columns.
=> [FancyZones] Responsive drawing

src/modules/launcher/Microsoft.Launcher/dllmain.cpp
Could apply to issues such as this one #6605. If the Launcher crashes, when we invoke it, nothing happens until it is manually restarted. This PR restarts the launcher if we detect that it crashed or exited somehow.
Start PT, enable the Launcher, terminate it using the Task Manager and hit the invoke hotkey. The launcher should appear immediately in the Task Manager and should show up on the screen in a few seconds.
=> Restart the Launcher if it had crashed when invoked

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/ZoneWindow.h, src/modules/fancyzones/lib/util.cpp, src/modules/fancyzones/lib/util.h, src/modules/fancyzones/tests/UnitTests/Util.Spec.cpp, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp
Improve current procedure for enumeration screens (work areas) which does not take into account possibility that we have more than one [display](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumdisplaydevicesa) per [monitor](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumdisplaymonitors).
Extensive regression testing as this affects every possible monitor / display configuration.
=> [FancyZones] Screen enumeration improvement

src/modules/fancyzones/lib/Zone.cpp, src/modules/fancyzones/lib/Zone.h, src/modules/fancyzones/lib/ZoneSet.cpp, src/modules/fancyzones/tests/UnitTests/Zone.Spec.cpp, src/modules/fancyzones/tests/UnitTests/ZoneSet.Spec.cpp, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp
In order to properly fix #6734 i.e. to match zone numbers between editor and engine and to be able to Win+ windows in zone-numbers-order, some refactoring was needed in Zone class. Zone Id will be used for iterating through zones on Win+arrow as iteration through zones based on their creation order is not reliable (e.g. creating custom grid layout - splitting and merging cells - doesn't give correct order all the time)
Pass zoneId on zone creaton and make it const
Refactor IZone and Zone - move static methods to anonymous namespace and make methods const
Remove SetId
Tested manually
=> [FancyZones] Refactor Zone class

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/VideoConference.xaml
This PR adds an image preview of the camera overlay image in settings. It tries to replicate the Windows 10 Settings UX when setting a new background.
- The path is shown when hovering over the image.
- Moved the Browse and Clear text to the resources file.
- The image provides feedback when using Narrator, meeting accessibility needs.
**Known 'issues':**
- The clear button is always enabled. If there's no image set, it should be disabled.
- When switching between images, there's a short flickering.
Both issues can be resolved by setting a default camera overlay image, tracked in issue https://github.com/microsoft/PowerToys/issues/6314#issuecomment-686401452. (@enricogior Do you want me to export those concepts and include them in the solution? Let me know what resolution you'd need.
=> [VideoConferenceMute] Add camera overlay image preview to settings

src/modules/fancyzones/lib/Settings.h, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/ZoneWindowDrawing.cpp, src/modules/fancyzones/lib/ZoneWindowDrawing.h
Right now we're drawing all zones twice most of the time. See issue #7279
Removed `drawHints` because it was not used and buggy anyway.
Check that zones are colored properly.
=> Fix duplicate zone drawing

src/modules/keyboardmanager/dll/Resources.resx
Remove redundant part from a Combobox name.
Check with the Narrator if combobox in Remap keys/Remap shortcuts windows have correct names that is they should not contain redundant `Drop Down`. As an alternative Accessibility Insight can be used.
=> Remove Drop Down from combo box name as it is redundant

src/common/interop/KeyboardHook.h, src/common/interop/interop.vcxproj
- size of `DWORD dwExtraInfo` was 4 bytes, and on x64 arch pointer size is 8 bytes. [We've stored a pointer in `dwExtraInfo` member](https://github.com/microsoft/PowerToys/blob/cfe2bbd75e35a17436d7ebf6e8a125dec4d5cb40/src/common/interop/KeyboardHook.cpp#L63), which will crash if the system allocator would want to supply us with pages from a higher virtual memory space half.
- treat warnings as errors
- tested that keyboard manager still works
=> interop: fix possible crash in keyboardhook

src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Storage/ConcurrentQueueEventHandlerTest.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/EventHandler.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/Win32ProgramRepository.cs
To prevent PT Run from immediately acting on an app which is installed, a delay of 5 seconds was added before working on any event sent by the file system watcher. However, this was done using a `Thread.Sleep` instead of `Task.Delay`. 
The `Thread.Sleep` blocks the thread whereas `Task.Delay` works based on a timer and schedules the thread to run after that given delay. This would improve the performance as a thread is not blocked anymore doing nothing.
All unit tests pass.
Installed calibre multiple times and ensured that it is installed as expected.
=> Use task delay instead of thread sleep

src/core/Microsoft.PowerToys.Settings.UI.Runner/MainWindow.xaml.cs
This PR adds a null check to the `sender` in the ChildChanged handler. According the the stack trace from Watson, the crash occurred when the user pressed Restart as Admin.
No repro steps, but according to the trace it could happen on pressing Restart as admin.
Validate manually that settings normally works fine and restart as admin works.
=> [Settings] Add null check for WindowsXamlHost_ChildChanged handler to prevent NullRefException

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs, src/modules/launcher/Wox.Test/MainViewModelTest.cs
Fix for autocomplete text is not updating immediately, if typed query text is not a substring of autocomplete text. 
Added check to clear autocomplete text, if the current query text is not a substring of autocomplete text.
Manually validated that the issue is fixed. 
Before : 
After:
=> Fix autocomplete text issue on query change

src/modules/keyboardmanager/common/Shortcut.cpp
As mentioned in the comment at https://github.com/microsoft/PowerToys/issues/6951#issuecomment-706626338, it was found that VK_KANJI sometimes gets set and doesn't get released while pressing Alt+` on Japanese IME. To prevent this from blocking shortcut remaps, this PR adds all the IME related keys as per the [Virtual Key Codes doc](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) to the ignore list.
- Add some shortcut to shortcut remapping
- Switch to Japanese IME keyboard layout
- Open a text editor, and do the following steps:
- Press Alt
- Press ` (At this point the Japanese IME should get changed)
- Release Alt
- Release `
- Press the shortcut you remapped (earlier this wouldn't work until you hit …
=> [KBM] Ignore IME keys while checking keyboard state for Shortcut Remaps

installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp
- show help and exit instead of ignoring invalid flags
- try invalid flags
- try invalid arguments for flags
- try valid flags
=> bootstrapper: treat invalid flags as fatal errors

src/modules/keyboardmanager/dll/KeyboardEventHandlers.cpp
This PR makes the tweaks mentioned in the title, found when writing the documentation for KBM.
- Corrected a comment
- Removed redundant assignment to isShortcutInvoked
- Send key up for target key only if it is pressed (since action key can be released without resetting the state).
Tests passed. This should be sufficient.
For extra validate, try remapping Win+Ctrl+A->B and check that pressing Win+Ctrl+A, releasing A, Ctrl, then Win works fine and start menu doesn't appear. Also check that pressing Win+Ctrl+A then releasing Win while Ctrl+A is still held selects all text in text editor.
=> Tweaked KBM comment, removed redundant assignment, and avoid sending key up for one case when not necessary

src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditorWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.Designer.cs, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx
Focusable items should have automation names added due to accessibility reasons.
1. Launch Accessibility Insights for Windows tool.
2. Open PowerToys Settings App.
3. Navigate to 'Fancy Zones' menu item and activate it. 'Fancy Zone' pane will open.
4. Navigate to 'Launch Zone Editor' button and activate it. 'Choose your layout for this desktop' window will open.
5. Run the Accessibility Insights for Windows tool.
Expected result: Spacing around zones and distance between adjacent zones text boxes should have names. Same goes for the "main" template tab, which allows You to choose between predefined and custom layouts.
=> [FancyZones] Add AutomationProperties.Name to focusable elements

src/modules/launcher/Plugins/Microsoft.Plugin.Calculator.UnitTest/ExtendedCalculatorParserTests.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/CalculateEngine.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/CalculateHelper.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/CalculateResult.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/ResultHelper.cs
This PR fixes some incorrect results and exceptions being thrown by the calculator plugin which might be slowing down PT Run.
1. Following the refactoring of the calculator plugin, the searched which resulted in 0 as the result were not working as there was no difference between a default result returned when the input was not valid and a valid input resulting in 0 as the answer. 
The `ValidResult` field has been added to distinguish a valid result from a default result. null couldn't be returned because CalculateResult is a non-nullable type.
Eg: 1-1.
2. Exceptions were being thrown when the user query is not complete, as the queryhelper thinks that the query is valid but the interpreter …
=> Fix exceptions and incorrect results within the calculator plugin

src/core/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
When text size is set to 225%, parts of UX would be clipped due to hardcoded values.
all instances of Tooltip with hotkey picker are now tweaked to correct. was caused by hardcoded width. bet languages could have also introduced this.
Fixed exclude app
bet languages could have also introduced this. due to hardcoded width and height
Image Resizer settings:
follow steps in #7068
=> Settings accessibility issues with clipping on large text

src/modules/fancyzones/editor/FancyZonesEditor/Models/Settings.cs, src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/Zone.cpp, src/modules/fancyzones/lib/ZoneSet.cpp, src/modules/fancyzones/lib/ZoneSet.h, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/ZoneWindowDrawing.cpp, src/modules/fancyzones/lib/ZoneWindowDrawing.h, src/modules/fancyzones/tests/UnitTests/ZoneSet.Spec.cpp, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp
Fix misaligned zone numbers between Editor and FancyZonesLib.
Cycle zone by zoneId on win+arrow
Update zone drawing logic
=> [FancyZones] Align zone numbers between Editor and FancyZonesLib

src/core/Microsoft.PowerToys.Settings.UI.Library/ViewModels/ImageResizerViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml.cs
This PR adds code to switch the tab focus to the new ListViewItem when the Add Size button is pressed.
The logic needs to happen in ContainerContentChanging and not the Button_Click handler as the ListView doesn't get updated immediately after `ViewModel.AddRow` is called.
**Note:** This PR only makes the focus change mentioned in the issue and not the "announcement after successful add/delete" feedback on the issue.
Turn on Narrator
- Tab through the Image Resizer page till the Add Sizes button and press it
- Validate that Narrator reads out the new item in the ListView and it focus is on that element
- Move focus to the remove button and press it
- Validate that narrator reads out the adjacent element and focus is on it.
=> [Settings] Switch focus to last Image Size ListViewItem on adding new size

src/core/Microsoft.PowerToys.Settings.UI.Library/Utilities/Logger.cs, src/core/Microsoft.PowerToys.Settings.UI.Runner/MainWindow.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI.Runner/Microsoft.PowerToys.Settings.UI.Runner.csproj, src/core/Microsoft.PowerToys.Settings.UI.Runner/Program.cs
Adding FxCop to the Microsoft.PowerToys.Settings.UI.Runner.csproj project, and fixing the resulting warnings and errors.
Minor changes to the Settings.UI.Runner project to enable FxCop. Includes marking Program class as static, checking if args is null, using (discarding) the return result of TryParse and changing Json.Parse to Json.TryParse on WindowsXamlHost_ChildChanged.
Ensure unit tests pass on Debug & Release mode, and manually validate settings functionality for Debug & Release builds.
=> [fxcop] Settings UI runner

src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp, src/modules/keyboardmanager/ui/EditShortcutsWindow.cpp, src/modules/keyboardmanager/ui/ShortcutControl.cpp, src/modules/keyboardmanager/ui/SingleKeyRemapControl.cpp
This PR adds tooltips for the Add and Delete buttons in Remap key and Remap shortcut windows. The same text that is used for the accessible name of the buttons has been used for the tooltip info so that it is consistent with Narrator.
Validate that the tooltips appear on hovering over Add and Delete buttons on both windows. Narrator does not read out tooltips, but the accessible name for these buttons already contains the same text so Narrator will read that out.
=> [KBM] Added tooltips for Add and Delete buttons

src/modules/keyboardmanager/ui/ShortcutControl.cpp
This PR implements the GotFocus handler for the Target App textbox, such that the text in the textbox is selected on tabbing to it (similar to address bar in Edge)
- Open Remap Shortcuts and ensure there is atleast 1 row
- While the textbox is empty, tab/shift+tab/mouse-click into the TextBox and validate that nothing happens
- While the textbox has some multi-char text, tab/shift+tab/mouse-click into the TextBox and validate that the entire text is selected (similar to address bar in Edge/Chrome)
=> [KBM] Select all text in Target App textbox on getting focus

src/core/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/KeyboardManagerPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml, src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
Visually impaired users user landmarks to classify the contents of the app. The main landmark is the one which contains all the main information.
This PR adds a main landmark to each of the settings pages. Tried to add it to the page style setter but it does not seem like the pages are using that style as it was not being reflected.
* Enable windows narrator
* Turn scan mode on,
* Press Caps+N to go to the main landmark or navigate the landmarks using D.
=> Added a main landmark to all settings pages

src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/DriveDetection/DriveInfoWrapper.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/DriveDetection/IndexerDriveDetection.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Interface/IDriveInfoWrapper.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.Designer.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx, src/modules/launcher/Wox.Test/Plugins/WindowsIndexerTest.cs
The Drive detection warning for the indexer plugin should not be displayed when there is only a single drive on the system.
Added an additional check where the drive detection warning is not displayed when there is only one drive on the system.
Tested it manually as well as added unit tests for the same.
=> Display Drive detection warning only for multiple drives

src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp, src/modules/keyboardmanager/ui/EditShortcutsWindow.cpp, src/modules/keyboardmanager/ui/KeyboardManagerUI.vcxproj, src/modules/keyboardmanager/ui/KeyboardManagerUI.vcxproj.filters, src/modules/keyboardmanager/ui/UIHelpers.cpp, src/modules/keyboardmanager/ui/UIHelpers.h
This PR adds logic so that after the Add remap button is pressed the keyboard focus is moved to the Type button on the new row.
- A new namespace UIHelpers has been added for any common UI operations to be done on both the windows.
- Tab to the Add remap button and press Enter to add a row. Validate that focus is on the Type button of the new row. This should be validated on both windows.
- Use Narrator and validate that the details of the row are read out on adding the remapping.
=> [KBM] Move Focus to Type button in new row on Adding a remap

src/core/Microsoft.PowerToys.Settings.UI.Runner/MainWindow.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Activation/ActivationHandler.cs, src/core/Microsoft.PowerToys.Settings.UI/Activation/DefaultActivationHandler.cs, src/core/Microsoft.PowerToys.Settings.UI/App.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Behaviors/NavigationViewHeaderBehavior.cs, src/core/Microsoft.PowerToys.Settings.UI/Controls/HotkeySettingsControl.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Converters/ModuleEnabledToForegroundConverter.cs, src/core/Microsoft.PowerToys.Settings.UI/Helpers/NativeMethods.cs, src/core/Microsoft.PowerToys.Settings.UI/Helpers/NavHelper.cs, src/core/Microsoft.PowerToys.Settings.UI/Interop.cs, src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj, src/core/Microsoft.PowerToys.Settings.UI/Services/ActivationService.cs, src/core/Microsoft.PowerToys.Settings.UI/ViewModels/ShellViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/KeyboardManagerPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml.cs, src/core/Microsoft.PowerToys.Settings.UI/Views/VisibleIfNotEmpty.cs
Enable FxCop on the Settings.UI project and fixing the associated warnings.
Fixes FxCop warnings including: removing redundant default-value initializations, ensuring Disposable fields are disposed, marking non-instance accessing methods and classes with only static members & methods as static, moving interop methods to NativeMethods class, fixing string-related issues (mainly specifying culture and string normalization), removing unused arguments or suppressing the warning if needed, using safe navigation operator as null argument checks, logging general exceptions that are caught and suppressing ConfigureAwait warnings (which are mostly intended for library code with unpredictable/unspecified execution environments--should be safe to do for UI code).
Ensure tests pass and manually …
=> [fxcop] Settings UI

installer/PowerToysSetup/Product.wxs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Microsoft.Plugin.Calculator.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Microsoft.Plugin.Folder.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Microsoft.Plugin.Indexer.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Microsoft.Plugin.Program.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Microsoft.Plugin.Shell.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Microsoft.Plugin.Uri.csproj, src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Microsoft.Plugin.WindowWalker.csproj
Remove duplicated dll's present in the plugin's output folder.
`Wox.infrastructure` and `Wox.plugin` are currently compiled for all plugins referencing it, and corresponding dll's are copied to each plugin's output folder. However, these extra copies are unnecessary as during runtime, required DLL's are loaded in memory by `PowerLauncher` project.
1. Manually validated that the plugins output folder do not contain dll's load at runtime by `PowerLauncher` project.
2. Manually validated that MSI complies and all plugins in PT Run work as expected.
MSI for reference : 
Master
[PowerToysSetup-0.23.1-x64.zip](https://github.com/microsoft/PowerToys/files/5455044/PowerToysSetup-0.23.1-x64.zip)
This PR
[PowerToysSetup-0.23.1-x64-withCopyLocal.zip](https://github.com/microsoft/PowerToys/files/54550 …
=> [PT Run] Remove duplicated dll's from Plugins

src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditorWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/GridEditorWindow.xaml.cs
Enable Closing Edit Canvas Layout and Edit Grid Layout windows by pressing Esc button. 
Navigating to 'Close' button using e.g. Tab button requires bigger rework of these windows. As complete rework of Editor is planned, this will probably be part of that work.
Scenario 1:
Open Power Toys App
Navigate to Fancy Zone Button and activate it.
Navigate to Launch Zones Editor and activate it.
Navigate to Custom tab in Choose your layout for this Desktop dialog and select it.
Navigate to Create new custom item and selet it
Navigate to Edit Selected layout element and activate it.
Press Esc button and confirm that Edit Selected Layout window is closed
Scenario 2:
Open Power Toys App
Navigate to Fancy Zone Button and activate it.
Navigate …
=> [Accessibility][FancyZones Editor] Close Edit Canvas Layout and Edit Grid Layout windows by pressing Esc

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs
Changed text position in the main editor window.  Wrap text in case if it won't fit into the line width.
For testing, you can set desired values for  `Space_Around_Zones` or  `Distance_adjacent_zones` in the resource file.
=> [Localization] Unreachable input box in FancyZones Editor fix.

src/modules/fancyzones/editor/FancyZonesEditor/GridEditorWindow.xaml
Bind *Name* label with associated textbox for GridEditorWindow. Issue says CanvasEditorWindow, however, that one is already bind correctly.
Open FancyZones Editor
Select e.g. PriorityGrid layout
Click "Edit Selected Layout"
Press Win+Ctrl+Enter to turn on the Narrator
Navigate to "Custom layout 1" text box
Observe that Narrator says "*Name* edit Custom layout 1"
=> [Accessibility] [FancyZones Editor] Associate Name label with textbox

src/modules/imageresizer/ui/Views/AccessibleHyperlink.cs, src/modules/imageresizer/ui/Views/AdvancedWindow.xaml, src/modules/imageresizer/ui/Views/CustomizableHyperlinkAutomationPeer.cs, src/modules/imageresizer/ui/Views/InputPage.xaml
fix hyperlink roles by introducing `CustomizableHyperlinkAutomationPeer`
Accessibility Insights reports those as buttons now.
=> ImageResizer: fix hyperlink buttons role

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml
FancyZones Editor has two tabs, `Templates` and `Custom` tab, one showing predefined layouts (columns, rows, grid etc.) and other showing user's custom layouts. Active tab is shown in [hex 2A87D7](https://www.colorhexa.com/2a87d7) color, while inactive tab has [hex C4C4C4](https://www.colorhexa.com/c4c4c4). Contrast ratio between inactive tab and white background is not 4.5:1 which is required minimum.
Since we want to have some sort of distinction between active and inactive tab, pick shade of gray for inactive that fits accessibility requirements. First one that fulfilled required ratio of 4.5:1 is [hex 767676](https://www.colorhexa.com/767676)
1. Open Power Toys App
2. Navigate to Fancy Zone Button and activate it.
3. Navigate to Launch Zones Editor and activate it.
4. Navigate to …
=> [FancyZones] Adjust template tab non-highlighted color

src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Sources/Path/FolderHelper.cs
Support for path starting with backslash: **an absolute path from the root of the current drive**
https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats
Support for path starting with backslash
The **\** is replaced with Windows drive (in most cases C:\)
- Open PT Run
- Type a path that starts with backslash (e.g. \windows\system32)
- Press enter
=> [PT Run] Folder path starting with backslash

src/modules/imageresizer/ui/App.xaml, src/modules/imageresizer/ui/Views/InputPage.xaml
I've changed ComboBox item colors to high contrast. I wasn't able to use the same approach as in #7781 to employ `SystemColors` because of "resource not found" error, so they're hardcoded. Tagging @niels9001 for visibility, perhaps he can suggest a solution for that 🙂 .
=> ImageResizer: fix Color contrast of ComboBox

src/modules/launcher/PowerLauncher/SettingsWatcher.cs
Apply correct theme at startup.
At first run theme is handled as system instead of user set Dark/Light.
- Set Windows color Dark
- Set PT Run color Light
- Reboot
- Invoke PT Run
- PT Run color is Light
=> [PT Run] Handle theme at startup

src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditorWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/GridEditorWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml
Use [hex 949494](https://www.colorhexa.com/949494) color for secondary buttons and custom layout name box, to achieve 3:1 contrast ratio against white background.
1. Open PowerToys App
2. Navigate to FancyZones Button and activate it.
3. Navigate to Launch Zones Editor and activate it.
4. Navigate to Custom tab in Choose your layout for this Desktop dialog and select it.
5. Navigate to Create new custom item and select it
6. Navigate to Edit Selected layout element and activate it.
7. Navigate to 'Name' edit field boundary and verify its luminosity ratio.
Expected result: Luminosity ratio is 3:1.
=> [FancyZones] Adjust colors of secondary buttons to maintain 3:1 contrast ratio against white background

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
This PR brings groupings to the FZ settings page.
- New headings
- Re-ordering of existing controls
=> [Settings] Updated FZ page

src/modules/fancyzones/editor/FancyZonesEditor/GridEditorWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.Designer.cs, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx
**Issue**:  All windows are missing window titles (it’s just announced as “Window” in NVDA, both when opening and when alt-tabbing)
**Fix**: Added name propery (value: Grid Layout Editor)
**Before**
**After**
- Open FancyZones Editor
- Select some of the predefined Layout (e.g. 3-zones Priority Grid)
- Press Edit Selected Layout
- Open Accessibility Insights for Windows app and scan Grid Layout Editor window
- Observe that there is name attribute set (value: Grid Layout Editor)
=> [Accessibility][FancyZones Editor] Add Grid Layout Editor name property

src/modules/keyboardmanager/ui/pch.h, tools/CleanUp_tool/main.cpp
To remove warnings about deprecated headers and for more robust C++, this replaces the deprecated C header with its C++ equivalent.
Replaces deprecated C headers with their C++ equivalent.
Replaces deprecated C headers with their C++ equivalent.
Passed all Unit Tests
=> Replace deprecated C headers with their C++ equivalent

src/common/common.cpp
No other usage of GetLastError has the result assigned to a variable first in this code, so it is better if we make check_user_is_admin the same in that regard.
GetLastError() is no longer assigned to a variable in check_user_is_admin
GetLastError() is no longer assigned to a variable in check_user_is_admin
Passed unit tests
=> Remove unneeded variable for GetLastError();

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.Designer.cs, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx
User's custom layouts shown in FancyZones Editor can be deleted by clicking on small delete button in top right corner of the layout preview. This delete button is lacking accessibility name, and therefore cannot be announced by narrator.
1. Open PowerToys Settings application.
2. Navigate to FancyZones present at the left side of the pane and activate it.
3. Navigate to 'Launch Zone Editor' present at the right side of the pane and activate it.
4. Navigate to Custom tab in Choose your layout for this Desktop dialog and activate it.
5. Run Accessibility Insights for Windows tool.
Expected result: Delete button is focusable element and it has valid descriptive name.
=> [FancyZones] Add name property for delete button

README.md
=> [README] [Fix] Links to File Explorer addons is a bit misleading

.github/actions/spell-check/expect.txt, src/core/Microsoft.PowerToys.Settings.UI.Library/PowerRenameLocalProperties.cs, src/core/Microsoft.PowerToys.Settings.UI.Library/PowerRenameProperties.cs, src/core/Microsoft.PowerToys.Settings.UI.Library/PowerRenameSettings.cs, src/core/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerRenameViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml, src/modules/powerrename/UWPui/PowerRenameUWPUI.vcxproj, src/modules/powerrename/UWPui/packages.config, src/modules/powerrename/dll/PowerRenameExt.vcxproj, src/modules/powerrename/dll/Resources.resx, src/modules/powerrename/dll/dllmain.cpp, src/modules/powerrename/dll/packages.config, src/modules/powerrename/lib/PowerRenameLib.vcxproj, src/modules/powerrename/lib/PowerRenameRegEx.cpp, src/modules/powerrename/lib/PowerRenameRegEx.h, src/modules/powerrename/lib/Settings.cpp, src/modules/powerrename/lib/Settings.h, src/modules/powerrename/lib/packages.config, src/modules/powerrename/lib/trace.cpp, src/modules/powerrename/testapp/PowerRenameTest.vcxproj, src/modules/powerrename/testapp/packages.config, src/modules/powerrename/unittests/PowerRenameLibUnitTests.vcxproj, src/modules/powerrename/unittests/PowerRenameLibUnitTests.vcxproj.filters, src/modules/powerrename/unittests/PowerRenameRegExBoostTests.cpp, src/modules/powerrename/unittests/PowerRenameRegExTests.cpp, src/modules/powerrename/unittests/packages.config
Adds the possibility to use Boost Library for Regular Expressions instead of the Standard Library. The Boost library has more features such as Lookbehind.
* Added Boost Regex Module (with its dependencies) as NuGet dependency.
* `CPowerRenameRegEx` uses library according to property.
* Extended signatures to set the library.
=> PowerRename: Add Lookbehind

src/modules/launcher/PowerLauncher/ReportWindow.xaml.cs, src/modules/launcher/Wox.Plugin/Logger/Log.cs
In master and 0.25.0 PT Run log file is not created.
PT Run log file is not created.
After PT Run startup the log file is created in `C:\Users\david\AppData\Local\Microsoft\PowerToys\PowerToys Run\Logs`.
=> [PT Run] Log file not created

.github/actions/spell-check/expect.txt, src/runner/Resources.resx, src/runner/tray_icon.cpp
Since we cannot localize hardcoded menuitem values in .rc files, we localize menuitems after they've been created with `LoadMenu` call.
- changed resources.resx file values to something different and verified that it still works
=> runner: localize tray menu item labels

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs
Template and custom layout items are now accessible through keyboard, either by navigating by `Tab` or through keyboard arrows. When certain layout is focused through keyboard, and user presses `Enter` or `Space` key, layout will be applied.
1. Open PowerToys Settings App.
2. Navigate to FancyZones menu item and activate it.
3. Navigate to Launch Zone Editor button and activate it. Choose your layout for this desktop window will open.
4. Try accessing one of Focus/Column/Rows/Grid/Power Grid menu items using keyboard (`Tab` or keyboard arrows).
5. Press `Enter` or `Space` key.
6. Open FancyZones Editor again, and do the same with custom layouts.
Expected result: Layout items (both template and custom) are accessible through keyboard.
=> [FancyZones] Enable keyboard accessibility for template and custom layout items

src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditorWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/GridEditorWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/GridEditorWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs, src/modules/fancyzones/lib/FancyZones.cpp
First interactive element is now focused by default when each FZ Editor window is shown.
Open FancyZones
Open FancyZones Editor
Navigate from one Editor window to another (Edit Selected Layout window - both Grid and Custom)
Observe that every window has focused element on opening, either by pressing Enter and observing the behavior, or if shown "focused dotted rectangle" for specific window element
=> [FancyZones Editor][Accessibility] Default focused elements in all FancyZones Editor windows

src/modules/fancyzones/editor/FancyZonesEditor/EditorOverlay.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs
Screen reader is reading Left/Right Window Commands elements of the Metro Window. To prevent this, remove them.
- Open FancyZones Editor
- Click Edit Selected item
- Turn on Narrator
- Navigate through window elements using arrow keys
- Observe that there are no hidden elements in top left corner of the screen, i.e. Narrator doesn't narrate them
Do the same for both Grid and Custom editor windows
=> [FancyZones Editor][Accessibility] Remove Left/Right Window Commands

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.Designer.cs, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx
Add custom, localized string which should be announced when user selects templates or custom tab. User can switch between those two by pressing ctrl + tab.
1. Open PowerToys Settings application.
2. Navigate to FancyZones present at the left side of the pane and activate it.
3. Navigate to 'Launch Zone Editor' present at the right side of the pane and activate it.
4. Choose your layout for this desktop utility dialog will get open.
5. Navigate to Template and Custom tab items using Tab key.
=> [FancyZones] Add custom announcement to tab items

.github/actions/spell-check/expect.txt, installer/PowerToysSetup/Product.wxs, src/modules/imageresizer/tests/Properties/AppFixture.cs, src/modules/imageresizer/ui/App.xaml, src/modules/imageresizer/ui/App.xaml.cs, src/modules/imageresizer/ui/ImageResizerUI.csproj, src/modules/imageresizer/ui/Properties/Resources.Designer.cs, src/modules/imageresizer/ui/Properties/Resources.resx, src/modules/imageresizer/ui/Themes/Dark.xaml, src/modules/imageresizer/ui/Themes/HighContrast1.xaml, src/modules/imageresizer/ui/Themes/HighContrast2.xaml, src/modules/imageresizer/ui/Themes/HighContrastBlack.xaml, src/modules/imageresizer/ui/Themes/HighContrastWhite.xaml, src/modules/imageresizer/ui/Themes/Light.xaml, src/modules/imageresizer/ui/Utilities/CustomLibraryThemeProvider.cs, src/modules/imageresizer/ui/Utilities/ThemeManager.cs, src/modules/imageresizer/ui/ViewModels/ProgressViewModel.cs, src/modules/imageresizer/ui/Views/AdvancedWindow.xaml, src/modules/imageresizer/ui/Views/AdvancedWindow.xaml.cs, src/modules/imageresizer/ui/Views/InputPage.xaml, src/modules/imageresizer/ui/Views/MainWindow.xaml, src/modules/imageresizer/ui/Views/ProgressPage.xaml, src/modules/imageresizer/ui/Views/ResultsPage.xaml
- It now adopts Fluent Design, and uses ModernWPF to mimic the WinUI look and feel. Theming support has been added as well (including all versions of high contrast)
In that sense, it addresses #1053 but I wouldn't close it since we need a bigger UI refresh to adopt WinUI and really rethink the UI logic.
- Added DataTriggers that will disable the input boxes when the custom radiobutton is not selected.
Impression:
Dark vs. light vs. high contrast
Settings
Progress view
Solves various narrator/accessibility insights issues by setting the AutomationProperties.Name values:
#7062, #7059, #7055, #7034, #7038, #7041, #7045
This does introduce a new issue on the Settings page that I do not know how to solve. These items are part of a ListView, so it makes sense that they all have the name …
=> [Image Resizer] Fluent UI and theming support

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
PowerRename Settings page uses "PowerRename" and "Power Rename" inconsistently 
Changes "Power Rename" to "PowerRename" in PowerRename Settings' Description
*Not required*
=> Change Settings' Resources.resw to use the name PowerRename consistently. 

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/FancyZonesData.cpp, src/modules/fancyzones/lib/VirtualDesktopUtils.cpp
1. If user never made a new virtual desktop, there will be no information about virtual desktop id in the registry, and zeroed-GUID will be used. Migrate persisted information for zeroed-GUID in primary desktop when virtual desktop switch occurs. 
2. Don't use `IVirtualDesktopManager::GetWindowDesktopId` on `GetForegroundWindow` during initialization. If PowerToys start right away when system starts, `GetForegroundWindow` might not contain valid HWND, and we could end up with zeroed-GUID.
1. Clear the registry (both _Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\SessionInfo\\<id>\\VirtualDesktops_ and _Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VirtualDesktops_) and persisted FancyZones settings (_C:\Users\<user-name>\AppData\Local\Microsoft\PowerToys\FancyZones_), …
=> [FancyZones] Update primary desktop data on virtual desktop switch

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/CanvasLayoutModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutSettings.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/MainWindowSettingsModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.Designer.cs, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx, src/modules/fancyzones/editor/FancyZonesEditor/Utils/FancyZonesEditorIO.cs, src/modules/fancyzones/lib/JsonHelpers.cpp, src/modules/fancyzones/lib/ZoneWindow.cpp
Allow resetting layout on the selected monitor.  
Added `Reset` button that helps to deselect applied or default layout on the selected monitor.
After resetting the layout has the `Blank` type.  All other layout settings (zones count, spacing, etc.) remain the same and are saved as usual.
* Reset layout with `Allow zones to span across monitors` selected.
* Reset layout with `Allow zones to span across monitors` deselected.
* Verify after resetting:
* no layout marked as selected (blue border)
* no layout marked as applied (blue background)
* layouts are saved and applied correctly
=> [FancyZones Editor] Reset layout

.pipelines/ci/templates/build-powertoys-steps.yml, installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp, installer/PowerToysBootstrapper/bootstrapper/pch.h, installer/PowerToysSetupCustomActions/CustomAction.cpp, installer/PowerToysSetupCustomActions/PowerToysSetupCustomActions.vcxproj, src/action_runner/action_runner.cpp, src/common/updating/installer.cpp, src/common/updating/installer.h, src/common/updating/notifications.h, src/common/updating/updating.cpp, src/common/updating/updating.h, src/common/updating/updating.vcxproj, src/common/updating/updating.vcxproj.filters, src/runner/main.cpp, src/runner/update_utils.cpp
talked to Matteo Pagani, this should be the fix. Net 5.0 requires NuGet 5.8. If you're using an older version, you will get that error
=> Fixing CI with moving NuGet to 5.8 for .NET 5

src/modules/keyboardmanager/common/KeyboardManagerCommon.vcxproj, src/settings/settings.vcxproj
- increase compiler limit for pch-heavy projects.
This may actually cause an inverse of what we want - if so, we'll revert it and remove /Zm150 from settings.vcxproj
- compile solution
=> kbm: increase compiler memory limit

src/modules/keyboardmanager/common/KeyboardManagerCommon.vcxproj, src/settings/settings.vcxproj
https://github.com/microsoft/PowerToys/pull/8211/checks?check_run_id=1449097433
Looks like /Zm doesn't work well with /MP option, so let's remove it 
- build Debug and Release PT locally 
- build release version w/ /p:CIBuild=true
=> build: remove compiler memory limits

src/modules/colorPicker/ColorPickerUI/Views/ColorEditorView.xaml
Hiding remove context menu when there are no colors in the history
Manual test
=> Hiding remove context menu when there are no colors in the history

src/modules/colorPicker/ColorPickerUI/Helpers/AppStateHandler.cs, src/modules/colorPicker/ColorPickerUI/Helpers/ClipboardHelper.cs, src/modules/colorPicker/ColorPickerUI/Keyboard/KeyboardMonitor.cs, src/modules/colorPicker/ColorPickerUI/NativeMethods.cs
Color picker can freeze when you pick a color because we are trying to access clipboard using `Clipboard.SetText` - but this method might as some other applications can hold clipboard.
Switching to use `Clipboard.SetDataObject` I couldn't reproduce this issue anymore
This also fixes another issue when user holds activations keys while picking - this was causing that show picker was called many times and in the end it resulted in a nasty bug where we called copy into clipboard and into the editor nonstop.  Can be seen here - https://youtu.be/6mzs90-KlMg?t=195
Described also here #6594
Unless you use some special tools for clipboard, it is hard to reproduce as it can happen randomly, but to get a stable reproduction, install [Clipjump](http://clipjump.sourceforge.net/) tool with this …
=> Fixing issues when color picker freezes

installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp
`--install_dir` CLI argument added to bootstrapper.
Require wiki update: https://github.com/microsoft/PowerToys/wiki/Installer-arguments-for-exe
The path is passed to the MSI as value of the INSTALLFOLDER property.
Test installation and update in custom directory.
=> [Bootstrapper] --install_dir arg

src/modules/fancyzones/lib/ZoneWindowDrawing.cpp
This should fix the Video memory leak issue some people are seeing. The reason why people saw their RAM used up is probably because their system doesn't have dedicated GPU memory.
You can test this even you have dedicated GPU memory. Open Task Manager, run PT, do the following a couple of times:
* Create a few new virtual desktops
* Apply a zone layout on each (if you have a layout applied on the parent VD, this should happen automatically)
* Make sure you use FancyZones on each VD (it's enough to make the overlay appear)
* Delete all those VDs
You should see Video memory usage increase and not come down when VDs are deleted. With this PR however, it should come down to where it was.
=> [FancyZones] Video memory leak fix, free render target

src/modules/fancyzones/lib/ZoneWindow.cpp
This PR should reduce use of VRAM by reducing the size of the window used to draw the overlay. We were multiplying the size by DPI, possibly because before we weren't DPI aware, but now it's completely unnecessary.
Create a large number of virtual desktops and use FZ on each. Ideally at least one monitor should have a high resolution and the highest DPI scaling possible. You should see a lot less memory use with this PR than without it.
Also, of course, FZ should display correctly.
=> [FancyZones] Reduce VRAM use

.pipelines/ci/templates/build-powertoys-steps.yml, src/common/interop-tests/Microsoft.Interop.Tests.csproj, src/common/interop-tests/packages.config
Migrate Microsoft.Interop.Tests to target .NET Core 3.1. 
This is part of projects to be migrated to .NET Core 3.1 in #776 
The unit test should run successfully
=> migrate Microsoft.Interop.Tests to target .NET Core 3.1

.pipelines/pipeline.user.windows.yml, installer/PowerToysSetup/Product.wxs, src/modules/colorPicker/ColorPicker/dllmain.cpp, src/modules/colorPicker/ColorPickerUI/App.config, src/modules/colorPicker/ColorPickerUI/App.xaml.cs, src/modules/colorPicker/ColorPickerUI/Behaviors/AppearAnimationBehavior.cs, src/modules/colorPicker/ColorPickerUI/Behaviors/ChangeWindowPositionBehavior.cs, src/modules/colorPicker/ColorPickerUI/Behaviors/CloseZoomWindowBehavior.cs, src/modules/colorPicker/ColorPickerUI/Behaviors/DragAndDropReorderBehavior.cs, src/modules/colorPicker/ColorPickerUI/Behaviors/DragWindowBehavior.cs, src/modules/colorPicker/ColorPickerUI/Behaviors/GridEffectBehavior.cs, src/modules/colorPicker/ColorPickerUI/Behaviors/MoveWindowBehavior.cs, src/modules/colorPicker/ColorPickerUI/Behaviors/ResizeBehavior.cs, src/modules/colorPicker/ColorPickerUI/ColorEditorWindow.xaml, src/modules/colorPicker/ColorPickerUI/ColorPickerUI.csproj, src/modules/colorPicker/ColorPickerUI/Controls/ColorPickerControl.xaml.cs, src/modules/colorPicker/ColorPickerUI/MainWindow.xaml, src/modules/colorPicker/ColorPickerUI/Program.cs, src/modules/colorPicker/ColorPickerUI/Views/ColorEditorView.xaml, src/modules/colorPicker/ColorPickerUI/Views/ZoomView.xaml, src/modules/colorPicker/ColorPickerUI/ZoomWindow.xaml
Conversion of the Color Picker module from .NET Framework to .NET Core 3.1.
The Unit Tests for the Color Picker run successfully, the module itself can be run properly in both a standalone instance and within the runner. Colors are properly detected and selected. The key combination works properly.
=> Color picker netcore 31

src/action_runner/action_runner.vcxproj, src/common/common.cpp, src/common/updating/notifications.cpp, src/common/updating/updating.cpp, src/common/updating/updating.h, src/runner/runner.vcxproj, src/runner/settings_window.cpp, src/runner/update_utils.cpp, src/runner/update_utils.h
We need a different method of updating when using Github's prerelease API. 
- update from a local build with the 0.0-version-check commented out
=> updating: add support for prereleases

PowerToys.sln
Fixes the issue [mentioned here](https://github.com/microsoft/PowerToys/pull/8412#issuecomment-742416712).
We'll re-enable it later as part of [this task](https://github.com/microsoft/PowerToys/issues/8542).
=> CI: disable win-app-driver project

.github/actions/spell-check/expect.txt, src/modules/powerrename/dll/PowerRenameExt.cpp, src/modules/powerrename/dll/dllmain.cpp, src/modules/powerrename/lib/Helpers.cpp, src/modules/powerrename/lib/Helpers.h, src/modules/powerrename/lib/PowerRenameInterfaces.h, src/modules/powerrename/lib/PowerRenameItem.cpp, src/modules/powerrename/lib/PowerRenameItem.h, src/modules/powerrename/lib/PowerRenameManager.cpp, src/modules/powerrename/lib/PowerRenameManager.h, src/modules/powerrename/lib/PowerRenameRegEx.cpp, src/modules/powerrename/lib/PowerRenameRegEx.h, src/modules/powerrename/lib/Settings.cpp, src/modules/powerrename/ui/PowerRenameUI.cpp, src/modules/powerrename/unittests/MockPowerRenameItem.cpp, src/modules/powerrename/unittests/MockPowerRenameItem.h, src/modules/powerrename/unittests/MockPowerRenameManagerEvents.cpp, src/modules/powerrename/unittests/MockPowerRenameRegExEvents.cpp, src/modules/powerrename/unittests/MockPowerRenameRegExEvents.h, src/modules/powerrename/unittests/PowerRenameManagerTests.cpp, src/modules/powerrename/unittests/PowerRenameRegExBoostTests.cpp, src/modules/powerrename/unittests/PowerRenameRegExTests.cpp
Fixes power rename tests which was inconsistently failing.
Increases test performance.
Set `fileTime` as a member of `PowerRenameRegEx` instead of passing it to `Replace()` call
PowerRename works as expected, especially with file attributes. (like `$YYYY` `$DDDD` `$MM` patterns)
**Also with Search For area and/or Replace With area empty, with different flags**
Tests are passing consistently.
=> [PowerRename] Fix tests inconsistency, improve test performance

src/modules/colorPicker/ColorPickerUI/Controls/ColorFormatControl.xaml
Due to a wrong reference to a non-existing style, the regular WPF right-click context menu showed. This PR fixes that by removing the reference entirely. To remove the selection border the selection brush color is overriden and made transparent.
Now, a context menu is shown that fits into the rest of the UI:
=> [Color Picker] Fix for wrong style of right-click context menu

.github/actions/spell-check/expect.txt, src/core/Microsoft.PowerToys.Settings.UI.Library/ColorPickerProperties.cs, src/core/Microsoft.PowerToys.Settings.UI.Library/ViewModels/ColorPickerViewModel.cs, src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/core/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml, src/modules/colorPicker/ColorPickerUI/Behaviors/AppearAnimationBehavior.cs, src/modules/colorPicker/ColorPickerUI/Converters/BoolToInvertedVisibilityConverter.cs, src/modules/colorPicker/ColorPickerUI/Helpers/ColorNameHelper.cs, src/modules/colorPicker/ColorPickerUI/MainWindow.xaml, src/modules/colorPicker/ColorPickerUI/Properties/Resources.Designer.cs, src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx, src/modules/colorPicker/ColorPickerUI/Resources/Styles.xaml, src/modules/colorPicker/ColorPickerUI/Settings/IUserSettings.cs, src/modules/colorPicker/ColorPickerUI/Settings/UserSettings.cs, src/modules/colorPicker/ColorPickerUI/ViewModelContracts/IMainViewModel.cs, src/modules/colorPicker/ColorPickerUI/ViewModels/MainViewModel.cs, src/modules/colorPicker/ColorPickerUI/Views/MainView.xaml
Showing color name in the picker. 
Ported internal WinUI implementation, now we show the same name as WinUI color picker
Added Niel's attribution into settings
In action: 
When show color name is disabled the color picker looks the same as it does now (one row, smaller color square)
Settings:
Manual validation
=> Color Picker - show color name

src/modules/imageresizer/ui/Models/ResizeSize.cs, src/modules/imageresizer/ui/Views/MainWindow.xaml
Aligned the behaviour of Image Resizer UI to PowerToys settings when using percentage as resize unit.
I have also set a minimum width for the window of 485px becouse the window automatically resizing selecting percentage looked so bad.
Aligned the behaviour of Image Resizer UI to PowerToys settings when using percentage as resize unit.
- Open Image Resizer
- Select Custom
- Select Percentage as resize unit
- The height textbox is set as not visible
=> [Image Resizer] Handling percentage unit

doc/devdocs/localization.md, installer/PowerToysBootstrapper/bootstrapper/bootstrapper.vcxproj, src/action_runner/action_runner.vcxproj, src/modules/colorPicker/ColorPicker/ColorPicker.vcxproj, src/modules/fancyzones/lib/FancyZonesLib.vcxproj, src/modules/imageresizer/dll/ImageResizerExt.vcxproj, src/modules/launcher/Microsoft.Launcher/Microsoft.Launcher.vcxproj, src/modules/powerrename/dll/PowerRenameExt.vcxproj, src/modules/powerrename/ui/PowerRenameUI.vcxproj, src/modules/previewpane/powerpreview/powerpreview.vcxproj, src/modules/shortcut_guide/shortcut_guide.vcxproj, src/runner/runner.vcxproj
On some machines, the localization script is invoked passing a project folder that is incorrect.
run `git clean -xfd` and then do a full build.
=> Fix passing project folder path to localization script

PowerToys.sln
We're including `version.h` header from interop, which is generated by building interop project.
=> build: make PowerToys interop depend on version

src/modules/imageresizer/tests/Models/ResizeSizeTests.cs, src/modules/imageresizer/ui/Models/ResizeSize.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ImageSize.cs
This fix the previous PR https://github.com/microsoft/PowerToys/pull/8567
Aligned the behaviour of Image Resizer and PowerToys Settings when using percentage as resize unit.
When percentage unit is selected height is displayed only if mode is stretch.
Validate height visibility when percetange unit is selected in Image Resizer and PowerToys Settings.
=> [Image Resizer] Handling percentage unit fix

PowerToys.sln, src/common/notifications/BackgroundActivator/BackgroundActivator.vcxproj
- always use pch, which apparently is required for C++/WinRT projects
- previewpane depends on version project
=> CDPX: fix build

tools/BugReportTool/BugReportTool/Main.cpp
For PT Run, don't include the cache and the query history.
For PowerRename, move the MRU files to the exclude list.
=> Update remove list

src/runner/settings_window.cpp
settings window could request "Last checked date" from the runner before the pipe is created, because we have a race condition between creating the pipe and starting the settings process. The issue was there probably a very long time, but we didn't discover it, because no other settings action was requesting something from the runner as part of XAML rendering
open settings page, restart as elevated
=> runner: fix possible crash when dispatching json 

src/modules/fancyzones/dll/dllmain.cpp, src/modules/fancyzones/lib/GenericKeyHook.h
`m_objectLocationWinEventHook` was uninitialized. also explicitly initialize some other fields, even though they're static and should be zero-initialized nevertheless, it just looks better 🙂
=> FZ: fix currently selected zone tracking

src/modules/fancyzones/lib/ZoneWindow.cpp
Make sure the zone container is properly initialized before using it when showing the zones.
After we fixed a [different bug]( https://github.com/microsoft/PowerToys/pull/8795/commits/feff9af242a5d7816bf7f9c2e91e66c564c91be1) this bug showed up since the zone container is never shown with the `SW_SHOWNORMAL` argument.
Since we cannot use `SW_SHOWNORMAL` when showing the zone while a window is dragged, we call it once when the window is created.
Restart PowerToys.exe multiple time and each time verify that all zones are displayed on all monitors when shift-dragging a window.
=> [FancyZones] initialize zone container window state

src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/ZoneWindowDrawing.cpp, src/modules/fancyzones/lib/ZoneWindowDrawing.h
Some of the member fields of `ZoneWindowDrawing` class weren't initialized, so the zone drawing thread didn't start sometimes.
=> FZ: disappearance fix

src/modules/powerrename/lib/PowerRenameManager.cpp
Treat regex syntax errors as normal program flow
Comment out the message box that shows the error message when a normal regex expression has been typed and not completed yet.
TODO: verify if there are cases when we should report an error.
Select the Regular expression checkbox and start typing an expression
=> [PowerRename] don't show an error message for invalid regex syntax

src/modules/fancyzones/lib/SecondaryMouseButtonsHook.cpp
Primary mouse button switch is transparent to the application, the system still returns the same values as for the default case
- Turn on 
- drag a window and verify that clicking on the right button toggles the zone activation
- open the Windows 10 Settings, go to the mouse settings and change the primary button to `Right`
- drag a window and verify that clicking on the left button toggles the zone activation
=> [FancyZones] fix for secondary mouse button

.pipelines/ci/templates/build-powertoys-steps.yml
The CI configuration steps for tests was outdated.
Move .NET Core tests to the proper step, rename the step for native tests.
Run CI and verify all the tests are executed.
=> [CI] tests grouping

src/modules/previewpane/SvgThumbnailProvider/SvgThumbnailProvider.cs
We were seeing some SVG thumbnail being scaled up blurry due to small, hard coded width and height values.  In these cases, when a viewbox attribute is provided, we set the width and height to 100% so we can depend on the viewbox to scale us to the appropriate thumbnail dimensions.
=> Ensure SVGs are scaled correctly when viewbox is provided

src/modules/previewpane/SvgPreviewHandler/SvgPreviewControl.cs
When disk access is really slow, or more commonly, when .svg files are being accessed using e.g. OneDrive, the reading and processing of the file was being done on the Explorer UI thread, which caused the window to be unresponsive. This PR fixes that issue. See #8152 
This PR moves the code which reads the file and checks if it is valid outside the UI loop, ensuring the UI stays responsive.
* Put a large .svg file in your OneDrive folder, for example, this one: https://upload.wikimedia.org/wikipedia/commons/6/63/A_large_blank_world_map_with_oceans_marked_in_blue.svg
* In OneDrive settings, set download speed limit to 400 KB/s
Before this PR, the UI will be unresponsive for about 10 seconds (the …
=> [File Explorer] OneDrive SVG fix

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/FancyZonesData.cpp, src/modules/fancyzones/lib/FancyZonesData.h, src/modules/fancyzones/lib/JsonHelpers.cpp, src/modules/fancyzones/lib/JsonHelpers.h
This adds functions to save the two JSON files separately. Also it adds a check to ensure that
these files aren't saved if the contents won't change. This also allows us to restore the functionality of FileWatcher.
Linked issue: #8779 
Check that FileWatcher can be used again. Use these repro steps:
* Create a grid layout with 6 zones
* Enable overriding Win+Arrows and disable moving zones based on position
* Slowly press Win+Right
On current master with `PostMessageW(m_window, WM_PRIV_FILE_UPDATE, NULL, NULL);` uncommented, the above
repro steps will result in the window not moving. With this PR however, it should work.
**One unit test in FZ is failing but it's also failing in master.**
A CLA …
=> [FancyZones] Refactor/improve saving JSON files

src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml.cs
Reset ScrollViewer to top on page change.
Same behaviour of Windows 10 settings.
ScrollViewer is reset to top on page change.
=> [Settings] Reset ScrollViewer on page change

src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/HotkeySettingsControl.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Styles/_Sizes.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/KeyboardManagerPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
This PR address various, small UX fixes. It also introduces a MaxWidth on the content grid, inline with W10 Settings and improving the visual gap between the sidebar and content grid.
Detailed fixes:
- Fixing an issue where the color formats listview + header text is not disabled when module is disabled (#8738)
- Fixing the contrast between the colorformat example text and highlight color (accent color) (#8634)
- Fixing an issue where the wordwrapping of the shortcut control tooltip was off, resulting in text truncated (#8578)
- Fixing an issue where the horizontal scrollbar would block content on the Image Resizer sizes listview (#8051)
- Settings a MaxWidth to the content grid (similar to W10 Settings) and improving the visual gap between sidebar and contentgrid (#7789)
=> [Settings] Various UX fixes

src/modules/imageresizer/ui/Properties/Resources.Designer.cs, src/modules/imageresizer/ui/Properties/Resources.resx, src/modules/imageresizer/ui/Themes/HighContrastWhite.xaml, src/modules/imageresizer/ui/Themes/Light.xaml, src/modules/imageresizer/ui/Views/InputPage.xaml
- Updated brushes for light theme so it's inline with default WinUI theming. (#8592)
- Added accessibility name for the Resize button.
- Updated brushes for Primary and Secondary background.
- Added accessible name in the Resources file.
- Run the app in light mode to see the theming updates.
- Run Accessibility Insights and see the name of the resize button.
=> [Image Resizer] UI fixes

src/runner/main.cpp, src/runner/powertoy_module.cpp, src/runner/powertoy_module.h
Rename all occurrences of 'module' to 'pt_module' to prevent intellisense error.
`module` is a reserved keyword in C++20 and it should not be used as a variable name.
Build the PowerToys solution and verify PowerToys runs as expected and the modules are loaded and active.
In particular verify that PT Run works as expected.
=> [runner] rename 'module' variables

.github/actions/spell-check/expect.txt, src/common/updating/dotnet_installation.cpp, src/common/updating/pch.h
use regex iterator to find out the latest 3.1.x dotnet version installed.
call `dotnet_is_installed` from runner's main.cpp / install on a machine which doesn't have 3.1.10+ dotnet core
=> updating: require dotnet >=3.1.10

src/modules/fancyzones/editor/FancyZonesEditor/FancyZonesEditor.csproj
_Create new layout_ and _Delete layout_ dialog windows renders semi-off the screen. The user needed to resize the editor window to fix the problem.
The fix was introduced in the release https://github.com/Kinnara/ModernWpf/releases/tag/v0.9.3 of the `ModernWpf` package.
=> [FZ Editor] Dialog window renders semi-off the screen

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs
After clicking the `Duplicate` or `Delete` button in the editing context menu of the layout the menu will be closed automatically.
=> [FZ Editor] Closing context menu after Duplicate or Delete button clicked

src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Storage/Win32ProgramRepositoryTest.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/Win32ProgramRepository.cs
Null reference exception on program rename. 
- Fix `oldApp` initialization for a shortcut. Before when a shortcut was renamed an old entry was not deleted from `ListRepository`.
- Fix unhandled null reference exception and added logs so it is easier to identify the root cause. The reason for the exception was `oldApp` was not initialized properly.
One can check that on a shortcut rename one item is deleted from `ListRepository` and one is added.
=> [Run] Fix exception

src/modules/fancyzones/editor/FancyZonesEditor/Converters/LayoutTypeCustomToVisibilityConverter.cs, src/modules/fancyzones/editor/FancyZonesEditor/Converters/LayoutTypeTemplateToVisibilityConverter.cs, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/CanvasLayoutModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/GridLayoutModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutSettings.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/MainWindowSettingsModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Overlay.cs
* Moved `+` and `-` buttons to the template layouts flyout.
* Possibility to change zone count individually for each template layout.
=> [FZ Editor] Move zones + and - buttons to the template layouts flyout

src/common/utils/elevation.h, src/runner/settings_window.cpp
Fix improper calls to CreateProcessW.
After carefully reading the docs regarding the CreateProcessW function, I identified two potential issues.
One is a missing flag and the other is uninitialized size member.
Fixed those issues.
No specific validation, just ensure that PT generally works both as user and as admin.
=> [Runner/common] Fixed two potential issues with CreateProcess

src/common/Microsoft.PowerToys.Common.UI/ThemeManager.cs, src/modules/launcher/PowerLauncher/SettingsWatcher.cs
With **Windows** color set to **Light** and **PT Run** color set to **Windows default** wrong icons are displayed in PT Run results list: white instead of black. 
Set black icons with Windows color to Light and PT Run color to Windows default.
- Set PT Run color to Windows default
- Set Windows color to Light
- Search "shutdown"
- The launcher should be white and the icons should be black
- Set Windows color to Dark
- The launcher should be black and the icons should be white
=> [PT Run] Black icons with light windows theme

src/modules/launcher/Plugins/Microsoft.Plugin.Calculator.UnitTest/ExtendedCalculatorParserTests.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/CalculateEngine.cs
This adds support for the euler number to the calculator.
- Type equations that contain e in the launcher, e. g. `2*e`, `e^5`, `log(e)`
=> Add e to calculator

src/runner/settings_window.cpp
Running the Settings process as non-elevated from elevated PowerToys.exe sometimes results in a crash.
After fixing wrong calls to CreateProcessW in #9063, we discovered that Settings was running elevated all along.
And sometimes, when running Settings non-elevated, we get a crash that can only be linked to a bug in .NET.
This has happened before: https://github.com/dotnet/runtime/issues/37129
For now, we disable running Settings from `run_settings_non_elevated` until we move to .NET 5 or figure out exactly what's going on.
The bug discussed in  #9063 is easiest to reproduce by building the installer, installing, running PowerToys, opening the settings, by clicking the tray icon, restarting as …
=> Run Settings on same elevation as PowerToys.exe

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation-issue.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/translation_issue.md
adding in Triage Needed by default
the templates with the tag
We merge in and check.  Does not touch any source
=> Default add triage to issues

src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry/Helper/RegistryHelper.cs
Change the variable type to nullable, to prevent the warning.
Build the solution and verify the warning/error is not generated.
=> Fix "Converting null literal or possible null value to non-nullable type" warning

src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/Main.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/Properties/Resources.Designer.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/Properties/Resources.resx
Improved shortcuts for PT Run Service plugin
- CTRL+R restart service
- CTRL+S open services
Validate new shortcuts and tooltip text on context menu buttons.
=> [PT Run][Service] Improved Shortcuts

src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml
Added a "Picker behavior" and "Editor" header in the ColorPicker settings, resolving: #8951
=> [Settings] ColorPicker spacing issue

src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator.UnitTest/NumberTranslatorTests.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/Main.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/NumberTranslator.cs
- Add different number localizations to calculator
- Fix bug in NumberTranslator
- Add NumberTranslatorTests
- Build setup
- Test Calculator plugin with numbers with commas as delimiters on a version of Windows that uses commas as number delimiter, e. g. "5,5+6" should output "11,5"
=> [Run][Calculator Plugin] Add number formatting for different Locales

src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry/LocProject.json, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/LocProject.json, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/LocProject.json
New PT Run plugins need a config file to enable localization in the build farm.
Added the required files.
It has been already tested in the build farm, it cannot be tested localy.
=> [build] add configuration to localize new plugins

.github/actions/spell-check/expect.txt, .pipelines/pipeline.user.windows.yml
Fix for CDPX pipeline.  points to their old image that use to be latest
https://github-private.visualstudio.com/microsoft/_build/results?buildId=19276&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=dcf93f35-c1ba-5dce-0078-8d628250da3a
=> Fix installer pipeline

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs
Set `MaxWidth` and `MaxHeight` for the main window.
=> [FancyZones Editor] Editor window size overflow

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/FancyZonesViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
Replaced `Move windows based on their position` checkbox with radio buttons.
Check each option by snapping a window to a zone and using Win+Arrow.
=> [FZ Settings] Refactor "Override Windows Snap shortcut (Win + Arrow) to move windows between zones" settings

src/modules/fancyzones/dll/dllmain.cpp, src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/FancyZonesData.cpp, src/modules/fancyzones/lib/FancyZonesData.h, src/modules/fancyzones/tests/UnitTests/JsonHelpers.Tests.cpp
Fix for a FZ regression in 0.31.1 that caused Win+arrow to stop working properly.
The `SaveFancyZonesData()` method was used to save the app zone history when a window is zoned.
Because  `SaveFancyZonesData()` also saves the `zones-settings.json` file, the  `zones-settings.json` was triggered to reload the fine and recreate some internal data structure, causing win+arrow to not work properly.
This PR replaces some calls to `SaveFancyZonesData()` with calls to `SaveAppZoneHistory()` to avoid triggering the file watcher for `zones-settings.json`
Turn on these options:
Create a large grid layout (9 or more zones) and try zoning a window using win+arrows and win+ctrl+alt+arrows.
Also test that …
=> [FanzyZones] app history and zone settings granular saving

src/modules/fancyzones/dll/dllmain.cpp, src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/FancyZonesData.cpp, src/modules/fancyzones/lib/FancyZonesData.h, src/modules/fancyzones/tests/UnitTests/JsonHelpers.Tests.cpp
move DeleteFancyZonesRegistryData to proper place
add logging
Cherry-pick hot fix from stable see https://github.com/microsoft/PowerToys/pull/9489
=> [FanzyZones] app history and zone settings granular saving (#9489)

src/modules/fancyzones/lib/ZoneSet.cpp, src/modules/fancyzones/lib/ZoneSet.h, src/modules/fancyzones/tests/UnitTests/ZoneSet.Spec.cpp
Some users like to have their zones overlap, sometimes, it was impossible to drop a window into a zone if it's covered by other, smaller zones. This PR should hopefully fulfill these users' needs. For the discussion, see issue #1167 
A modification of a single function. With this change, if there are multiple overlapping zones covering the point above which the user is hovering, one of the zones will be selected based on the position inside the overlapped area, allowing the user to drop the window into the desired zone.
Check the discussion in #1167. Also, make sure there are no changes in behavior if zones don't overlap, e.g. we can still select multiple non-overlapping zones by hovering between them.
One unit test is …
=> [FancyZones] Improve zone selection

src/settings-ui/Microsoft.PowerToys.Settings.UI/Helpers/StartProcessHelper.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml.cs
Replaced `NavigateUri` with a handler calling `Process.Start` to open Windows Colors settings.
=> [PT Settings] Opening windows color settings from inside PT

src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Sources/Path/FolderHelper.cs
Tilde recognized as user home directory as PowerShell does.
- Open PT Run
- Type `~`
- Should be recognized as user home directory `%USERPROFILE%`
=> [PT Run] Tilde as user home

src/runner/main.cpp, src/runner/restart_elevated.cpp, src/runner/restart_elevated.h, src/runner/settings_window.cpp
`--open-settings` parameter added to `PowerToys.exe` used when user restart the PowerToys as admin
When the user press **Restart as administrator** button from settings UI PowerToys is restarted and settings UI is opened
- Start PowerToys as user
- Open Settings
- Press **Restart as administrator** button
- PowerToys should be restarted and settings UI should be opened
=> [Runner] Open settings when restarted as admin

installer/PowerToysSetupCustomActions/PowerToysSetupCustomActions.vcxproj
Move the PowerToysSetupCustomActions intermediate dir to the project subfolder.
Change to the PowerToysSetupCustomActions.vcxproj file.
Build the MSI, install PowerToys and verify in `Task Scheduler` that the scheduled task has been added.
Uninstall PowerToys and verify that the scheduled task has been removed.
=> [msi] PowerToysSetupCustomActions intermediate dir

.github/actions/spell-check/expect.txt, installer/PowerToysBootstrapper/bootstrapper/Resources.resx, installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp
When a newer version is detected, don't run the new version's MSI, instead show an error dialog and exit.
Improve the error dialog logic. Add more logging.
- Build the bootstrapper
- Run the bootstrapper when there is no newer version installed -> the bootstrapper should proceed to install PowerToys
- Run the bootstrapper when a newer version is installed -> the bootstrapper should show the error dialog and exit
=> [bootstrapper] change newer version detected action

src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/plugin.json, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/plugin.json, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/plugin.json, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Shell/plugin.json, src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Uri/plugin.json, src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/plugin.json, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/Main.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/plugin.json, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry/Main.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry/plugin.json, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/Main.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/plugin.json, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Main.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/plugin.json, src/modules/launcher/PowerLauncher/SettingsWatcher.cs, src/modules/launcher/Wox.Plugin/IPlugin.cs, src/modules/launcher/Wox.Plugin/PluginMetadata.cs
Show localized name and description in settings.
- Add `Name` and `Description` properties to `IPlugin` in order to take localized strings
- Remove `Description` from plugin.json as it is not used anywhere
- Delete `PowerToys Run\settings.json`
- Start PowerToys
- Check that name and description is taken from resource files
=> Localize name and description

src/modules/launcher/PowerLauncher/LauncherControl.xaml
Right-clicking the search box would bring up a context menu with an outdated look and feel (#9607):
This PR adds the correct visual style:
=> [Run] Fix context menu

src/modules/launcher/Microsoft.Launcher/dllmain.cpp
In issue #9519, a user has an older Windows 10 build, and one code path thinks that PT Run is enabled and should accept its keyboard shortcut (Alt+Space by default), so the user cannot use this shortcut even though PT Run isn't running. This PR fixes the issue.
The issue is not with the centralized keyboard hook as initially suspected, but with the member `m_enabled` being set to `true` even when PT Run isn't actually enabled, thus causing the hook to accept the shortuct.
Set `m_enabled = true` only when PT Run is actually started.
First, make sure that PT Run is enabled in the settings and the shortcut is set to some value e.g. Alt+Space. Replace the implementation of `inline bool …
=> [Runner] Fix stealing shortcuts on older Win10 builds

src/settings-ui/PowerToys.Settings/Program.cs
Fixes arguments parsing in the new settings app. 
Check that settings app is working as expected.
=> [Settings] Settings window arguments revision

installer/PowerToysSetup/Product.wxs, src/modules/fancyzones/editor/FancyZonesEditor/CanvasZone.xaml, src/modules/fancyzones/editor/FancyZonesEditor/CanvasZone.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/GridZone.xaml, src/modules/fancyzones/editor/FancyZonesEditor/GridZone.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.Designer.cs, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx, src/modules/fancyzones/editor/FancyZonesEditor/Styles/ButtonStyles.xaml
This PR introduces some minor UX changes:
- Smaller font-size and use of secondary brush for the zone resolution labels.
- Layout title no longer runs through the edit button (#9610)
- Added tooltips to the increment/decrement buttons. (#7075)
- Redesign edit dialog (partly #9335):
- NumberBoxes instead of TextBoxes for numeric values
- LayoutPreview is now also visible within the dialog.
- Improved visual hierarchy, aligned with inbox applications (like the new Alarms & Clock applications).
=> [FZ editor] UX update for edit dialog

src/common/SettingsAPI/settings_helpers.cpp, src/common/SettingsAPI/settings_helpers.h, src/runner/main.cpp, src/runner/settings_window.cpp, src/runner/settings_window.h, src/settings-ui/PowerToys.Settings/App.xaml, src/settings-ui/PowerToys.Settings/App.xaml.cs, src/settings-ui/PowerToys.Settings/Program.cs
At the first PT launch, the OOBE window will be opened automatically without opening the settings window. 
`oobe_settings.json` in the root settings folder marks oobe state to avoid opening the window later.
* Launch PT without `oobe_settings.json`, verify that OOBE window was opened and the settings file was created.
* Launch PT with `oobe_settings.json`, verify that OOBE window wasn't opened, file was not changed.
=> [Oobe] Show OOBE window at the first launch.

src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/ProgramArgumentParser/ProgramArgumentParserTests.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System.UnitTests/ImageTests.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System.UnitTests/QueryTests.cs, src/modules/launcher/PowerLauncher/Plugin/PluginManager.cs, src/modules/launcher/PowerLauncher/Plugin/QueryBuilder.cs, src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs, src/modules/launcher/Wox.Plugin/Query.cs, src/modules/launcher/Wox.Test/QueryBuilderTest.cs
- Use list instead of Dictionary for `PluginManager.NonGlobalPlugins`. It allows showing results from more than one plugin for the action keyword
- Removed `search` and `terms` arguments From `Query` as they can be calculated from the other two
- Removed ref form `QueryBuilder.Build`
- `QueryBuilderShouldRemoveExtraSpacesForDisabledNonGlobalPlugin` test is redundant as there is not consumers of `QueryBuilder.Build` that expect `queryText` to be normalized when there is no plugins
- Added `QueryBuilderShouldReturnAllPluginsWithTheActionWord` test for new functionality
- Try to assign the same action keys for few plugins
- Test for regressions …
=> Possibility to use the same action keyword for more than one plugin

src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/Helpers/ServiceHelper.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/Properties/Resources.Designer.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/Properties/Resources.resx, src/modules/launcher/PowerLauncher/PublicAPIInstance.cs, src/modules/launcher/Wox.Plugin/IPublicAPI.cs
Improvements for PT Run Service plugin notifications
Unfortunately error is just an exit. Not sure if we can translate in error message.
Validate new notifications
=> [PT Run] Service Notification Improvements

doc/devdocs/style.md
Repaired the link to .clang-format
Click on the link
=> Updated link for .clang-format

src/modules/fancyzones/editor/FancyZonesEditor/CanvasZone.xaml, src/modules/fancyzones/editor/FancyZonesEditor/GridZone.xaml, src/modules/fancyzones/editor/FancyZonesEditor/LayoutPreview.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Styles/LayoutPreviewStyles.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Themes/Dark.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Themes/HighContrast1.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Themes/HighContrast2.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Themes/HighContrastBlack.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Themes/HighContrastWhite.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Themes/Light.xaml
This PR splits out the colors for the LayoutPreview. ActualScale is used for the background preview, SmallScale is used for the thumbnail preview.
It also aligns the colors with what WinUI defines in their upcoming design token refresh.
Dark
Light
=> [FZ Editor] Updated (preview) zone colors

.github/actions/spell-check/expect.txt, src/modules/previewpane/SvgPreviewHandler/SvgPreviewControl.cs, src/modules/previewpane/SvgPreviewHandler/Utilities/SvgPreviewHandlerHelper.cs
SVG preview needs to be centered and scaled.
Fixed issue with centering and scaling preview SVG.
Just fix for this.
Need PowerToys to be built and installed.
=> Svg image preview is displayed unscaled and uncentered

src/modules/launcher/Plugins/Microsoft.Plugin.Folder/ContextMenuLoader.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Sources/ShellAction.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/ContextMenuLoader.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Storage/Win32ProgramRepositoryTest.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWPApplication.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Main.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Properties/Resources.Designer.cs, src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Properties/Resources.resx, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry/Helper/RegistryHelper.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/Helpers/ServiceHelper.cs, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Service/Microsoft.PowerToys.Run.Plugin.Service.csproj, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Main.cs, src/modules/launcher/PowerLauncher/ReportWindow.xaml.cs, src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs, src/modules/launcher/Wox.Infrastructure/Helper.cs
Common helper for execute shell across PT Run plugins.
Removed most of the `Process.Start` used for invoking shell across PT Run plugins.
Still have 2 hardcorded `explorer.exe` in folder and indexer plugin used to focus the file when explorer is opened https://github.com/microsoft/PowerToys/issues/7339#issuecomment-774528261
- Folder plugin
- Open file
- Open folder
- Open containing folder
- Indexer plugin
- Open containing folder
- Click on index warning
- Open file
- Program plugin
- Open containing folder UWP app
- Open containing folder Win32 app
- URI plugin
- Open an URI
- Registry plugin
- Open registry
- Service plugin
- Open services.msc
- System plugin
- Shutdown
- Reboot
- Report …
=> [PT Run] Helper for Execute Shells Process Calls

src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFancyZones.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFileExplorer.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeImageResizer.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeKBM.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobePowerRename.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeVideoConference.xaml
For some modules "Launch _module_" button makes no sense since the module couldn't be launched without additional stuff such as a file to rename for PowerRename, etc.
Removed buttons for modules:
* FancyZones
* File explorer
* Image resizer
* Keyboard manager
* Power rename
* Video conference
=> [Oobe] Removed "Launch module" buttons for several modules.

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerLauncherPluginViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerLauncherViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml
- Consider showing a warning when all plugins are disabled
- Consider validating Action keyword for * and ~
- Reconsider author placement #9650 (comment)
- Reorder Plugins and Appearance sections
Not allowed action keywords are: "~", "\\", "\\\\". All of them rewrite the behavior of the folder plugin. Take into account that we show a warning but a user still can use not allowed action keywords.
Check if warnings are shown.
=> [Run] [Plugin manager] UI fixes

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerLauncherPluginViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerLauncherViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml
Disable all controls when a plugin is disabled.
- Added `IsEnabled` property to controls that have it
- Added `Opacity` property to controls that do not have `IsEnabled` property
Check for different themes that plugin's controls are disabled for a disabled plugin.
=> disable plugin options when plugin is disabled

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerLauncherPluginViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml.cs
Navigation from the Additional info panel to the next and previous list item.
- Replace `Microsoft.Xaml.Interactivity` with code behind visibility handling for Additional info panel 
Navigate to controls in additional info panel with tab and try to move up/down with arrow up/down
=> Navigation from additional panel

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/FancyZones.h, src/modules/fancyzones/lib/Settings.cpp, src/modules/fancyzones/lib/Settings.h, src/modules/fancyzones/lib/ZoneSet.cpp, src/modules/fancyzones/lib/ZoneSet.h, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/trace.cpp, src/modules/fancyzones/tests/UnitTests/ZoneSet.Spec.cpp, src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/FZConfigProperties.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/FancyZonesViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Styles/_Sizes.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
In a previous PR #9447, we added support for different algorithms which should determine which zone gets selected when a user drags a window over a point contained inside several zones. The default is "smallest zone wins", and this is also respected in this PR. This PR exposes the option in PowerToys settings (only the new settings, for now).
In order to test this, create a canvas zone layout with overlapping zones. For examples of such layouts, see #1167.
Change the setting and check whether the highlighted zone is the expected one.
Some unit tests fail because the logger isn't initialized.
=> [FancyZones] Overlapping zones selection algorithm - settings

src/settings-ui/PowerToys.Settings/MainWindow.xaml, src/settings-ui/PowerToys.Settings/MainWindow.xaml.cs, src/settings-ui/PowerToys.Settings/OobeWindow.xaml.cs
Cancel closing event from MainWindow if the Oobe window is opened.
* open Settings 
* open OOBE
* close Settings -> check if oobe window works.
* reopen Settings -> check if Settings window works
* reopen OOBE
* close OOBE
* close Settings
Check that both windows could be opened and closed, and responding as expected.
=> [Oobe] Keep oobe window working after closing settings window

src/common/interop/interop.cpp, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml.cs, src/settings-ui/PowerToys.Settings/MainWindow.xaml.cs
Open Run, ColorPicker, Shortcut guide from OOBE, and check that default shortcuts still works.
To cancel the Shotcut guide one has to click on it and then press ESC. 
- [] **Linked issue:** #xxx
- [] No new binaries
=> start run, color picker, shortcut guide from oobe

src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFancyZones.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFileExplorer.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeImageResizer.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeKBM.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobePowerRename.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml.cs, src/settings-ui/PowerToys.Settings/MainWindow.xaml.cs
Test settings button for all modules. It should bring PT settings on the front and navigate to the appropriate tab.
I am not sure about the following code. But after testing it does not seem to leak or crash.
```
if (isOpen)
{
this.Activate();
}
else
{
var newWindow = new MainWindow();
newWindow.Show();
}
ShellPage.Navigate(type);
```
=> [OOBE - Settings] Deep linking

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/Telemetry/Events/OobeSectionEvent.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/ViewModel/OobePowerToysModule.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFancyZones.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFileExplorer.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeImageResizer.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeKBM.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeOverview.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobePowerRename.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeVideoConference.xaml.cs, src/settings-ui/PowerToys.Settings/OobeWindow.xaml, src/settings-ui/PowerToys.Settings/OobeWindow.xaml.cs
Added to log for how long section was opened.
Logs are being sent on the `OnNavigatedFrom` event and on OOBE window closing.
=> [Oobe] Telemetry: When specific OOBE sections are entered/exited

src/modules/shortcut_guide/d2d_window.cpp, src/modules/shortcut_guide/shortcut_guide.cpp
This PR fixes the way the Shortcut Guide window is activated from the OOBE window. With this PR, the window is also activated i.e. brought to focus, so it can be exited by clicking Esc without having to click the window first.
Check that you can quit the Shortcut Guide window using the Esc key after lauching it from OOBE.
=> [Shortcut guide] Activate from OOBE

src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeOverview.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeOverview.xaml.cs
Added a button to open the General settings page from OOBE window.
=> [Oobe] Link to the General settings

src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFancyZones.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFileExplorer.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeImageResizer.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeKBM.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeOverview.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobePowerRename.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml.cs, src/settings-ui/PowerToys.Settings/App.xaml.cs, src/settings-ui/PowerToys.Settings/MainWindow.xaml.cs, src/settings-ui/PowerToys.Settings/OobeWindow.xaml.cs
Moved the callbacks setting from the main window to the oobe window. 
=> [OOBE] Fix opening PT modules and settings at the first launch 

src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs
I hit this null reference when going between the OOBE and main branch.  
settings.AdditionalOptions was null so wrapped the detection.  On only master, i couldn't repro but going between the two, my settings got into a state where this was a valid permutation.
=> Additional Options in indexer had null value exception

src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFancyZones.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFileExplorer.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeImageResizer.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeKBM.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeOverview.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobePowerRename.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeVideoConference.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml
- Solving the scrollbar issue: #9985
- Text spacing issue on File Explorer add-ons page: #9984
In the (unique) case that the resolution of the screen is lower than 1100x700, the NavigationView will collapse and the pane button will be shown: #9986
=> [OOBE] UI bugfixes

src/settings-ui/PowerToys.Settings/MainWindow.xaml.cs
Restart PT with the OOBE window opened could cause a crash with an unhandled exception. Crash causes the `Show` method that's called after the `Shutdown` on restart. 
Since the OOBE window is opened, the `isOpen` flag doesn't being reset on the `Closing` event, so `Show` is called as like as the program didn't stop.
Added try-catch block to catch possible `InvalidOperationException` on `Show`.
Set `isOpen` flag to false before calling shutdown to prevent calling `Show`.
=> [PT Settings] Crash on restart with OOBE window opened.

src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Enums/PowerToysModulesEnum.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml.cs
Changed position on the "File Explorer add-ons" in the navigation view.
=> [OOBE] Changed modules order

src/modules/fancyzones/editor/FancyZonesEditor/LayoutOverlayWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/LayoutOverlayWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Utils/NativeMethods.cs
FZ Editor had two windows that were shown as targets when alt-tabbing.
Add a helper class to invoke `SetWindowLong` to set the window style to `WS_EX_TOOLWINDOW` so it's not shown as a alt-tab target.
Open the FZ Editor and then press alt-tab.
=> [FZ Editor] hide tool windows from alt-tab

src/settings-ui/PowerToys.Settings/App.xaml.cs, src/settings-ui/PowerToys.Settings/MainWindow.xaml, src/settings-ui/PowerToys.Settings/MainWindow.xaml.cs, src/settings-ui/PowerToys.Settings/OobeWindow.xaml.cs, src/settings-ui/PowerToys.Settings/Utils.cs
and ensure the window is inside the screen work area
This is a pre-requisite for #3685, it sets a default location for the Settings that is the screen center and also guarantees the window is fully inside the screen work area. That is done for both the Settings and OOBE.
Added some helpers to center and resize windows.
The Settings window didn't have a min height set.
Run PT on large and small screen and verify that the Settings window is centered and it's all contained in the screen work area.
Open OOBE and verify it's centered and it's all contained in the screen work area.
=> [Settings, OOBE] set location to center screen

src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Main.cs
Shell history stores a resolved version of the command e.g the query `> %appdata%` is saved in the shell history as `C:\Users\someuser\AppData\Roaming`.
Modified `Microsoft.Plugin.Shell.Main.PrepareProcessStartInfo()` to remember the raw command (trimmed) instead of the resolved command.
1. Open Run
1. Query `> %appdata%`, hit enter to execute the command
1. Open Run, type in `> %app`
1. `%appdata` should show up in the history
=> [PT Run] Save raw command instead of resolved command in shell history

src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/PowerToys.Settings/MainWindow.xaml, src/settings-ui/PowerToys.Settings/MainWindow.xaml.cs, src/settings-ui/PowerToys.Settings/OobeWindow.xaml, src/settings-ui/PowerToys.Settings/OobeWindow.xaml.cs
Use localized resources for the PT Settings and OOBE window titles.
=> [PT Settings] PowerToys Settings and OOBE title hardcoded for localization

src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/LocProject.json
- Run the build to see if localize process succeeds 
=> Fix localization of  VSCode workspace plugin

src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
- Removed the TextBlock that was acting as a Header and used the Header property of the ComboBox to fix inconsistent spacing.
- Set the IsEnabled property to resolve: #10089
=> [Settings] ComboBox fix on FZ page

installer/PowerToysSetup/Product.wxs
```
2021-03-08T00:44:23.1596961Z [INFO] [61] S:\installer\PowerToysSetup\Product.wxs(901): error LGHT0094: Unresolved reference to symbol 'Directory:ResourcecsVSCodeWorkspacesPluginFolder' in section 'Fragment:'. [S:\installer\PowerToysSetup\PowerToysSetup.wixproj]
2021-03-08T00:44:23.1598278Z [INFO] [62] S:\installer\PowerToysSetup\Product.wxs(901): error LGHT0094: Unresolved reference to symbol 'Directory:ResourcedeVSCodeWorkspacesPluginFolder' in section 'Fragment:'. [S:\installer\PowerToysSetup\PowerToysSetup.wixproj]
2021-03-08T00:44:23.1599515Z [INFO] [63] S:\installer\PowerToysSetup\Product.wxs(901): error LGHT0094: Unresolved reference to symbol 'Directory:ResourceesVSCodeWorkspacesPluginFolder' in section 'Fragment:'. …
```
=> Build of PowerToysSetup.sln fail on build farm

src/modules/launcher/PowerLauncher/Plugin/PluginManager.cs, src/modules/launcher/PowerLauncher/Plugin/PluginsLoader.cs
We get `System.InvalidOperationException: Collection was modified` on startup of PT Run. It happens because `PluginConfig.PluginMetadatas` is modified while related `IEnumerable` is used in `foreach`. 
`PluginConfig.PluginMetadatas` should be initialized only once so that's why `AllPlugins` should be a threadsafe singleton.
Notice that `Lazy` is not used for singleton implementation because we need to initialize `AllPlugins` from tests. 
- Thread-safe singleton for PluginManager.AllPlugins
- Apply `ToList` before foreach
There is no way to test it unless you experienced the issue before. We will ask the author of the issue to verify it. …
=> System.InvalidOperationException: Collection was modified

src/common/logger/logger.cpp
Tests fail if the logger is not initialized. Initialize it to `null_logger_mt`.
Run Fancy zones tests.
=> Initialize logger to default

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/FastAccessKeysModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Utils/FancyZonesEditorIO.cs, src/modules/fancyzones/lib/JsonHelpers.cpp, src/modules/fancyzones/tests/UnitTests/JsonHelpers.Tests.cpp
Added `fast-access-layout-keys` to the zones-settings.json.
Currently the schema is:
```
{
"devices": [],
"custom-zone-sets": [],
"templates": [],
"fast-access-layout-keys": [
{
"key": 1,
"uuid": "{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}"
}
]
}
```
For testings purposes, I added the temporary button at the bottom of the Editor that calls adding and freeing fast access keys. 
After clicking you can verify in the JSON file that some values were added (and weren't duplicated) and they're not erased after reading and rewriting settings by the FancyZonesLib.
The temporary button will be removed in the next PR or in this PR after reviewing.
By default, the `fast-access-layout-keys` array is empty.
A CLA …
=> [FZ Editor] Layout hotkeys: add the schema element to zones-settings.json

src/modules/fancyzones/lib/ZoneWindow.cpp
This PR implements a new class which manages created HWNDs used for zone windows, in order to fix (but not close) #8976.
The reason for using this class is the need to call `ShowWindow(window, SW_SHOWNORMAL);` on each newly created window for it to be displayed properly. The call sometimes has side effects when a fullscreen app is running, and happens when the resolution change event is triggered (e.g. when running some games).
This class will serve as a pool of windows for which this call was already done.
Check that FancyZones works and everything is displayed properly after changing resolution and connecting/disconnecting displays. Make sure that games are not minimized as in issue #8976. All …
=> [FancyZones] Use a window pool for zone windows

src/modules/fancyzones/editor/FancyZonesEditor/LayoutPreview.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Models/CanvasLayoutModel.cs
One member of CanvasLayoutModel was not initialized when a new layout is created, leading to some bugs like #9330. This PR should fix that.
A new CanvasLayoutModel constructor which is called when a new layout is created. It sets the reference width/height for the layout.
Create new layouts, use old layouts, try switching between monitors, especially if they have different resolutions or DPIs. This PR also fixes an issue when the option to span zones across monitors is used.
=> [FancyZones editor] Fix CanvasRect not being initialized

src/common/updating/dotnet_installation.cpp
=> [Updating] Install dotnet 3.1.13 and bump min required version

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerLauncherViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/PowerLauncherViewModelTest.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml.cs
Sometimes plugins list is not shown in the settings because plugins were not loaded yet. We show a warning message and update settings when they are loaded.
- Show warning 'Plugins are loading...' when list of plugins are empty
- File watcher for settings.json file
- Disable PowerToys Run
- Exit PowerToys
- Delete `PowerToys Run\settings.json`
- Start PowerToys
- Go to PowerToys Run page
- Enable PowerToys Run
- Verify that 'Plugins are loading...' warning is shown and the page eventually get updated with plugins
Extra testing:
- Open PowerToys on PowerToys Run page
- Chage settings in `PowerToys Run\settings.json` file
- Verify that changes are propagated to the page
A CLA must be signed. If …
=> Update PowerToys Run page on settings.json change

src/modules/fancyzones/lib/CallTracer.cpp, src/modules/fancyzones/lib/CallTracer.h, src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/FancyZonesData.cpp, src/modules/fancyzones/lib/FancyZonesData.h, src/modules/fancyzones/lib/FancyZonesLib.vcxproj, src/modules/fancyzones/lib/FancyZonesLib.vcxproj.filters, src/modules/fancyzones/lib/OnThreadExecutor.cpp, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/ZoneWindowDrawing.cpp
Due to a bug, FancyZones sometimes hangs. We think this is because of a deadlock, so this PR adds trace logging to function calls which use synchronization.
A new class CallTracer which logs construction and destruction of its instances. Objects of this class are then placed into various functions, allowing us to see which function calls are happening.
Perhaps we should also log the thread ID?
Run PowerToys with logging level set to Trace, and look at the logs.
=> [FancyZones] Trace various function calls

.github/actions/spell-check/expect.txt, src/modules/colorPicker/ColorPickerUI/Controls/ColorPickerControl.xaml, src/modules/colorPicker/ColorPickerUI/Controls/ColorPickerControl.xaml.cs, src/modules/colorPicker/ColorPickerUI/Properties/Resources.Designer.cs, src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx, src/modules/colorPicker/ColorPickerUI/Resources/Styles.xaml
- Adding tooltips (#8824)
- Swapped out RGB TextBoxes for NumberBox, added autoselect for HEX TextBox when getting focus with keyboard. (#10143)
=> [ColorPicker] UX fixes

src/modules/fancyzones/editor/FancyZonesEditor/GridZone.xaml.cs
- Replaced the WindowGlassBrush (that takes the color that is used as a 1px border around a window) with a true AccentColorBrush (ModernWPF).
@enricogior I wasn't able to reproduce the bug you described. Either way, we shouldn't use the SystemParameters.WindowGlassBrush.
=> [FZ Editor] Updated accent color

installer/PowerToysSetup/Product.wxs
After initial investigation tipped by [this comment](https://github.com/microsoft/PowerToys/issues/9720#issuecomment-786146539) (thanks!) it looks like MSI asks for the original installer location due to advertised icon. Since we don't need [that functionality](https://www.advancedinstaller.com/user-guide/advertised-shortcuts.html), this PR refactors the code not to use them.
=> [MSI] Do not use advertised icon

.vsconfig, doc/devdocs/readme.md
Onboarding is important.  This will replace the need for the install script from here:
https://github.com/microsoft/PowerToys/tree/master/doc/devdocs#prerequisites-for-compiling-powertoys
We'll still need an install script for Wix and what not but this gets the main SLN however in a 'shovel ready' state for work.
VS Config was added to replace setup script
setup new VM, install VS as just a pure "core", clone and "install"
After everything is installed, this will install remaining dependencies needed.
=> adding vsconfig to main solution

installer/PowerToysSetup/Product.wxs
- factor out shortcut for toasts into a separate component
- remove `Impersonate` attribute, since Wix was warning it'd be ignored anyway.
=> [MSI installer] fix WIX build warnings

.github/actions/spell-check/expect.txt, src/modules/fancyzones/lib/Resources.resx, src/modules/fancyzones/lib/Settings.cpp, src/modules/fancyzones/lib/Settings.h, src/modules/fancyzones/tests/UnitTests/FancyZones.Spec.cpp, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ConfigDefaults.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/FZConfigProperties.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/FancyZonesViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
Added `Quick layout switch` section in the FancyZones settings with `Enable quick layout switch` and `Flash zones when switching layout` CheckBoxes.
The options are saved in settings as `fancyzones_quickLayoutSwitch` and `fancyzones_flashZonesOnQuickSwitch`.
=> [FZ Settings] Options for layout quick swap: on/off keyboard hook

src/modules/fancyzones/lib/trace.cpp
Added flags `QuickLayoutSwitch`, `FlashZonesOnQuickSwitch`  in the settings changed event.
=> [FZ Settings] Options for layout quick swap: telemetry

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutModel.cs, src/modules/fancyzones/editor/FancyZonesEditor/Utils/FancyZonesEditorIO.cs
* Disabled layout hotkeys assignment for templates.
* Reverted saving UUID in the `zones-settings.json` for template layouts.
=> [FZ Editor] Disable templates key assignment

installer/PowerToysSetupCustomActions/PowerToysSetupCustomActions.vcxproj, installer/PowerToysSetupCustomActions/Telemetry/ProjectTelemetry.h, installer/PowerToysSetupCustomActions/Telemetry/TraceLoggingDefines.h
MSI build on the build farm didn't have telemetry enabled (since 0.15)
Change the include path for the telemetry headers to use the headers from the common folder since those headers are corregly replaced with the ones that enable telemetry.
Verify the that msi project builds correctly, after deleting the `installer\PowerToysSetupCustomActions\Telemtry\` folder.
To validate the MSI sends telemetry events, we will do a signed build and test it on an Windows Insider machine.
=> [msi] enable telemetry on build farm

installer/PowerToysSetupCustomActions/CustomAction.cpp
Add the version number to the MSI telemetry events.
Update all the MSI telemetry events to include the version number.
To verify this, we will kick off a farm build and test the installer in a Windows 10 Insider machine.
=> [msi] add version number in telemetry events

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml
Changed margins of elements in the dialog, added wrapping to text labels.
=> [FZ Editor] Layout hotkeys label should fit the dialog.

src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/Community.PowerToys.Run.Plugin.VSCodeWorkspaces.csproj, src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry/Microsoft.PowerToys.Run.Plugin.Registry.csproj
Registry and VScode workspaces plugins have the wrong version. And it is probably the reason for #10092.
Open powershell from launcher output folder
`[System.Diagnostics.FileVersionInfo]::GetVersionInfo("Plugins\Microsoft.PowerToys.Run.Plugin.Registry\Microsoft.PowerToys.Run.Plugin.Registry.dll").FileVersion`
and
`[System.Diagnostics.FileVersionInfo]::GetVersionInfo("Plugins\VSCodeWorkspaces\Community.PowerToys.Run.Plugin.VSCodeWorkspaces.dll").FileVersion`
Verify that version is 0.0.1.0
=> Fix versions for registry and vscode workspaces plugins

src/modules/launcher/PowerLauncher/MainWindow.xaml, src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
A user experiences a flicker from previous results when "Clear the previous query on launch" option is selected. It happens even if we clear results before a window collapse. Apparently, UI changes that were not applied before a window collapse are then applied when the window is opened again.
- Move `ClearQueryCommand.Execute` to windows collapse from `OnActivated`
- Wait 100ms before collapsing the window so UI updates before collapsing and will not happen when the windows is opened again
- Select `Clear the previous query on launch` in the settings
- Try to search for something in PT Run
- Relaunch PT Run and check that flicker is gone
- Try different collapsing scenarios: click on the side, …
=> "Clear the previous query on launch" has a flicker

src/common/interop/interop.cpp, src/common/interop/shared_constants.h, src/modules/interface/powertoy_module_interface.h, src/modules/launcher/Microsoft.Launcher/dllmain.cpp, src/modules/launcher/PowerLauncher.Telemetry/Events/PluginModel.cs, src/modules/launcher/PowerLauncher.Telemetry/Events/RunPluginsSettingsEvent.cs, src/modules/launcher/PowerLauncher.Telemetry/Events/RunSettingsEvent.cs, src/modules/launcher/PowerLauncher/Helper/NativeEventWaiter.cs, src/modules/launcher/PowerLauncher/MainWindow.xaml.cs, src/runner/main.cpp, src/runner/runner.vcxproj, src/runner/runner.vcxproj.filters, src/runner/settings_telemetry.cpp, src/runner/settings_telemetry.h
We decided to send settings telemetry every day. The runner is responsible for sending coordination. We save last sent time to a file in order to avoid sending more than once a day.
- Run sending of telemetry in a separate thread
- Store last send time in `telemetry-settings.json`
- Add `send_settings_telemetry` method in `PowertoyModuleIface`
- Use the auto-reset event to signal the `PowerLauncher.exe` process to send telemetry. At first glance, it can look that it is better to send PT Run telemetry from inside of the runner process. But because the PT Run module interface is unaware of PT Run settings it is better to keep it this way.
It is going to be tested in a Windows 10 Insider machine
A …
=> Settings telemetry for PT Run

src/modules/colorPicker/ColorPickerUI/Helpers/AppStateHandler.cs, src/modules/colorPicker/ColorPickerUI/Keyboard/KeyboardMonitor.cs
Use the escape key to exit the colour editor UI. I wasn't sure if this was the right way to do this but using other methods didn't produce a reliable result especially when opening the UI from the picker and not interacting with it, escape wouldn't actually work.
Use the escape key to exit the colour editor UI.
Add additional methods to detect and close the UI.
Manual testing.
=> [Color Picker] Use escape key to exit colour editor UI

src/common/interop/interop.cpp, src/common/interop/shared_constants.h, src/modules/colorPicker/ColorPickerUI/Helpers/Logger.cs
Change ColorPicker's logs path to `Microsoft\PowerToys\ColorPicker\Logs`.
Check that logs are written to the new location.
=> Color picker logs path

src/modules/colorPicker/ColorPickerUI/Keyboard/KeyboardMonitor.cs
According to https://github.com/microsoft/PowerToys/issues/9573#issuecomment-795812278, we get null reference exception  in https://github.com/microsoft/PowerToys/blob/77d67f35999bdf5cbaf96092c87e718afab91409/src/modules/colorPicker/ColorPickerUI/Keyboard/KeyboardMonitor.cs#L103
Note, that the variable `currentlyPressedKeys` is initialized at the beginning of the method.
We do not have steps to reproduce. Thioreticly, it is possible to get that exception if the first keyboard event captured by ColorPicker is keyup. Furthermore, from https://github.com/microsoft/PowerToys/issues/9573#issuecomment-795812278 we can see that it is possible. …
=> [Color Picker] Fix null reference exception

src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/Main.cs
Add tooltip to vscode workspaces plugin for powertoys run
Tooltips
**How does someone test / validate:**
Move the mouse over a result of vscode workspaces 
=> [Run plugin] add tooltips to vscode workspaces plugin

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/MonitorWorkAreaHandler.cpp, src/modules/fancyzones/lib/MonitorWorkAreaHandler.h, src/modules/fancyzones/lib/ZoneWindow.cpp, src/modules/fancyzones/lib/ZoneWindow.h, src/modules/fancyzones/lib/ZoneWindowDrawing.cpp, src/modules/fancyzones/lib/ZoneWindowDrawing.h
See issue #10026 
This PR currently does not add any extra telemetry or do anything if there is no layout with the desired key.
I'll add telemetry once we agree what should be included.
* Press Ctrl+Win+Alt+number to quickly switch layouts. Other shortcuts didn't work or are already in use by Windows.  This modifier combo might need to be updated.
* The monitor is picked based on cursor position.
* The layout will flash if the corresponding option is turned on. All layouts on the current VD will flash. If this is not desired, this can also be easily modified.
Try switching layouts while dragging and quickly switching layouts and activating zones to stress test the concurrency code controlling …
=> [FancyZones] Implement quick access keys, flashing

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs
`stream` is a COM object, so GC should free it at some non-deterministic time, but it's also ref-counted, so the issue might be caused by GC delay. `Marshal.ReleaseComObject` will release it immediately instead. 
I've also added logging to discover if the objects are leaked.
=> [PT Run plugin] Immediately releases AppxManifest stream objects

src/modules/fancyzones/lib/FancyZones.cpp, src/modules/fancyzones/lib/FancyZonesData.cpp, src/modules/fancyzones/lib/FancyZonesDataTypes.cpp, src/modules/fancyzones/lib/FancyZonesDataTypes.h
Due to a less than ideal data schema in FancyZones, we need to update information stored in custom zone sets, such as `sensitivityRadius` and `spacing` to the target device when applying the layout. See issue #10390
Check that the zone layout is applied correctly when switching layouts using the shortcut key.
=> [FancyZones] Update device info when setting custom zone sets from lib

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/BasePTModuleSettings.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerLauncherViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml.cs
We get a lot of glitches while updating plugins in the Plugin Manager. It happens because the view is completly rerendered on every change
- Ovverided equal facilities for `BasePTModuleSettings`
- Move reading settings and comparing  out of UI thread
- Do not update the view if it is up to date.
- Check that glitches are gone
- Check that the view is updated on settings change
=> [Run Settings] Don't update view if settings were not changed

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ColorFormatModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/ColorPickerViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml.cs
Replaced dragging with up/down buttons for color ordering.
=> [ColorPicker] Order colors with up/down buttons.

src/modules/launcher/Microsoft.Launcher/dllmain.cpp, src/runner/centralized_kb_hook.cpp, src/runner/powertoy_module.cpp
- Logs for centralized keyboard hook
- Do not terminate the PowerToys Run process if it was already terminated. We get a lot `Launcher process was not terminated. 
Access is denied`. I think it happens because the process is already terminated and is not an issue with the PowerToys Run interface.
=> Centralized keyboard hook logs

.pipelines/build-tools.cmd, .pipelines/pipeline.user.windows.yml
The internal CI fails to build the WebcamReportTool.
Remove the WebcamReportTool from the build.
=> [CI build] exclude WebcamReportTool from build

src/modules/colorPicker/ColorPickerUI/Mouse/MouseHook.cs
ColorPicker captures the mouse scroll event while active. The event should not be forwarded to other apps. In the future we will consider adding an option to only capture scroll events while Ctrl is pressed.
Returning -1 from the hook when scrolling achieves the effect.
Use ColorPicker above a browser or any other app which responds to scroll events. Also try moving the mouse away from the zoomed-in preview panel and scroll.
=> [ColorPicker] Disable forwarding the scroll event

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/PowerLauncherViewModel.cs
We should not update settings three times when in reality only one property changes.
Verify that glitch is gone.
=> [Settings] Fix UI glitch

.gitignore, src/modules/powerrename/lib/Helpers.cpp, src/modules/powerrename/lib/Helpers.h, src/modules/powerrename/lib/PowerRenameEnum.cpp, src/modules/powerrename/lib/PowerRenameEnum.h, src/modules/powerrename/lib/PowerRenameInterfaces.h, src/modules/powerrename/lib/PowerRenameLib.vcxproj, src/modules/powerrename/lib/PowerRenameManager.cpp, src/modules/powerrename/lib/pch.h, src/modules/powerrename/ui/PowerRenameUI.cpp, src/modules/powerrename/ui/PowerRenameUI.h, src/modules/powerrename/ui/Resources.resx
This change adds a standard shell progress dialog during startup to give feedback to the user that we are gathering all the items that were selected (including items in subfolders).  This allows the user to know we are still doing work as well as provide a means to cancel the operation.
Applies to #9254
=> Show progress dialog during startup 

src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/WorkspacesHelper/VSCodeStorageFile.cs, src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/WorkspacesHelper/VSCodeWorkspacesApi.cs
Unfortunately the latest vscode stable and insiders changed the format of the storage.json which made the plugin not work for some.
This fix makes the plugin work with previous versions and the more recently ones.
- Activate vscode plugin
- Use the keyword {
=> Workspaces not showing in vscode plugin #10530

src/modules/shortcut_guide/shortcut_guide.cpp, src/modules/shortcut_guide/shortcut_guide.h, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ShortcutGuideProperties.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/ShortcutGuideViewModel.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
Excluded apps for Shortcut Guide
Option for exclude programs from Shortcut Guide similar to FanzyZones
- Build
- Add one or more apps in Settings > Shortcut Guide > Excluded apps
- Open an excluded app
- Long press win key
- Shortcut Guide shouldn't be showed
- Release win key
- Start menu should be opened
Wondering if original poster issue is fixed by this.
Any chance to test it against a program that is using win key without remapping it?
=> [Shortcut Guide] Excluded Apps

src/settings-ui/Microsoft.PowerToys.Settings.UI/App.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/KeyVisual/KeyVisual.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/KeyVisual/KeyVisual.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/ShortcutTextControl.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/ShortcutTextControl.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/ShortcutVisualControl.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Controls/ShortcutVisualControl.xaml.cs, src/settings-ui/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFancyZones.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFileExplorer.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeImageResizer.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeKBM.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobePowerRename.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeVideoConference.xaml, src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw, src/settings-ui/Microsoft.PowerToys.Settings.UI/Styles/TextBlock.xaml, src/settings-ui/PowerToys.Settings/MainWindow.xaml.cs
This PR introduces a new TextBlock-based control that can be used to highlight/bold e.g. shortcuts or important instructions, inline with Windows Tips.
Parts of strings can be bolded by using the { and } tags.
E.g.:
Press {Ctrl} to open this module => Press **Ctrl** to open this module
@crutkas @enricogior I went for the text-highlighting option, putting in a shortcut visual was a bit complex when having shortcuts within the text string itself. I kept that control (ShortcutVisualControl) in if we want to use it later on.
=> [OOBE] Bolded shortcuts / instructions

src/modules/launcher/PowerLauncher/LauncherControl.xaml, src/modules/launcher/PowerLauncher/MainWindow.xaml, src/modules/launcher/PowerLauncher/ResultList.xaml
Removed manual ClearType setting since it causes on higher resolution screens (as discussed with @crutkas here: #6462). It now renders smoother.
Before:
After:
=> [Run] Revert ClearType regression

src/modules/fancyzones/lib/ZoneSet.cpp
There was an error in calculating the zones for grid layouts, see #10594.
This PR fixes that.
Verify that the layout described in the issue gets drawn correctly. Don't forget to set spacing to see the difference. Also verify its transpose, as it also had this issue. By transpose i mean:
12
33
=> [FancyZones] Fix an issue with zone sizes

PowerToys.sln, src/common/logger/logger_settings.h, src/common/utils/logger_helper.h, src/modules/fancyzones/dll/dllmain.cpp
Create a subfolder with the version number for logs, e.g. `PowerToys\FancyZones\Logs\v0.35.0`.
Delete old logs in `PowerToys\FancyZones\FancyZonesLogs` and logs in subfolders with different versions.
=> [FancyZones] Place log files in subfolders with the version number.

src/modules/launcher/PowerLauncher/Plugin/PluginManager.cs, src/modules/launcher/PowerLauncher/SettingsReader.cs, src/modules/launcher/Wox.Plugin/PluginPair.cs, src/modules/launcher/Wox.Test/PluginManagerTest.cs
A plugin has to be always loaded as plugin instance provide settings(Name, Description, AdditionalSettings) to be stored in `settings.json` file.
Divide load and initializing of plugins
- Test empty configuration(delete AppData)
- Try to disable and enable plugins
- Start PowerToys when there are few plugins disabled. Try to enable them and test if they work
=> Divide load and initialize of plugins into two stages

src/modules/colorPicker/ColorPickerUI/Helpers/AppStateHandler.cs, src/modules/colorPicker/ColorPickerUI/Keyboard/KeyboardMonitor.cs
Color Picker captures the Escape key event while active. The event should not be forwarded to other applications.
Return whether Color Picker was successfully closed, as a `bool`, from `EndUserSession`, then set `e.Handled` to the returned value in `Hook_KeyboardPressed`.
Open an app that responds to Escape being pressed, use Color Picker, then press escape to close Color Picker.
=> Disable forwarding the Escape event

installer/PowerToysSetup/Product.wxs
Color picker does not start because some dlls are missing
- Install PowerToys
- Verify that color picker works
=> [VCM branch][Color Picker] Add missing dlls

.github/actions/spell-check/expect.txt, doc/specs/preview-monaco.md
Adds the spec for the monaco preview pane
The spec file
Read through and check for mistakes
=> monaco preview specification

src/modules/imageresizer/ui/Views/InputPage.xaml
- Swapped out the custom input TextBox with NumberBox so they will have immediate keyboard focus (#10363)
- NumberBoxes need more width to display all UI chrome, therefore the inputfields are moved under the title to save space (especially for languages that have long titles). Did the same with the predefined sizes. 
Result:
=> [Image Resizer] Visual updates + NumberBox

src/common/utils/logger_helper.h
As was pointed out by @enricogior `delete_other_versions_log_folders` is not reliable. It can throw if `std::filesystem::directory_iterator` fails and we do not catch it.
One can artificially test it. For example, the folder does not exist or the process does not have rights to access the folder.
=> Make delete_other_versions_log_folders more reliable

src/modules/launcher/PowerLauncher/Plugin/PluginManager.cs
Some users report that typing in PowerToys Run is slow. It can be caused by plugins taking a lot of time to search. We want to verify it. For example, in https://github.com/microsoft/PowerToys/issues/10714 PT Run froze. But if a user disables Windows search everything works smoothly.
Log a warning if a plugin takes more than 50 milliseconds. It's a bad idea to log all queries cost as it generates a lot of logs(using PT Run for one minute generates more than 1MB of logs).
We may consider deleting other version logs as we do for c++ projects
=> Log a warning if a plugin search takes more than 50 milliseconds

src/modules/keyboardmanager/KeyboardManagerEditor/KeyboardManagerEditor.vcxproj, src/modules/keyboardmanager/KeyboardManagerEditorLibrary/KeyboardManagerEditorLibrary.vcxproj, src/modules/keyboardmanager/KeyboardManagerEngineLibrary/KeyboardManagerEngineLibrary.vcxproj, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/KeyboardManagerViewModel.cs
Editor output folder: `modules\KeyboardManager\KeyboardManagerEditor`
`KeyboardManagerEditorLibrary` and `KeyboardManagerEngineLibrary` output folder: `modules\KeyboardManager`
Rebuild projects and verify that files are in place.
=> [KBM] Changed Editor and libraries output folders

src/modules/keyboardmanager/KeyboardManagerEditor/KeyboardManagerEditor.cpp, src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/KeyboardManagerViewModel.cs
- Exit editor when parent process exited
- Do not run more than one editor instance
- Open an editor's window and exit PowerToys
- Verify that the editor's window exit as well(It's not enough to just close settings window because we hide it and the settings process is still alive)
- Try to start few single instances of the editor. Notice that the editor has mandatory cmd arguments
- Verify that only the first one starts and there is warnings in the logs
=> [KBM editor] Run only one instance, exit when parent process exits

src/modules/keyboardmanager/KeyboardManagerEditorLibrary/EditKeyboardWindow.cpp, src/modules/keyboardmanager/KeyboardManagerEditorLibrary/EditShortcutsWindow.cpp
See the issue
Killing the Editor process when exiting.
Removed logging before and after `xamlBridge.MessageLoop()` since `xamlBridge.MessageLoop()` already logs the start and stop.
Open and close multiple times the key and shortcut editor and verify no crash is reported in the Event viewer.
=> [KBM] Force kill editor process to avoid XAML crash

src/common/utils/EventLocker.h, src/modules/keyboardmanager/KeyboardManagerEditorLibrary/EditKeyboardWindow.cpp, src/modules/keyboardmanager/KeyboardManagerEditorLibrary/EditShortcutsWindow.cpp, src/modules/keyboardmanager/KeyboardManagerEngineLibrary/KeyboardManager.cpp, src/modules/keyboardmanager/KeyboardManagerEngineLibrary/KeyboardManager.h
- Redesign `EvenLocker`. The empty instance is returned if the Event can not be created
- Rename event for settings changes, add comment
=> Check success of event creation

src/modules/keyboardmanager/KeyboardManagerEngine/main.cpp
The internal pipeline was still failing to build with `error C2872` 
Don't use global namespace to prevent `error C2872`
Also fix a build warning for winMain missing the SAL annotation.
Run a internal pipeline build.
=> [KBM Engine] Remove global usings

src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
FZ Editor default hotkey has been changed.
https://github.com/microsoft/PowerToys/pull/10751 didn't include the change for OOBE
Open OOBE and verify the new hotkey is displayed:
We should consider putting the second sentence to a new line since the current formatting isn't ideal
=> [OOBE] FZ Editor hotkey change

src/common/Display/dpi_aware.cpp, src/common/Display/dpi_aware.h, src/modules/keyboardmanager/KeyboardManagerEditorLibrary/EditKeyboardWindow.cpp, src/modules/keyboardmanager/KeyboardManagerEditorLibrary/EditShortcutsWindow.cpp
Since the editor is DPI aware, it needs to scale it's startup size accordingly.
Added a helper function to scale dimensions based on current cursor position.
Open the Settings page on a monitor with high DPI scaling and verify the editor windows are sized as expected.
=> [KBM] scale editor window size based on DPI

src/modules/fancyzones/editor/FancyZonesEditor/App.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml, src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.Designer.cs, src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx, src/modules/fancyzones/editor/FancyZonesEditor/Styles/GridViewStyles.xaml
**THIS PR SHOULD BE MERGED IN BEFORE: #11047**
This PR replaces the ItemsControls (showing the monitors and layouts) with a ModernWPF GridView. This comes with the following advantages:
- Keyboard navigation is way better now and inline with Windows standards (Tab for moving between GridViews, arrow to move around between layouts)
- Solving a bunch of narrator issues.
- Mouse-over visual now inline with WinUI.
- Right-mouse context menu added (since we no longer have the MouseDown event to trigger the layout)
Final result:
=> [FZ Editor] Replace ItemsControls with GridViews

src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.VSCodeWorkspaces/Main.cs
**What is this about:** 
Improve workspaces order in vscode workspace plugin for powertoys run.
A new way of sorting workspaces.
Enable vscode plugin on powertoys run setting and then use { to query for available workspaces.
=> improve sorting vscodeworkspaces plugin

src/modules/colorPicker/ColorPickerUI/ViewModels/MainViewModel.cs
If color already exists in history, move it to position 0.
This prevents new duplicate colors, but ignores existing duplicates.
Currently, chosen colors are always added to the top of history, regardless of existing history. This can lead to many duplicates existing simultaneously. In most cases, this is undesirable behavior.
Before adding a new color, check if the color already exists in history, then move it to the top.
Use the color picker to choose a color already in history. Instead of creating a new color, it will move the existing color to the top.
If the existing color is already at the top, it essentially does nothing. …
=> [ColorPicker] Prevent creation of duplicate colors in history
