microsoft/PowerToys

README.md

Corrected letter transpositions, and capitalized Alt+Tab for consistency (all other key names were at the beginning of their respective lines, so were already capitalized, but on my Surface Book all modifier keys and Tab are capitalized)

Minor spelling corrections

---

src/README.md

Fixes small typo in `src` folder's readme.

Small typo fix

---

README.md

Typo: Fanzy -> Fancy

---

README.md

trivial typo fixes
trivial typos in readme fixed
* [NA ] Closes #xxx
* [ NA] Tests added/passed
manually double checked proposed changes

Fix minor typos in readme.md

---

doc/planning/PowerToysBacklog.md

It's just a typo fix in a doc.

Fixing typo

---

README.md

Add the Azure pipeline CI build status to the repo README.
Verified on the staging repo.

add build status to readme

---

src/README.md

Simple edit to the README.md
None
None required

Couple of typos

---

README.md

I added documentation regarding the Chocolatey installation.
Just a small documentation update.
N/A
N/A

Add documentation about Chocolatey installation

---

src/editor/main.cpp

After a fatal error, exit the Settings process.
After showing a MessageBox with the error, exit the process.
Fix some places where WINRT_VERIFY was used improperly.
Code formatting.
Manual test.

exit Settings on fatal error

---

src/settings-web/package.json

Update the destination folder in the setting-html build command.
This is a regression from renaming the `src/editor` folder to `src/settings`
https://github.com/microsoft/PowerToys/commit/b50df5afe141ea5bff21aeadec1373f6d8209d72
Manual testing.

update destination folder

---

src/settings-web/README.md
src/settings-web/src/components/App.tsx
src/settings-web/src/components/ModuleSettings.tsx

Rename CustomSettingsScreen to ModuleSettings

---

.pipelines/pipeline.user.windows.buddy.yml
.pipelines/pipeline.user.windows.yml

Ignore tool files.
Ignores Wix Toolset files.
Built.

Ignore wix toolset items

---

.pipelines/pipeline.user.windows.buddy.yml

Ignore files for build.
Build succeeded.

ignore javascript files

---

.pipelines/pipeline.user.windows.yml

Add item to build file for all build types.
Tests passed locally.  Build succeeded.

exclude items for all build types

---

doc/coding/organization.md

Fixes a typo in `organization.md`

Fix typo in organization.md

---

README.md

Typo at line 42 

---

README.md

Adjusted formatting a bit based on a linting project, also added in privacy policy.

prepping for 0.12 release

---

README.md

- added in processor support type with issue links
- added in section to call out WinStore support issue
- reduced size on image

Updates for readme

---

README.md

The install link was a bit difficult to find, this is one alternative

Add link to releases tab

---

doc/coding/style.md

- how to use clang-format from Visual studio
- how to use `format_sources` script

docs: add paragraph about clang-format

---

README.md

Now in line with #913
Just fixing some links, checked them myself, now in line with package structure.
Just checked links.

Correct readme links

---

src/modules/fancyzones/editor/FancyZonesEditor/GridEditor.xaml.cs

validated with owner regarding proper math and other spots in code match pattern.  Example:
`Canvas.SetTop(resizer, _rowInfo[row].End + (spacing / 2) - 24);`

fix for #923

---

src/settings/StreamURIResolverFromFile.cpp
src/settings/StreamUriResolverFromFile.h
src/settings/main.cpp

Codying style applied to the settings project.
Verified solution builds correctly.

Coding style (settings)

---

src/runner/auto_start_helper.cpp
src/runner/general_settings.cpp
src/runner/general_settings.h
src/runner/lowlevel_keyboard_event.cpp
src/runner/main.cpp
src/runner/powertoy_module.cpp
src/runner/powertoy_module.h
src/runner/powertoys_events.cpp
src/runner/powertoys_events.h
src/runner/restart_elevated.cpp
src/runner/settings_window.cpp
src/runner/system_menu_helper.cpp
src/runner/system_menu_helper.h
src/runner/trace.cpp
src/runner/trace.h
src/runner/tray_icon.cpp
src/runner/tray_icon.h
src/runner/unhandled_exception_handler.cpp
src/runner/unhandled_exception_handler.h
src/runner/win_hook_event.cpp
src/runner/win_hook_event.h

Codying style applied to the runner project.

Coding style (runner)

---

src/settings-web/package.json

settings-web: use Windows build-in commands

---

src/common/common.cpp
src/runner/restart_elevated.cpp

Fixes restarting with the same elevation when installed from MSIX
Manual

Runner: fix restarting with same elevation

---

src/settings/main.cpp
src/settings/pch.h
src/settings/settings.vcxproj
src/settings/settings.vcxproj.filters
src/settings/trace.cpp
src/settings/trace.h

Implement the new event and telemetry support in the settings project.

Webview error telemetry event

---

PowerToys.sln

fix project dependency order
- performed a clean rebuild 2 times

sln: fix project dependency order

---

doc/specs/FancyZones-DCR.md

Design change request for improvements in virtual desktops creating/deleting behavior.

Add design change request for improvements in virtual desktops handling

---

src/runner/general_settings.cpp
src/runner/general_settings.h
src/runner/main.cpp
src/runner/trace.cpp
src/runner/trace.h

Added telemetry event on applying general settings. Updated runner launch event with elevated value.

Add telemetry event for general settings

---

.pipelines/pipeline.user.windows.yml

PowerRenameExt.dll was not signed during the release build.
Built on the internal pipeline (pending).

Setup: sign PowerRenameExt.dll

---

tools/FancyZones_zonable_tester/FancyZones_zonable_tester.sln
tools/FancyZones_zonable_tester/FancyZones_zonable_tester.vcxproj
tools/FancyZones_zonable_tester/FancyZones_zonable_tester.vcxproj.filters
tools/FancyZones_zonable_tester/main.cpp

Uses FancyZones logic to test if window is zonable or not. Displays window styles and results for various tests if the window should be zonable or not.

tools: add tool to debug FancyZones zonable windows

---

.pipelines/nuget.config

Update the internal nuget feed used to restore the telemetry header.
Manually tested the `.pipelines/restore-telemetry.cmd` script and verified that the packaged is downloaded and the header copied to its final destination.

[CDPx] update nuget feed

---

.pipelines/build-installer.cmd
.pipelines/msix/build_msix.cmd

Fix to invoke makeappx and updated the SDK version for building the MSI.

[CDPx] fix for makeappx, update SDK for MSI

---

.pipelines/pipeline.user.windows.yml

Move the package build step to the `package` section to enable package signing.
After the signing is fixed, we will have to verify if the current signing profile is the correct one for side-loading.

[CDPx] sign MSIX package and bundle

---

.pipelines/pipeline.user.windows.yml

Remove `signing_options` for package since a global `signing_options` is already set.

[CDPx] remove 'signing_options' for package

---

.pipelines/pipeline.user.windows.yml

Archive symbols to Microsoft Symbol Server.
Need to verify if it's ok to have the `name: 'Archive symbols to Symbol Server'` tag since in the documentation example it's not present.

[CDPx] archive symbols to Symbol Server

---

installer/README.md

Docs say MSI is deprecated, not true currently.

Adjusting installer instructions back

---

src/settings-web/src/components/GeneralSettings.tsx

Fixes a spelling mistake in the ```src/settings-web/src/components/GeneralSettings.tsx``` file
It was already noticed, & suggested by another contributor, in https://github.com/microsoft/PowerToys/pull/494, but they forgot to commit that suggestion.
Changes ```Chose``` to ```Choose```
Manual

Fix spelling mistake

---

README.md

Updated the broken link for build definition in `README.md`

Updated build definition link in readme

---

.pipelines/ci/templates/build-powertoys-steps.yml

Set up CI to run unit tests

---

src/common/msi_to_msix_upgrade_lib/msi_to_msix_upgrade_lib.vcxproj

tweaking this fixed it.
* [] Applies to #1595

fix for #1595

---

src/common/json.cpp

Check if file is open, before running JSON parser on it.

Check if settings file is open before parsing JSON

---

src/runner/general_settings.cpp

Check key existance before getting it from JSON

---

doc/devdocs/readme.md

Added details on the workflow process.

Update dev doc github workflow

---

src/tests/win-app-driver/FancyZonesTests/EditorSettingsTests.cs
src/tests/win-app-driver/PowerToysSession.cs
src/tests/win-app-driver/win-app-driver.csproj

Test for editing zone count in editor
* [] Applies to #846

Editor settings test

---

src/tests/win-app-driver/FancyZonesTests/EditorTemplatesEditTests.cs
src/tests/win-app-driver/PowerToysSession.cs
src/tests/win-app-driver/win-app-driver.csproj

Tests for editing template layouts in editor

Editor templates tests

---

src/modules/powerrename/lib/stdafx.h
src/modules/powerrename/testapp/stdafx.h
src/modules/powerrename/ui/stdafx.h
src/runner/unhandled_exception_handler.cpp

Replaced Deprecated headers
I replaced the deprecated STL headers and replaced them with the equivalent ones.
- Unit tests

Replace deprecated C headers with C++ headers

---

src/tests/win-app-driver/FancyZonesTests/EditorTemplatesApplyTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorTemplatesEditTests.cs
src/tests/win-app-driver/PowerToysSession.cs
src/tests/win-app-driver/win-app-driver.csproj

Open editor, apply template layout, check if zones-settings were changed

Editor tests: apply templates 

---

src/tests/win-app-driver/FancyZonesTests/EditorTemplatesEditTests.cs
src/tests/win-app-driver/PowerToysSession.cs

added checks for zones count and type in Editor templates edit tests

Editor templates tests update

---

.pipelines/pipeline.user.windows.yml

MSI: sign remaining binaries

---

src/modules/windowwalker/app/Window Walker/ViewModels/WindowWalkerViewModel.cs

Removed the part of the code in Window Walker which added a registry entry in HKCU to set it as a startup application.
Built Debugx64 and installed with MSI to verify that functionality is working.

Remove WW being set as startup app

---

src/tests/win-app-driver/FancyZonesTests/EditorCanvasZoneResizeTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorCustomLayoutsTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorGridZoneResizeTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorOpeningTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorTemplatesApplyTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorTemplatesEditTests.cs
src/tests/win-app-driver/FancyZonesTests/FancyZonesEditor.cs
src/tests/win-app-driver/PowerToysSession.cs
src/tests/win-app-driver/win-app-driver.csproj

Creation, deletion, edit custom layouts tests
Tests were revealed problems related to issues #1712, #1754 
Tests done:
- Create custom layout
- layout with zones
- layout without zones
- layout with empty name
- name with unicode characters
- several layouts with same names  
- Edit custom layouts:
- Add/remove canvas zones
- Move borders of canvas zones
- Move splitters of grid zones
- Create new splitters
- Merge grid zones 
- Delete custom layout
- Delete layout and close editor
- Delete and add new layout

Editor custom layouts tests

---

README.md

Readme updates to include 0.16 change log.
**DO NOT MERGE IN UNTIL 0.16 IS RELEASED :)**

Main readme for 0.16 - DO NOT MERGE

---

src/tests/win-app-driver/FancyZonesTests/EditorTemplatesEditTests.cs
src/tests/win-app-driver/FancyZonesTests/FancyZonesSettingsTests.cs
src/tests/win-app-driver/PowerToysSession.cs
src/tests/win-app-driver/PowerToysTrayTests.cs

* Updated names for visual elements
* Updated elements search in tray tests
* Changed PowerToys launch
* Updated FancyZones Settings tests for toggles and color sliders

Tests updates

---

README.md

Language pedantry. Corrects use of the always incorrect "off of" with "on" in the Readme.
I've not looked for anything beyond the root readme, which I probably should've done. Feel free to tell me if there's anything else.
N/A
* [N/A] Applies to #xxx
* [N/A] Tests added/passed
* [N/A] Requires documentation to be updated

Correct use of "off of" in the readme

---

src/runner/general_settings.cpp

Disabling powertoy only if it's explicitly off in settings

Disabling powertoy only if it's explicitly off

---

src/common/VersionHelper.cpp
src/common/VersionHelper.h
src/common/msi_to_msix_upgrade_lib/msi_to_msix_upgrade.cpp
src/common/msi_to_msix_upgrade_lib/msi_to_msix_upgrade.h
src/runner/main.cpp

- automatic MSIX package uninstallation on startup
- shows simple toast on success

runner: implement automatic MSIX package uninstallation on startup

---

src/tests/win-app-driver/FancyZonesTests/EditorSettingsTests.cs

Editor settings tests
* [] Applies to #846 
Added tests for "Show space around zones" checkbox and "Space around zones" field

Tests: Editor settings tests

---

src/tests/win-app-driver/FancyZonesTests/EditorCanvasZoneResizeTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorCustomLayoutsTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorOpeningTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorSettingsTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorTemplatesEditTests.cs
src/tests/win-app-driver/FancyZonesTests/FancyZonesEditor.cs
src/tests/win-app-driver/FancyZonesTests/FancyZonesSettingsTests.cs
src/tests/win-app-driver/PowerToysSession.cs
src/tests/win-app-driver/PowerToysTrayTests.cs

Changed behavior of element appear waiting: increased waiting time for settings reading and replaced fixed time interval to `WaitElement` method.
Also updated PowerToys launch: removed additional capabilities.

WinAppDriver tests fix

---

NOTICE.md

updated notice

---

src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/KeyboardManagerPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml

Adding in the attribution
* [] Applies to #862

xaml adjustments, including contributors

---

src/modules/launcher/PowerLauncher/App.xaml.cs
src/modules/launcher/PowerLauncher/MainWindow.xaml
src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
src/modules/launcher/PowerLauncher/ReportWindow.xaml.cs
src/modules/launcher/Wox.Infrastructure/Exception/ExceptionFormatter.cs
src/modules/launcher/Wox.Infrastructure/Wox.cs
src/modules/launcher/Wox/App.xaml.cs
src/modules/launcher/Wox/Helper/ErrorReporting.cs
src/modules/launcher/Wox/ReportWindow.xaml.cs
src/modules/launcher/Wox/ViewModel/MainViewModel.cs

removing everything references 

---

src/modules/launcher/PowerLauncher/App.xaml.cs

* Set the MainWindow Visibility to hidden on startup.
* Manually verified that the PowerLauncher Application is running in the task manager but doesn't pop up.
* Pressing Alt+Space triggers it.

Set MainWindow visibility to hidden on startup

---

.pipelines/ci/ci.yml
.pipelines/ci/templates/build-powertoys-steps.yml
src/modules/launcher/PowerLauncher/PowerLauncher.csproj

Adding CI trigger for `dev/PowerLauncher` branch. Currently using hard coded branch name in the `yml` which should be removed while merging to master. Alternatively, we can use wildcard for mentioning all the feature branch like `feature/*` but currently there are many other branches with `dev/*` pattern.

Enable CI build on PowerLauncher Branch

---

src/modules/launcher/PowerLauncher.UI/LauncherControl.xaml

tweak text

---

src/runner/tray_icon.cpp

[PowerToys] Show version on tooltip
* [] Applies to #1532 

Fix for issue #1532 - [PowerToys tray icon] Show version on tooltip

---

README.md

update github releases to latest link

---

installer/PowerToysSetup/Product.wxs
src/common/monitors.cpp
src/common/monitors.h
src/modules/fancyzones/editor/FancyZonesEditor/GridEditor.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/GridZone.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/RowColInfo.cs
src/modules/fancyzones/editor/FancyZonesEditor/SplitEventArgs.cs
src/modules/fancyzones/lib/Zone.cpp
src/modules/fancyzones/lib/ZoneWindow.cpp
src/modules/powerrename/dll/dllmain.cpp
src/modules/powerrename/lib/Settings.cpp
src/modules/powerrename/lib/Settings.h
src/modules/powerrename/ui/PowerRenameUI.cpp
src/modules/powerrename/ui/PowerRenameUI.h
src/modules/previewpane/MarkdownPreviewHandler/MarkdownPreviewHandlerControl.cs
src/runner/tray_icon.cpp
src/tests/win-app-driver/FancyZonesTests/EditorGridZoneResizeTests.cs
src/tests/win-app-driver/FancyZonesTests/FancyZonesEditor.cs

Merge master into dev/PowerLauncher
Manually verified the working of launcher plugins.

Pull changes from master to dev/powerLauncher

---

community.md

Adding in a community attribution page for high impact community members.  
#862 would be tracking item

Adding community page

---

src/modules/launcher/Wox.Infrastructure/StringMatcher.cs

* Modify scoring algorithm so that `code` shows up vscode.
* https://github.com/jjw24/Wox/pull/182#pullrequestreview-395892103
Manually validated it.

Modify scoring algorithm for fuzzy search

---

installer/PowerToysSetup/Product.wxs

We had removed this code as the folder plugin was removed. Adding it back in.

Add the folder plugin wxs back in

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/PowerLauncherSettings.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/PowerLauncherViewModel.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/Microsoft.PowerToys.Settings.UnitTest.csproj
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/PowerLauncherViewModelTest.cs
src/modules/fancyzones/tests/UnitTests/UnitTests.vcxproj.filters

Added unit tests to `PowerLauncherViewModel`

PowerLauncherSettings unit tests

---

src/action_runner/action_runner.cpp
src/common/updating/updating.cpp
src/runner/auto_start_helper.cpp
src/runner/main.cpp
src/runner/powertoy_module.cpp
src/runner/settings_window.cpp
src/runner/update_utils.cpp

Removed headers that never be used.

Remove unused header

---

src/modules/launcher/PowerLauncher.UI/App.xaml
src/modules/launcher/PowerLauncher.UI/LauncherControl.xaml
src/modules/launcher/PowerLauncher.UI/ResultList.xaml
src/modules/launcher/PowerLauncher/MainWindow.xaml
src/modules/launcher/PowerLauncher/MainWindow.xaml.cs

Merge in two missing commits from dev/PowerLauncher
* [Launcher] Fluent UX fixes for the results list (#2427) 
* [Launcher] Fluent UX enhancements (#2477)

Merge missing commits from power launcher

---

src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Main.cs
src/modules/launcher/Plugins/Wox.Plugin.Folder/Main.cs
src/modules/launcher/Plugins/Wox.Plugin.Shell/Main.cs
src/modules/launcher/Plugins/Wox.Plugin.WindowWalker/Main.cs

Updated Description of search results to show which plugin it came from. 
Manually validated that plugins show updated descriptions.

Updated file path/description of plugins

---

doc/Interns/MyFirstCommit.md

Updates the My First Commit instructions

Updated instructions

---

doc/Interns/sanids/MyFirstCommit.md

First commit

---

src/common/notifications/notifications_dll.rc
src/common/notifications/notifications_dll.vcxproj
src/common/notifications/notifications_dll.vcxproj.filters
src/common/notifications/resource.h

Added information about company name, module name, version into windowwalker.dll, notifications.dll, windowwalker.exe 
Added information to WindowWalker resource file, added resource file for notifications dll project. Added assembly info to WindowWalker app
Manually tested, checked details of notifications.dll, windowwalker.dll, windowwalker.exe

Added needed info to dll's and exe

---

src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml

[Settings v2] FancyZones settings: multi-line input for excluded apps

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/FZConfigProperties.cs
src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/FancyZonesViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml

Bring FancyZones checkboxes up to date

[Settings v2] FancyZones settings checkboxes update

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/FZConfigProperties.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/FancyZonesSettingsIPCMessage.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/HotkeySettings.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/KeyBoardKeysProperty.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/ShortcutGuideProperties.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/FancyZonesViewModel.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/Microsoft.PowerToys.Settings.UnitTest.csproj
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/FancyZones.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/ShortcutGuide.cs

- Updated Shortcut Guide settings default values.
- Updated FancyZones settings default values.
- Updated Shortcut guide tests to check for default values.
- Updated FancyZones tests to check for default values.
- Ran and updated tests

[Settings V2] Upated Fancy Zone and Shortcut Guid default values.

---

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml

Fixing ordering in settings and text tweaks

---

src/modules/Cursor/Cursor.cpp

Exercise of pushing codes from my own branch.

Sample commit with comment to Cursor code

---

src/core/Microsoft.PowerToys.Settings.UI/App.xaml
src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj
src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/core/Microsoft.PowerToys.Settings.UI/Styles/Button.xaml
src/core/Microsoft.PowerToys.Settings.UI/Styles/_Thickness.xaml
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/GeneralViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/KeyboardManagerPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/General.cs

- Re-organized the General page (#2804 #2688)
- Applied consistent add button styling (for KBM and ImageResizer( #2806 #2710)
- Increased the default step value for the shortcut transition time (#2808)
- Changed the 'About feature' text to 'About [MODULE NAME]' (#2805)
- Added a direct link to this GitHub repo on the General page.
- Minor localization fixes.
General page:
New Add button style:
#2804 #2688 #2806 #2710 #2808 #2805

[Settings] Various UX tweaks

---

src/modules/keyboardmanager/common/Helpers.cpp
src/modules/keyboardmanager/common/Shortcut.cpp

This PR fixes the warnings mentioned in #2884. The changes don't affect the functionality since both scenarios it was making sure "else" cases are handled correctly but there was no actual code path where those values could enter the function.
Verified that modified control paths work as expected

Fix KBM compile time warnings

---

POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Strings/en-us/Resources.resw
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/MainPage.xaml
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/MainPage.xaml.cs
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/ShellPage.xaml

- Added Teaching Tips for general settings page (MainPage.xaml and MainPage.xaml.cs)
- Made pages scrollable (ShellPage.xaml)
- Removed default header setting included in WinTS template app

[intern] Push General Settings TeachingTips to OOBE POC

---

src/action_runner/action_runner.cpp

See #2942 for issue description.
- install PT on a clean VM, verified `dotnet --list-runtimes` output:
```
Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

wix: Install .NET Core 3.0.x instead of .NET Core 3.1.x

---

POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/PowerToys Settings Sandbox.csproj
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/MainPage.xaml.cs
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/onLaunchContentDialog.xaml
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/onLaunchContentDialog.xaml.cs

Created a stand-alone contentDialog for the welcome screen introduced in pull request[#2950](https://github.com/microsoft/PowerToys/pull/2950)

refactored on-launch contentDialog

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/EnabledModules.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/PowerLauncherSettings.cs
src/modules/launcher/Wox.Infrastructure/Wox.cs

Updated powertoy run module name in settings. This is to fix powertoy run not reacting to settings changes cause in #2961 
Manually validated that powertoy run reacts to change in all the settings.

Fixed powertoys run not reacting to change in settings

---

POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/MainPage.xaml

- New teaching tips to reflect new design

[intern] New General Settings teaching tips to reflect new design (OOBE POC)

---

POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/App.xaml.cs
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Services/ActivationService.cs
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Services/NotificationService.cs
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/MainPage.xaml.cs

- Create toast for new Update and Update available
- Changed design of button
- refactored code for notifications
- Add activation tags
- On Launch both a "Get Started with PowerToys" and "New PowerToys Update" toast should pop up

[intern] Create Update Toast

---

POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/PowerToys Settings Sandbox.csproj
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/MainPage.xaml
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/MainPage.xaml.cs
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/UpdateContentDialog.xaml
POC-OOBE/OOBE-Sandbox/PowerToys Settings Sandbox/Views/UpdateContentDialog.xaml.cs

- on click of the "Check for Updates button" in General Settings, the update content dialog should pop up

[intern] Pushing initial update content dialog files (OOBE POC)

---

src/modules/Cursor/Cursor.cpp

Detect grey cases. Mainly change is replacing RGB(255 - r, 255 - g, 255 - b) with the function "COLORREF opposite_color(int r, int g, int b)"

[intern] Detect grey case and deal them with threshold

---

proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/App.config
proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/ColorPickerAlpha.csproj
proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/app.manifest

Fixed the app.manifest and app.config to accomodate the change in DPI for getPixel.

[Interns] DPI Issue patched

---

src/modules/Cursor/README.md

Image resize md

---

src/modules/Cursor/README.md

Image final

---

src/modules/Cursor/README.md

Limitations and bugs

---

proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/ColorPickerAlpha.csproj
proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/MainWindow.xaml
proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/MainWindow.xaml.cs
proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/OverlayWindow.xaml
proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/OverlayWindow.xaml.cs

Add click eyedropper functionality and preventing color picking in the color picker window.

[intern] Interns/users/vassenx/ui connect

---

src/core/Microsoft.PowerToys.Settings.UI/ViewModels/ImageResizerViewModel.cs

Very obvious problem with a very obvious fix.
See #3052
Tested manually, now the crash does not happen and the settings work.

Fixed a crash in Settings/ImageResizer

---

src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml

Fix for randomly collapsing and expanding excluded apps list

Fz Settings excluded apps multiline behavior - fix

---

proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/MainWindow.xaml
proofOfConcept/ColorPickerAlpha/ColorPickerAlpha/MainWindow.xaml.cs

Click escape when in color picking mode to close the application.
When color picking, the mouse turns into a cross, and is restored afterwards.

[Intern] Interns/users/vassenx/polish ui

---

POC/ColorPicker/ColorPicker/ColorPicker.csproj
POC/ColorPicker/ColorPicker/PixelColorFinder.cs
POC/ColorPicker/ColorPicker/ScreenMagnification.cs
POC/ColorPicker/ColorPicker/TransparentWindow.xaml
POC/ColorPicker/ColorPicker/TransparentWindow.xaml.cs

Here is the code for the magnification. The basic premise is that the magnification image contents updates on an interval, while the position updates upon mouse movements. This keeps the mouse movements responsive.

[interns] Color Picker Magnification

---

.pipelines/packages.config
.pipelines/restore-telemetry.cmd

Update to use the telemetry nuget package v2 that contains a fix for the C++ header and the new base class for the C# projects.
None. It will be tested in the pipeline.

[CDPx] update to use telemetry nuget package v2

---

README.md

Replaced the image MD tag with HTML. Seems to solve the issue.
#3104

Fix for hero image not showing in GitHub mobile app on Android

---

src/modules/launcher/PowerLauncher/MainWindow.xaml.cs

This PR reduces query delay in launcher from 200ms to 100ms
Manually validated working of launcher and plugins.

Reduce query delay in launcher

---

README.md

Dev/crutkas/change log0.18

---

POC-OOBE/OOBE-Sandbox/README.md

Linked Rafael's GitHub to his name in the documentation

linked to Rafael's github

---

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw

Capitalize GitHub properly

---

.github/pull_request_template.md

Fix GitHub markdown for PR template

Use check boxes

---

.pipelines/build.cmd

Do not build notifications projects after we do build the .sln

CI: remove unnecessary build commands

---

src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml

Migrate numberboxes to compact mode

---

src/common/common-md-flag/common-md-flag.vcxproj
src/common/common-md-flag/packages.config
src/common/common.vcxproj
src/common/packages.config
src/core/Microsoft.PowerToys.Settings.UI.Lib/Microsoft.PowerToys.Settings.UI.Lib.csproj
src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj
src/core/Microsoft.PowerToys.Settings.UnitTest/Microsoft.PowerToys.Settings.UnitTest.csproj
src/modules/fancyzones/dll/FancyZonesModule.vcxproj
src/modules/fancyzones/dll/packages.config
src/modules/fancyzones/editor/FancyZonesEditor/FancyZonesEditor.csproj
src/modules/fancyzones/lib/FancyZonesLib.vcxproj
src/modules/fancyzones/lib/packages.config
src/modules/fancyzones/tests/UnitTests/UnitTests.vcxproj
src/modules/fancyzones/tests/UnitTests/packages.config
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Microsoft.Plugin.Indexer.csproj
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Microsoft.Plugin.Program.csproj
src/modules/launcher/PowerLauncher/PowerLauncher.csproj
src/modules/launcher/Wox/Wox.csproj
src/runner/packages.config
src/runner/runner.vcxproj

updated sql lite, oledb, mahapps, contract sdk, WIL and UWP.  This shoudl also help reduce our file size on CI too

Nuget updates

---

src/modules/example_powertoy/dllmain.cpp
src/modules/fancyzones/README.md
src/modules/fancyzones/dll/dllmain.cpp
src/modules/fancyzones/editor/FancyZonesEditor/CanvasZone.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/GridZone.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutModel.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/Settings.cs
src/modules/fancyzones/lib/FancyZones.cpp
src/modules/fancyzones/lib/FancyZones.h
src/modules/fancyzones/lib/Settings.cpp
src/modules/fancyzones/lib/ZoneWindow.h
src/modules/imageresizer/dll/dllmain.cpp
src/modules/keyboardmanager/common/KeyboardManagerState.cpp
src/modules/keyboardmanager/common/KeyboardManagerState.h
src/modules/keyboardmanager/common/Shortcut.cpp
src/modules/keyboardmanager/common/Shortcut.h
src/modules/keyboardmanager/dll/dllmain.cpp
src/modules/powerrename/dll/dllmain.cpp
src/modules/powerrename/ui/PowerRenameUI.cpp
src/modules/previewpane/README.md
src/modules/previewpane/SvgPreviewHandler/Telemetry/Events/SvgFilePreviewError.cs
src/modules/previewpane/common/handlers/PreviewHandlerBase.cs
src/modules/previewpane/powerpreview/powerpreview.cpp
src/modules/previewpane/powerpreview/powerpreview.h
src/modules/previewpane/powerpreview/settings.cpp
src/modules/previewpane/powerpreview/settings.h
src/modules/shortcut_guide/overlay_window.cpp

Spelling: ... src/modules

---

doc/Interns/FancyZonesHotkeysSpec.md
doc/Interns/TechnicalDocHandOff.md

Added Technical handoff (for multi-mon and hotkeys) as well as a Hotkeys specs draft for PowerToys FancyZones.

[intern] Interns/users/t kaelde/fancy zone technical doc

---

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ModelsTests/SettingsUtilsTests.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/ImageResizer.cs

https://github.com/microsoft/PowerToys/pull/3741#issuecomment-634656139

Spelling: ... core

---

src/runner/auto_start_helper.cpp
src/runner/auto_start_helper.h
src/runner/main.cpp
src/runner/powertoy_module.cpp
src/runner/powertoys_events.cpp
src/runner/system_menu_helper.cpp
src/runner/system_menu_helper.h
src/settings/main.cpp
src/tests/win-app-driver/FancyZonesTests/EditorCustomLayoutsTests.cs
src/tests/win-app-driver/FancyZonesTests/EditorTemplatesEditTests.cs
src/tests/win-app-driver/FancyZonesTests/FancyZonesEditor.cs
src/tests/win-app-driver/PowerToysSession.cs

https://github.com/microsoft/PowerToys/pull/3741#issuecomment-634656139

Spelling: ... runner settings

---

.pipelines/pipeline.user.windows.yml

Enable build step to publish the symbols.

[CDPx] publish symbols

---

src/modules/quick_resolution/readme.md

Added readme for project documentation. 

[intern] Quick screen resolution - Added readme

---

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32.cs
src/modules/launcher/Wox.Infrastructure/StringMatcher.cs
src/modules/launcher/Wox.Test/FuzzyMatcherTest.cs
src/modules/launcher/Wox.Test/Plugins/ProgramPluginTest.cs
src/modules/launcher/Wox.Test/Wox.Test.csproj

Hot fixes for launcher. 
They are already in master.
Cherry picked them for the stable branch.

Launcher hot fixes

---

NOTICE.md
community.md

Expanding 'community' section

---

doc/devdocs/readme.md

Script to get VS to install all needed components

Getting system up and going instructions

---

src/action_runner/action_runner.cpp
src/modules/launcher/Microsoft.Launcher/dllmain.cpp

Title should be enough, for more details, see issue #3862
Ran PT as administrator and tested the Launcher by turning it on/off.

[Action runner] Support running generic targets as non-elevated

---

src/runner/main.cpp

Fix invalid namespace for string.

[Installer] Fix invalid namespace crash on master

---

src/action_runner/action_runner.cpp
src/common/notifications.cpp
src/common/notifications.h
src/common/updating/http_client.cpp
src/common/updating/http_client.h
src/common/updating/toast_notifications_helper.cpp
src/common/updating/toast_notifications_helper.h
src/common/updating/updating.cpp
src/common/updating/updating.h
src/common/updating/updating.vcxproj
src/common/updating/updating.vcxproj.filters
src/core/Microsoft.PowerToys.Settings.UI.Runner/MainWindow.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/GeneralViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml.cs
src/runner/main.cpp
src/runner/settings_window.cpp
src/runner/update_utils.cpp
src/runner/update_utils.h

Checked manually. Tried different variations with enabled/disabled auto-download option and different versions.
For testing hardcoded current version [here](https://github.com/SeraphimaZ/PowerToys/blob/6f11b833d4625f16a8f7aa87a1f8bac73d29ea6f/src/common/updating/updating.cpp#L112)

[Settings] Check for updates button behavior changed

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/Microsoft.PowerToys.Settings.UI.Lib.csproj
src/core/Microsoft.PowerToys.Settings.UI.Runner/Microsoft.PowerToys.Settings.UI.Runner.csproj
src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj
src/core/Microsoft.PowerToys.Settings.UnitTest/Microsoft.PowerToys.Settings.UnitTest.csproj

Added info to projects inside core folder
Added/changed info for new settings projects (Microsoft.PowerToys.Settings)
Manually tested, checked compiled .exe's and .dll's

Added info to projects inside core folder

---

src/common/ManagedCommon/ManagedCommon.csproj

Added info to ManagedCommon project
Manually tested, checked compiled .dll's

Added info to ManagedCommon project

---

.pipelines/ci/templates/build-powertoys-steps.yml

Add the common lib unit tests to CI

[CI, test] add common lib unit tests

---

.pipelines/ci/templates/build-powertoys-steps.yml

Add the `**\` prefix to the common lib test dll.

[CI, test] add prefix to common lib test dll

---

installer/PowerToysSetup/Product.wxs

Add Missing images from the calculator plugin in MSI.

Add calculator images to MSI

---

src/modules/launcher/Wox/ViewModel/ResultViewModel.cs

Added a null check to fix the null reference exception
Tried searching through various results by hovering and arrow keys but I couldn't repro it anymore.

Fixed null reference exception on context menu buttons

---

src/modules/launcher/Wox/ViewModel/ResultViewModel.cs

Changed logic to use ? operator rather than explicit null check as suggested by @ryanbodrug-microsoft

Cleanup null reference fix with correct code practice

---

README.md

0.19 readme update

---

src/core/Microsoft.PowerToys.Settings.UI/ViewModels/FancyZonesViewModel.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/FancyZones.cs

Fixes for unit tests
Runned unit tests

[FancyZones] Fixes for unit tests

---

doc/devdocs/run-as-admin-detection.md

Changed to where it is in line with PowerToys

---

src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/AppxManifests/DevelopmentApp/AppxManifest.xml
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/AppxManifests/FrameworkApp/AppxManifest.xml
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/AppxManifests/PackagedApp/AppxManifest.xml
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Microsoft.Plugin.Program.UnitTests.csproj
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Programs/UWPTest.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Programs/UWPTests.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Microsoft.Plugin.Program.csproj
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/IPackage.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/IPackageManager.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/PackageWrapper.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/PackagemanagerWrapper.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/PackageRepository.cs

Added test for searching packaged app in development mode
1. Added `IPackage` interface to add a wrapper for `Package` class. This is required because the interfaces implemented by `Package` class are all internal and not cannot be used to create mocks.
2. Added `IPackageManager` interface to add a wrapper for `PackageManager` class. This is required because the interfaces implemented by `PackageManager` class are all internal. 
3. Added dummy manifests file to easily mock UWP packages. This will help us in easily testing Packaged programs similar to the way we currently do with win32 programs. 
Manually validated that tests pass.

Packaged apps test

---

README.md

Updated the Windows .msi installer version to `PowerToysSetup-0.19.2-x64.msi` from `PowerToysSetup-0.19.1-x64.msi` in README file.

updated the .msi installer version in README.md

---

src/modules/launcher/PowerLauncher/ResultList.xaml

Fix focus issue when result or context menu item is selected.
Manually validated that focus is not lost in subsequent launch after clicking on the result or context menu.

Fix Focus issue on clicking list view

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/BoolPropertyJsonConverter.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/FZConfigProperties.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/FancyZonesSettingsIPCMessage.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/GeneralSettingsCustomAction.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/HotkeySettingsControlHook.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/PowerRenameSettingsIPCMessage.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/SndFancyZonesSettings.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/SndShortcutGuideSettings.cs
src/core/Microsoft.PowerToys.Settings.UI.Lib/Telemetry/Events/SettingsEnabledEvent.cs
src/core/Microsoft.PowerToys.Settings.UI/Controls/BodyTextBlock.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Controls/GroupTitleTextBlock.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/VisibleIfNotEmpty.cs

Adding in headers

---

src/modules/launcher/Directory.Build.targets

- IncrementalClean was disabled in the PowerLauncher and Microsoft.PowerToys.Settings.UI.Runner as they were both XAML islands based projects and the increment clean step of the build target was deleting some files on every other run.
- However, the issue that was caused by this was that `Clean` could no longer be performed as we were overriding the default functionality of `IncrementalClean` with an empty increment clean target.
```
<Target Name="IncrementalClean"
DependsOnTargets="_CleanGetCurrentAndPriorFileWrites">
```
* https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2019
* https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets?view=vs-2019
This PR partially solves the issue of Clean no longer working for the …

Removing Incremental clean for Launcher

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/HotkeySettingsControlHook.cs

Fix more warnings

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/HotkeySettings.cs

Fixing a crash where if you try and pull up FZ, it crashes since it is expecting Key json object since the two processes use different implementations for JSON

Adding back in key for FZ Json

---

src/core/Microsoft.PowerToys.Settings.UI/Controls/HotkeySettingsControl.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Converters/ModuleEnabledToForegroundConverter.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/FancyZonesViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml.cs

Fixed spaces, namespace ordering, and blank lines.

fixed another set of warnings

---

doc/devdocs/run-as-admin-detection.md

Fix casing in documentation

---

README.md

adding in stable and installer to build status

---

src/modules/launcher/PowerLauncher/Helper/ResultCollection.cs
src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
src/modules/launcher/PowerLauncher/PowerLauncher.csproj
src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
src/modules/launcher/PowerLauncher/ViewModel/ResultsViewModel.cs

Reduce work on UI thread and improve list view performance.
1. https://stackoverflow.com/questions/7687000/fast-performing-and-thread-safe-observable-collection/7687108#7687108
The following optimizations are made in this PR to reduce work on UI thread : 
1. Modified `ResultCollection` data structure to support the bulk adding of results. This reduces the number of `NotifyCollectionChangedEventArgs` events argument to one per query from one per result item. 
2. Moved Result modification/adding/removing to a background thread. 
3. Reduced query delay timing to 20ms which seems to work a lot smoother now.
Manually validated that all plugins work as expected.

Improving UI performance

---

.pipelines/build.cmd
.pipelines/pipeline.user.windows.yml

CI: sign new binaries

---

.pipelines/ci/templates/build-powertoys-ci.yml

CDPx: revert parallel msbuild building also in build-powertoys-ci.yml

---

installer/PowerToysSetup/Product.wxs

Fixing installer not having images.

adjust for modules images in settings

---

.pipelines/build.cmd
.pipelines/ci/templates/build-powertoys-ci.yml

#5274 and #5275
Adding back in -m

reenabling multi-core

---

src/runner/main.cpp

Monitor process list after using RestartManager API and manually restart explorer.exe in case it didn't appear after 10s.
- manually tested when the explorer is there and not using `PowerToys.exe -report_update_success`

runner: make sure that explorer is restarted

---

src/codeAnalysis/format_sources.ps1

- clean up root dir as discussed internally
- add check for file existence to prevent false errors
- formatted some source files

chore: move codeAnalysis folder to src

---

src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml

Fixes URL redirect for a page that was moved.
Updates URL
Clicking on hyperlink leads to correct page.

Updated `Administrator mode` URL to new wiki page

---

src/runner/main.cpp

- set app id in time for download_update to use it.
- test the update locally

autoupdate: Fix updating toast

---

src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj

suppressing warning 8305

---

.github/ISSUE_TEMPLATE/feature_request.md

Fixes typo in the Feature Request template.

[Feature request.md] Fix typo

---

src/core/Microsoft.PowerToys.Settings.UnitTest/Microsoft.PowerToys.Settings.UnitTest.csproj
src/core/Microsoft.PowerToys.Settings.UnitTest/ModelsTests/BasePTModuleSettingsTest.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ModelsTests/BasePTSettingsTest.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ModelsTests/HelperTest.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ModelsTests/SettingsUtilsTests.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/UnitTestApp.xaml.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/ColorPicker.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/FancyZones.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/General.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/ImageResizer.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/KeyboardManager.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/PowerLauncherViewModelTest.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/PowerPreview.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/PowerRename.cs
src/core/Microsoft.PowerToys.Settings.UnitTest/ViewModelTests/ShortcutGuide.cs

StyleCop For Microsoft.PowerToys.Settings.UnitTest

---

README.md

0.20.1 readme

---

.pipelines/ci/templates/build-powertoys-steps.yml

CI: add installer

---

src/core/Microsoft.PowerToys.Settings.UI/Converters/ModuleEnabledToForegroundConverter.cs
src/core/Microsoft.PowerToys.Settings.UI/Interop.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/ColorPickerViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/Commands/ButtonClickCommand.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/FancyZonesViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/GeneralViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/ImageResizerViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/KeyboardManagerViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/PowerPreviewViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/ViewModels/ShortcutGuideViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/FancyZonesPage.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerLauncherPage.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerRenamePage.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/VisibleIfNotEmpty.cs

Warnings were being thrown for style cop related items.

Style cop for Settings.UI

---

src/Version.props

Now working on 0.20.2

---

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Main.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Settings.cs

Reduce results from the program plugin. 
This PR removes results below a given fraction of the maximum score from program plugin results. 
Manually validated that tests pass and program plugin removes results.

Reduce program plugin results

---

src/modules/fancyzones/dll/dllmain.cpp
src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditor.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/GridEditor.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/GridZone.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/LayoutPreview.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/CanvasLayoutModel.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/GridLayoutModel.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutModel.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/Settings.cs
src/modules/fancyzones/lib/FancyZones.cpp
src/modules/fancyzones/lib/FancyZonesData.cpp
src/modules/fancyzones/lib/Settings.cpp
src/modules/fancyzones/lib/Settings.h
src/modules/fancyzones/lib/VirtualDesktopUtils.cpp
src/modules/fancyzones/lib/WindowMoveHandler.cpp
src/modules/fancyzones/lib/ZoneSet.cpp
src/modules/fancyzones/lib/ZoneWindow.cpp
src/modules/fancyzones/lib/fancyzones.rc
src/modules/fancyzones/lib/resource.h
src/modules/fancyzones/lib/trace.cpp
src/modules/fancyzones/lib/util.cpp

Localize strings in _FancyZones_ (both library and editor project) and mark those who should not be localized.

[FancyZones] Clasify strings in FancyZones to localizable and non-localizable

---

src/tests/win-app-driver/README.md

Update Readme for the WinAppDriver tests.

update readme for WinAppDriver tests

---

src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Microsoft.Plugin.Program.UnitTests.csproj
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Programs/UWPTests.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Programs/Win32Tests.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Storage/ListRepositoryTests.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Storage/Win32ProgramRepositoryTest.cs

Getting most issues minus var renaming wrapped up.  With have another PR after this for unit tests.

[stylecop] program plugin unit tests part2

---

doc/devdocs/readme.md

Getting dev startup script to autodetect VS version

---

src/modules/launcher/Plugins/Microsoft.Plugin.Program/AddProgramSource.xaml.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Logger/ProgramLogger.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Main.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/ProgramPluginSettings.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/ApplicationActivationHelper.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/AppxPackageHelper.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/IShellLinkHelper.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/PackageCatalogWrapper.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/PackageWrapper.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/ShellLinkHelper.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWPApplication.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/Win32Program.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/PackageRepository.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/Win32ProgramFileSystemWatchers.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Storage/Win32ProgramRepository.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Views/Commands/ProgramSettingDisplay.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Views/ProgramSetting.xaml.cs

lots of whitespace / type fixes.  Braces, multiple classes in a single file and var naming mostly left.  The brace work should be its own PR as it will have a lot of small stuff

[stylecop] Run's program plugin - Whitespace and type fixes

---

src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Microsoft.Plugin.Program.UnitTests.csproj
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Programs/Win32Tests.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program.UnitTests/Storage/Win32ProgramRepositoryTest.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWP.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/UWPApplication.cs

Remaining adjustments, namely around fixing var naming violations

[stylecop] Program Plugin, last needed PR

---

src/modules/launcher/PowerLauncher/Helper/DataWebRequestFactory.cs
src/modules/launcher/PowerLauncher/Helper/ResultCollection.cs
src/modules/launcher/PowerLauncher/Helper/SingleInstance.cs
src/modules/launcher/PowerLauncher/MainWindow.xaml.cs
src/modules/launcher/PowerLauncher/PublicAPIInstance.cs
src/modules/launcher/PowerLauncher/ReportWindow.xaml.cs
src/modules/launcher/PowerLauncher/Settings.cs
src/modules/launcher/PowerLauncher/Storage/HistoryItem.cs
src/modules/launcher/PowerLauncher/Storage/QueryHistory.cs
src/modules/launcher/PowerLauncher/Storage/TopMostRecord.cs
src/modules/launcher/PowerLauncher/ViewModel/ContextMenuItemViewModel.cs
src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
src/modules/launcher/PowerLauncher/ViewModel/ResultViewModel.cs
src/modules/launcher/PowerLauncher/ViewModel/ResultsViewModel.cs
src/modules/launcher/PowerLauncher/ViewModel/SettingWindowViewModel.cs

Another round of tweaks, this will need one if not two more PRs to wrap up due to the amount of additional errors being thrown

[stylecop] PowerLauncher project

---

PowerToys.sln

This PR removes unused files in in modules/interface from the solution.
Built PT

Remove deleted files from the solution

---

README.md
doc/unofficalInstallMethods.md

Simplifying main readme and allowing us to have more community driven installers

Move alt installers to new file

---

src/modules/powerrename/lib/Helpers.cpp
src/modules/powerrename/lib/Helpers.h
src/modules/powerrename/lib/PowerRenameManager.cpp
src/modules/powerrename/unittests/PowerRenameManagerTests.cpp

Changes in the feature
* Recognize only `$f` patterns for milliseconds,.
* Handle double $ signs. Replacements have to be done before regex operation to achieve that. You can escape the feature with `$$YYYY` for ex.
* Add `$x` for all. If the number is single digit,  it won't be padded with zero.
* Add `$MMM` `$DDD` for short names of months and days of the week, `$MMMM` and `$DDDD` for full names.
* Localize day/month names.

[PowerRename] Using File Attributes Update

---

src/modules/fancyzones/lib/FancyZonesData.h
src/modules/fancyzones/tests/UnitTests/FancyZonesSettings.Spec.cpp
src/modules/fancyzones/tests/UnitTests/ZoneSet.Spec.cpp
src/modules/fancyzones/tests/UnitTests/ZoneWindow.Spec.cpp

Updated unit tests, added issue #6064.
* `ZoneWindow` tests refactored.
* `ZoneSet` tests: updated borders check based on the zone type.
* `FancyZonesSettings`: updated config tests.

[FancyZones] Failing unit tests update

---

src/common/common.cpp
src/common/common.h
src/modules/fancyzones/lib/FancyZones.cpp
src/modules/fancyzones/lib/JsonHelpers.cpp
src/modules/fancyzones/lib/WindowMoveHandler.cpp
src/modules/fancyzones/lib/ZoneSet.cpp
src/modules/fancyzones/lib/ZoneWindow.cpp
src/modules/fancyzones/lib/util.cpp
src/modules/fancyzones/lib/util.h
src/modules/fancyzones/tests/UnitTests/JsonHelpers.Tests.cpp
src/modules/fancyzones/tests/UnitTests/Util.Spec.cpp
src/modules/shortcut_guide/shortcut_guide.cpp

Move module-related methods from common to modules.
Refactor fancyzoneslib/util.[h|cpp].

Refactor common and fancyzones/utils

---

src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/SearchHelper/OleDBSearch.cs

This PR adds a missing `!` to a condition which caused indexer plugin to return no results.

Added missing ! to condition check in Indexer Plugin

---

tools/CleanUp_tool/CleanUp_tool.sln
tools/CleanUp_tool/CleanUp_tool.vcxproj
tools/CleanUp_tool/CleanUp_tool.vcxproj.filters
tools/CleanUp_tool/main.cpp
tools/CleanUp_tool_powershell_script/CleanUp_tool.ps1

Clean Up tool to clean PowerToys data
Clean Up tool to clean PowerToys settings inside %AppData% and registry
- Installed different versions of PowerToys
- Changed some settings
- Runned Clean Up tool
- Checked PowerToys settings

Clean Up tool

---

src/Version.props

Increase the version number to 0.21.0

Update version to 0.21.0

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/ViewModels/FancyZonesViewModel.cs

Changed format for color values in the setting file.
Change any color in FancyZones settings, verify that in the settings file it was saved in RGB format.

[FancyZones] Convert ARGB color values to RGB

---

src/Version.props

Update version to 0.21.1

---

src/Version.props

Update version to 0.21.2 (for internal dev builds)

Now working on 0.21.2

---

README.md

0.21 readme

---

.github/ISSUE_TEMPLATE/config.yml

See #6312 
Look on new issue page

Implement #6312

---

src/common/updating/updating.cpp
src/common/updating/updating.h
src/core/Microsoft.PowerToys.Settings.UI.Lib/ViewModels/GeneralViewModel.cs
src/core/Microsoft.PowerToys.Settings.UI.Runner/MainWindow.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI.Runner/Program.cs
src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs
src/core/Microsoft.PowerToys.Settings.UI/Views/ShellPage.xaml.cs
src/runner/settings_window.cpp
src/runner/update_utils.cpp
src/runner/update_utils.h

A string appears after users click the "Check for updates" button.
Besides the temp string added a handler for received IPC messages and a list of actions to update view models.
Open settings and click `Check for updates`.

[Settings] Temporary string showing latest available version

---

doc/devdocs/tools.md
tools/monitor_info_report/main.vcxproj
tools/monitor_info_report/monitor-report-info.cpp
tools/monitor_info_report/monitor_info_report.sln

tools: monitor report info

---

doc/devdocs/readme.md

docs: add bootstrapper cmd args description

---

doc/devdocs/readme.md

Fix a grammatical error in readme.md under doc/devdocs.
Grammatical error fix to readme.md under doc/devdocs.

devdocs: readme: fix grammar

---

README.md

updated .exe installer version number

Updated .exe installer version number from 0.21.0 to 0.21.1

---

tools/monitor_info_report/print_wmi_monitor_info.ps1

- get monitor serial number/instance name/user friendly name by WMI means
- print to log file and stdout

tools: add wmi monitor info powershell script

---

.pipelines/pipeline.user.windows.yml

Add missing symbols for the .exe installer.

[CDPx] add bootstrapper symbols

---

src/modules/keyboardmanager/dll/Resources.resx
src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp
src/modules/keyboardmanager/ui/EditShortcutsWindow.cpp
src/modules/keyboardmanager/ui/KeyDropDownControl.cpp
src/modules/keyboardmanager/ui/ShortcutControl.cpp
src/modules/keyboardmanager/ui/ShortcutControl.h
src/modules/keyboardmanager/ui/SingleKeyRemapControl.cpp
src/modules/keyboardmanager/ui/pch.h

The following changes fixes the Accessibility issues of the KBM powerToy (C++ code).
1. Accessible names have been set for all the buttons in code (Type, +, delete button).
2. Accessible names have been added to the combo boxes.
3. Accessible names have to added to the font icons (->) which indicate remapping.
The following issues are known-
1. On running accesisibility insights on the KBM windows, we would face this issue that `the names of sibling elements are the same`. This issue would no longer exist once we switch to a list view as mentioned in issue #2170 
2. ~The windows narrator issue with font icons still exists. The font icons are being read by NVDA though. Communicating with the …

Fix KBM Accessibility issues

---

src/modules/fancyzones/lib/FancyZones.cpp
src/modules/fancyzones/lib/WindowMoveHandler.cpp
src/modules/fancyzones/lib/WindowMoveHandler.h
src/modules/fancyzones/lib/ZoneSet.cpp
src/modules/fancyzones/lib/ZoneSet.h
src/modules/fancyzones/lib/ZoneWindow.cpp
src/modules/fancyzones/lib/ZoneWindow.h

Not much to say that's not already contained in the title.
Added members and methods to support this operation.
The shortcut keys, variable and method names and code readability may require some feedback.
Tested with a large grid layout. Unit tests passed.

[FancyZones] Use Ctrl+Win+Alt+arrows to Expand/shrink windows to adjacent zones

---

src/core/Microsoft.PowerToys.Settings.UI.Lib/SettingsUtils.cs

Adding Trim('\0') to overcome possible NTFS file corruption.
Look at issue https://github.com/microsoft/PowerToys/issues/6413 you'll see the file has a large sum of \0 to fill up a 4096 byte buffer for writing to disk
This, while not totally ideal, does work around the problem by trimming the end.
The file itself did write the content correctly but something is off with the actual end of the file, hence the 0x00 bug

Fixing 0x00 file load issue

---

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/core/Microsoft.PowerToys.Settings.UI/Styles/TextBlock.xaml
src/core/Microsoft.PowerToys.Settings.UI/Views/PowerPreviewPage.xaml

Adjusting header and text for File explorer adjustments in settings

tweaking text and adding in headers

---

src/settings/main.cpp

FIx a typo in the URL pointing to the github bug report page.

Fix typo in URL

---

src/common/ManagedTelemetry/Telemetry/Events/EventBase.cs
src/common/ManagedTelemetry/Telemetry/Events/IEvent.cs
src/common/ManagedTelemetry/Telemetry/Telemetry.csproj
src/common/Telemetry/TelemetryBase.cs

Getting telem project with FxCop

[FxCop] Telemetry.csproj

---

src/common/interop-tests/InteropTests.cs
src/common/interop-tests/Microsoft.Interop.Tests.csproj

getting interop tests to pass and use FxCop

[FxCop] Interop tests

---

doc/devdocs/readme.md

Updating docs and wiki for new args

Tweak docs for installer

---

src/common/ManagedTelemetry/Telemetry/Events/EventBase.cs
src/common/ManagedTelemetry/Telemetry/Events/IEvent.cs
src/common/ManagedTelemetry/Telemetry/Telemetry.csproj
src/common/Telemetry/TelemetryBase.cs

Reverts microsoft/PowerToys#6642
- Added a warning comment on the TelemetryBase.cs file
Validation on build farm https://github-private.visualstudio.com/microsoft/_build/results?buildId=11890&view=results

Revert "[FxCop] Telemetry.csproj"

---

src/modules/fancyzones/dll/dllmain.cpp
src/modules/fancyzones/lib/FancyZones.cpp
src/modules/fancyzones/lib/FancyZones.h
src/modules/fancyzones/lib/FancyZonesData.cpp
src/modules/fancyzones/lib/Resources.resx
src/modules/fancyzones/lib/Settings.cpp
src/modules/fancyzones/tests/UnitTests/FancyZones.Spec.cpp
src/runner/main.cpp
src/runner/powertoy_module.cpp

Make initial steps in exception handling improvements within `FancyZones`. Display message box once exception occurs, and depending on error, close PowerToys or proceed if we can recover from it.

[FancyZones] Initial improvements in FancyZones exception handling

---

src/core/Microsoft.PowerToys.Settings.UI/Microsoft.PowerToys.Settings.UI.csproj

Updated WinUI to the september pre-release released yesterday. Validated that the update fixes #6022 

Updated winUI version in Settings.UI project

---

src/Version.props

Update master version to 0.23.1
Hopefully this will be the last time we do this.

Now working on 0.23.1

---

README.md

0.23 readme update

---

README.md

ReadMe / Video Overview
* [x ] Applies to ALL
* [x ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/PowerToys) and sign the CLA

Add link to the PowerToys ep of Tabs vs Spaces

---

src/modules/fancyzones/editor/FancyZonesEditor/App.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/LayoutModel.cs
src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.Designer.cs
src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx

Localize strings in App.xaml.cs (new exception handler with crash reporting).

[FancyZones] Localize strings in FancyZones editor

---

src/core/Microsoft.PowerToys.Settings.UI/loc/pl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPicker/loc/pl/src/modules/colorPicker/ColorPicker/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/pl/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/dll/loc/pl/src/modules/imageresizer/dll/Resources.resx.lcl
src/modules/imageresizer/ui/loc/pl/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/pl/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Microsoft.Launcher/loc/pl/src/modules/launcher/Microsoft.Launcher/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/loc/pl/src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/pl/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/loc/pl/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Program/loc/pl/src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Shell/loc/pl/src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Uri/loc/pl/src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/loc/pl/src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/pl/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/powerrename/dll/loc/pl/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/ui/loc/pl/src/modules/powerrename/ui/Resources.resx.lcl
src/modules/previewpane/MarkdownPreviewHandler/loc/pl/src/modules/previewpane/MarkDownPreviewHandler/Properties/Resources.resx.lcl
src/modules/previewpane/SvgPreviewHandler/loc/pl/src/modules/previewpane/SvgPreviewHandler/Resource.resx.lcl
src/modules/previewpane/powerpreview/loc/pl/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/shortcut_guide/loc/pl/src/modules/shortcut_guide/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201006230551662 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201006230551662 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/ko/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPicker/loc/ko/src/modules/colorPicker/ColorPicker/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ko/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/ko/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/dll/loc/ko/src/modules/imageresizer/dll/Resources.resx.lcl
src/modules/imageresizer/ui/loc/ko/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/ko/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Microsoft.Launcher/loc/ko/src/modules/launcher/Microsoft.Launcher/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/loc/ko/src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/ko/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/loc/ko/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Program/loc/ko/src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Shell/loc/ko/src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Uri/loc/ko/src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/loc/ko/src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/ko/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/powerrename/dll/loc/ko/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/ui/loc/ko/src/modules/powerrename/ui/Resources.resx.lcl
src/modules/previewpane/MarkdownPreviewHandler/loc/ko/src/modules/previewpane/MarkDownPreviewHandler/Properties/Resources.resx.lcl
src/modules/previewpane/powerpreview/loc/ko/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/shortcut_guide/loc/ko/src/modules/shortcut_guide/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201007110553169 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201007110553169 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/hu/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPicker/loc/hu/src/modules/colorPicker/ColorPicker/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/hu/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/hu/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/dll/loc/hu/src/modules/imageresizer/dll/Resources.resx.lcl
src/modules/imageresizer/ui/loc/hu/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/hu/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Microsoft.Launcher/loc/hu/src/modules/launcher/Microsoft.Launcher/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/loc/hu/src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/hu/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/loc/hu/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Program/loc/hu/src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Shell/loc/hu/src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/loc/hu/src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/hu/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/powerrename/dll/loc/hu/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/ui/loc/hu/src/modules/powerrename/ui/Resources.resx.lcl
src/modules/previewpane/MarkdownPreviewHandler/loc/hu/src/modules/previewpane/MarkDownPreviewHandler/Properties/Resources.resx.lcl
src/modules/previewpane/SvgPreviewHandler/loc/hu/src/modules/previewpane/SvgPreviewHandler/Resource.resx.lcl
src/modules/previewpane/powerpreview/loc/hu/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/shortcut_guide/loc/hu/src/modules/shortcut_guide/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201008110549338 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201008110549338 to master

---

src/modules/keyboardmanager/dll/loc/hu/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/hu/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl

Fixes the build farm failing due to a bad merge between the two PRs from csigs.
Validating on build farm https://github-private.visualstudio.com/microsoft/_build/results?buildId=13333&view=results

Fix build farm failing due to localization

---

src/core/Microsoft.PowerToys.Settings.UI/loc/es/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPicker/loc/es/src/modules/colorPicker/ColorPicker/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/es/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/it/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/zh-Hans/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/es/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/dll/loc/es/src/modules/imageresizer/dll/Resources.resx.lcl
src/modules/imageresizer/ui/loc/es/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/es/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/it/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/zh-Hans/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/es/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/it/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/zh-Hans/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/loc/es/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Shell/loc/es/src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx.lcl
src/modules/powerrename/dll/loc/es/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/ui/loc/es/src/modules/powerrename/ui/Resources.resx.lcl
src/modules/previewpane/MarkdownPreviewHandler/loc/es/src/modules/previewpane/MarkDownPreviewHandler/Properties/Resources.resx.lcl
src/modules/shortcut_guide/loc/es/src/modules/shortcut_guide/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201010110548113 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201010110548113 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/ko/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/sv/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPicker/loc/sv/src/modules/colorPicker/ColorPicker/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/sv/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/sv/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/dll/loc/sv/src/modules/imageresizer/dll/Resources.resx.lcl
src/modules/imageresizer/ui/loc/sv/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/sv/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Microsoft.Launcher/loc/sv/src/modules/launcher/Microsoft.Launcher/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/loc/sv/src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/ko/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/sv/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/loc/sv/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Program/loc/sv/src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Shell/loc/sv/src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Uri/loc/sv/src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/loc/sv/src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/sv/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/powerrename/dll/loc/sv/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/ui/loc/sv/src/modules/powerrename/ui/Resources.resx.lcl
src/modules/previewpane/MarkdownPreviewHandler/loc/sv/src/modules/previewpane/MarkDownPreviewHandler/Properties/Resources.resx.lcl
src/modules/previewpane/SvgPreviewHandler/loc/sv/src/modules/previewpane/SvgPreviewHandler/Resource.resx.lcl
src/modules/previewpane/powerpreview/loc/ko/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/previewpane/powerpreview/loc/pl/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/previewpane/powerpreview/loc/sv/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/shortcut_guide/loc/sv/src/modules/shortcut_guide/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201012110556037 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201012110556037 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/de/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/zh-Hant/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPicker/loc/zh-Hant/src/modules/colorPicker/ColorPicker/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/zh-Hant/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/zh-Hant/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/dll/loc/zh-Hant/src/modules/imageresizer/dll/Resources.resx.lcl
src/modules/imageresizer/ui/loc/zh-Hant/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/zh-Hant/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Microsoft.Launcher/loc/zh-Hant/src/modules/launcher/Microsoft.Launcher/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/loc/zh-Hant/src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/pl/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/zh-Hant/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/loc/zh-Hant/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Program/loc/zh-Hant/src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Shell/loc/zh-Hant/src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Uri/loc/zh-Hant/src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/loc/zh-Hant/src/modules/launcher/Plugins/Microsoft.Plugin.WindowWalker/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/zh-Hant/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/powerrename/dll/loc/zh-Hant/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/ui/loc/zh-Hant/src/modules/powerrename/ui/Resources.resx.lcl
src/modules/previewpane/MarkdownPreviewHandler/loc/zh-Hant/src/modules/previewpane/MarkDownPreviewHandler/Properties/Resources.resx.lcl
src/modules/previewpane/SvgPreviewHandler/loc/zh-Hant/src/modules/previewpane/SvgPreviewHandler/Resource.resx.lcl
src/modules/previewpane/powerpreview/loc/de/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/previewpane/powerpreview/loc/pl/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/previewpane/powerpreview/loc/zh-Hant/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/shortcut_guide/loc/zh-Hant/src/modules/shortcut_guide/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201012230535949 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201012230535949 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/ja/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl

LEGO: Pull request from lego/hb_2939_20201014110529105 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201014110529105 to master

---

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/core/Microsoft.PowerToys.Settings.UI/Views/ImageResizerPage.xaml

Adding placeholder text labels.
FZ:
Image Resizer:

[Settings] Added placeholder labels

---

.gitmodules
PowerToys.sln
deps/cxxopts.props
deps/spdlog.props
installer/PowerToysBootstrapper/PowerToysBootstrapper.sln
installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp
installer/PowerToysBootstrapper/bootstrapper/bootstrapper.vcxproj
installer/PowerToysBootstrapper/bootstrapper/pch.h
src/logging/logging.vcxproj
src/logging/logging.vcxproj.filters

- add cxxopts and spdlog libraries as git submodules
- implement cmd flag for log severity
- add debug and error messages
You can test it by cloning the branch with `git clone --single-branch --branch bootstrapper_logging --recurse-submodules https://github.com/yuyoyuppe/PowerToys.git`. After building, run `PowerToysSetup-0.23.1-x64.exe --log_level debug`. You can find **powertoys-bootstrapper-0.23.1.log**  and **powertoys-bootstrapper-msi-0.23.1.log** files in the directory you've launched the bootstrapper from.
- test with various log levels
- tested with silent mode

bootstrapper: implement logging support

---

doc/devdocs/logging.md
src/logging/logging.vcxproj

- use a correct Windows SDK version for logging project
- quick start on how to use `spdlog` for other projects

Logging improvements

---

src/common/updating/updating.cpp

autoupdate: ignore local builds

---

src/modules/keyboardmanager/ui/KeyDropDownControl.cpp

Fix accessibility bug for dropdown's popup
Check if dropdown's popups are accessible for the narrator.

Fix dropdown popup narrator bug

---

installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp

... defaults to current dir
- try (non)existing log paths and skipping it

bootstrapper: add cmd argument for custom log location

---

NOTICE.md

update notice for spdlog and cxxotps

---

deps/cxxopts.props
deps/restore_git_submodules.props
deps/spdlog.props

now we checkout submodules when its corresponding .props is referenced
delete submodules dirs and rebuild main/installer solution

checkout git submodules as PowerToys.sln prebuild action

---

doc/devdocs/settings.md

[Docs] Fix 404 error settings.md

---

src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/ShellLinkHelper.cs

This PR handles exception thrown in the call to `IShellLinkW.GetDescription` function, which fetches Win32 program description.
Call to `IShellLinkW.GetDescription` function throws `HRESULT` with the message `Error HRESULT E_FAIL has been returned from a call to a COM component`. Since `E_FAIL` corresponds to an unspecified error, we do not get an explicit cause of the error. This error was handled at the end of `LnkPrograms` functions, preventing indexing of any program throwing this exception.
In this PR we handle this error by setting description to empty. This would ensure that the program is indexed and shows up in PT Run. The only downside would be that it's description score would not be counted while scoring a result.
Manually validated that Windows Media Player is shown in PT …

Handle error in fetching Win32 program description

---

src/core/Microsoft.PowerToys.Settings.UI/loc/cs/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/de/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/es/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/fr/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/hu/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/it/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/ja/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/ko/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/nl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-BR/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-PT/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/ru/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/sv/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/tr/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/zh-Hans/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/zh-Hant/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl

LEGO: Pull request from lego/hb_2939_20201028145308375 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201028145308375 to master

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/translation_issue.md
README.md

0.25 readme update and issue #7616

0.25 readme & loc translation issue template

---

installer/PowerToysBootstrapper/bootstrapper/Resources.resx
installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp
src/action_runner/Resources.resx
src/action_runner/action_runner.cpp
src/common/common.cpp
src/common/common.h
src/common/notifications.cpp
src/common/notifications.h
src/common/updating/notifications.cpp
src/common/updating/notifications.h
src/common/updating/updating.cpp
src/common/updating/updating.h
src/runner/LocProject.json
src/runner/Resources.resx
src/runner/general_settings.cpp
src/runner/main.cpp
src/runner/settings_window.cpp
src/runner/update_utils.cpp
tools/build/convert-resx-to-rc.ps1

- refactored update/notifications API to accept localized strings struct
- moved out all remaining localized strings to their corresponding projects
- make rc build script less noisy
- installed PT using bootstrapper
- checked for updates (seen updating-related toasts)

Support localized strings in common project

---

README.md

We refer to Color Picker (with spacing) throughout the PT app. Readme mentioned it as ColorPicker.

[ReadMe] Fixed Color Picker spacing.

---

src/modules/colorPicker/UnitTest-ColorPickerUI/Helpers/ColorHelperTest.cs
src/modules/colorPicker/UnitTest-ColorPickerUI/UnitTest-ColorPickerUI.csproj

Fix project UnitTest-ColorPickerUI
Fix project UnitTest-ColorPickerUI
Unit test running in Visual Studio

Fix test project UnitTest-ColorPickerUI

---

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw

Added in comments for loc as well.

Change "Module overview" to "Learn more" in settings menu

---

src/modules/imageresizer/ui/App.xaml
src/modules/imageresizer/ui/Views/InputPage.xaml
src/modules/imageresizer/ui/Views/VisibilityBoolConverter.cs

Had to bind to `Visibility`, since binding `ShowAdvancedSettings` didn't produce any effect.
pressed Tab multiple times

ImageResizer: skip Settings tab focus when hidden

---

src/modules/imageresizer/ui/App.xaml

Image resizer: fix Color contrast of 'Resize Your Pictures'

---

installer/PowerToysSetup/Product.wxs

With the System.IO.Abstraction lib being added in, we didn't properly add it to the WSX.

added in abstraction to WSX

---

src/core/Microsoft.PowerToys.Settings.UI/loc/hu/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/nl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/lib/loc/de/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/lib/loc/it/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/lib/loc/pl/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/lib/loc/sv/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/ui/loc/nl/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/nl/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/loc/hu/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/loc/pt-PT/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/de/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/it/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/pl/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/sv/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/previewpane/powerpreview/loc/nl/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/shortcut_guide/loc/nl/src/modules/shortcut_guide/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201102230612006 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201102230612006 to master

---

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw

Tweaked from zone to layout editor and added in comments

Change to FancyZone Layout Editor and added in comments

---

src/settings-web/package-lock.json
src/settings-web/package.json

Update the npm packages used to build the settings-web project

[settings-web] Update packages

---

.github/actions/spell-check/expect.txt

hmon
IMonitor
scrollviewer
VDId

Additional spelling ignores

---

.github/ISSUE_TEMPLATE/translation_issue.md

updating tag to add additional clarity for what is a translation issue versus just the larger localization effort

adding Issue-Translation tag to translation issue template

---

src/core/Microsoft.PowerToys.Settings.UI/loc/pl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-PT/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/imageresizer/ui/loc/pt-PT/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/previewpane/powerpreview/loc/pt-PT/src/modules/previewpane/powerpreview/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201106230530020 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201106230530020 to master

---

src/modules/fancyzones/editor/FancyZonesEditor/Models/Settings.cs
src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.Designer.cs
src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx

Localize names of predefined layouts.
Open PowerToys in non-english region and verify names of predefined layotus.

[FancyZones] Localize names of predefined layotus

---

installer/PowerToysBootstrapper/bootstrapper/loc/it/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
src/action_runner/loc/it/src/runner/Resources.resx.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/it/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/it/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/powerrename/ui/loc/it/src/modules/powerrename/ui/Resources.resx.lcl
src/runner/loc/it/src/action_runner/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201108230556187 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201108230556187 to master

---

installer/PowerToysBootstrapper/bootstrapper/loc/pt-PT/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
src/action_runner/loc/pt-PT/src/action_runner/Resources.resx.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/cs/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/ko/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/nl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-PT/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/sv/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pt-PT/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/sv/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/powerrename/dll/loc/cs/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/dll/loc/ko/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/dll/loc/nl/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/dll/loc/pl/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/ui/loc/pt-PT/src/modules/powerrename/ui/Resources.resx.lcl
src/modules/shortcut_guide/loc/de/src/modules/shortcut_guide/Resources.resx.lcl
src/modules/shortcut_guide/loc/sv/src/modules/shortcut_guide/Resources.resx.lcl
src/runner/loc/pt-PT/src/runner/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201111110613998 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201111110613998 to master

---

src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/core/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml

added made with love

---

src/modules/fancyzones/editor/FancyZonesEditor/loc/es/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/it/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201113000515080 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201113000515080 to master

---

src/modules/fancyzones/editor/FancyZonesEditor/loc/de/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ja/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/nl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/zh-Hant/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201113120703275 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201113120703275 to master

---

src/modules/fancyzones/lib/ZoneWindowDrawing.cpp

There are some reports of ZoneWindowDrawing instances failing to initialize. This refactoring should make debugging that easier.
Run FZ and make sure it works.

[FancyZones] Refactor a function in ZoneWindowDrawing

---

src/core/Microsoft.PowerToys.Settings.UI/loc/de/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/es/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/it/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/ja/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-BR/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/tr/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/zh-Hans/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/zh-Hant/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/hu/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pt-BR/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pt-PT/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ru/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/tr/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/runner/loc/ru/src/runner/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201114000606270 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201114000606270 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/cs/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/nl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/cs/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201114120538945 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201114120538945 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/ko/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-PT/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ko/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201116000536744 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201116000536744 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/sv/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/powerrename/dll/loc/sv/src/modules/powerrename/dll/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201116120631658 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201116120631658 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/fr/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/ru/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/cs/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/de/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/es/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/fr/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/hu/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/it/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/nl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pt-PT/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ru/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/zh-Hans/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/zh-Hant/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201117000533444 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201117000533444 to master

---

src/core/Microsoft.PowerToys.Settings.UI.Library/ColorPickerProperties.cs
src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/core/Microsoft.PowerToys.Settings.UI/Views/ColorPickerPage.xaml
src/modules/colorPicker/ColorPickerUI/Properties/Resources.Designer.cs
src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx

Suggested v2 WPF color picker adjustments

---

src/core/Microsoft.PowerToys.Settings.UI/loc/hu/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/hu/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/cs/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/de/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/es/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/fr/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/hu/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/it/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/ja/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/ko/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/nl/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/pl/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/pt-BR/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/pt-PT/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/ru/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/sv/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/tr/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/zh-Hans/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/zh-Hant/src/modules/imageresizer/ui/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201118000548825 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201118000548825 to master

---

src/common/logger/logger.cpp
src/common/logger/logger.h
src/common/logger/logger_settings.h
src/modules/launcher/Microsoft.Launcher/dllmain.cpp
src/runner/main.cpp

Improvements for runner logging.
- Add not localizable comment to every log function
- Use dedicated folder RunnerLogs
- Use Logs folder for PT Run
- Rename files to runner-log.txt and launcher-log.txt
- Try to add an option for keeping at most 30 log files

Adjustments for runner process logging

---

src/core/Microsoft.PowerToys.Settings.UI.UnitTests/BackwardsCompatibility/BackCompatTestProperties.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/Microsoft.PowerToys.Settings.UI.UnitTests.csproj
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/Mocks/IIOProviderMocks.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/Mocks/ISettingsUtilsMocks.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ModelsTests/BasePTModuleSettingsTest.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ModelsTests/SettingsRepositoryTest.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ModelsTests/SettingsUtilsTests.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/ColorPicker.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/FancyZones.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/General.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/ImageResizer.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/PowerLauncherViewModelTest.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/PowerPreview.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/PowerRename.cs
src/core/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/ShortcutGuide.cs

Getting StyleCop with Microsoft.PowerToys.Settings.UI.UnitTests.  Mostly whitespace changes

StyleCop Microsoft.PowerToys.Settings.UI.UnitTests 

---

.pipelines/ci/ci.yml

See #8105 
Remove stable part of the build status table in the README

CI on the stable branch as well

---

src/core/Microsoft.PowerToys.Settings.UI/loc/cs/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/de/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/es/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/fr/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/nl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-BR/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/ru/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/cs/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/de/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/es/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/fr/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/nl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pt-BR/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ru/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/cs/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/de/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/es/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/fr/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/ko/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/nl/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/pl/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/ru/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/tr/src/modules/imageresizer/ui/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201119000611307 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201119000611307 to master

---

src/common/keyboard_layout.cpp

- `ToUnicodeEx` returns -1 for dead characters, which we still could show.
- don't allocate keystates
- refactor unicode mapping into a function
- Win+` for ENG INTL/US, Win+Ё for Russian

FZ: fix keyboard layout mapping for dead characters

---

src/core/Microsoft.PowerToys.Settings.UI/loc/ja/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/ko/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/sv/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/tr/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/zh-Hans/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ja/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ko/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/sv/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/tr/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/zh-Hans/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/ja/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/zh-Hans/src/modules/imageresizer/ui/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201119120652245 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201119120652245 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/it/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-PT/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/it/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pt-PT/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/sv/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/hu/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/it/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/pt-PT/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/imageresizer/ui/loc/sv/src/modules/imageresizer/ui/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201120000551890 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201120000551890 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/ru/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/cs/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/de/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/es/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/fr/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/hu/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/it/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ja/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ko/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/nl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pl/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pt-BR/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pt-PT/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ru/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/sv/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/tr/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/zh-Hans/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/zh-Hant/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201120120553737 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201120120553737 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/hu/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/sv/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/hu/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/sv/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201121000545634 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201121000545634 to master

---

src/modules/colorPicker/UnitTest-ColorPickerUI/UnitTest-ColorPickerUI.csproj

specify unittest platform explicitly.
- reopen .sln

colorpicker: fix .sln issue with unittest project

---

src/core/Microsoft.PowerToys.Settings.UI/loc/ko/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/sv/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/zh-Hans/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPickerUI/loc/ko/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/colorPicker/ColorPickerUI/loc/sv/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201123120634392 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201123120634392 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/de/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/es/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/zh-Hant/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPickerUI/loc/de/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/colorPicker/ColorPickerUI/loc/es/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/colorPicker/ColorPickerUI/loc/zh-Hant/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201124000528125 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201124000528125 to master

---

src/common/logger/logger_settings.h
src/modules/shortcut_guide/ShortcutGuideLogger.cpp
src/modules/shortcut_guide/ShortcutGuideLogger.h
src/modules/shortcut_guide/shortcut_guide.cpp
src/modules/shortcut_guide/shortcut_guide.vcxproj

Logs for shortcut guide
- Add new class ShortcutGuideLogger
- One should call the static method `GetLogger` to retrieve the logger 
- The Logger is initialized in `OverlayWindow` constructor.

shortcut guide logs

---

src/modules/launcher/Wox.Plugin/ToolTipData.cs

No strings to localize. Just one to be marked with DO NOT LOCALIZE

[Wox.Plugin] Mark string with DO NOT LOCALIZE

---

installer/PowerToysBootstrapper/bootstrapper/loc/cs/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/de/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/es/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/nl/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/pl/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
src/action_runner/loc/cs/src/action_runner/Resources.resx.lcl
src/action_runner/loc/de/src/action_runner/Resources.resx.lcl
src/action_runner/loc/es/src/action_runner/Resources.resx.lcl
src/action_runner/loc/nl/src/action_runner/Resources.resx.lcl
src/action_runner/loc/pl/src/action_runner/Resources.resx.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/fr/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-BR/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPickerUI/loc/fr/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/colorPicker/ColorPickerUI/loc/pt-BR/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/runner/loc/cs/src/runner/Resources.resx.lcl
src/runner/loc/de/src/runner/Resources.resx.lcl
src/runner/loc/es/src/runner/Resources.resx.lcl
src/runner/loc/nl/src/runner/Resources.resx.lcl
src/runner/loc/pl/src/runner/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201125000600534 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201125000600534 to master

---

src/common/logger/logger_settings.h
src/modules/fancyzones/dll/FancyZonesModule.vcxproj
src/modules/fancyzones/dll/dllmain.cpp
src/modules/fancyzones/lib/FancyZonesLib.vcxproj
src/modules/fancyzones/lib/FancyZonesLogger.cpp
src/modules/fancyzones/lib/FancyZonesLogger.h

Logs for fancy zones
- Add new class FancyZonesLogger
- One should call the static method `GetLogger` to retrieve the logger 
- The Logger is initialized in `FancyZonesModule` PowerToy interface.

added logs to fancy zones

---

installer/PowerToysBootstrapper/bootstrapper/loc/it/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/ja/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/ko/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
src/action_runner/loc/it/src/action_runner/Resources.resx.lcl
src/action_runner/loc/ja/src/action_runner/Resources.resx.lcl
src/action_runner/loc/ko/src/action_runner/Resources.resx.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/it/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/nl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPickerUI/loc/it/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/colorPicker/ColorPickerUI/loc/nl/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/runner/loc/it/src/runner/Resources.resx.lcl
src/runner/loc/ja/src/runner/Resources.resx.lcl
src/runner/loc/ko/src/runner/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201125120624164 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201125120624164 to master

---

installer/PowerToysBootstrapper/bootstrapper/loc/pt-BR/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/pt-PT/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/ru/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
src/action_runner/loc/pt-BR/src/action_runner/Resources.resx.lcl
src/action_runner/loc/pt-PT/src/action_runner/Resources.resx.lcl
src/action_runner/loc/ru/src/action_runner/Resources.resx.lcl
src/runner/loc/pt-BR/src/runner/Resources.resx.lcl
src/runner/loc/pt-PT/src/runner/Resources.resx.lcl
src/runner/loc/ru/src/runner/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201127000526832 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201127000526832 to master

---

src/core/Microsoft.PowerToys.Settings.UI/loc/pt-PT/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/cs/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/pt-PT/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/dll/loc/pt-PT/src/modules/imageresizer/dll/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/pt-PT/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201128000545286 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201128000545286 to master

---

installer/PowerToysBootstrapper/bootstrapper/loc/sv/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
src/action_runner/loc/sv/src/action_runner/Resources.resx.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/ja/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/runner/loc/sv/src/runner/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201126120617106 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201126120617106 to master

---

installer/PowerToysBootstrapper/bootstrapper/loc/ko/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/ko/src/modules/keyboardmanager/dll/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201130074650503 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201130074650503 to master

---

installer/PowerToysBootstrapper/bootstrapper/loc/cs/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/de/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/es/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/hu/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/nl/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/pl/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/pt-BR/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/pt-PT/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/tr/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/zh-Hant/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
src/action_runner/loc/zh-Hant/src/action_runner/Resources.resx.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/cs/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/hu/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/it/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pl/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/pt-BR/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/core/Microsoft.PowerToys.Settings.UI/loc/sv/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/colorPicker/ColorPickerUI/loc/cs/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/colorPicker/ColorPickerUI/loc/ja/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/colorPicker/ColorPickerUI/loc/pl/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/colorPicker/ColorPickerUI/loc/tr/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/pt-BR/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/hu/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/lib/loc/pt-BR/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/dll/loc/hu/src/modules/imageresizer/dll/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/it/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/runner/loc/zh-Hant/src/runner/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201201033406876 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201201033406876 to master

---

.github/actions/spell-check/expect.txt
README.md

0.27 readme update

---

.github/actions/spell-check/expect.txt
README.md

Updating description of Color Picker

[Color Picker] Update README.md with updated module description

---

src/modules/fancyzones/lib/FancyZones.cpp
src/modules/fancyzones/lib/JsonHelpers.cpp

Added logs on editor exit event and in temp JSON files parsing.

[FancyZones] Logging on the editor exit event

---

src/modules/fancyzones/lib/FancyZones.cpp
src/modules/fancyzones/lib/util.cpp
src/modules/fancyzones/lib/util.h

Same as https://github.com/microsoft/PowerToys/pull/8451 for the `stable` branch.

[FancyZones] Obtain device id (stable)

---

src/modules/colorPicker/UnitTest-ColorPickerUI/Helpers/ColorConverterTest.cs
src/modules/colorPicker/UnitTest-ColorPickerUI/Helpers/ColorRepresentationHelperTest.cs
src/modules/colorPicker/UnitTest-ColorPickerUI/UnitTest-ColorPickerUI.csproj

Adding in FxCop.  All tests pass

FxCop to UnitTests for ColorPicker

---

src/common/updating/dotnet_installation.cpp

install: update the installed dotnet version

---

src/modules/colorPicker/ColorPickerUI/Helpers/AppStateHandler.cs
src/modules/colorPicker/ColorPickerUI/Helpers/ClipboardHelper.cs
src/modules/colorPicker/ColorPickerUI/Keyboard/KeyboardMonitor.cs
src/modules/colorPicker/ColorPickerUI/NativeMethods.cs

Cherry pick of #8376  into stable

color picker freeze hotfix into stable

---

.pipelines/ci/templates/build-powertoys-steps.yml

Enable the PowerRename tests in CI since they are now working as expected.

[CI] enable PowerRename tests

---

src/common/logger/logger.cpp

use spdlog's msvc sink if we detect that the app is launched with a debugger attached.
launch FZ from VS and see output window

logging: support msvc debug window output

---

.github/actions/spell-check/expect.txt
COMMUNITY.md

Adding in Davide and InVEST team to community.md

---

tools/localization/move_uwp_resources.ps1

- update hardcorded localization paths

Fix CDPX build

---

.github/actions/spell-check/expect.txt
.github/workflows/codeql-analysis.yml

This PR adds a CI workflow which runs CodeQL to analyze the project for security vulnerabilities. 
This pull request includes a simple GitHub Actions build. It includes a special case for the C# and C++ builds which calls the existing build scripts. These steps could be switched out as appropriate for another build technique in the future, though!
I ran this in my own fork, and you can do so as well. If you look at the Actions runs, you'll see the build runs. Then you can look at the Security tab to view the findings.

Add CodeQL Analysis

---

.github/actions/spell-check/expect.txt

Remove redundant spelling

---

src/core/Microsoft.PowerToys.Settings.UI/loc/ja/src/core/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/modules/fancyzones/editor/FancyZonesEditor/loc/ja/src/modules/fancyzones/editor/FancyZonesEditor/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/ja/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/imageresizer/dll/loc/ja/src/modules/imageresizer/dll/Resources.resx.lcl
src/modules/imageresizer/ui/loc/ja/src/modules/imageresizer/ui/Properties/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/ja/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/loc/ja/src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/loc/ja/src/modules/launcher/Plugins/Microsoft.Plugin.Indexer/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Program/loc/ja/src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Shell/loc/ja/src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx.lcl
src/modules/powerrename/dll/loc/ja/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/ui/loc/ja/src/modules/powerrename/ui/Resources.resx.lcl
src/modules/previewpane/powerpreview/loc/ja/src/modules/previewpane/powerpreview/Resources.resx.lcl
src/modules/shortcut_guide/loc/ja/src/modules/shortcut_guide/Resources.resx.lcl

LEGO: Pull request from lego/hb_2939_20201228140616941 to master with localized lcls

LEGO: Pull request from lego/hb_2939_20201228140616941 to master

---

.github/actions/spell-check/expect.txt
.github/workflows/codeql-analysis.yml

From  @jhutchings1 in https://github.com/microsoft/PowerToys/pull/8598, this would add in codeql.  Since we couldn't test this against branch before, i'm doing a branch then into master.

Add CodeQL Analysis (#8598)

---

.github/actions/spell-check/expect.txt
README.md

0.29 release update for readme.

Update README.md for 0.29 release

---

src/action_runner/action_runner.cpp
src/action_runner/action_runner.vcxproj
src/common/logger/logger_settings.h

Add logging to action-runner project

---

CONTRIBUTING.md
doc/devdocs/readme.md

Update dev docs.
Merged the `Development` paragraph from https://github.com/microsoft/PowerToys/blob/master/CONTRIBUTING.md to https://github.com/microsoft/PowerToys/blob/master/doc/devdocs/readme.md
Added a link to reach the dev docs readme.md from the CONTRIBUTING.md page
Updated https://github.com/microsoft/PowerToys/blob/master/doc/devdocs/readme.md with extra steps needed before building the installers.
no code to test.
direct links to the changed documents:
https://github.com/microsoft/PowerToys/blob/dev/enricogior/dev-docs-update/CONTRIBUTING.md
https://github.com/microsoft/PowerToys/blob/dev/enricogior/dev-docs-update/doc/devdocs/readme.md …

Dev docs update

---

src/common/interop/two_way_pipe_message_ipc.cpp
src/common/interop/two_way_pipe_message_ipc_impl.h
src/runner/settings_window.cpp

- simplify logic
- handle exceptions to prevent crashes
- log errors

interop: fix issues in IPC message construction

---

tools/BugReportTool/BugReportTool/BugReportTool.vcxproj
tools/BugReportTool/BugReportTool/Main.cpp
tools/BugReportTool/BugReportTool/packages.config

Write dotnet runtime installation info to `dotnet-installation-info.txt`

Report dotnet runtime installation info

---

.github/actions/spell-check/expect.txt
src/modules/launcher/Plugins/Microsoft.Plugin.Calculator.UnitTest/ExtendedCalculatorParserTests.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Calculator/CalculateHelper.cs

This PR adds hyperbolic functions to the calculator plugin.
- Add hyperbolic functions to `RegValidExpressChar`
- Add tests for hyperbolic functions
Test if `sinh(0)`, `cosh(0)`, `tanh(0)`, `arsinh(0)`, `arcosh(1)`, `artanh(pi/4)` return the right results if typed into the launcher.

[Run][Calculator Plugin] Add hyperbolic functions

---

src/common/logger/logger_settings.h
src/modules/keyboardmanager/dll/KeyboardManager.vcxproj
src/modules/keyboardmanager/dll/dllmain.cpp
src/modules/keyboardmanager/dll/pch.h
src/modules/keyboardmanager/ui/EditKeyboardWindow.cpp
src/modules/keyboardmanager/ui/EditShortcutsWindow.cpp
src/modules/keyboardmanager/ui/KeyboardManagerUI.vcxproj
src/modules/keyboardmanager/ui/pch.h

Add logging to keyboard manager

---

src/modules/fancyzones/editor/FancyZonesEditor/GridData.cs
src/modules/fancyzones/editor/FancyZonesEditor/GridEditor.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/LayoutPreview.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs

Fix app crash on opening layout editor.

[FZ Editor] Editor opening fix

---

installer/PowerToysSetup/Product.wxs

Service plugin resources added to setup.
Not sure if this can be tested since resources are generated in build farm.

[PT Run] Service resources

---

src/common/updating/dotnet_installation.cpp

[Setup] install dotnet 3.1.11

---

doc/devdocs/readme.md

Removing current modules, heavily out of date and not used.

update to devdocs main section removing modules

---

src/common/updating/dotnet_installation.cpp

[Setup] require dotnet >= 3.1.11

---

src/modules/fancyzones/editor/FancyZonesEditor/EditorWindow.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/CanvasLayoutModel.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/GridLayoutModel.cs

[FZ Editor] Update the small layout preview after canceling zone editing.

---

.github/actions/spell-check/expect.txt
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Main.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Programs/ShellLinkHelper.cs
src/modules/launcher/PowerLauncher/App.xaml.cs
src/modules/launcher/PowerLauncher/Plugin/PluginManager.cs
src/modules/launcher/PowerLauncher/Plugin/PluginsLoader.cs
src/modules/launcher/Wox.Infrastructure/Image/ImageLoader.cs
src/modules/launcher/Wox.Plugin/Logger/Log.cs

Logs for PowerToys Run are hard to read. This PR aims to improve their readability. See #9347
Changes to log formatting and how logging functions are called.
Delete the log for the current day, start PowerToys and use PowerToys Run for a while, then check the log.

[PT Run] Improve logs

---

doc/devdocs/modules/launcher/plugins/overview.md

Link to changed doc: https://github.com/microsoft/PowerToys/blob/a1fbc4cce3e3a85ef06365ee8c95d60e7c0f3db2/doc/devdocs/modules/launcher/plugins/overview.md
- Exposed plugins settings
- Replacement of `ActionKeywords` with `ActionKeyword` and `IsGlobal`

[PT Run] Documentation for changes to PT Run

---

installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp

use null_logger instead of failing to setup the logger. creation of the null_logger shouldn't throw.

[Bootstrapper] improve logging

---

installer/PowerToysBootstrapper/bootstrapper/loc/zh-Hans/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
installer/PowerToysBootstrapper/bootstrapper/loc/zh-Hant/installer/PowerToysBootstrapper/bootstrapper/Resources.resx.lcl
src/modules/colorPicker/ColorPickerUI/loc/pl/src/modules/colorPicker/ColorPickerUI/Properties/Resources.resx.lcl
src/modules/fancyzones/lib/loc/zh-Hans/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/keyboardmanager/dll/loc/zh-Hans/src/modules/keyboardmanager/dll/Resources.resx.lcl
src/modules/launcher/Microsoft.Launcher/loc/pt-BR/src/modules/launcher/Microsoft.Launcher/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/es/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/loc/pt-BR/src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Program/loc/es/src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Program/loc/pt-BR/src/modules/launcher/Plugins/Microsoft.Plugin.Program/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Shell/loc/es/src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx.lcl
src/modules/launcher/Plugins/Microsoft.Plugin.Shell/loc/pt-BR/src/modules/launcher/Plugins/Microsoft.Plugin.Shell/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/es/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/launcher/PowerLauncher/loc/pt-BR/src/modules/launcher/PowerLauncher/Properties/Resources.resx.lcl
src/modules/powerrename/dll/loc/es/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/dll/loc/pt-BR/src/modules/powerrename/dll/Resources.resx.lcl
src/modules/powerrename/ui/loc/es/src/modules/powerrename/ui/Resources.resx.lcl
src/modules/powerrename/ui/loc/pt-BR/src/modules/powerrename/ui/Resources.resx.lcl
src/settings-ui/Microsoft.PowerToys.Settings.UI/loc/es/src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/settings-ui/Microsoft.PowerToys.Settings.UI/loc/pl/src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/settings-ui/Microsoft.PowerToys.Settings.UI/loc/pt-BR/src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl
src/settings-ui/Microsoft.PowerToys.Settings.UI/loc/zh-Hans/src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw.lcl

LEGO: Pull request from lego/hb_a13bbffa-1136-4930-9ebe-33895240f846_20210222153336560 to master with localized lcls

LEGO: Pull request from lego/hb_a13bbffa-1136-4930-9ebe-33895240f846_20210222153336560 to master

---

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/Telemetry/Events/OobeStartedEvent.cs
src/settings-ui/PowerToys.Settings/App.xaml.cs

[Oobe] Telemetry: Date/Time of first-run

---

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/Telemetry/Events/OobeModuleRunEvent.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/Telemetry/Events/OobeSectionEvent.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/Telemetry/Events/OobeSettingsEvent.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/ViewModel/OobePowerToysModule.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFancyZones.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFancyZones.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFileExplorer.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFileExplorer.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeImageResizer.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeImageResizer.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeKBM.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeKBM.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobePowerRename.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobePowerRename.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeVideoConference.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeVideoConference.xaml.cs

Log events:
* When specific OOBE sections are entered/exited
* Access to linked settings pages
* PowerToys launched while OOBE window is active.

[Oobe] Telemetry 

---

src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml

Renamed `OOBE` to `PowerToys Tour`, added to resources.

[Oobe] Renamed button in the settings

---

src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw

Added info on how to close it.

[Oobe] Updated Shortcut Guide description 

---

src/modules/shortcut_guide/native_event_waiter.h

[ShortcutGuide] make SCG launching behavior a bit more deterministic

---

.github/actions/spell-check/expect.txt
README.md

Readme 0.33

---

src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw

[PT Settings] Rename the OOBE opening button and 'File Explorer' section

---

src/modules/colorPicker/ColorPicker/trace.cpp
src/modules/launcher/Microsoft.Launcher/trace.cpp

Remove events that have `::` in their tag.
Remove two events that were examples from the module template. They were not used.
Build the solution and verify that it builds successfully.

[chore] remove unused telemetry events

---

src/modules/colorPicker/ColorPicker/trace.h
src/modules/launcher/Microsoft.Launcher/trace.h

In #10030 I forgot to remove the function declaration
Deleted two function declarations from the header files.
Build the solution and verify it build successfully (CI will take care of that).

[chore] remove unused functions

---

src/modules/fancyzones/lib/Zone.cpp
src/modules/fancyzones/lib/util.cpp
src/modules/fancyzones/lib/util.h

In several scenarios, taskbar position/size is incorrectly taken into account. This PR takes a different approach to computing the taskbar's position, and works in all tested scenarios I could find.
For more information, see the tracker issue #7371.
The most complex part is the new function which translates screen coordinates to workspace coordinates. The workspace coordinate system is only used in two Windows API functions `GetWindowPlacement` and `SetWindowPlacement`, which we have to use because they are the only ones which can resize a window that's minimized. The translation between these two coordinate systems is not documented, and the function included here seems to correctly translate between the two in all tested scenarios. …

[FancyZones] Fix taskbar size issues

---

.pipelines/ci/templates/build-powertoys-steps.yml
src/common/interop/interop-tests/Microsoft.Interop.Tests.csproj
src/modules/colorPicker/UnitTest-ColorPickerUI/UnitTest-ColorPickerUI.csproj
src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry.UnitTest/Microsoft.PowerToys.Run.Plugin.Registry.UnitTests.csproj
src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System.UnitTests/ImageTests.cs
src/modules/previewpane/PreviewPaneUnitTests/UnitTests-MarkdownPreviewHandler.csproj
src/modules/previewpane/UnitTests-PreviewHandlerCommon/UnitTests-PreviewHandlerCommon.csproj
src/modules/previewpane/UnitTests-SvgPreviewHandler/SvgPreviewControlTests.cs
src/modules/previewpane/UnitTests-SvgPreviewHandler/UnitTests-SvgPreviewHandler.csproj
src/modules/previewpane/UnitTests-SvgThumbnailProvider/UnitTests-SvgThumbnailProvider.csproj
src/settings-ui/Microsoft.PowerToys.Settings.UI.UnitTests/Microsoft.PowerToys.Settings.UI.UnitTests.csproj

Not all tests were included or run on the CI pipeline. For example, MS Tests could not be loaded by the MS Test adapter
Some test dlls were missing from the list or had wrong naming.
- Update `MSTest.TestFramework` and `MSTest.TestAdapter` to the newest version. That fixes discoverability of MS Tests. Luckily for us, it was just fixed for both Visual studio and pipeline https://github.com/microsoft/testfx/releases/tag/v2.2.2
- Group .net core tests runs by test adapter(MS Test, XUnit, NUnit). It is important as MS Tests have problems with counting data-driven tests
- Commented out `SvgPreviewControlShouldSetScrollBarsEnabledPropertyWhenDoPreviewCalled`, related issue #10262
- Fix name for `Microsoft.Plugin.Folder.UnitTest.dll`
- …

Tests on pipeline

---

installer/PowerToysBootstrapper/bootstrapper/Resources.resx
installer/PowerToysBootstrapper/bootstrapper/bootstrapper.cpp
src/common/updating/installer.cpp
src/common/updating/installer.h
src/common/updating/updating.cpp
src/common/utils/os-detect.h
src/common/version/helper.cpp
src/common/version/helper.h

[Auto-update] Turn off on Windows < 1903

---

src/modules/fancyzones/lib/trace.cpp
src/modules/fancyzones/lib/trace.h

Telemetry for the quick layout switch event.

[FancyZones] Quick layout switch telemetry

---

src/runner/main.cpp

Adding checks for the existence of PT Run assets and log if they aren't there. Should help with diagnosing the issue.

[Runner] verify the existence of PT Run assets

---

src/common/interop/interop.cpp
src/common/interop/shared_constants.h
src/modules/colorPicker/ColorPicker/dllmain.cpp
src/modules/colorPicker/ColorPickerUI/Helpers/NativeEventWaiter.cs
src/modules/colorPicker/ColorPickerUI/Settings/IUserSettings.cs
src/modules/colorPicker/ColorPickerUI/Settings/UserSettings.cs
src/modules/colorPicker/ColorPickerUI/Telemetry/ColorPickerSettings.cs
src/modules/colorPicker/ColorPickerUI/ViewModels/MainViewModel.cs
src/modules/interface/powertoy_module_interface.h
src/modules/launcher/Microsoft.Launcher/dllmain.cpp

It is going to be tested on a windows insider machine.

Settings telemetry for ColorPicker

---

src/modules/launcher/Microsoft.Launcher/dllmain.cpp

Logging for PT Run module interface

---

.github/actions/spell-check/expect.txt
README.md

Readme 0.35

---

.github/actions/spell-check/expect.txt

Add terms to spell checker expected list 

[spell checker] Add expected terms

---

src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Enums/PowerToysModulesEnum.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeOverview.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw

- Removed the periods from the links to a separate TextBlock run. (https://github.com/microsoft/PowerToys/issues/9882#issuecomment-785301967)
- Fixed the order of Run and PowerRename so they are aligned with Settings (and in alphabetically order). (#10576)

[OOBE] UX fixes

---

src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml
src/modules/fancyzones/editor/FancyZonesEditor/ViewModels/MonitorViewModel.cs

- Added resolution to the monitor cards, so it's a bit clearer that they are actually monitors :).

[FZ Editor] Added resolution to monitor

---

src/common/interop/PowerToysInterop.vcxproj
src/modules/videoconference/VideoConferenceShared/Logging.h

[VCM] fix CI build

---

.github/ISSUE_TEMPLATE/bug_report.yml

Tweaking title back inline to old and shifting "As admin" to be checkbox

Tweaking bug report template

---

tools/BugReportTool/BugReportTool/Main.cpp

[BugReport] add VCM logs to the report

---

src/modules/videoconference/VideoConferenceModule/Toolbar.cpp
src/modules/videoconference/VideoConferenceProxyFilter/ImageLoading.cpp

Feature/video conference mute 0.36 pr

---

src/modules/videoconference/VideoConferenceProxyFilter/VideoCaptureProxyFilter.cpp

More logging

---

doc/devdocs/modules/launcher/new-plugin-checklist.md

Rendered md file:
https://github.com/microsoft/PowerToys/blob/ad0aa9a3c397b0888ee415aeb3db2e2967649b6f/doc/devdocs/modules/launcher/new-plugin-checklist.md

[docs] New plugin checklist

---

src/common/updating/updating.cpp

[Auto-update] Remove special case logic for autoupdate disabling

---

src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeColorPicker.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFancyZones.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeFileExplorer.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeImageResizer.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeKBM.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeOverview.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobePowerRename.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeRun.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShellPage.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeShortcutGuide.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/OOBE/Views/OobeVideoConference.xaml
src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw

This PR address a couple of Accessibility issues.

[OOBE] Accessibility fixes

---

src/modules/keyboardmanager/KeyboardManagerEngine/KeyboardManagerEngine.vcxproj
src/modules/keyboardmanager/dll/dllmain.cpp

Rename engine executable

---

src/common/utils/logger_helper.h
src/modules/keyboardmanager/KeyboardManagerEditor/KeyboardManagerEditor.cpp
src/modules/keyboardmanager/KeyboardManagerEngineLibrary/KeyboardManager.cpp
src/modules/keyboardmanager/dll/dllmain.cpp

- Init logs for the KBM editor
- Change structure of logs for the KBM interface
- Delete old logs for the KBM interface

[KBM] New logs structure

---

src/modules/keyboardmanager/KeyboardManagerEditor/KeyboardManagerEditor.cpp
src/modules/keyboardmanager/KeyboardManagerEditor/KeyboardManagerEditor.vcxproj

[KBM] Unhandled exception handling for the editor

---

src/modules/keyboardmanager/KeyboardManagerEditorLibrary/EditKeyboardWindow.cpp
src/modules/keyboardmanager/KeyboardManagerEditorLibrary/XamlBridge.cpp

[KBM] Trace for edit keyboard window

---

src/modules/keyboardmanager/KeyboardManagerEditor/KeyboardManagerEditor.exe.manifest

Make the editor dpi aware

---

src/modules/fancyzones/editor/FancyZonesEditor/GridData.cs
src/modules/fancyzones/editor/FancyZonesEditor/GridEditor.xaml.cs
src/modules/fancyzones/editor/FancyZonesEditor/Models/GridLayoutModel.cs
src/modules/fancyzones/editor/FancyZonesEditor/Utils/FancyZonesEditorIO.cs

FZ Editor crashes when trying to edit a layout that contains malformed data. 
* Added verification steps on parsing model from json file.
* Removed unhandled exception throwing on the editor opening.
Create and edit custom grid layout or paste an example to reproduce the bug.
Verify that on the FZ Editor start there is a error message informing about the malformed layout that would be deleted. 
Verify that malformed layout was deleted.
Example that caused the crash:
```
{
"uuid": "{274770A2-54D9-4654-A117-F179B37B03E6}",
"name": "test",
"type": "grid",
"info": {
"rows": 4,
"columns": 6,
"rows-percentage": [
3194,
1431,
2447,
2838
],
"columns-percentage": [
1013,
117,
1663,
2522,
3661,
1024
], …
```

[FancyZones Editor] Fix FZ Editor crash on opening custom layout for editing 

---

.github/actions/spell-check/expect.txt

Spell checker complaining for some new terms
Add terms

[spell checker] add terms

---

src/action_runner/action_runner.cpp
src/common/updating/updateState.cpp
src/common/updating/updateState.h
src/common/updating/updating.vcxproj
src/runner/main.cpp
src/runner/settings_window.cpp
src/runner/update_utils.cpp

[Updating] Don't use underscores in update_state

---

src/modules/fancyzones/editor/FancyZonesEditor/CanvasEditorWindow.xaml
src/modules/fancyzones/editor/FancyZonesEditor/GridEditorWindow.xaml
src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml
src/modules/fancyzones/editor/FancyZonesEditor/MainWindow.xaml.cs

[FZ Editor] Accessibility fixes

---

README.md
src/common/updating/dotnet_installation.cpp

[Setup] Update .net core to 3.1.14

---

src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.cpp
src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.h
src/modules/ShortcutGuide/ShortcutGuide/target_state.cpp
src/modules/ShortcutGuide/ShortcutGuide/target_state.h
src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/ShortcutGuideViewModel.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/ShortcutGuide.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml

- Verify that `win` does not work and `shift+win+?` works

[Shortcut Guide] Drop win key long press support

---

src/modules/ShortcutGuide/ShortcutGuideModuleInterface/dllmain.cpp
src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ShortcutGuideProperties.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ShortcutGuideSettingsIPCMessage.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/SndShortcutGuideSettings.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/ShortcutGuideViewModel.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw
src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/ShortcutGuidePage.xaml

Ability to configure SG shortcut.
- Add `HotkeySettingsControl` to SG page
- Send settings on field change
- Use `set_settings` module interface to update hotkey
- Verify that old SG setting are persisted 
- Delete SG's `settings.json` and verify that SG works

[Shortcut Guide] Open sg shortcut

---

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/UpdatingSettings.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/GeneralViewModel.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml.cs

Added file watcher to track changes in the `UpdateState.json` and updates the UI.

[Auto-update][PT Settings] File watcher monitoring UpdateState.json

---

src/settings-ui/Microsoft.PowerToys.Settings.UI.Library/ViewModels/GeneralViewModel.cs
src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml

Handle update button clicks.
* Update `src/Version.props`, set any version below `0.37.2` for testing (e.g. `<Version>0.35.1</Version>`)
* Clean build PT Release
* Build `installer/PowerToysSetup`
* Install `installer/PowerToysSetup/x64/Release/PowerToysSetup-0.35.1-x64.msi`
* Click `Check for updates` in the PT Settings, verify that installer was downloaded, button and text corresponding to the updating were changed.
Update `AppData\Local\Microsoft\PowerToys\UpdateState.json` to verify that UI reacts on file change.

[Auto-update][PT Settings] Handle button clicks

---

src/runner/action_runner_utils.h

[Updating] Document ActionRunner cmd flags

---

src/settings-ui/Microsoft.PowerToys.Settings.UI/Strings/en-us/Resources.resw

[Shortcut Guide] OOBE updates

---

src/modules/ShortcutGuide/ShortcutGuide/main.cpp
src/modules/ShortcutGuide/ShortcutGuide/shortcut_guide.cpp

Verify that the Shortcut guide does not open if the app is disabled

[Shortcut Guide] Fix disabled apps

---

src/settings-ui/Microsoft.PowerToys.Settings.UI/Views/GeneralPage.xaml

[Auto-update][Settings] Show error text with error brush.

---

src/common/utils/elevation.h
src/modules/launcher/Microsoft.Launcher/dllmain.cpp
src/modules/launcher/PowerLauncher/App.xaml.cs
src/modules/previewpane/powerpreview/powerpreview.vcxproj

- Correlation logs between PT Run and the module interface
- Tracing for `run_non_elevated`

[PowerToys Run] Logging

---

doc/devdocs/modules/launcher/new-plugin-checklist.md

[Issue-Docs] Update new-plugin-checklist.md

---

src/ActionRunner/LocProject.json

[Updating] Fix localization path

---

.github/actions/spell-check/patterns.txt

Add a new rule for the spell checker, see https://github.com/microsoft/PowerToys/pull/11406#issuecomment-847396333

[spell checker] add rule

---

tools/BugReportTool/BugReportTool/EventViewer.cpp
tools/BugReportTool/BugReportTool/XmlDocumentEx.h

Fix for the internal build farm build break.
Added standard headers for strings and streams.

[Bug Report Tool] Fix internal build

---

src/common/logger/framework.h

Allows builiding the solution in VS2019 16.10 (latest stable).
- Update to latest spdlog (which correctly prefixes all ftm calls because there has been a new formatter class added in the C++ 20 library

Update Logger library to support VS2019 16.10

---

installer/PowerToysSetup/Product.wxs
installer/PowerToysSetupCustomActions/CustomAction.cpp

* Renamed dll
* Added `PowerToys.FancyZones.exe`
* Added to the processes to terminate 

[FancyZones] Updated installer

---

src/modules/fancyzones/FancyZones/FancyZones.vcxproj
src/modules/fancyzones/FancyZones/FancyZones.vcxproj.filters
src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj
src/modules/fancyzones/FancyZonesLib/LocProject.json
src/modules/fancyzones/FancyZonesLib/loc/cs/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/de/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/es/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/fr/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/hu/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/it/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/ja/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/ko/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/nl/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/pl/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/pt-BR/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/pt-PT/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/ru/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/sv/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/tr/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/zh-Hans/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/loc/zh-Hant/src/modules/fancyzones/lib/Resources.resx.lcl
src/modules/fancyzones/FancyZonesLib/resource.base.h
src/modules/fancyzones/FancyZonesModuleInterface/FancyZonesModuleInterface.vcxproj
src/modules/fancyzones/FancyZonesModuleInterface/FancyZonesModuleInterface.vcxproj.filters

* Updated projects
* Updated localization paths

[FancyZones] Update string resources

---

installer/PowerToysSetup/Product.wxs

Fix internal build

---

.pipelines/pipeline.user.windows.yml

Update pipeline.user.windows.yml to include UnitConverter

---

src/modules/fancyzones/FancyZones/main.cpp

Terminate `PowerToys.FancyZones.exe` when the runner process was terminated.
Start runner from VisualStudio, stop debugging, verify in Task Manager that `PowerToys.FancyZones.exe` was terminated.

[FancyZones] Terminate FancyZones with runner

---

src/modules/launcher/Plugins/Community.PowerToys.Run.Plugin.UnitConverter/Main.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Folder/Main.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Program/Main.cs
src/modules/launcher/Plugins/Microsoft.Plugin.Uri/Main.cs
src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Calculator/Main.cs
src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.Registry/Main.cs
src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.WindowsSettings/Main.cs

[Run-Plugin][Program] Fix null reference exception on Dispose

---

src/modules/fancyzones/FancyZonesLib/Settings.cpp
src/modules/fancyzones/FancyZonesLib/trace.cpp
src/modules/fancyzones/FancyZonesLib/trace.h
src/modules/fancyzones/FancyZonesModuleInterface/dllmain.cpp

Send settings telemetry once a day according to a new telemetry approach.
It is going to be tested on a windows insider machine.

Settings telemetry for FancyZones

---

src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj
src/modules/fancyzones/FancyZonesLib/FancyZonesLib.vcxproj.filters
src/modules/fancyzones/FancyZonesLib/MonitorWorkAreaHandler.cpp
src/modules/fancyzones/FancyZonesLib/MonitorWorkAreaHandler.h
src/modules/fancyzones/FancyZonesLib/VirtualDesktop.cpp
src/modules/fancyzones/FancyZonesLib/VirtualDesktop.h
src/modules/fancyzones/FancyZonesLib/VirtualDesktopUtils.cpp
src/modules/fancyzones/FancyZonesLib/VirtualDesktopUtils.h
src/modules/fancyzones/FancyZonesLib/util.cpp
src/modules/fancyzones/FancyZonesLib/util.h
src/modules/fancyzones/FancyZonesTests/UnitTests/ZoneSet.Spec.cpp

Moved the code related to virtual desktops into a single class.

[FancyZones] Virtual desktop utils refactoring

---

src/modules/awake/Awake/Core/APIHelper.cs
src/modules/awake/Awake/Program.cs

Also addressing some cosmetic changes, like the string in the tray, and the crash in `ForceExit`.

[Hotfix] PowerToys Awake - fixing CPU usage

---

src/modules/fancyzones/FancyZonesLib/JsonHelpers.cpp
src/modules/fancyzones/FancyZonesTests/UnitTests/JsonHelpers.Tests.cpp

* Updated expected json in tests
* Added constants

[FancyZones] Unit tests fix

---

src/modules/fancyzones/FancyZonesLib/FancyZones.cpp
src/modules/fancyzones/FancyZonesLib/FancyZonesWinHookEventIDs.cpp

Removed mutexes from `FancyZones`.

[FancyZones] Clean up mutexes

---

src/runner/tray_icon.cpp

[Runner] Place tooltip text for tray icon on a single line

---

src/modules/launcher/PowerLauncher/ViewModel/ContextMenuItemViewModel.cs
src/modules/launcher/PowerLauncher/ViewModel/MainViewModel.cs
src/modules/launcher/PowerLauncher/ViewModel/ResultViewModel.cs
src/modules/launcher/PowerLauncher/ViewModel/ResultsViewModel.cs
src/modules/launcher/PowerLauncher/ViewModel/SettingWindowViewModel.cs
src/modules/launcher/Wox.Plugin/Wox.Plugin.csproj
src/modules/launcher/Wox.Test/ResultsViewModelTest.cs

PT Run ViewModels cleanup.
Removed unused properties and public setters.
Opne PT Run and validate that everything work as expected. Most of the work is on results and context menus.

[Run] ViewModels Cleanup

---

doc/devdocs/readme.md

Building the Webcam reporting tool is a prerequisite to building the installer.
Update the installer docs to reflect this.
Changes to the installer docs.
Look at the resulting markdown to verify the changes are there.
Try building the installer following the instructions.

[devdocs] webcam reporting tool build instructions

---

.github/actions/spell-check/expect.txt
README.md

**What is this about:** 
Readme updates for the upcoming v0.43 release

v0.43 Updates

---

.pipelines/build-installer-PTCustomActions.cmd
.pipelines/pipeline.user.windows.yml

We don't sign PowerToysSetupCustomActions.dll, which means it can cause install errors on some strict security environments.
Changes to build PowerToysSetupCustomActions.dll first, sign it, and only then build the rest of the installer.
I've uploaded the resulting build as a release here: https://github.com/jaimecbernardo/PowerToys/releases/tag/v0.0.2-signedPTCustomActions
I'm mostly looking for a second set of eyes regarding the code changes I've introduced to the pipelines.
In case one wants to verify it, one way is checking that the PTCustomActions.dll inside the msi is signed, using Orca.
1 - Orca can be installed from inside Windows SDK. `C:\Program Files (x86)\Windows …

[Build] Sign PowerToysSetupCustomActions.dll

---

src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Main.cs
src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Properties/Resources.Designer.cs
src/modules/launcher/Plugins/Microsoft.PowerToys.Run.Plugin.System/Properties/Resources.resx

Adding option to system commands plugin for localization.
By default commands are localized (current PT behaviour).
_Settings_
_Localize: true_
_Localize: false_
- In order to see the new option in the settings https://github.com/microsoft/PowerToys/pull/12920 is needed, but additional option `{"Key":"LocalizeSystemCommands","DisplayLabel":"Use localized system commands instead of english ones","Value":true}` can be added manually to `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\settings.json`.
- Since resources are localized in build farm you need to manually add to build output localized resources, eg: `PowerToys\x64\Debug\modules\launcher\Plugins\System\it\Microsoft.PowerToys.Run.Plugin.Sy …

[PT Run] Option for system commands localization

---

src/modules/launcher/PowerLauncher/SettingsReader.cs

Add/Remove additional options for PT Run plugins on startup
Need to be tested in debug.
- Add these additional options to Indexer Plugin
```
new PluginAdditionalOption()
{
Key = "Option0",
DisplayLabel = "Option 0",
Value = false,
},
new PluginAdditionalOption()
{
Key = "Option1",
DisplayLabel = "Option 1",
Value = false,
},
```
- Build and run PT
- Option 0 and Option 1 should be displayed in Plugin Manager
- PT Run should work
- Close PT
- Remove Option 0 and Option 1 from the additional options
- Build and run PT
- Option 0 and Option 1 should not be displayed in Plugin Manager
A CLA must be signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/PowerToys) and sign the …

[Run Plugin Manager] Update additional options

---

.pipelines/pipeline.user.windows.yml

[CI] Sign VCM x86 module dll

---

README.md

Readme updated for v0.46's release.

Update README.md for v0.46 release

---

installer/PowerToysSetup/Product.wxs

Uncomment resource files reference in installer.
Uncomment resource files reference in installer.
Not tested manually.

[PT Run: Settings plugin] [Installer] Update installer to include loc files

---

.github/actions/spell-check/expect.txt
COMMUNITY.md

Updating the community file to add Heiko.
@htcfreek, thank you for your contributions!

Adding in Heiko to community.md

---

src/modules/imageresizer/ui/App.xaml
src/modules/imageresizer/ui/Properties/Resources.Designer.cs
src/modules/imageresizer/ui/Properties/Resources.resx
src/modules/imageresizer/ui/Views/InputPage.xaml
src/modules/imageresizer/ui/Views/SizeTypeToVisibilityConverter.cs

Replacing the ListView (that doesn't scroll) with a ComboBox. This improves accesibility navigation and is more scalable when having a lot of sizes configured).

[Image Resizer] ComboBox UI

---

README.md
SUPPORT.md

adding in links a bit more 
pure text updates 

Add how to using PT links in readme and support

---

.github/actions/spell-check/expect.txt
README.md

Readme updates for PowerToys v0.47

v0.47 Updates

---

src/modules/previewpane/UnitTests-PdfPreviewHandler/UnitTests-PdfPreviewHandler.csproj
src/modules/previewpane/UnitTests-SvgPreviewHandler/SvgPreviewControlTests.cs

Fix PreviewPane build warnings

[Chore] Fix PreviewPane build warnings

---

src/settings-ui/Microsoft.PowerToys.Settings.UI.UnitTests/ViewModelTests/FancyZones.cs

~~Uncomment commented out test to figure out why does it fail in the pipeline.~~
Fix typo in the test.

[Settings.UI.UnitTests][FancyZones] Uncomment test in CI

---

tools/BugReportTool/BugReportTool/BugReportTool.vcxproj
tools/BugReportTool/BugReportTool/BugReportTool.vcxproj.filters
tools/BugReportTool/BugReportTool/EventViewer.cpp
tools/BugReportTool/BugReportTool/ProcessesList.cpp
tools/BugReportTool/BugReportTool/RegistryUtils.cpp

To avoid having 2 processes list and maintaining both, let's centralize them.

[BugReportTool] Centralized process list

---

.github/actions/spell-check/expect.txt

Fix typo founded by the bot in https://github.com/microsoft/PowerToys/pull/14392/files#diff-c502a81cdf8afa7a38f0f462709abcdbdfcc44beaa6227a1e64a26566c7e8876
Add `wca` and `homepage` to `.github/actions/spell-check/expect.txt`
Not required.

Fix spellcheck

---

doc/devdocs/akaLinks.md

Rename master into main in the link

Rename master -> main in the link

---

src/modules/awake/Awake/Core/TrayHelper.cs

…led from a common spot w/ settings
Getting these in sync.
small text change, this keeps it hard coded as is.

Getting setting and systray in-sync
